(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),last=performance.now(),pointer=null,origin={x:0,y:0},input={x:0,y:0,mag:0},selectedPanel=null,autoTarget=null,workClock=0,passiveClock=0,nightSpawned=false;
const SAVE='guild-infinity-buildjoy-v10',BACKUP=SAVE+'-backup',DB='guild-infinity-buildjoy-db',STORE='save',WORLD={minX:-620,maxX:620,minY:-430,maxY:470};
const BUILD_SLOTS=[[-72,40],[72,40],[-150,-45],[150,-45],[-220,80],[220,80],[-70,-145],[70,-145],[-290,-80],[290,-80],[0,170],[-180,190],[180,190],[0,-235]];
const RECIPES={hut:{name:'小屋',wood:12,stone:4},lumber:{name:'木材所',wood:18,stone:6},quarry:{name:'採石所',wood:14,stone:12},barricade:{name:'防壁',wood:10,stone:0},lantern:{name:'灯火塔',wood:8,stone:3}};
const state={version:10,day:1,cycle:.12,phase:'day',wood:0,stone:0,food:0,gold:0,gem:0,hourglass:1,ticket:0,boost:1,boostUntil:0,player:{x:0,y:115,vx:0,vy:0,dir:'down',walk:0,swing:0},nodes:[],buildings:[],workers:[],zombies:[],lastSaved:0,nightRewarded:false};
const cam={x:0,y:40};
const particles=[],floats=[];
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rnd=(a,b)=>a+Math.random()*(b-a),sx=x=>W/2+x-cam.x,sy=y=>H/2+y-cam.y;
function toast(t){$('ticker-text').textContent=t;$('ticker').classList.remove('flash');void $('ticker').offsetWidth;$('ticker').classList.add('flash')}
function fmt(n){return Math.floor(n)}
function phaseInfo(c=state.cycle){if(c<.07)return['dawn','DAWN'];if(c<.68)return['day','DAY'];if(c<.76)return['dusk','DUSK'];return['night','NIGHT']}
function objective(){if(!state.buildings.some(b=>b.type==='hut'))return'木を集めて最初の小屋を建てよう';if(state.workers.length===0)return'小屋が完成 · 最初の作業員を雇おう';if(!state.buildings.some(b=>b.type==='lumber'))return'木材所を建てて採取を速くしよう';if(!state.buildings.some(b=>b.type==='barricade'))return'夜に備えて防壁を建てよう';return`街を広げよう · BUILDINGS ${state.buildings.length}`}
function updateHud(){
 $('wood').textContent=fmt(state.wood);$('stone').textContent=fmt(state.stone);$('food').textContent=fmt(state.food);$('people').textContent=state.workers.length+'/200';$('day').textContent='DAY '+state.day;const [ph,label]=phaseInfo();state.phase=ph;$('phase').textContent=label;const mins=Math.floor(state.cycle*24*60),hh=String(Math.floor(mins/60)%24).padStart(2,'0'),mm=String(mins%60).padStart(2,'0');$('clock').textContent=hh+':'+mm;$('objective-text').textContent=objective();$('worker-caption').textContent=state.buildings.some(b=>b.type==='hut')?state.workers.length+'/200':'小屋で解禁';$('hourglass').textContent=state.hourglass;$('ticket').textContent=state.ticket;$('gem').textContent=state.gem;$('last-save').textContent=state.lastSaved?new Date(state.lastSaved).toLocaleTimeString('ja-JP'):'--:--:--';$('save-status').textContent=state.lastSaved?'SAVED':'AUTO';$('speed').textContent='×'+state.boost;
}
function seededNodes(){if(state.nodes.length)return;const immediate=[[-48,150,'tree'],[62,160,'tree'],[-100,85,'tree'],[110,75,'tree'],[-130,145,'rock'],[145,140,'rock'],[-35,205,'food'],[80,215,'food']];let id=0;state.nodes=immediate.map(v=>makeNode('n'+id++,...v));for(let i=0;i<30;i++){let a=i/30*Math.PI*2,r=190+(i%5)*58;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-28,28),Math.sin(a)*r*.72+rnd(-24,24),'tree'))}for(let i=0;i<20;i++){let a=(i+.45)/20*Math.PI*2,r=150+(i%4)*85;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-25,25),Math.sin(a)*r*.7+rnd(-20,20),'rock'))}for(let i=0;i<12;i++){let a=(i+.8)/12*Math.PI*2,r=130+(i%3)*95;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-20,20),Math.sin(a)*r*.68+rnd(-20,20),'food'))}}
function makeNode(id,x,y,type){return{id,x,y,type,hp:type==='food'?1:type==='tree'?4:4,maxHp:type==='food'?1:4,alive:true,respawnAt:0}}
seededNodes();
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function shadow(x,y,w,h=6){ctx.fillStyle='#0a13118a';ctx.fillRect(Math.round(x-w/2),Math.round(y-h/2),Math.round(w),Math.round(h))}
function drawGround(){const ph=state.phase,top=ph==='night'?'#102025':ph==='dusk'?'#314049':ph==='dawn'?'#345350':'#36584c',bot=ph==='night'?'#172720':ph==='dusk'?'#4a4934':ph==='dawn'?'#465b48':'#425f4d';const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,top);g.addColorStop(1,bot);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const ox=((-cam.x)%32+32)%32,oy=((-cam.y)%32+32)%32;ctx.strokeStyle='rgba(178,167,123,.035)';ctx.lineWidth=1;for(let x=ox;x<W;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=oy;y<H;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const cx=sx(0),cy=sy(0);rect(cx-22,cy+10,44,6,'#51493a');rect(cx-14,cy+4,9,6,'#80765a');rect(cx+5,cy+4,9,6,'#80765a')}
function drawTree(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+18,27,6);rect(x-4,y-5,8,27,'#65472f');rect(x-2,y-5,2,23,'#9a6d43');rect(x-18,y-31,36,23,'#1f3c30');rect(x-13,y-39,26,17,'#2d5140');rect(x-6,y-34,11,10,'#49684c')}
function drawRock(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+12,26,5);rect(x-12,y-7,24,17,'#5e6661');rect(x-8,y-12,16,7,'#7d8173');rect(x-6,y-7,7,4,'#a3a087')}
function drawFood(n){const x=sx(n.x),y=sy(n.y);rect(x-12,y+2,24,12,'#29402f');rect(x-9,y-4,18,10,'#4b6647');for(const d of[-6,0,6])rect(x+d-1,y+1,3,3,'#bf6258')}
function drawPlayer(){const p=state.player,x=sx(p.x),y=sy(p.y),bob=Math.sin(p.walk)*1.2;shadow(x,y+16,21,6);rect(x-7,y-16+bob,14,19,'#c56b42');rect(x-5,y-24+bob,11,9,'#d5aa7d');rect(x-7,y-27+bob,15,5,'#73818b');rect(x-5,y+3-bob,4,11,'#31363a');rect(x+2,y+3+bob,4,11,'#31363a');if(p.swing>0){const a=(1-p.swing)*Math.PI*.9-.3,ax=x+Math.cos(a)*18,ay=y-8+Math.sin(a)*18;ctx.strokeStyle='#c7c4b9';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+5,y-8);ctx.lineTo(ax,ay);ctx.stroke();rect(ax-2,ay-4,7,6,'#9fa8a8')}}
function drawWorker(w,i){const x=sx(w.x),y=sy(w.y),bob=Math.sin(performance.now()*.006+i)*1;shadow(x,y+13,17,4);rect(x-6,y-14+bob,12,17,w.role==='guard'?'#8d4d42':w.role==='wood'?'#627e55':w.role==='stone'?'#6d7182':'#8c7650');rect(x-4,y-21+bob,9,8,'#d0a37a');rect(x-4,y+3-bob,3,8,'#31363a');rect(x+2,y+3+bob,3,8,'#31363a')}
function drawBuilding(b){const x=sx(b.x),y=sy(b.y),age=clamp((performance.now()-b.builtAt)/650,0,1),rise=(1-age)*18;ctx.save();ctx.globalAlpha=.35+.65*age;ctx.translate(0,rise);shadow(x,y+17,b.type==='barricade'?54:48,7);if(b.type==='hut'){rect(x-25,y-10,50,30,'#806044');ctx.fillStyle='#bb8a55';ctx.beginPath();ctx.moveTo(x-31,y-10);ctx.lineTo(x,y-32);ctx.lineTo(x+31,y-10);ctx.closePath();ctx.fill();rect(x-6,y+3,12,17,'#2d241e')}else if(b.type==='lumber'){rect(x-26,y-7,52,23,'#775035');rect(x-22,y-12,44,7,'#a67948');for(let i=-18;i<=18;i+=12)rect(x+i,y+15,7,14,'#513723');rect(x+15,y-18,7,12,'#8b633e')}else if(b.type==='quarry'){rect(x-27,y,54,16,'#555d5c');rect(x-22,y-12,44,13,'#717970');rect(x-16,y-20,32,9,'#90917e')}else if(b.type==='barricade'){for(let i=-24;i<=24;i+=12){rect(x+i-3,y-18,7,35,'#724b31');rect(x+i-2,y-18,2,31,'#a37349')}}else{rect(x-3,y-29,6,42,'#765137');rect(x-15,y-36,30,10,'#27313a');rect(x-9,y-33,18,5,'#e8b45c');glow(x,y-28,80)}ctx.restore()}
function glow(x,y,r){ctx.save();ctx.globalCompositeOperation='screen';const g=ctx.createRadialGradient(x,y,4,x,y,r);g.addColorStop(0,'rgba(255,186,83,.22)');g.addColorStop(1,'rgba(255,135,50,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore()}
function drawZombie(z){const x=sx(z.x),y=sy(z.y);shadow(x,y+13,18,5);rect(x-7,y-14,14,20,z.hit>0?'#d6d0a4':'#687d61');rect(x-5,y-22,10,9,'#a7a48b');rect(x-4,y-19,2,2,'#321f1e');rect(x+2,y-19,2,2,'#321f1e');rect(x-6,y+5,4,11,'#433735');rect(x+2,y+5,4,11,'#433735')}
function particlesAt(wx,wy,color,count=7){for(let i=0;i<count;i++)particles.push({x:wx,y:wy,vx:rnd(-38,38),vy:rnd(-55,-15),life:rnd(.35,.65),color,size:rnd(2,4)})}
function floatText(wx,wy,text,color='#f0d187'){floats.push({x:wx,y:wy,text,color,life:1})}
function rareDrop(wx,wy){const r=Math.random();if(r<.025){state.hourglass++;toast('RARE DROP · 砂時計 +1');floatText(wx,wy,'HOURGLASS!','#c6a6ff');BuildjoyAudio.sfx('rare');return}if(r<.04){state.ticket++;toast('RARE DROP · 召喚券 +1');floatText(wx,wy,'TICKET!','#8dd8ff');BuildjoyAudio.sfx('rare');return}if(r<.055){state.gem++;toast('RARE DROP · GEM +1');floatText(wx,wy,'GEM!','#9ac5ff');BuildjoyAudio.sfx('rare')}}
function nearestNode(){let best=null,d=999;for(const n of state.nodes){if(!n.alive)continue;const q=Math.hypot(state.player.x-n.x,state.player.y-n.y);if(q<46&&q<d){best=n;d=q}}return best}
function workNode(n){if(!n||!n.alive)return;state.player.dir=Math.abs(n.x-state.player.x)>Math.abs(n.y-state.player.y)?(n.x>state.player.x?'right':'left'):(n.y>state.player.y?'down':'up');state.player.swing=1;const mul=n.type==='tree'?(state.buildings.some(b=>b.type==='lumber')?1.25:1):n.type==='rock'?(state.buildings.some(b=>b.type==='quarry')?1.25:1):1;if(n.type==='tree'){const gain=2*mul;state.wood+=gain;floatText(n.x,n.y-18,'+WOOD '+Math.ceil(gain));particlesAt(n.x,n.y,'#b9824c');BuildjoyAudio.sfx('chop')}else if(n.type==='rock'){const gain=1.5*mul;state.stone+=gain;floatText(n.x,n.y-14,'+STONE '+Math.ceil(gain));particlesAt(n.x,n.y,'#9ea099');BuildjoyAudio.sfx('mine')}else{state.food+=3;floatText(n.x,n.y-12,'+FOOD 3');particlesAt(n.x,n.y,'#b85f59');BuildjoyAudio.sfx('pickup')}n.hp--;if(n.hp<=0){n.alive=false;n.respawnAt=Date.now()+(n.type==='food'?7000:11000);rareDrop(n.x,n.y)}save('mutation');updateHud()}
function respawnNodes(){const now=Date.now();for(const n of state.nodes)if(!n.alive&&n.respawnAt&&now>=n.respawnAt){n.alive=true;n.hp=n.maxHp;n.respawnAt=0}}
function build(type){const r=RECIPES[type];if(!r)return;if(state.wood<r.wood||state.stone<r.stone){toast(`${r.name} · 素材不足 W${r.wood} / S${r.stone}`);BuildjoyAudio.sfx('cancel');return}if(type!=='barricade'&&state.buildings.some(b=>b.type===type)){toast(r.name+' は建設済み');return}const used=new Set(state.buildings.map(b=>b.slot));const candidates=BUILD_SLOTS.map((p,i)=>({p,i,d:Math.hypot(state.player.x-p[0],state.player.y-p[1])})).filter(v=>!used.has(v.i)).sort((a,b)=>a.d-b.d);if(!candidates.length){toast('建築スロットがいっぱい');return}const s=candidates[0];state.wood-=r.wood;state.stone-=r.stone;state.buildings.push({id:'b'+Date.now()+Math.random(),type,slot:s.i,x:s.p[0],y:s.p[1],hp:type==='barricade'?120:200,maxHp:type==='barricade'?120:200,builtAt:performance.now()});particlesAt(s.p[0],s.p[1],'#e1b769',18);floatText(s.p[0],s.p[1]-28,'BUILD!','#ffd785');BuildjoyAudio.sfx('build');toast(r.name+' 完成 · 街が広がった');closeSheet();save('mutation');updateHud()}
function hire(role){if(!state.buildings.some(b=>b.type==='hut')){toast('小屋を建てると雇用できる');return}const cost=role==='guard'?8:role==='food'?5:6;if(state.food<cost){toast('FOOD不足 · '+cost);return}if(state.workers.length>=200){toast('人口上限 200');return}state.food-=cost;const b=state.buildings.find(b=>b.type==='hut')||{x:0,y:0};state.workers.push({id:'w'+Date.now()+Math.random(),role,x:b.x+rnd(-20,20),y:b.y+rnd(10,30)});BuildjoyAudio.sfx('hire');toast((role==='wood'?'木こり':role==='stone'?'採石人':role==='food'?'採集人':'衛兵')+' が加入した');save('mutation');updateHud()}
function passiveWorkers(dt){passiveClock+=dt;if(passiveClock<1)return;passiveClock=0;for(const w of state.workers){if(w.role==='wood')state.wood+=state.buildings.some(b=>b.type==='lumber')?1.4:.85;else if(w.role==='stone')state.stone+=state.buildings.some(b=>b.type==='quarry')?1.1:.7;else if(w.role==='food')state.food+=.8}updateHud()}
function spawnNight(){if(nightSpawned||state.phase!=='night')return;nightSpawned=true;const count=Math.min(4,2+Math.floor(state.day/2));for(let i=0;i<count;i++){const side=i%4,x=side===0?-560:side===1?560:rnd(-300,300),y=side===2?-390:side===3?430:rnd(-220,280);state.zombies.push({id:'z'+Date.now()+i,x,y,hp:45,maxHp:45,hit:0,dead:false,cool:0})}toast('NIGHT · ゾンビが近づいている');BuildjoyAudio.sfx('warning');BuildjoyAudio.setMood('night')}
function updateZombies(dt){for(const z of state.zombies){if(z.dead)continue;if(z.hit>0)z.hit-=dt;if(z.cool>0)z.cool-=dt;let target={x:0,y:0,kind:'camp',obj:null};const bars=state.buildings.filter(b=>b.type==='barricade'&&b.hp>0);if(bars.length){bars.sort((a,b)=>Math.hypot(z.x-a.x,z.y-a.y)-Math.hypot(z.x-b.x,z.y-b.y));target={x:bars[0].x,y:bars[0].y,kind:'bar',obj:bars[0]}}const dx=target.x-z.x,dy=target.y-z.y,d=Math.hypot(dx,dy)||1;if(d>28){z.x+=dx/d*18*dt*state.boost;z.y+=dy/d*18*dt*state.boost}else if(z.cool<=0){z.cool=1.1;if(target.kind==='bar'){target.obj.hp-=7;particlesAt(target.obj.x,target.obj.y,'#8b6042',4)}else{state.wood=Math.max(0,state.wood-1);state.stone=Math.max(0,state.stone-.5)}BuildjoyAudio.sfx('hit')}}const guards=state.workers.filter(w=>w.role==='guard').length;if(guards){for(const z of state.zombies){if(z.dead)continue;z.hp-=guards*3*dt;if(z.hp<=0)killZombie(z)}}}
function killZombie(z){z.dead=true;state.gem+=Math.random()<.12?1:0;particlesAt(z.x,z.y,'#7e936c',8);floatText(z.x,z.y-18,'DOWN','#d9d1aa');BuildjoyAudio.sfx('pickup');save('mutation')}
function contextTarget(){let best=null,d=999;for(const z of state.zombies){if(z.dead)continue;const q=Math.hypot(state.player.x-z.x,state.player.y-z.y);if(q<55&&q<d){best={kind:'attack',obj:z};d=q}}for(const b of state.buildings){if(b.type==='barricade'&&b.hp<b.maxHp){const q=Math.hypot(state.player.x-b.x,state.player.y-b.y);if(q<55&&q<d){best={kind:'repair',obj:b};d=q}}}return best}
function refreshContext(){const t=contextTarget();$('context').hidden=!t;if(!t)return;if(t.kind==='attack'){$('context-main').textContent='ATTACK';$('context-sub').textContent='斧で敵を攻撃'}else{$('context-main').textContent='REPAIR';$('context-sub').textContent='WOOD 3 で修理'}}
function contextAct(){const t=contextTarget();if(!t)return;BuildjoyAudio.enable();if(t.kind==='attack'){t.obj.hp-=30;t.obj.hit=.12;particlesAt(t.obj.x,t.obj.y,'#c7b4a2',7);BuildjoyAudio.sfx('hit');if(t.obj.hp<=0)killZombie(t.obj)}else{if(state.wood<3){toast('WOOD不足 · 3');return}state.wood-=3;t.obj.hp=Math.min(t.obj.maxHp,t.obj.hp+35);BuildjoyAudio.sfx('build');toast('防壁を修理 +35')}save('mutation');updateHud()}
function phaseTick(dt){const mult=state.boost;state.cycle+=dt/180*mult;if(state.cycle>=1){state.cycle-=1;state.day++;nightSpawned=false;state.zombies=state.zombies.filter(z=>!z.dead);state.nightRewarded=false;BuildjoyAudio.setMood('day');toast('DAWN · 新しい朝 '+state.day);state.food+=2;BuildjoyAudio.sfx('hire');save('mutation')}const prev=state.phase;const [ph]=phaseInfo();state.phase=ph;if(prev!==ph){if(ph==='dusk'){toast('DUSK · そろそろ夜になる');BuildjoyAudio.sfx('warning')}if(ph==='night')spawnNight();if(ph==='day')BuildjoyAudio.setMood('day')}if(state.boostUntil&&Date.now()>=state.boostUntil){state.boost=1;state.boostUntil=0;toast('砂時計の効果が切れた · ×1');save('mutation')}}
function movement(dt){const p=state.player,m=input.mag,tx=input.x*95,ty=input.y*95,acc=m>.04?1-Math.pow(.00002,dt):1-Math.pow(.0004,dt);p.vx=lerp(p.vx,tx,acc);p.vy=lerp(p.vy,ty,acc);if(Math.abs(p.vx)<.5)p.vx=0;if(Math.abs(p.vy)<.5)p.vy=0;if(autoTarget&&m<.78){p.vx*=.7;p.vy*=.7}else{p.x=clamp(p.x+p.vx*dt*state.boost,WORLD.minX,WORLD.maxX);p.y=clamp(p.y+p.vy*dt*state.boost,WORLD.minY,WORLD.maxY)}if(Math.hypot(p.vx,p.vy)>4){p.walk+=dt*10;const ax=Math.abs(p.vx),ay=Math.abs(p.vy);p.dir=ax>ay?(p.vx>0?'right':'left'):(p.vy>0?'down':'up')}p.swing=Math.max(0,p.swing-dt*3.8);cam.x=p.x;cam.y=p.y-45}
function autoGather(dt){respawnNodes();const p=state.player;if(input.mag>.8){autoTarget=null;workClock=0;return}if(!autoTarget||!autoTarget.alive||Math.hypot(p.x-autoTarget.x,p.y-autoTarget.y)>49)autoTarget=nearestNode();if(!autoTarget){workClock=0;return}const d=Math.hypot(p.x-autoTarget.x,p.y-autoTarget.y);if(d>42)return;workClock+=dt*state.boost;if(workClock>=.48){workClock=0;workNode(autoTarget);if(!autoTarget.alive)autoTarget=null}}
function drawEffects(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=55*dt;p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}ctx.globalAlpha=clamp(p.life*2,0,1);rect(sx(p.x),sy(p.y),p.size,p.size,p.color);ctx.globalAlpha=1}for(let i=floats.length-1;i>=0;i--){const f=floats[i];f.y-=20*dt;f.life-=dt;if(f.life<=0){floats.splice(i,1);continue}ctx.globalAlpha=clamp(f.life,0,1);ctx.font='900 9px ui-monospace,monospace';ctx.textAlign='center';ctx.fillStyle='#000c';ctx.fillText(f.text,sx(f.x)+1,sy(f.y)+1);ctx.fillStyle=f.color;ctx.fillText(f.text,sx(f.x),sy(f.y));ctx.globalAlpha=1}}
function draw(){drawGround();const drawables=[];for(const n of state.nodes)if(n.alive)drawables.push({y:n.y,draw:()=>n.type==='tree'?drawTree(n):n.type==='rock'?drawRock(n):drawFood(n)});for(const b of state.buildings)drawables.push({y:b.y+20,draw:()=>drawBuilding(b)});state.workers.slice(0,14).forEach((w,i)=>drawables.push({y:w.y+16,draw:()=>drawWorker(w,i)}));for(const z of state.zombies)if(!z.dead)drawables.push({y:z.y+15,draw:()=>drawZombie(z)});drawables.push({y:state.player.y+16,draw:drawPlayer});drawables.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());if(state.phase==='night'){ctx.fillStyle='rgba(4,9,16,.24)';ctx.fillRect(0,0,W,H)}for(const b of state.buildings)if(b.type==='lantern')glow(sx(b.x),sy(b.y)-28,95)}
function tick(dt){movement(dt);autoGather(dt);passiveWorkers(dt);phaseTick(dt);updateZombies(dt);refreshContext();updateHud()}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;tick(dt);draw();drawEffects(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function vec(e){let dx=e.clientX-origin.x,dy=e.clientY-origin.y,mag=Math.hypot(dx,dy),max=55;if(mag<7){input={x:0,y:0,mag:0};return}if(mag>max){dx=dx/mag*max;dy=dy/mag*max;mag=max}input={x:dx/max,y:dy/max,mag:mag/max}}
canvas.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();BuildjoyAudio.enable();pointer=e.pointerId;origin={x:e.clientX,y:e.clientY};input={x:0,y:0,mag:0};try{canvas.setPointerCapture(pointer)}catch(_){}});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();vec(e)});function end(e){if(pointer===null||e.pointerId!==pointer)return;pointer=null;input={x:0,y:0,mag:0};save('mutation')}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
function openSheet(name){selectedPanel=name;$('sheet').hidden=false;$('sheet-title').textContent=name.toUpperCase();$('build-panel').hidden=name!=='build';$('workers-panel').hidden=name!=='workers';$('bag-panel').hidden=name!=='bag';$('save-panel').hidden=name!=='save';if(name==='workers')$('workers-lock').hidden=state.buildings.some(b=>b.type==='hut')}function closeSheet(){$('sheet').hidden=true;selectedPanel=null}
$('build-open').onclick=()=>openSheet('build');$('workers-open').onclick=()=>openSheet('workers');$('bag-open').onclick=()=>openSheet('bag');$('save-open').onclick=()=>openSheet('save');$('sheet-close').onclick=closeSheet;document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));document.querySelectorAll('[data-hire]').forEach(b=>b.onclick=()=>hire(b.dataset.hire));$('context').onclick=contextAct;$('manual-save').onclick=()=>{save('manual');toast('保存した')};$('sound').onclick=async()=>{$('sound').textContent=(await BuildjoyAudio.toggle())?'♪ OFF':'♪ ON'};$('speed').onclick=()=>{BuildjoyAudio.enable();if(state.hourglass<=0){toast('砂時計が必要');BuildjoyAudio.sfx('cancel');return}if(state.boost>=3){toast('最大×3');return}state.hourglass--;state.boost++;state.boostUntil=Date.now()+30000;toast(`砂時計 · ×${state.boost} / 30秒`);BuildjoyAudio.sfx('rare');save('mutation');updateHud()};
function serial(){return JSON.stringify(state)}function apply(o){if(!o||o.version!==10)return false;Object.assign(state,o);state.player={...state.player,...o.player};state.nodes=Array.isArray(o.nodes)?o.nodes:[];state.buildings=Array.isArray(o.buildings)?o.buildings:[];state.workers=Array.isArray(o.workers)?o.workers:[];state.zombies=Array.isArray(o.zombies)?o.zombies:[];return true}
function idbOpen(){return new Promise((res,rej)=>{if(!indexedDB)return rej();const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function mirror(){try{const db=await idbOpen(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(serial(),'current');tx.oncomplete=()=>db.close()}catch(_){}}
function save(reason='auto'){try{const prev=localStorage.getItem(SAVE);if(prev)localStorage.setItem(BACKUP,prev);state.lastSaved=Date.now();localStorage.setItem(SAVE,serial());if(reason!=='auto')mirror();updateHud();return true}catch(_){return false}}
async function load(){let ok=false;for(const key of[SAVE,BACKUP]){try{const raw=localStorage.getItem(key);if(raw&&apply(JSON.parse(raw))){ok=true;break}}catch(_){}}if(!ok){try{const db=await idbOpen(),raw=await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get('current');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();if(raw)ok=apply(JSON.parse(raw))}catch(_){}}if(!state.nodes.length)seededNodes();state.boost=state.boostUntil>Date.now()?clamp(state.boost,1,3):1;if(state.boost===1)state.boostUntil=0;updateHud();return ok}
setInterval(()=>save('auto'),1000);setInterval(mirror,5000);addEventListener('pagehide',()=>save('lifecycle'));addEventListener('beforeunload',()=>save('lifecycle'));document.addEventListener('visibilitychange',()=>{if(document.hidden)save('lifecycle')});
load().then(ok=>{updateHud();toast(ok?'AUTO SAVE · 続きから再開':'BUILDJOY v1.0 · 近くの木から自動採取');BuildjoyAudio.setMood(state.phase==='night'?'night':'day')});
window.BUILDJOY=Object.freeze({getState:()=>JSON.parse(serial()),save,build,hire});
})();