'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
const A=window.FrontierAudio||{enable(){},toggle:async()=>true,setMood(){},sfx(){}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const SAVE=document.body.dataset.save||'guild-infinity-v16-clean',BACKUP=SAVE+'-backup',WORLD={minX:-900,maxX:900,minY:-720,maxY:760};
const RANKS=['E','D','C','B','A','S'],POP_CAP=[20,45,80,130,200,300],WALL_CAP=[1,2,3,4,5,6];
const BUILD={
 hut:{name:'HOUSE',base:{wood:30,stone:10},repeat:true,max:5,unlock:0},warehouse:{name:'WAREHOUSE',base:{wood:65,stone:42},repeat:false,max:5,unlock:1},watchtower:{name:'WATCHTOWER',base:{wood:80,stone:50,iron:1},repeat:true,max:5,unlock:1},barracks:{name:'BARRACKS',base:{wood:105,stone:72,iron:2},repeat:false,max:5,unlock:2},guild:{name:'GUILD HALL',base:{wood:110,stone:90,renown:4},repeat:false,max:5,unlock:0},lantern:{name:'LANTERN',base:{wood:18,stone:6},repeat:true,max:3,unlock:0},lumber:{name:'LUMBER',base:{wood:55,stone:22},repeat:false,max:3,unlock:0},quarry:{name:'QUARRY',base:{wood:48,stone:38},repeat:false,max:3,unlock:0}
};
const ROLE_NAMES={wood:'木こり',stone:'採石人',food:'採集人',guard:'衛兵'};
const COLORS={wood:'#b87946',stone:'#9b9e92',food:'#c36658',hit:'#f3cda1',blood:'#b65449',heal:'#7ba07a'};
const state={version:16,day:1,cycle:.17,phase:'day',wood:0,stone:0,food:0,iron:0,renown:0,morale:100,hourglass:1,boost:1,boostUntil:0,player:{x:0,y:120,vx:0,vy:0,dir:'down',walk:0,swing:0},nodes:[],buildings:[],workers:[],enemies:[],projectiles:[],palisade:{built:false,level:0,hp:0,maxHp:0,builtAt:0},stats:{kills:0,nights:0,bestWall:0},lastSaved:0};
let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),last=performance.now(),pointer=null,origin={x:0,y:0},input={x:0,y:0,mag:0},dragged=false,currentPanel=null,nightWaveMask=0,lastPhase='day',autoTarget=null,playerWork=0;
const cam={x:0,y:20},fx=[],floats=[],slashes=[];
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const sx=x=>W/2+x-cam.x,sy=y=>H/2+y-cam.y;
function phaseInfo(c=state.cycle){if(c<.07)return['dawn','DAWN'];if(c<.69)return['day','DAY'];if(c<.78)return['dusk','DUSK'];return['night','NIGHT']}
function rankIndex(){const g=state.buildings.find(b=>b.type==='guild');return clamp(g?.level||0,0,5)}function rank(){return RANKS[rankIndex()]}
function settlementLevel(){return state.palisade.built?state.palisade.level:1}function bounds(level=settlementLevel()){const L=Math.max(1,level),hw=150+(L-1)*76,hh=108+(L-1)*54,gap=44+L*3;return{l:-hw,r:hw,t:-hh,b:hh,gap}}
function inside(x,y,B=bounds()){return x>B.l&&x<B.r&&y>B.t&&y<B.b}
function wallStats(level){const L=clamp(level,1,6),hp=[0,360,620,980,1450,2050,2800][L],wood=[0,70,110,170,250,360,500][L],stone=[0,20,48,90,150,230,340][L],iron=[0,0,0,1,2,4,7][L];return{hp,wood,stone,iron}}
function capacity(){const w=state.buildings.find(b=>b.type==='warehouse'),L=w?.level||0;return{wood:160+L*220,stone:100+L*150,food:100+L*90}}
function houseCapacity(){return state.buildings.filter(b=>b.type==='hut').reduce((s,b)=>s+4+b.level*3,0)}function maxWorkers(){return Math.min(POP_CAP[rankIndex()],houseCapacity())}
function capResource(type){if(document.body.dataset.edition==='chief'&&!window.Chief)return;const c=capacity()[type];state[type]=clamp(state[type],0,c)}function addRes(type,n){state[type]+=n;capResource(type)}
function toast(text,danger=false){$('ticker-text').textContent=text;$('ticker').classList.toggle('ticker-danger',danger);$('ticker').classList.remove('flash');void $('ticker').offsetWidth;$('ticker').classList.add('flash')}
function savePulse(){$('save-dot')?.classList.add('flash');setTimeout(()=>$('save-dot')?.classList.remove('flash'),160)}
function costFor(type,nextLevel=1){if(type==='palisade')return wallStats(nextLevel);const d=BUILD[type],count=state.buildings.filter(b=>b.type===type).length,scale=d.repeat?1+count*.24:1;const lvScale=nextLevel>1?1+(nextLevel-1)*.65:1;const c={};for(const [k,v] of Object.entries(d.base))c[k]=Math.ceil(v*scale*lvScale);return c}
function hasCost(c){return (!c.wood||state.wood>=c.wood)&&(!c.stone||state.stone>=c.stone)&&(!c.food||state.food>=c.food)&&(!c.iron||state.iron>=c.iron)&&(!c.renown||state.renown>=c.renown)}
function pay(c){for(const k of['wood','stone','food','iron','renown'])if(c[k])state[k]-=c[k]}
function fmtCost(c){return [['wood','W'],['stone','S'],['food','F'],['iron','I'],['renown','R']].filter(([k])=>c[k]).map(([k,l])=>`${l}${c[k]}`).join(' · ')}
function threat(){return Math.max(1,Math.floor(state.day*.72)+rankIndex()*2)}
function updateHud(){const c=capacity();$('wood').textContent=Math.floor(state.wood);$('stone').textContent=Math.floor(state.stone);$('food').textContent=Math.floor(state.food);$('wood-cap').textContent='/'+c.wood;$('stone-cap').textContent='/'+c.stone;$('food-cap').textContent='/'+c.food;$('people').textContent=`${state.workers.length}/${maxWorkers()}`;$('morale').textContent='M'+Math.round(state.morale);$('day').textContent='DAY '+state.day;const[ph,label]=phaseInfo();state.phase=ph;$('phase').textContent=label;const mins=Math.floor(state.cycle*1440),hh=String(Math.floor(mins/60)%24).padStart(2,'0'),mm=String(mins%60).padStart(2,'0');$('clock').textContent=hh+':'+mm;$('rank').textContent='RANK '+rank();$('threat').textContent='THREAT '+threat();$('meta').textContent=`IRON ${state.iron} · RENOWN ${state.renown}`;if($('speed'))$('speed').textContent='×'+state.boost;$('people-caption').textContent=maxWorkers()?`${state.workers.length}/${maxWorkers()}`:'小屋で解禁';$('people-lock').hidden=maxWorkers()>0;$('record-rank').textContent=rank();$('nights').textContent=state.stats.nights;$('kills').textContent=state.stats.kills;$('best-wall').textContent='Lv.'+state.stats.bestWall;$('iron').textContent=state.iron;$('renown').textContent=state.renown;updateObjective();updateBuildSheet();updatePeopleSummary()}
function updateObjective(){let text='木を集めて小屋を建てる';if(state.buildings.some(b=>b.type==='hut'))text='STONEを集めて防壁を完成させる';if(state.palisade.built)text='夜までに衛兵か見張り台を用意する';if(state.stats.nights>=1)text='GUILD HALLを強化してRANK Dへ';if(rankIndex()>=1)text='城壁を拡張し、外の強敵に備える';if(rankIndex()>=2)text='IRONを集めて兵舎と見張り台を強化';if(state.day>=8)text='RANKを上げてさらに大きい街へ';$('objective-text').textContent=text}
function updateBuildSheet(){for(const t of Object.keys(BUILD)){const el=$('cost-'+t);if(!el)continue;const d=BUILD[t],existing=state.buildings.filter(b=>b.type===t),locked=rankIndex()<d.unlock||(!d.repeat&&existing.length>0);const c=costFor(t,1);el.textContent=locked?(rankIndex()<d.unlock?`RANK ${RANKS[d.unlock]}で解禁`:'建設済み'):fmtCost(c);el.closest('button')?.classList.toggle('locked',locked)}const wl=$('wall-label'),wd=$('wall-desc'),wc=$('cost-palisade'),next=state.palisade.built?state.palisade.level+1:1;if(next>6){wl.textContent='PALISADE MAX';wd.textContent='最大拡張済み';wc.textContent='Lv.6'}else{const rankCap=WALL_CAP[rankIndex()],c=wallStats(next);wl.textContent=state.palisade.built?`PALISADE Lv.${state.palisade.level} → ${next}`:'PALISADE';wd.textContent=next>rankCap?`RANK ${RANKS[Math.min(5,next-1)]}が必要`:'敷地・耐久・見た目が成長';wc.textContent=fmtCost(c)}renderUpgrades();renderUnlocks()}
function renderUpgrades(){const el=$('upgrade-grid');if(!el)return;const cards=[];for(const b of state.buildings){const d=BUILD[b.type];if(!d||b.level>=d.max)continue;if(cards.some(x=>x.type===b.type))continue;const c=costFor(b.type,b.level+1);cards.push({type:b.type,name:d.name,L:b.level,c})}el.innerHTML=cards.length?cards.map(x=>`<button data-upgrade="${x.type}" ${hasCost(x.c)?'':'disabled'}><b>${x.name} Lv.${x.L} → ${x.L+1}</b><small>${upgradeBenefit(x.type,x.L+1)}</small><em>${fmtCost(x.c)}</em></button>`).join(''):'<div class="notice">建物を建てると強化が解禁</div>';el.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>upgrade(b.dataset.upgrade))}
function upgradeBenefit(type,L){if(type==='hut')return`人口枠 +${4+L*3}`;if(type==='warehouse')return'資源上限を大幅拡張';if(type==='watchtower')return'射程・威力・連射UP';if(type==='barracks')return'衛兵攻撃力UP';if(type==='guild')return`RANK ${RANKS[L]} / 上限解放`;if(type==='lantern')return'夜の照明範囲UP';if(type==='lumber')return'木こり効率UP';if(type==='quarry')return'採石効率UP';return'性能UP'}
function renderUnlocks(){const el=$('unlock-list');if(!el)return;el.innerHTML=[['D','WAREHOUSE / WATCHTOWER / WALL Lv.2'],['C','BARRACKS / WALL Lv.3 / POP 80'],['B','WALL Lv.4 / POP 130'],['A','WALL Lv.5 / POP 200'],['S','WALL Lv.6 / POP 300']].map((x,i)=>`<p>${rankIndex()>i?'✓':'·'} RANK ${x[0]} — ${x[1]}</p>`).join('')}
function updatePeopleSummary(){const c={wood:0,stone:0,food:0,guard:0};state.workers.forEach(w=>c[w.role]++);$('worker-summary').innerHTML=Object.entries(c).map(([k,v])=>`<span><small>${ROLE_NAMES[k]}</small><b>${v}</b></span>`).join('')}
function node(id,x,y,type,starter=false){const hp=type==='tree'?18:type==='rock'?26:12;return{id,x,y,type,hp,maxHp:hp,alive:true,respawnAt:0,starter,seed:Math.random()}}
function outsidePos(pad=80){const B=bounds(),a=Math.random()*Math.PI*2,rx=Math.max(Math.abs(B.l),Math.abs(B.r))+pad+rnd(40,300),ry=Math.max(Math.abs(B.t),Math.abs(B.b))+pad+rnd(40,250);return{x:clamp(Math.cos(a)*rx,WORLD.minX+40,WORLD.maxX-40),y:clamp(Math.sin(a)*ry,WORLD.minY+40,WORLD.maxY-40)}}
function seedNodes(){let id=0;const starter=[[-52,148,'tree'],[54,150,'tree'],[-105,105,'tree'],[108,108,'tree'],[-118,56,'rock'],[120,60,'rock'],[-32,205,'food'],[75,210,'food']];state.nodes=starter.map(v=>node('n'+id++,...v,true));for(let i=0;i<28;i++){const p=outsidePos();state.nodes.push(node('n'+id++,p.x,p.y,'tree'))}for(let i=0;i<18;i++){const p=outsidePos(95);state.nodes.push(node('n'+id++,p.x,p.y,'rock'))}for(let i=0;i<12;i++){const p=outsidePos(75);state.nodes.push(node('n'+id++,p.x,p.y,'food'))}}
function relocate(n){const p=outsidePos(90);n.x=p.x;n.y=p.y;n.alive=true;n.hp=n.maxHp;n.respawnAt=0;n.starter=false}
function clearInside(){if(!state.palisade.built)return;for(const n of state.nodes)if(n.alive&&inside(n.x,n.y))relocate(n)}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function poly(p,c){ctx.fillStyle=c;ctx.beginPath();p.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fill()}function shadow(x,y,w,h=6,a=.42){rect(x-w/2,y-h/2,w,h,`rgba(0,0,0,${a})`)}function glow(x,y,r,a=.2){ctx.save();ctx.globalCompositeOperation='screen';const g=ctx.createRadialGradient(x,y,2,x,y,r);g.addColorStop(0,`rgba(255,177,86,${a})`);g.addColorStop(1,'rgba(255,177,86,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore()}
function drawGround(){const ph=state.phase,top=ph==='night'?'#0c1a20':ph==='dusk'?'#31434a':ph==='dawn'?'#3a574e':'#3f604c',bot=ph==='night'?'#14241d':ph==='dusk'?'#504b36':'#4c694e';const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,top);g.addColorStop(1,bot);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<120;i++){const wx=(i*139)%1750-875,wy=(i*91)%1400-700,x=sx(wx),y=sy(wy);if(x<0||x>W||y<0||y>H)continue;rect(x,y,2,1,i%3?'#9aa36a21':'#cab36b18')}const B=bounds();if(state.palisade.built){ctx.fillStyle='rgba(160,125,74,.18)';ctx.fillRect(sx(B.l+6),sy(B.t+6),B.r-B.l-12,B.b-B.t-12)}const cx=sx(0),cy=sy(0);rect(cx-7,cy-175,14,310,'rgba(166,139,84,.12)');rect(cx-210,cy+20,420,12,'rgba(166,139,84,.10)');for(let i=-4;i<=4;i++){rect(cx-82+i*19,cy+17,10,2,'rgba(208,179,112,.10)')}drawBaseCamp()}
function drawBaseCamp(){const x=sx(0),y=sy(24),t=performance.now()/180;shadow(x,y+14,38,7,.45);for(const a of[-11,0,11]){ctx.save();ctx.translate(x+a,y+9);ctx.rotate(a/38);rect(-9,-2,18,4,'#583824');ctx.restore()}const flick=Math.sin(t)*2;poly([[x-9,y+8],[x-4,y-10-flick],[x,y+2],[x+5,y-18+flick],[x+10,y+8]],'#d9783f');poly([[x-5,y+7],[x,y-8+flick],[x+5,y+7]],'#f4c35f');glow(x,y-2,48,.10);rect(x-52,y-34,4,40,'#62432e');poly([[x-48,y-33],[x-20,y-27],[x-48,y-17]],'#876339');ctx.fillStyle='#d8bb72';ctx.font='900 9px monospace';ctx.textAlign='center';ctx.fillText('∞',x-37,y-22);rect(x+34,y+2,24,16,'#6a4a32');rect(x+36,y+4,20,4,'#b1814e')}
function drawNode(n){const x=sx(n.x),y=sy(n.y);if(n.type==='tree'){shadow(x,y+20,31);rect(x-5,y-5,10,28,'#5d3c29');poly([[x-23,y-18],[x-13,y-40],[x+3,y-50],[x+20,y-35],[x+23,y-15],[x+8,y-8],[x-16,y-8]],'#183d2d');poly([[x-14,y-30],[x-5,y-46],[x+12,y-43],[x+18,y-27],[x+6,y-18],[x-12,y-19]],'#29533b')}else if(n.type==='rock'){shadow(x,y+10,30);poly([[x-15,y+7],[x-10,y-8],[x-1,y-15],[x+12,y-8],[x+16,y+4],[x+8,y+11],[x-10,y+10]],'#5d6662');poly([[x-8,y-5],[x-1,y-11],[x+8,y-7],[x+10,y-1],[x+2,y+2]],'#8f9187')}else{shadow(x,y+9,25);poly([[x-13,y+8],[x-8,y-7],[x+3,y-11],[x+12,y+5],[x+7,y+11],[x-8,y+11]],'#294936');for(const q of[-7,0,7])rect(x+q-1,y,3,3,'#c85e55')}}
const PAL=['#d8ad83','#c79067','#e2ba90','#b87e59'];function drawPerson(o,role='wood',enemy=false){const x=sx(o.x),y=sy(o.y),walk=Math.sin((o.anim||0)*2)*1.5,bob=Math.abs(Math.sin(o.anim||0))*1.2;shadow(x,y+17,19,5,.5);if(enemy){const t=o.type||'walker',c=t==='brute'?'#6e6359':t==='runner'?'#6d7d55':t==='spitter'?'#536e68':t==='warden'?'#7b4e53':'#65785e',s=t==='brute'?1.35:t==='warden'?1.55:1;ctx.save();ctx.translate(x,y);ctx.scale(s,s);rect(-7,-11+bob,14,18,o.hit>0?'#d6c5a2':c);rect(-5,-21+bob,10,10,'#aaa28a');rect(-4,-18+bob,2,2,'#391e20');rect(2,-18+bob,2,2,'#391e20');rect(-6,7-bob,4,10+walk,'#3c3432');rect(2,7+bob,4,10-walk,'#3c3432');if(t==='spitter')rect(7,-9+bob,5,5,'#8a9d69');ctx.restore();return}const skin=PAL[(o.seed||0)%PAL.length|0],cloth=role==='guard'?'#52667a':role==='stone'?'#75624f':role==='food'?'#657752':'#8a5d48';rect(x-6,y+6+walk,4,10,'#303637');rect(x+2,y+6-walk,4,10,'#303637');rect(x-8,y-10+bob,16,18,cloth);rect(x-6,y-21+bob,12,10,skin);rect(x-7,y-26+bob,14,6,'#3b2d24');if(role==='guard'){ctx.strokeStyle='#c6ad78';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+8,y-14);ctx.lineTo(x+8,y+12);ctx.stroke();poly([[x+8,y-18],[x+5,y-12],[x+11,y-12]],'#d6d1bf')}else{ctx.strokeStyle='#795536';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+7,y-9);ctx.lineTo(x+13,y+3);ctx.stroke();rect(x+11,y-1,6,4,'#abb0aa')}}
function drawPlayer(){const p=state.player;drawPerson({...p,seed:0},'wood');if(p.swing>0){const x=sx(p.x),y=sy(p.y),a=(1-p.swing)*2.2-.4;ctx.strokeStyle='#d6be89';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x+5,y-5,22,a,a+1.3);ctx.stroke()}}
function buildingSize(type,L){if(type==='guild')return[86+L*6,58+L*3];if(type==='watchtower')return[38,56+L*5];if(type==='lantern')return[24,48];return[62+L*3,40+L*2]}
function drawBuilding(b){const x=sx(b.x),y=sy(b.y),L=b.level||1,[w,h]=buildingSize(b.type,L);shadow(x,y+18,w,7,.5);if(b.type==='hut'){rect(x-w/2,y-h/4,w,h/2,'#76583f');poly([[x-w*.58,y-h/4],[x,y-h*.7],[x+w*.58,y-h/4]],L>=4?'#76513b':'#9c6841');rect(x-7,y+2,14,18,'#2e251f');for(let i=0;i<Math.min(3,L);i++)rect(x-w/2+10+i*17,y-8,8,8,'#e1b76d')}else if(b.type==='warehouse'){rect(x-w/2,y-h/4,w,h/2,'#5d4c3d');poly([[x-w*.55,y-h/4],[x,y-h*.62],[x+w*.55,y-h/4]],'#6e5339');rect(x-12,y-1,24,19,'#2f2a23');for(let i=-1;i<=1;i++)rect(x+i*15-5,y-10,10,5,'#b3834c')}else if(b.type==='watchtower'){rect(x-5,y-h*.55,10,h,'#5c4935');rect(x-18,y-h*.58,36,17,'#574638');poly([[x-20,y-h*.58],[x,y-h*.78],[x+20,y-h*.58]],'#85573a');rect(x-4,y-h*.51,8,8,'#e4b861')}else if(b.type==='barracks'){rect(x-w/2,y-h/4,w,h/2,'#645043');poly([[x-w*.56,y-h/4],[x,y-h*.64],[x+w*.56,y-h/4]],'#70463a');rect(x-9,y-1,18,19,'#2d2622');rect(x-23,y-11,11,9,'#bd8b55');rect(x+12,y-11,11,9,'#bd8b55');rect(x-2,y-h*.44,4,15,'#8a3d37')}else if(b.type==='guild'){rect(x-w/2,y-h/4,w,h/2,'#6f543e');rect(x-w*.42,y-h*.48,w*.84,h*.25,'#7f6042');poly([[x-w*.52,y-h*.48],[x,y-h*.75],[x+w*.52,y-h*.48]],'#7d4f38');rect(x-10,y,20,18,'#29221d');rect(x-8,y-h*.42,16,11,'#d3aa61');ctx.fillStyle='#1d2f34';ctx.font='900 10px monospace';ctx.textAlign='center';ctx.fillText('∞',x,y-h*.33)}else if(b.type==='lumber'){rect(x-w/2,y-h/4,w,h/2,'#6d4d38');for(let i=-2;i<=2;i++)rect(x+i*11-4,y+13,8,14,'#4a3325')}else if(b.type==='quarry'){rect(x-w/2,y-2,w,h/2,'#555d59');poly([[x-w/2,y-2],[x-12,y-h*.4],[x+17,y-h*.35],[x+w/2,y-2]],'#737a72')}else if(b.type==='lantern'){rect(x-3,y-28,6,43,'#704c31');rect(x-11,y-34,22,10,'#242a2a');rect(x-7,y-32,14,6,'#e4b059');if(state.phase==='night')glow(x,y-29,70+L*18,.23)}}
function drawWall(){if(!state.palisade.built)return;const B=bounds(),L=state.palisade.level,stone=L>=4;for(let x=B.l;x<=B.r;x+=14){if(x>-B.gap/2&&x<B.gap/2)continue;drawWallSeg(x,B.t,stone);drawWallSeg(x,B.b,stone)}for(let y=B.t+14;y<B.b;y+=14){drawWallSeg(B.l,y,stone);drawWallSeg(B.r,y,stone)}const gy=sy(B.b),gx=sx(0);rect(gx-B.gap/2-5,gy-20,10,34,stone?'#777970':'#61402a');rect(gx+B.gap/2-5,gy-20,10,34,stone?'#777970':'#61402a');rect(gx-B.gap/2+5,gy-13,B.gap-10,4,'#9a6b43')}
function drawWallSeg(wx,wy,stone){const x=sx(wx),y=sy(wy);shadow(x,y+8,12,4,.4);if(stone){rect(x-6,y-13,12,27,'#777a72');rect(x-4,y-10,8,22,'#96958b')}else{rect(x-4,y-11,8,24,'#65432c');poly([[x-4,y-11],[x,y-17],[x+4,y-11]],'#8e5f3a')}}
function fxBurst(x,y,color,n=8,pow=1){for(let i=0;i<n;i++)fx.push({x,y,vx:rnd(-55,55)*pow,vy:rnd(-70,-20)*pow,life:rnd(.3,.65),size:rnd(2,4),color})}function floatText(x,y,text,color='#f0ce88'){floats.push({x,y,text,color,life:.9})}function slash(x,y,angle=0,color='#efc681'){slashes.push({x,y,angle,life:.22,color})}
function drawEffects(dt){for(let i=fx.length-1;i>=0;i--){const p=fx[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=105*dt;p.life-=dt;if(p.life<=0){fx.splice(i,1);continue}ctx.globalAlpha=clamp(p.life*2,0,1);rect(sx(p.x),sy(p.y),p.size,p.size,p.color);ctx.globalAlpha=1}for(let i=floats.length-1;i>=0;i--){const f=floats[i];f.y-=22*dt;f.life-=dt;if(f.life<=0){floats.splice(i,1);continue}ctx.globalAlpha=clamp(f.life*1.5,0,1);ctx.font='900 9px monospace';ctx.textAlign='center';ctx.fillStyle='#000c';ctx.fillText(f.text,sx(f.x)+1,sy(f.y)+1);ctx.fillStyle=f.color;ctx.fillText(f.text,sx(f.x),sy(f.y));ctx.globalAlpha=1}for(let i=slashes.length-1;i>=0;i--){const s=slashes[i];s.life-=dt;if(s.life<=0){slashes.splice(i,1);continue}ctx.save();ctx.translate(sx(s.x),sy(s.y));ctx.rotate(s.angle);ctx.globalAlpha=s.life/.22;ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,18,-1.1,.7);ctx.stroke();ctx.restore()}}
