function lanternRadius(b){return 130+(b.level||1)*38}
function spawnSuppressed(x,y){for(const b of state.buildings){if(b.type!=='lantern')continue;if(Math.hypot(x-b.x,y-b.y)<=lanternRadius(b))return true}return false}
function spawnPoint(i){const B=bounds(),side=i%4;return{x:side===0?B.l-150:side===1?B.r+150:rnd(B.l-180,B.r+180),y:side===2?B.t-140:side===3?B.b+155:rnd(B.t-130,B.b+130)}}
function spawnWave(wave){const count=Math.min(18,3+wave+Math.floor(state.day*.55)+rankIndex());let spawned=0,blocked=0;for(let i=0;i<count;i++){let p=null;for(let attempt=0;attempt<10;attempt++){const q=spawnPoint(i+attempt);if(!spawnSuppressed(q.x,q.y)){p=q;break}}if(!p){blocked++;continue}const type=enemyType(i,wave),s=enemySpec(type,wave);state.enemies.push({id:'e'+Date.now()+i+Math.random(),type,x:p.x,y:p.y,hp:s.hp,maxHp:s.hp,spd:s.spd,dmg:s.dmg,anim:rnd(0,6),cool:rnd(0,.7),hit:0,dead:false,death:0,seed:i,sunBurn:false,burnFx:0});spawned++}if(spawned)toast(`NIGHT WAVE ${wave+1} · ${spawned}体${blocked?` · 灯火が${blocked}体を抑止`:''}`,true);else toast(`LANTERN SAFE ZONE · WAVE ${wave+1} を完全抑止`);A.setMood('night');A.sfx(blocked?'confirm':'warning')}
function nearestWallPoint(z){const B=bounds(),x=clamp(z.x,B.l,B.r),y=clamp(z.y,B.t,B.b),a=[{x,y:B.t},{x,y:B.b},{x:B.l,y},{x:B.r,y}];return a.sort((p,q)=>dist(z,p)-dist(z,q))[0]}
function damageEnemy(e,dmg,ax=e.x,ay=e.y,guard=false){if(e.dead)return;e.hp-=dmg;e.hit=.12;const ang=Math.atan2(e.y-ay,e.x-ax);e.x+=Math.cos(ang)*4;e.y+=Math.sin(ang)*4;slash(e.x,e.y,ang,guard?'#d3d9c6':'#f0c278');fxBurst(e.x,e.y,'#d0b08c',6);floatText(e.x,e.y-22,'-'+Math.round(dmg),'#ffd19b');A.sfx('hit');if(e.hp<=0)killEnemy(e)}
function killEnemy(e){if(e.dead)return;e.dead=true;e.death=.68;state.stats.kills++;const dropChance=e.type==='brute'?.7:e.type==='warden'?1:e.type==='spitter'?.45:.18;if(Math.random()<dropChance){const n=e.type==='warden'?3:1;state.iron+=n;floatText(e.x,e.y-30,'IRON +'+n,'#a9c4c1')}if(Math.random()<(e.type==='warden'?.9:.12)){state.renown++;floatText(e.x,e.y-40,'RENOWN +1','#e1bd6a')}fxBurst(e.x,e.y,e.sunBurn?'#dc8d4e':'#7b8f6a',18,1.25);toast(`${e.type.toUpperCase()} DOWN`);A.sfx('pickup')}
function ensureLifeState(){if(!Number.isFinite(state.player.maxHp))state.player.maxHp=120;if(!Number.isFinite(state.player.hp))state.player.hp=state.player.maxHp;if(!Number.isFinite(state.player.attackCd))state.player.attackCd=0;if(!Number.isFinite(state.player.down))state.player.down=0;if(!Number.isFinite(state.player.invuln))state.player.invuln=0;for(const w of state.workers)ensureWorkerVitals(w)}
function humanAccessible(e,h){if(!state.palisade.built||state.palisade.hp<=0)return true;const B=bounds();return inside(e.x,e.y,B)===inside(h.x,h.y,B)}
function nearestHuman(e){const candidates=[];if(state.player.down<=0&&humanAccessible(e,state.player))candidates.push({kind:'player',obj:state.player,d:dist(e,state.player)});for(const w of state.workers){ensureWorkerVitals(w);if(w.dead||!humanAccessible(e,w))continue;candidates.push({kind:'worker',obj:w,d:dist(e,w)})}candidates.sort((a,b)=>a.d-b.d);return candidates[0]||null}
function chooseEnemyTarget(e){const human=nearestHuman(e);if(human&&human.d<260)return{x:human.obj.x,y:human.obj.y,kind:human.kind,obj:human.obj,wall:false};if(state.palisade.built&&state.palisade.hp>0&&!inside(e.x,e.y,bounds())){const p=nearestWallPoint(e);return{...p,kind:'wall',obj:state.palisade,wall:true}}if(human)return{x:human.obj.x,y:human.obj.y,kind:human.kind,obj:human.obj,wall:false};return{x:0,y:20,kind:'settlement',obj:null,wall:false}}
function damagePlayer(dmg,e){const p=state.player;if(p.down>0||p.invuln>0)return;p.hp=Math.max(0,p.hp-dmg);p.invuln=.18;p.vx+=(p.x-e.x)*.18;p.vy+=(p.y-e.y)*.18;floatText(p.x,p.y-28,'-'+Math.round(dmg),'#ff9f91');fxBurst(p.x,p.y,'#d56f61',7,.8);A.sfx('hit');if(p.hp<=0){p.down=1.35;p.vx=p.vy=0;state.morale=Math.max(0,state.morale-6);toast('PLAYER DOWN · 拠点へ退避',true)}}
function damageWorker(w,dmg,e){if(w.dead)return;ensureWorkerVitals(w);w.hp=Math.max(0,w.hp-dmg);w.hit=.18;const dx=w.x-e.x,dy=w.y-e.y,d=Math.hypot(dx,dy)||1;w.x+=dx/d*3;w.y+=dy/d*3;floatText(w.x,w.y-25,'-'+Math.round(dmg),'#ffb0a0');fxBurst(w.x,w.y,'#c96a5f',6,.75);A.sfx('hit');if(w.hp<=0){w.dead=true;w.death=.85;w.targetId=null;state.morale=Math.max(0,state.morale-8);toast(`${ROLE_NAMES[w.role]} が倒れた`,true);fxBurst(w.x,w.y,'#9e6a5e',12,1.1)}}
function updateHumanLife(dt){const p=state.player;p.attackCd=Math.max(0,(p.attackCd||0)-dt);p.invuln=Math.max(0,(p.invuln||0)-dt);if(p.down>0){p.down-=dt;if(p.down<=0){p.x=0;p.y=70;p.hp=Math.ceil(p.maxHp*.7);p.invuln=1.4;toast('主人公が拠点へ戻った · HP 70%')}}for(const w of state.workers){if(w.dead)w.death-=dt}state.workers=state.workers.filter(w=>!w.dead||w.death>0)}
function playerAutoCombat(){const p=state.player;if(p.down>0||p.attackCd>0)return;let best=null,bd=62;for(const e of state.enemies){if(e.dead)continue;const d=dist(p,e);if(d<bd){best=e;bd=d}}if(!best)return;p.attackCd=.46;p.swing=1;damageEnemy(best,28+rankIndex()*3,p.x,p.y,false)}
function igniteDawnSurvivors(){let n=0;for(const e of state.enemies){if(e.dead)continue;e.sunBurn=true;e.burnFx=0;n++}if(n){toast(`DAWN · 日光で${n}体が燃え始めた`);A.sfx('warning')}}
function sunBurn(e,dt){if(!e.sunBurn||e.dead||!(state.phase==='dawn'||state.phase==='day'))return false;e.burnFx=(e.burnFx||0)-dt;const dps=7+e.maxHp*.10;e.hp-=dps*dt;if(e.burnFx<=0){e.burnFx=.24;fxBurst(e.x+rnd(-4,4),e.y-10+rnd(-5,5),'#ef8d46',4,.7);if(Math.random()<.35)floatText(e.x,e.y-28,'BURN','#ffc06d')}if(e.hp<=0)killEnemy(e);return true}
function fireAtHuman(e,target){const kind=target.kind,id=kind==='worker'?target.obj.id:null;state.projectiles.push({kind:'spit',targetKind:kind,targetId:id,x:e.x,y:e.y-10,tx:target.obj.x,ty:target.obj.y,target:null,speed:130,damage:e.dmg,life:2.2})}
function updateEnemies(dt){for(const e of state.enemies){if(e.dead){e.death-=dt;e.y+=10*dt;continue}const burning=sunBurn(e,dt);if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.cool=Math.max(0,e.cool-dt);e.anim+=dt*e.spd*.16;const target=chooseEnemyTarget(e),d=dist(e,target),speedMul=burning?.58:1;if(e.type==='spitter'&&!target.wall&&(target.kind==='player'||target.kind==='worker')&&d<150&&d>52&&e.cool<=0){e.cool=1.4;fireAtHuman(e,target);continue}if(e.type==='spitter'&&target.wall&&d<145&&e.cool<=0){e.cool=1.35;state.projectiles.push({kind:'spit',targetKind:'wall',targetId:null,x:e.x,y:e.y-10,tx:target.x,ty:target.y,target:null,speed:130,damage:e.dmg,life:2.2});continue}if(d>22){e.x+=(target.x-e.x)/d*e.spd*speedMul*dt;e.y+=(target.y-e.y)/d*e.spd*speedMul*dt}else if(e.cool<=0){e.cool=e.type==='runner'?.58:e.type==='brute'?1.15:.88;if(target.kind==='wall'){state.palisade.hp=Math.max(0,state.palisade.hp-e.dmg);fxBurst(target.x,target.y,'#9c6546',7);floatText(target.x,target.y-10,'-'+e.dmg,'#ef9b86');A.sfx('hit');if(state.palisade.hp<=0)toast('防壁崩壊 · 敵が街へ侵入',true)}else if(target.kind==='player')damagePlayer(e.dmg,e);else if(target.kind==='worker')damageWorker(target.obj,e.dmg,e);else{state.morale=Math.max(0,state.morale-.04*e.dmg)}}}state.enemies=state.enemies.filter(e=>!e.dead||e.death>0);updateProjectiles(dt)}
function updateProjectiles(dt){for(let i=state.projectiles.length-1;i>=0;i--){const p=state.projectiles[i];p.life-=dt;if(p.life<=0){state.projectiles.splice(i,1);continue}if(p.kind==='arrow'&&p.target&&!p.target.dead){p.tx=p.target.x;p.ty=p.target.y}if(p.kind==='spit'&&p.targetKind==='player'){if(state.player.down>0){state.projectiles.splice(i,1);continue}p.tx=state.player.x;p.ty=state.player.y}if(p.kind==='spit'&&p.targetKind==='worker'){const w=state.workers.find(w=>w.id===p.targetId&&!w.dead);if(!w){state.projectiles.splice(i,1);continue}p.tx=w.x;p.ty=w.y}const dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy)||1,step=p.speed*dt;if(d<=step+4){if(p.kind==='arrow'&&p.target&&!p.target.dead)damageEnemy(p.target,p.damage,p.x,p.y,true);else if(p.kind==='spit'){if(p.targetKind==='player')damagePlayer(p.damage,{x:p.x,y:p.y});else if(p.targetKind==='worker'){const w=state.workers.find(w=>w.id===p.targetId&&!w.dead);if(w)damageWorker(w,p.damage,{x:p.x,y:p.y})}else if(p.targetKind==='wall'&&state.palisade.hp>0){state.palisade.hp=Math.max(0,state.palisade.hp-p.damage);fxBurst(p.tx,p.ty,'#7c9c6d',8);floatText(p.tx,p.ty-10,'-'+p.damage,'#9bd08a')}}state.projectiles.splice(i,1);continue}p.x+=dx/d*step;p.y+=dy/d*step}}
function drawProjectile(p){const x=sx(p.x),y=sy(p.y);if(p.kind==='arrow'){ctx.strokeStyle='#d6c18c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-5,y);ctx.lineTo(x+5,y);ctx.stroke()}else{rect(x-3,y-3,6,6,'#7fad6f');glow(x,y,18,.09)}}
function drawEnemy(e){ctx.save();if(e.dead)ctx.globalAlpha=clamp(e.death/.68,0,1);drawPerson(e,null,true);ctx.restore();const x=sx(e.x),y=sy(e.y);if(e.sunBurn&&!e.dead&&(state.phase==='dawn'||state.phase==='day')){glow(x,y-8,25,.08);rect(x-3,y-28,3,7,'#f1a24b');rect(x+2,y-24,3,6,'#d96d3e')}if(!e.dead&&(e.hit>0||e.type==='brute'||e.type==='warden')){const w=e.type==='warden'?40:28;rect(x-w/2,y-34,w,4,'#271d1b');rect(x-w/2,y-34,w*clamp(e.hp/e.maxHp,0,1),4,e.type==='warden'?'#b45858':'#c07b61')}}
function drawWorkerEntity(w){ctx.save();if(w.dead)ctx.globalAlpha=clamp(w.death/.85,0,1);drawPerson(w,w.role);ctx.restore();if(!w.dead&&Number.isFinite(w.hp)&&w.hp<w.maxHp){const x=sx(w.x),y=sy(w.y)-29;rect(x-11,y,22,3,'#281b19');rect(x-11,y,22*clamp(w.hp/w.maxHp,0,1),3,'#79a26d')}}
function drawPlayerEntity(){drawPlayer();const p=state.player,x=sx(p.x),y=sy(p.y)-31;if(p.hp<p.maxHp||p.down>0){rect(x-14,y,28,4,'#281b19');rect(x-14,y,28*clamp(p.hp/p.maxHp,0,1),4,p.down>0?'#7a5148':'#79a26d')}}
function wallCollision(x,y,r=9){if(!state.palisade.built||state.palisade.hp<=0)return false;const B=bounds(),th=9;if(x+r>B.l-th&&x-r<B.r+th){if(y+r>B.t-th&&y-r<B.t+th)return true;if(y+r>B.b-th&&y-r<B.b+th&&!(x>-B.gap/2+r&&x<B.gap/2-r))return true}if(y+r>B.t-th&&y-r<B.b+th){if(x+r>B.l-th&&x-r<B.l+th)return true;if(x+r>B.r-th&&x-r<B.r+th)return true}return false}
function movement(dt){const p=state.player;if(p.down>0){p.vx=p.vy=0;cam.x=lerp(cam.x,p.x,1-Math.pow(.0005,dt));cam.y=lerp(cam.y,p.y-40,1-Math.pow(.0005,dt));return}const tx=input.x*145,ty=input.y*145,a=input.mag>.04?1-Math.pow(.00002,dt):1-Math.pow(.0003,dt);p.vx=lerp(p.vx,tx,a);p.vy=lerp(p.vy,ty,a);if(Math.abs(p.vx)<.3)p.vx=0;if(Math.abs(p.vy)<.3)p.vy=0;let nx=clamp(p.x+p.vx*dt*state.boost,WORLD.minX,WORLD.maxX),ny=p.y;if(!wallCollision(nx,ny))p.x=nx;else p.vx=0;nx=p.x;ny=clamp(p.y+p.vy*dt*state.boost,WORLD.minY,WORLD.maxY);if(!wallCollision(nx,ny))p.y=ny;else p.vy=0;if(Math.hypot(p.vx,p.vy)>3){p.walk+=dt*10;const ax=Math.abs(p.vx),ay=Math.abs(p.vy);p.dir=ax>ay?(p.vx>0?'right':'left'):(p.vy>0?'down':'up')}p.swing=Math.max(0,p.swing-dt*3.7);cam.x=lerp(cam.x,p.x,1-Math.pow(.0005,dt));cam.y=lerp(cam.y,p.y-40,1-Math.pow(.0005,dt))}
function repairTarget(){if(!state.palisade.built||state.palisade.hp>=state.palisade.maxHp||state.wood<5)return false;const B=bounds(),q=Math.min(Math.abs(state.player.x-B.l),Math.abs(state.player.x-B.r),Math.abs(state.player.y-B.t),Math.abs(state.player.y-B.b));return q<45}
function refreshContext(){$('context').hidden=!repairTarget();if(!$('context').hidden){$('context-main').textContent='REPAIR';$('context-sub').textContent='WOOD 5'}}
function contextAct(){if(!repairTarget())return;state.wood-=5;state.palisade.hp=Math.min(state.palisade.maxHp,state.palisade.hp+90+state.palisade.level*18);fxBurst(state.player.x,state.player.y,'#d7b26e',8);A.sfx('build');toast('防壁を修理');save()}
function updateVitalsHud(){const m=$('meta');if(m)m.textContent=`HP ${Math.ceil(state.player.hp)}/${state.player.maxHp} · IRON ${state.iron} · RENOWN ${state.renown}`}
function phaseTick(dt){const prev=state.phase;state.cycle+=dt/125*state.boost;if(state.cycle>=1){state.cycle-=1;state.day++;nightWaveMask=0;state.stats.nights++;igniteDawnSurvivors();const upkeep=Math.ceil(state.workers.filter(w=>!w.dead).length*.72+state.buildings.length*.28);if(state.food>=upkeep){state.food-=upkeep;state.morale=Math.min(100,state.morale+4);toast(`DAWN · FOOD -${upkeep} · 士気回復`)}else{const miss=upkeep-state.food;state.food=0;state.morale=Math.max(25,state.morale-miss*2.2-7);toast(`食料不足 ${miss} · MORALE ${Math.round(state.morale)}`,true)}const survive=Math.max(0,Math.round((state.palisade.maxHp?state.palisade.hp/state.palisade.maxHp:0)*3));state.renown+=survive;A.setMood('day');A.sfx('dawn');save()}const[ph]=phaseInfo();state.phase=ph;if(ph==='night'){const thresholds=[.79,.85,.91,.97];thresholds.forEach((t,i)=>{if(state.cycle>=t&&!(nightWaveMask&(1<<i))){nightWaveMask|=1<<i;spawnWave(i)}})}if(prev!==ph&&ph==='dusk')toast(`DUSK · THREAT ${threat()} · 防衛準備`,true);if(state.boostUntil&&Date.now()>=state.boostUntil){state.boost=1;state.boostUntil=0;toast('砂時計の効果終了')}}
function draw(){drawGround();const items=[];for(const n of state.nodes)if(n.alive)items.push({y:n.y,fn:()=>drawNode(n)});for(const b of state.buildings)items.push({y:b.y+25,fn:()=>drawBuilding(b)});state.workers.forEach(w=>items.push({y:w.y+16,fn:()=>drawWorkerEntity(w)}));state.enemies.forEach(e=>items.push({y:e.y+16,fn:()=>drawEnemy(e)}));items.push({y:state.player.y+17,fn:drawPlayerEntity});items.sort((a,b)=>a.y-b.y).forEach(o=>o.fn());drawWall();state.projectiles.forEach(drawProjectile);if(state.phase==='night'){ctx.fillStyle='rgba(4,9,15,.26)';ctx.fillRect(0,0,W,H);for(const b of state.buildings)if(b.type==='lantern')glow(sx(b.x),sy(b.y)-28,lanternRadius(b),.16)}}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;movement(dt);playerGather(dt);updateWorkers(dt);playerAutoCombat();updateEnemies(dt);updateHumanLife(dt);phaseTick(dt);refreshContext();updateHud();updateVitalsHud();draw();drawEffects(dt);requestAnimationFrame(loop)}
function vec(e){let dx=e.clientX-origin.x,dy=e.clientY-origin.y,m=Math.hypot(dx,dy),max=64;if(m<7){input={x:0,y:0,mag:0};return}dragged=true;if(m>max){dx=dx/m*max;dy=dy/m*max;m=max}input={x:dx/max,y:dy/max,mag:m/max}}
canvas.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();A.enable();pointer=e.pointerId;origin={x:e.clientX,y:e.clientY};dragged=false;input={x:0,y:0,mag:0};try{canvas.setPointerCapture(pointer)}catch(_){}});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();vec(e)});function end(e){if(e.pointerId!==pointer)return;pointer=null;input={x:0,y:0,mag:0};save()}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
function openPanel(name){currentPanel=name;$('sheet').hidden=false;$('sheet-title').textContent=name.toUpperCase();$('sheet-kicker').textContent=name==='build'?'SETTLEMENT':name==='people'?'ROSTER':'PROGRESS';['build','people','record'].forEach(p=>$('panel-'+p).hidden=p!==name);document.querySelectorAll('#dock button').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));updateHud();A.sfx('confirm')}function closeSheet(){$('sheet').hidden=true;currentPanel=null;document.querySelectorAll('#dock button').forEach(b=>b.classList.remove('active'))}
document.querySelectorAll('#dock [data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$('sheet-close').onclick=()=>{closeSheet();A.sfx('cancel')};document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));document.querySelectorAll('[data-hire]').forEach(b=>b.onclick=()=>hire(b.dataset.hire));$('context').onclick=contextAct;$('sound').onclick=async()=>{$('sound').textContent=(await A.toggle())?'♪':'♪×'};$('speed').onclick=()=>{A.enable();if(state.hourglass<=0){toast('砂時計が必要');return}if(state.boost>=3){toast('最大×3');return}state.hourglass--;state.boost++;state.boostUntil=Date.now()+30000;toast(`砂時計 · ×${state.boost} 30秒`);save()};
function serial(){return JSON.stringify(state)}function save(){if(document.body.dataset.resetting==='true')return false;try{const p=localStorage.getItem(SAVE);if(p)localStorage.setItem(BACKUP,p);state.lastSaved=Date.now();localStorage.setItem(SAVE,serial());savePulse();return true}catch(_){return false}}function apply(o){if(!o||o.version!==16)return false;Object.assign(state,o);state.player={...state.player,...o.player};state.palisade={...state.palisade,...o.palisade};state.stats={...state.stats,...o.stats};for(const k of['nodes','buildings','workers','enemies','projectiles'])state[k]=Array.isArray(o[k])?o[k]:[];return true}function load(){for(const k of[SAVE,BACKUP]){try{const raw=localStorage.getItem(k);if(raw&&apply(JSON.parse(raw)))return true}catch(_){}}return false}
setInterval(save,1000);addEventListener('pagehide',save);addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});const loaded=load();if(!state.nodes.length)seedNodes();for(const k of['wood','stone','food'])capResource(k);ensureLifeState();updateHud();updateVitalsHud();toast(loaded?'AUTO SAVE · 続きから再開':'v1.6 LIFE AI · 小屋→防壁→夜防衛');A.setMood(state.phase==='night'?'night':'day');requestAnimationFrame(t=>{last=t;requestAnimationFrame(loop)});window.GUILD_V16=Object.freeze({state:()=>JSON.parse(serial()),save,build,hire,upgrade,spawnWave});
