(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
ctx.imageSmoothingEnabled=false;
let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),last=performance.now(),pointer=null,origin={x:0,y:0},input={x:0,y:0,mag:0},autoTarget=null,workClock=0,passiveClock=0,nightSpawned=false,currentPanel=null,lastWorkerHash='';
const LW=240;let LH=Math.round(LW*H/W);const scene=document.createElement('canvas'),g=scene.getContext('2d',{alpha:false});g.imageSmoothingEnabled=false;
const SAVE='guild-infinity-buildjoy-v12',BACKUP=SAVE+'-backup',LEGACY='guild-infinity-buildjoy-v11';
const WORLD={minX:-470,maxX:470,minY:-340,maxY:390};
const BUILD_SLOTS=[[-54,28],[54,28],[-104,-34],[104,-34],[-152,58],[152,58],[-52,-104],[52,-104],[-205,-58],[205,-58],[0,132],[-126,148],[126,148],[0,-178]];
const RECIPES={hut:{name:'小屋',wood:10,stone:3},lumber:{name:'木材所',wood:16,stone:5},quarry:{name:'採石所',wood:12,stone:9},palisade:{name:'集落防壁',wood:22,stone:4},lantern:{name:'灯火塔',wood:6,stone:2}};
const ROLE={wood:'木こり',stone:'採石人',food:'採集人',guard:'衛兵'};
const NAMES=['リナ','ガルド','ミラ','レオン','ノア','セラ','エリナ','ロウ','カイ','フィア','ユノ','バルド'];
const PERSON=[['明るい','手際よし','今日も街を広げよう！','作業速度 +3%'],['慎重','丁寧仕事','急がず、壊れないように','修理効率 +6%'],['無口','集中力','……仕事、行ってくる','採取安定 +5%'],['熱血','全力作業','任せろ、すぐ終わらせる！','木材/戦闘 +5%'],['のんびり','節約上手','まあ、焦らずいこう','食料消費 -4%']];
const state={version:12,day:1,cycle:.13,phase:'day',wood:0,stone:0,food:0,gold:0,gem:0,hourglass:1,ticket:0,boost:1,boostUntil:0,player:{x:0,y:88,vx:0,vy:0,dir:'down',walk:0,swing:0},nodes:[],buildings:[],workers:[],zombies:[],lastSaved:0};
const cam={x:0,y:20};const particles=[],floats=[],motes=[],rings=[],ambient=[];
const assets={puny:null,hero:null,male:null,female:null,ready:0,total:4};
const URLS={puny:'https://opengameart.org/sites/default/files/punyworld-overworld-tileset_0.png',hero:'https://opengameart.org/sites/default/files/Hero.png',male:'https://opengameart.org/sites/default/files/base_male.png',female:'https://opengameart.org/sites/default/files/base_female.png'};
function loadImg(key,url){const im=new Image();im.onload=()=>{assets[key]=im;assets.ready++;updateAssetState()};im.onerror=()=>{assets.ready++;updateAssetState()};im.src=url}
Object.entries(URLS).forEach(([k,u])=>loadImg(k,u));
function updateAssetState(){$('asset-state').textContent=assets.ready>=assets.total?'CC0 SPRITES '+(assets.hero?'ON':'FALLBACK'):`SPRITES ${assets.ready}/${assets.total}`;if(assets.ready>=assets.total)setTimeout(()=>{$('asset-state').style.opacity=.18},1200)}
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);ctx.imageSmoothingEnabled=false;LH=Math.round(LW*H/W);scene.width=LW;scene.height=LH;g.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rnd=(a,b)=>a+Math.random()*(b-a),sx=x=>LW/2+x-cam.x,sy=y=>LH/2+y-cam.y;
function toast(t){$('ticker-text').textContent=t;$('ticker').classList.remove('flash');void $('ticker').offsetWidth;$('ticker').classList.add('flash')}
function phaseInfo(c=state.cycle){if(c<.06)return['dawn','DAWN'];if(c<.70)return['day','DAY'];if(c<.78)return['dusk','DUSK'];return['night','NIGHT']}
function objective(){if(!state.buildings.some(b=>b.type==='hut'))return'小屋を建てて最初の住人を迎えよう';if(!state.workers.length)return'PEOPLEから最初の仲間を雇おう';if(!state.buildings.some(b=>b.type==='lumber'))return'木材所を建てて自動化を加速';if(!state.buildings.some(b=>b.type==='palisade'))return'夜に備えて集落防壁を一気に建てよう';return`開拓を広げる · BUILDINGS ${state.buildings.length}`}
function updateHud(){
 $('wood').textContent=Math.floor(state.wood);$('stone').textContent=Math.floor(state.stone);$('food').textContent=Math.floor(state.food);$('people').textContent=state.workers.length+'/200';$('day').textContent='DAY '+state.day;const [ph,label]=phaseInfo();state.phase=ph;$('phase').textContent=label;const mins=Math.floor(state.cycle*24*60),hh=String(Math.floor(mins/60)%24).padStart(2,'0'),mm=String(mins%60).padStart(2,'0');$('clock').textContent=hh+':'+mm;$('quest-text').textContent=objective();$('people-caption').textContent=state.buildings.some(b=>b.type==='hut')?state.workers.length+'/200':'小屋で解禁';$('hourglass').textContent=state.hourglass;$('ticket').textContent=state.ticket;$('gem').textContent=state.gem;$('last-save').textContent=state.lastSaved?new Date(state.lastSaved).toLocaleTimeString('ja-JP'):'--:--:--';$('save-status').textContent=state.lastSaved?'SAVED':'AUTO';$('speed').textContent='×'+state.boost;renderWorkers()}
function makeNode(id,x,y,type){return{id,x,y,type,hp:type==='food'?1:3,maxHp:type==='food'?1:3,alive:true,respawnAt:0,seed:Math.random()}}
function seedNodes(){if(state.nodes.length)return;let id=0;const near=[[-36,112,'tree'],[40,118,'tree'],[-78,74,'tree'],[86,67,'tree'],[-116,110,'tree'],[122,112,'tree'],[-90,43,'rock'],[98,46,'rock'],[-136,145,'rock'],[142,150,'rock'],[-20,163,'food'],[62,170,'food']];state.nodes=near.map(v=>makeNode('n'+id++,...v));for(let i=0;i<48;i++){const a=i/48*Math.PI*2,r=145+(i%7)*47;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-24,24),Math.sin(a)*r*.72+rnd(-22,22),'tree'))}for(let i=0;i<32;i++){const a=(i+.31)/32*Math.PI*2,r=120+(i%6)*60;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-22,22),Math.sin(a)*r*.70+rnd(-19,19),'rock'))}for(let i=0;i<18;i++){const a=(i+.7)/18*Math.PI*2,r=108+(i%4)*75;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-18,18),Math.sin(a)*r*.68+rnd(-17,17),'food'))}}
seedNodes();
function workerIdentity(i){const p=PERSON[i%PERSON.length];return{name:NAMES[i%NAMES.length],personality:p[0],trait:p[1],line:p[2],bonus:p[3],sex:i%3===0?'female':'male',hue:(i*47)%360}}
function ensureWorker(w,i){const d=workerIdentity(i);for(const k of Object.keys(d))if(w[k]===undefined)w[k]=d[k];return w}
function renderWorkers(){const hash=state.workers.map(w=>w.id+':'+w.role+':'+w.name).join('|');if(hash===lastWorkerHash)return;lastWorkerHash=hash;const el=$('worker-list');if(!el)return;if(!state.workers.length){el.innerHTML='<div class="notice">まだ仲間はいない · 小屋を建てて最初の一人を迎えよう</div>';return}el.innerHTML=state.workers.slice(0,8).map((w,i)=>{ensureWorker(w,i);return `<article class="worker-card"><span class="worker-portrait" style="background:linear-gradient(145deg,hsl(${w.hue} 28% 26%),#101616)"><span style="position:absolute;left:11px;top:7px;width:18px;height:18px;background:#d5a67d;border-radius:2px;box-shadow:0 -5px 0 hsl(${w.hue} 25% 18%)"></span><span style="position:absolute;left:15px;top:15px;width:2px;height:2px;background:#241b18;box-shadow:7px 0 #241b18"></span><span style="position:absolute;left:8px;right:8px;bottom:2px;height:17px;background:hsl(${(w.hue+90)%360} 25% 38%);border-top:3px solid #aa8050"></span></span><span class="worker-copy"><b>${w.name} · ${ROLE[w.role]||w.role}</b><small>${w.personality} / ${w.line}</small><span>${w.bonus}</span></span><em class="trait">${w.trait}</em></article>`}).join('')+(state.workers.length>8?`<div class="notice">ほか ${state.workers.length-8}人 · ${state.workers.length}/200</div>`:'')}
function rect(x,y,w,h,c){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function shadow(x,y,w,h=4,a=.55){g.fillStyle=`rgba(2,7,6,${a})`;g.fillRect(Math.round(x-w/2),Math.round(y-h/2),Math.round(w),Math.round(h))}
function drawTileGround(){
 const ph=state.phase;const grad=g.createLinearGradient(0,0,0,LH);grad.addColorStop(0,ph==='night'?'#0d1b23':ph==='dusk'?'#33454b':ph==='dawn'?'#416056':'#45694f');grad.addColorStop(1,ph==='night'?'#172921':ph==='dusk'?'#5b543b':ph==='dawn'?'#526a4f':'#536f52');g.fillStyle=grad;g.fillRect(0,0,LW,LH);
 if(assets.puny){for(let y=(-cam.y%16)-16;y<LH+16;y+=16){for(let x=(-cam.x%16)-16;x<LW+16;x+=16){const v=((x+y+Math.floor(cam.x)+Math.floor(cam.y))>>4)&3;const sx0=v===0?0:v===1?16:v===2?32:0;g.globalAlpha=.35;g.drawImage(assets.puny,sx0,0,16,16,Math.round(x),Math.round(y),16,16)}}g.globalAlpha=1}
 for(let i=0;i<54;i++){const wx=(i*137)%880-440,wy=(i*83)%650-310,x=sx(wx),y=sy(wy);if(x<-4||x>LW+4||y<-4||y>LH+4)continue;rect(x,y,1+(i%2),1,i%3?'#9a9a6230':'#d0ad6a26')}
 // settlement dirt clearing + paths
 const cx=sx(0),cy=sy(0);g.fillStyle='rgba(132,103,66,.28)';g.beginPath();g.ellipse(cx,cy+18,70,53,0,0,Math.PI*2);g.fill();rect(cx-6,cy-115,12,170,'rgba(173,142,84,.23)');rect(cx-118,cy+8,236,12,'rgba(173,142,84,.20)');
}
function drawTree(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+9,24,5,.52);if(assets.puny){g.save();g.globalAlpha=.97;g.drawImage(assets.puny,0,72,48,64,Math.round(x-24),Math.round(y-46),48,64);g.restore();return}rect(x-3,y-8,7,22,'#603f28');rect(x-16,y-28,33,17,'#173a2c');rect(x-12,y-38,25,15,'#24513a');rect(x-6,y-45,14,10,'#3a6846')}
function drawRock(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+7,20,4,.48);g.fillStyle='#56615e';g.beginPath();g.moveTo(x-10,y+5);g.lineTo(x-8,y-5);g.lineTo(x-3,y-10);g.lineTo(x+7,y-8);g.lineTo(x+11,y+2);g.lineTo(x+6,y+8);g.lineTo(x-6,y+8);g.closePath();g.fill();g.fillStyle='#8d9180';g.beginPath();g.moveTo(x-6,y-3);g.lineTo(x-2,y-7);g.lineTo(x+4,y-6);g.lineTo(x+7,y-1);g.closePath();g.fill();rect(x-5,y+2,5,2,'#b5b39b')}
function drawFood(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+6,20,3,.35);rect(x-10,y+1,20,8,'#24422f');rect(x-7,y-5,15,8,'#4e754d');for(const d of[-5,0,5])rect(x+d,y,2,2,'#d06a5c')}
function dirRow(dir){return dir==='down'?0:dir==='left'?1:dir==='right'?2:3}
function drawSprite(img,wx,wy,dir,walk,scale=2.05){if(!img)return false;const cols=Math.max(1,Math.floor(img.naturalWidth/16)),rows=Math.max(1,Math.floor(img.naturalHeight/16)),row=Math.min(rows-1,dirRow(dir)),frame=Math.min(cols-1,Math.floor(walk)%Math.min(cols,4));const x=sx(wx),y=sy(wy);g.drawImage(img,frame*16,row*16,16,16,Math.round(x-16*scale/2),Math.round(y-16*scale+6),Math.round(16*scale),Math.round(16*scale));return true}
function drawPlayer(){const p=state.player,x=sx(p.x),y=sy(p.y);shadow(x,y+7,15,4,.58);const ok=drawSprite(assets.hero,p.x,p.y,p.dir,p.walk,2.2);if(!ok){rect(x-6,y-13,12,15,'#b9583f');rect(x-5,y-21,10,9,'#d7aa7d');rect(x-6,y-25,12,5,'#463127');rect(x-4,y+2,3,8,'#30363a');rect(x+2,y+2,3,8,'#30363a')}if(p.swing>0){const a=(1-p.swing)*Math.PI*.95-.4,ax=x+Math.cos(a)*17,ay=y-5+Math.sin(a)*16;g.strokeStyle='#7a5433';g.lineWidth=2;g.beginPath();g.moveTo(x+6,y-5);g.lineTo(ax,ay);g.stroke();rect(ax-2,ay-4,7,5,'#c3c7c3');rect(ax+2,ay-4,3,1,'#f2ead4')}}
function drawWorker(w,i){ensureWorker(w,i);const img=w.sex==='female'?assets.female:assets.male;shadow(sx(w.x),sy(w.y)+7,13,3,.45);const ok=drawSprite(img,w.x,w.y,'down',performance.now()*.008+i,1.9);if(!ok){const x=sx(w.x),y=sy(w.y);rect(x-5,y-11,10,13,`hsl(${(w.hue+90)%360} 28% 42%)`);rect(x-4,y-18,8,8,'#d1a179');rect(x-5,y-22,10,5,`hsl(${w.hue} 24% 22%)`)}const x=sx(w.x),y=sy(w.y);const cloth=`hsl(${(w.hue+90)%360} 30% 36% / .78)`;rect(x-7,y-7,14,7,cloth);if(w.role==='wood'){g.strokeStyle='#77502f';g.lineWidth=1;g.beginPath();g.moveTo(x+5,y-7);g.lineTo(x+10,y+2);g.stroke();rect(x+8,y-1,5,3,'#b6bbb7')}else if(w.role==='stone'){rect(x+6,y-3,7,2,'#9ea6a3')}else if(w.role==='guard'){rect(x+6,y-9,2,11,'#c8c2ad');rect(x+5,y-10,4,2,'#e4d8b9')}}
function buildingPalette(type){return type==='hut'?['#9a6940','#c58b4f','#e0b86d']:type==='lumber'?['#765039','#a16c42','#d5a15d']:type==='quarry'?['#59625e','#85897b','#b7b39a']:['#786044','#b5874e','#e0b565']}
function drawBuilding(b){const x=sx(b.x),y=sy(b.y),age=clamp((performance.now()-b.builtAt)/900,0,1),stage=age<.33?0:age<.68?1:2,[dark,mid,hi]=buildingPalette(b.type);g.save();g.globalAlpha=.35+.65*age;if(stage===0){rect(x-19,y+5,38,3,'#d0ad68');for(let i=-16;i<=16;i+=8)rect(x+i,y-5,2,12,'#89623d')}else if(b.type==='hut'||b.type==='lumber'){rect(x-20,y-8,40,23,mid);rect(x-18,y-6,36,18,dark);rect(x-15,y-4,30,15,mid);if(stage>1){g.fillStyle=hi;g.beginPath();g.moveTo(x-24,y-8);g.lineTo(x,y-27);g.lineTo(x+24,y-8);g.closePath();g.fill();rect(x-5,y+2,10,13,'#32231d');rect(x-15,y-2,7,7,'#e5b85c');rect(x+9,y-2,7,7,'#e5b85c')}}else if(b.type==='quarry'){rect(x-22,y,44,13,dark);g.fillStyle=mid;g.beginPath();g.moveTo(x-20,y);g.lineTo(x-12,y-15);g.lineTo(x+13,y-13);g.lineTo(x+22,y);g.closePath();g.fill();if(stage>1){rect(x-8,y-7,6,4,hi);rect(x+5,y-5,8,3,'#c1bd9e')}}else if(b.type==='lantern'){rect(x-2,y-24,4,31,dark);rect(x-9,y-29,18,9,hi);glow(x,y-25,44)}g.restore();if(age<1){for(let i=0;i<2;i++)spawnDust(b.x+rnd(-18,18),b.y+rnd(-8,12),false)}else if(!b.finishedFx){b.finishedFx=true;rings.push({x:b.x,y:b.y-8,r:4,life:.8,color:'#f4c96f'});for(let i=0;i<20;i++)particles.push({x:b.x+rnd(-10,10),y:b.y+rnd(-8,8),vx:rnd(-25,25),vy:rnd(-42,-8),life:rnd(.35,.7),color:i%2?'#f0c879':'#dba35a',size:1.5});BuildjoyAudioV12.sfx('finish')}}
function glow(x,y,r){g.save();g.globalCompositeOperation='screen';const gr=g.createRadialGradient(x,y,2,x,y,r);gr.addColorStop(0,'rgba(255,195,91,.34)');gr.addColorStop(.35,'rgba(255,157,66,.13)');gr.addColorStop(1,'rgba(255,120,30,0)');g.fillStyle=gr;g.fillRect(x-r,y-r,r*2,r*2);g.restore()}
function drawPalisade(){if(!state.buildings.some(b=>b.type==='palisade'))return;const left=sx(-150),right=sx(150),top=sy(-118),bottom=sy(126),gateL=sx(-24),gateR=sx(24);g.save();g.fillStyle='#6d452b';g.strokeStyle='#b17a46';g.lineWidth=1;for(let x=left;x<=right;x+=6){rect(x,top,4,12,'#70452b');rect(x,top,4,2,'#b17a46')}for(let x=left;x<=right;x+=6){if(x>gateL&&x<gateR)continue;rect(x,bottom-8,4,12,'#70452b');rect(x,bottom-8,4,2,'#b17a46')}for(let y=top;y<=bottom;y+=6){rect(left,y,12,4,'#70452b');rect(right-8,y,12,4,'#70452b')}rect(gateL,bottom-9,3,15,'#b98b54');rect(gateR-3,bottom-9,3,15,'#b98b54');rect(gateL,bottom-10,gateR-gateL,3,'#8f633b');g.restore()}
function drawZombie(z){const x=sx(z.x),y=sy(z.y);shadow(x,y+6,14,3,.5);rect(x-5,y-10,10,14,z.hit>0?'#d5d0ad':'#6d815f');rect(x-4,y-17,8,8,'#aaa88c');rect(x-3,y-14,2,2,'#2f211d');rect(x+2,y-14,2,2,'#2f211d');rect(x-4,y+4,3,7,'#453936');rect(x+1,y+4,3,7,'#453936')}
function spawnDust(wx,wy,heavy=true){if(particles.length>220)return;particles.push({x:wx,y:wy,vx:rnd(-18,18),vy:rnd(heavy?-24:-12,-5),life:rnd(.22,.48),color:heavy?'#c8a06a':'#ad8b61',size:rnd(1,2.3)})}
function burst(wx,wy,color,count=10,power=36){for(let i=0;i<count;i++)particles.push({x:wx,y:wy,vx:rnd(-power,power),vy:rnd(-power*1.2,-5),life:rnd(.3,.7),color,size:rnd(1,2.5)})}
function floatText(wx,wy,text,color='#f1d18b'){floats.push({x:wx,y:wy,text,color,life:1})}
function resourceMotes(wx,wy,type,count=3){const colors={tree:'#b97a43',rock:'#a5a797',food:'#c96759'};for(let i=0;i<count;i++)motes.push({x:wx+rnd(-4,4),y:wy+rnd(-4,4),tx:-LW*.42+(type==='rock'?44:type==='food'?88:0),ty:-LH*.43,life:.65,color:colors[type]})}
function rareDrop(wx,wy){const r=Math.random();if(r<.025){state.hourglass++;toast('RARE DROP · 砂時計 +1');floatText(wx,wy,'HOURGLASS!','#c9a7ff');rings.push({x:wx,y:wy,r:5,life:1,color:'#c9a7ff'});BuildjoyAudioV12.sfx('rare');return}if(r<.043){state.ticket++;toast('RARE DROP · 召喚券 +1');floatText(wx,wy,'TICKET!','#8fdcff');rings.push({x:wx,y:wy,r:5,life:1,color:'#8fdcff'});BuildjoyAudioV12.sfx('rare');return}if(r<.06){state.gem++;toast('RARE DROP · GEM +1');floatText(wx,wy,'GEM!','#91bfff');rings.push({x:wx,y:wy,r:5,life:1,color:'#91bfff'});BuildjoyAudioV12.sfx('rare')}}
function nearestNode(){let best=null,d=999;for(const n of state.nodes){if(!n.alive)continue;const q=Math.hypot(state.player.x-n.x,state.player.y-n.y);if(q<38&&q<d){best=n;d=q}}return best}
function workNode(n){if(!n||!n.alive)return;state.player.dir=Math.abs(n.x-state.player.x)>Math.abs(n.y-state.player.y)?(n.x>state.player.x?'right':'left'):(n.y>state.player.y?'down':'up');state.player.swing=1;const bonus=n.type==='tree'&&state.buildings.some(b=>b.type==='lumber')?1.3:n.type==='rock'&&state.buildings.some(b=>b.type==='quarry')?1.3:1;if(n.type==='tree'){const q=3*bonus;state.wood+=q;floatText(n.x,n.y-22,'+WOOD '+Math.ceil(q));burst(n.x,n.y-18,'#b67a42',12,32);resourceMotes(n.x,n.y-10,'tree',4);BuildjoyAudioV12.sfx('chop')}else if(n.type==='rock'){const q=2*bonus;state.stone+=q;floatText(n.x,n.y-13,'+STONE '+Math.ceil(q));burst(n.x,n.y-8,'#a7a794',10,29);resourceMotes(n.x,n.y-4,'rock',3);BuildjoyAudioV12.sfx('mine')}else{state.food+=4;floatText(n.x,n.y-10,'+FOOD 4');burst(n.x,n.y,'#c86558',8,24);resourceMotes(n.x,n.y,'food',3);BuildjoyAudioV12.sfx('pickup')}n.hp--;if(n.hp<=0){n.alive=false;n.respawnAt=Date.now()+(n.type==='food'?4800:7600);burst(n.x,n.y,n.type==='tree'?'#557248':'#86877a',18,44);rareDrop(n.x,n.y)}save('mutation');updateHud()}
function respawn(){const now=Date.now();for(const n of state.nodes)if(!n.alive&&n.respawnAt&&now>=n.respawnAt){n.alive=true;n.hp=n.maxHp;n.respawnAt=0}}
function build(type){const r=RECIPES[type];if(!r)return;if(state.wood<r.wood||state.stone<r.stone){toast(`${r.name} · 素材不足 W${r.wood} / S${r.stone}`);BuildjoyAudioV12.sfx('cancel');return}if(state.buildings.some(b=>b.type===type)){toast(r.name+' は建設済み');return}let x=0,y=0,slot=-1;if(type==='palisade'){x=0;y=0}else{const used=new Set(state.buildings.map(b=>b.slot));const c=BUILD_SLOTS.map((p,i)=>({p,i,d:Math.hypot(state.player.x-p[0],state.player.y-p[1])})).filter(v=>!used.has(v.i)).sort((a,b)=>a.d-b.d)[0];if(!c){toast('建築スロットがいっぱい');return}slot=c.i;x=c.p[0];y=c.p[1]}state.wood-=r.wood;state.stone-=r.stone;const b={id:'b'+Date.now(),type,slot,x,y,hp:type==='palisade'?360:200,maxHp:type==='palisade'?360:200,builtAt:performance.now()};state.buildings.push(b);if(type==='palisade'){for(let i=0;i<60;i++){const a=i/60*Math.PI*2;particles.push({x:Math.cos(a)*150,y:Math.sin(a)*120,vx:rnd(-8,8),vy:rnd(-24,-4),life:rnd(.35,.9),color:i%2?'#a87343':'#d2a163',size:rnd(1,2.2)})}rings.push({x:0,y:0,r:15,life:1.3,color:'#e3b968'})}else burst(x,y,'#d8aa65',22,45);BuildjoyAudioV12.sfx('build');toast(type==='palisade'?'集落防壁 · 外周を一気に建設！':r.name+' 建設開始');closeSheet();save('mutation');updateHud()}
function hire(role){if(!state.buildings.some(b=>b.type==='hut')){toast('小屋を建てると雇用できる');return}const cost=role==='guard'?7:role==='food'?4:5;if(state.food<cost){toast('FOOD不足 · '+cost);return}if(state.workers.length>=200){toast('人口上限 200');return}state.food-=cost;const h=state.buildings.find(b=>b.type==='hut')||{x:0,y:0},w={id:'w'+Date.now()+Math.random(),role,x:h.x+rnd(-12,12),y:h.y+rnd(8,20)};ensureWorker(w,state.workers.length);state.workers.push(w);burst(w.x,w.y-10,'#e5bd6c',14,28);rings.push({x:w.x,y:w.y-8,r:3,life:.7,color:'#e5bd6c'});BuildjoyAudioV12.sfx('hire');toast(`${w.name} · ${ROLE[role]} が加入した`);save('mutation');updateHud()}
function passive(dt){passiveClock+=dt;if(passiveClock<.9)return;passiveClock=0;for(const w of state.workers){if(w.role==='wood')state.wood+=state.buildings.some(b=>b.type==='lumber')?1.6:1;else if(w.role==='stone')state.stone+=state.buildings.some(b=>b.type==='quarry')?1.3:.85;else if(w.role==='food')state.food+=1}updateHud()}
function spawnNight(){if(nightSpawned||state.phase!=='night')return;nightSpawned=true;const count=Math.min(5,2+Math.floor(state.day/2));for(let i=0;i<count;i++){const a=i/count*Math.PI*2,z={id:'z'+Date.now()+i,x:Math.cos(a)*430,y:Math.sin(a)*310,hp:48,hit:0,cool:0,dead:false};state.zombies.push(z)}toast('NIGHT · 防壁の外に気配がある');BuildjoyAudioV12.sfx('warning');BuildjoyAudioV12.setMood('night')}
function updateZombies(dt){const wall=state.buildings.find(b=>b.type==='palisade'&&b.hp>0);for(const z of state.zombies){if(z.dead)continue;if(z.hit>0)z.hit-=dt;if(z.cool>0)z.cool-=dt;let tx=0,ty=0;if(wall){const ax=Math.abs(z.x/150),ay=Math.abs(z.y/120);if(ax>ay){tx=z.x>0?150:-150;ty=clamp(z.y,-105,105)}else{ty=z.y>0?120:-118;tx=clamp(z.x,-132,132)}}const dx=tx-z.x,dy=ty-z.y,d=Math.hypot(dx,dy)||1;if(d>16){z.x+=dx/d*22*dt*state.boost;z.y+=dy/d*22*dt*state.boost}else if(z.cool<=0){z.cool=1.1;if(wall){wall.hp=Math.max(0,wall.hp-8);burst(tx,ty,'#9b6d49',5,18);toast(`防壁 HP ${wall.hp}/${wall.maxHp}`)}else{state.wood=Math.max(0,state.wood-1);state.stone=Math.max(0,state.stone-.5)}BuildjoyAudioV12.sfx('hit')}}const guards=state.workers.filter(w=>w.role==='guard').length;if(guards)for(const z of state.zombies){if(z.dead)continue;z.hp-=guards*4*dt;if(z.hp<=0)killZombie(z)}}
function killZombie(z){z.dead=true;burst(z.x,z.y,'#7e946b',12,35);floatText(z.x,z.y-14,'DOWN','#d8d1ae');BuildjoyAudioV12.sfx('pickup');if(Math.random()<.15)state.gem++;save('mutation')}
function contextTarget(){let best=null,d=999;for(const z of state.zombies){if(z.dead)continue;const q=Math.hypot(state.player.x-z.x,state.player.y-z.y);if(q<42&&q<d){best={kind:'attack',obj:z};d=q}}const wall=state.buildings.find(b=>b.type==='palisade'&&b.hp<b.maxHp);if(wall&&Math.hypot(state.player.x,state.player.y)<180)best=best||{kind:'repair',obj:wall};return best}
function refreshContext(){const t=contextTarget();$('context').hidden=!t;if(!t)return;$('context-main').textContent=t.kind==='attack'?'ATTACK':'REPAIR';$('context-sub').textContent=t.kind==='attack'?'斧で敵を攻撃':'WOOD 3 · 防壁を修理'}
function contextAct(){const t=contextTarget();if(!t)return;BuildjoyAudioV12.unlock();if(t.kind==='attack'){t.obj.hp-=32;t.obj.hit=.12;burst(t.obj.x,t.obj.y,'#d4b7a4',10,31);BuildjoyAudioV12.sfx('hit');if(t.obj.hp<=0)killZombie(t.obj)}else{if(state.wood<3){toast('WOOD不足 · 3');return}state.wood-=3;t.obj.hp=Math.min(t.obj.maxHp,t.obj.hp+42);BuildjoyAudioV12.sfx('build');toast(`防壁修理 ${t.obj.hp}/${t.obj.maxHp}`)}save('mutation');updateHud()}
function movement(dt){const p=state.player,m=input.mag,tx=input.x*112,ty=input.y*112,acc=m>.04?1-Math.pow(.000015,dt):1-Math.pow(.00035,dt);p.vx=lerp(p.vx,tx,acc);p.vy=lerp(p.vy,ty,acc);if(Math.abs(p.vx)<.35)p.vx=0;if(Math.abs(p.vy)<.35)p.vy=0;if(autoTarget&&m<.72){p.vx*=.64;p.vy*=.64}else{p.x=clamp(p.x+p.vx*dt*state.boost,WORLD.minX,WORLD.maxX);p.y=clamp(p.y+p.vy*dt*state.boost,WORLD.minY,WORLD.maxY)}if(Math.hypot(p.vx,p.vy)>4){p.walk+=dt*9.5;const ax=Math.abs(p.vx),ay=Math.abs(p.vy);p.dir=ax>ay?(p.vx>0?'right':'left'):(p.vy>0?'down':'up')}p.swing=Math.max(0,p.swing-dt*4.2);cam.x=p.x;cam.y=p.y-28}
function autoGather(dt){respawn();if(input.mag>.78){autoTarget=null;workClock=0;return}if(!autoTarget||!autoTarget.alive||Math.hypot(state.player.x-autoTarget.x,state.player.y-autoTarget.y)>40)autoTarget=nearestNode();if(!autoTarget){workClock=0;return}if(Math.hypot(state.player.x-autoTarget.x,state.player.y-autoTarget.y)>34)return;workClock+=dt*state.boost;if(workClock>=.33){workClock=0;workNode(autoTarget);if(!autoTarget.alive)autoTarget=null}}
function phaseTick(dt){const prev=state.phase;state.cycle+=dt/200*state.boost;if(state.cycle>=1){state.cycle-=1;state.day++;nightSpawned=false;state.zombies=state.zombies.filter(z=>!z.dead);state.food+=3;toast('DAWN · 新しい朝 '+state.day);BuildjoyAudioV12.sfx('dawn');BuildjoyAudioV12.setMood('day');rings.push({x:0,y:0,r:20,life:1.4,color:'#f0d38a'});save('mutation')}const [ph]=phaseInfo();state.phase=ph;if(prev!==ph){if(ph==='dusk'){toast('DUSK · ランタンが灯り始める');BuildjoyAudioV12.sfx('warning')}if(ph==='night')spawnNight();if(ph==='day')BuildjoyAudioV12.setMood('day')}if(state.boostUntil&&Date.now()>=state.boostUntil){state.boost=1;state.boostUntil=0;toast('砂時計の効果が切れた · ×1');save('mutation')}}
function updateAmbient(dt){if(ambient.length<45&&Math.random()<.25){ambient.push({x:cam.x+rnd(-LW*.6,LW*.6),y:cam.y+rnd(-LH*.5,LH*.5),life:rnd(2,5),vy:rnd(-5,-1),type:state.phase==='night'?'firefly':'leaf'})}for(let i=ambient.length-1;i>=0;i--){const a=ambient[i];a.y+=a.vy*dt;a.life-=dt;if(a.life<=0)ambient.splice(i,1)}}
function drawAmbient(){for(const a of ambient){const x=sx(a.x),y=sy(a.y);if(a.type==='firefly'){g.fillStyle='#e8c86a';g.globalAlpha=.35+.35*Math.sin(performance.now()*.005+a.x);g.fillRect(Math.round(x),Math.round(y),1,1);g.globalAlpha=1}else{g.fillStyle='#b5a36a35';g.fillRect(Math.round(x),Math.round(y),1,2)}}}
function drawEffects(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=40*dt;p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}g.globalAlpha=clamp(p.life*2,0,1);rect(sx(p.x),sy(p.y),p.size,p.size,p.color);g.globalAlpha=1}for(let i=floats.length-1;i>=0;i--){const f=floats[i];f.y-=15*dt;f.life-=dt;if(f.life<=0){floats.splice(i,1);continue}g.globalAlpha=clamp(f.life,0,1);g.font='900 6px monospace';g.textAlign='center';g.fillStyle='#000c';g.fillText(f.text,Math.round(sx(f.x)+1),Math.round(sy(f.y)+1));g.fillStyle=f.color;g.fillText(f.text,Math.round(sx(f.x)),Math.round(sy(f.y)));g.globalAlpha=1}for(let i=motes.length-1;i>=0;i--){const m=motes[i];m.life-=dt;if(m.life<=0){motes.splice(i,1);continue}const t=1-m.life/.65;m.x=lerp(m.x,cam.x+m.tx,.08+.12*t);m.y=lerp(m.y,cam.y+m.ty,.08+.12*t);rect(sx(m.x),sy(m.y),2,2,m.color)}for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.life-=dt;r.r+=34*dt;if(r.life<=0){rings.splice(i,1);continue}g.strokeStyle=r.color;g.globalAlpha=clamp(r.life,0,1);g.lineWidth=1;g.beginPath();g.arc(sx(r.x),sy(r.y),r.r,0,Math.PI*2);g.stroke();g.globalAlpha=1}}
function drawScene(dt){drawTileGround();drawAmbient();drawPalisade();const drawables=[];for(const n of state.nodes)if(n.alive)drawables.push({y:n.y,fn:()=>n.type==='tree'?drawTree(n):n.type==='rock'?drawRock(n):drawFood(n)});for(const b of state.buildings)if(b.type!=='palisade')drawables.push({y:b.y+18,fn:()=>drawBuilding(b)});state.workers.slice(0,18).forEach((w,i)=>drawables.push({y:w.y+12,fn:()=>drawWorker(w,i)}));for(const z of state.zombies)if(!z.dead)drawables.push({y:z.y+11,fn:()=>drawZombie(z)});drawables.push({y:state.player.y+13,fn:drawPlayer});drawables.sort((a,b)=>a.y-b.y).forEach(o=>o.fn());if(state.phase==='night'){g.fillStyle='rgba(4,8,16,.28)';g.fillRect(0,0,LW,LH);for(const b of state.buildings)if(b.type==='lantern')glow(sx(b.x),sy(b.y)-22,54)}drawEffects(dt);ctx.clearRect(0,0,W,H);ctx.imageSmoothingEnabled=false;ctx.drawImage(scene,0,0,LW,LH,0,0,W,H)}
function vec(e){let dx=e.clientX-origin.x,dy=e.clientY-origin.y,mag=Math.hypot(dx,dy),max=62;if(mag<7){input={x:0,y:0,mag:0};return}if(mag>max){dx=dx/mag*max;dy=dy/mag*max;mag=max}input={x:dx/max,y:dy/max,mag:mag/max}}
canvas.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();BuildjoyAudioV12.unlock();pointer=e.pointerId;origin={x:e.clientX,y:e.clientY};input={x:0,y:0,mag:0};try{canvas.setPointerCapture(pointer)}catch(_){}});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();vec(e)});function end(e){if(pointer===null||e.pointerId!==pointer)return;pointer=null;input={x:0,y:0,mag:0};save('mutation')}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
function openSheet(name){currentPanel=name;$('sheet').hidden=false;$('sheet-title').textContent=name.toUpperCase();$('build-panel').hidden=name!=='build';$('people-panel').hidden=name!=='people';$('bag-panel').hidden=name!=='bag';$('save-panel').hidden=name!=='save';$('people-lock').hidden=state.buildings.some(b=>b.type==='hut');BuildjoyAudioV12.sfx('confirm')}
function closeSheet(){$('sheet').hidden=true;currentPanel=null}
$('build-open').onclick=()=>openSheet('build');$('people-open').onclick=()=>openSheet('people');$('bag-open').onclick=()=>openSheet('bag');$('save-open').onclick=()=>openSheet('save');$('sheet-close').onclick=closeSheet;document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));document.querySelectorAll('[data-hire]').forEach(b=>b.onclick=()=>hire(b.dataset.hire));$('context').onclick=contextAct;$('manual-save').onclick=()=>{save('manual');toast('SAVE · 記録した')};$('sound').onclick=async()=>{$('sound').textContent=(await BuildjoyAudioV12.toggle())?'♪ OFF':'♪ ON'};$('speed').onclick=()=>{BuildjoyAudioV12.unlock();if(state.hourglass<=0){toast('砂時計が必要');BuildjoyAudioV12.sfx('cancel');return}if(state.boost>=3){toast('最大×3');return}state.hourglass--;state.boost++;state.boostUntil=Date.now()+30000;toast(`砂時計 · ×${state.boost} / 30秒`);BuildjoyAudioV12.sfx('rare');save('mutation');updateHud()};
function serial(){return JSON.stringify(state)}function apply(o){if(!o)return false;if(o.version===12){Object.assign(state,o);state.player={...state.player,...o.player};return true}if(o.version===11){Object.assign(state,{day:o.day,cycle:o.cycle,wood:o.wood,stone:o.stone,food:o.food,gold:o.gold,gem:o.gem,hourglass:o.hourglass,ticket:o.ticket,boost:o.boost,boostUntil:o.boostUntil,player:{...state.player,...o.player},nodes:o.nodes||[],buildings:(o.buildings||[]).map(b=>({...b,type:b.type==='barricade'?'palisade':b.type})),workers:o.workers||[],zombies:o.zombies||[]});return true}return false}
function save(reason='auto'){try{const prev=localStorage.getItem(SAVE);if(prev)localStorage.setItem(BACKUP,prev);state.lastSaved=Date.now();localStorage.setItem(SAVE,serial());updateHud();return true}catch(_){return false}}
async function load(){let ok=false;for(const key of[SAVE,BACKUP,LEGACY]){try{const raw=localStorage.getItem(key);if(raw&&apply(JSON.parse(raw))){ok=true;break}}catch(_){}}if(!state.nodes.length)seedNodes();state.workers.forEach(ensureWorker);state.boost=state.boostUntil>Date.now()?clamp(state.boost,1,3):1;if(state.boost===1)state.boostUntil=0;updateHud();return ok}
setInterval(()=>save('auto'),1000);addEventListener('pagehide',()=>save('lifecycle'));addEventListener('beforeunload',()=>save('lifecycle'));document.addEventListener('visibilitychange',()=>{if(document.hidden)save('lifecycle')});
function tick(dt){movement(dt);autoGather(dt);passive(dt);phaseTick(dt);updateZombies(dt);updateAmbient(dt);refreshContext();updateHud()}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;tick(dt);drawScene(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
load().then(ok=>{toast(ok?'v1.2 REFORM · 続きから再開':'v1.2 REFORM · 木へ近づくと自動採取');BuildjoyAudioV12.setMood(state.phase==='night'?'night':'day');updateHud()});
window.BUILDJOY_V12=Object.freeze({getState:()=>JSON.parse(serial()),save,build,hire});
})();