(()=>{'use strict';
const c=document.getElementById('game'),ctx=c.getContext('2d',{alpha:false}),$=id=>document.getElementById(id);
let W=innerWidth,H=innerHeight,last=performance.now(),time=0,pointer=null,target=null,saveTimer=0,autoTimer=0,toolSwing=0;
const DPR=Math.min(devicePixelRatio||1,1),SAVE='guild-v092-builder',BACK=SAVE+'-backup',CAP=1e9,NPC_MAX=200;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':Math.floor(n),now=()=>Date.now();
const state={v:92,day:1,phase:'day',phaseElapsed:0,dayDuration:100,nightDuration:34,speed:1,speedLeft:0,res:{wood:0,stone:0,food:3,gold:0,crystal:0,sand:0},core:100,kills:0,harvested:0,pity:0,built:{},lv:{},crew:[],collection:[],revision:0,savedAt:0};
const player={x:0,y:110,vx:0,vy:0,dir:'down',walk:0,hp:5};
const camera={x:0,y:55};
const BUILDINGS=[
{id:'hut',name:'開拓小屋',x:-76,y:15,w:88,h:62,cost:{wood:8,stone:4},desc:'建設の第一歩。人員1人を雇える',unlock:()=>true,type:'hut'},
{id:'lumber',name:'木こり小屋',x:-178,y:-82,w:94,h:66,cost:{wood:12,stone:5},desc:'WOODを自動生産',unlock:()=>true,type:'hut'},
{id:'quarry',name:'採石場',x:175,y:-76,w:104,h:68,cost:{wood:10,stone:10},desc:'STONEを自動生産',unlock:()=>true,type:'quarry'},
{id:'store',name:'倉庫',x:90,y:24,w:92,h:64,cost:{wood:14,stone:8},desc:'街の成長感と資源効率を上げる',unlock:()=>true,type:'store'},
{id:'barricade',name:'バリケード',x:0,y:210,w:126,h:52,cost:{wood:12,stone:6},desc:'夜襲を軽く受け止める',unlock:()=>state.day>=2||Object.keys(state.built).length>=2,type:'wall'},
{id:'inn',name:'宿屋',x:0,y:-132,w:118,h:82,cost:{wood:22,stone:12,food:5},desc:'人員上限を増やす',unlock:()=>state.built.hut,type:'inn'},
{id:'forge',name:'鍛冶場',x:205,y:120,w:104,h:74,cost:{wood:28,stone:20,gold:10},desc:'防衛と採取効率を強化',unlock:()=>state.built.inn,type:'forge'},
{id:'guild',name:'ギルド本部',x:-205,y:126,w:142,h:98,cost:{wood:60,stone:40,food:14,gold:35},desc:'街の到達点。ここから都市へ',unlock:()=>state.built.inn&&state.built.forge,type:'guild'}
];
function ringPoints(count,minR,maxR,offset=0){const out=[];for(let i=0;i<count;i++){const a=i/count*Math.PI*2+offset+rnd(-.08,.08),r=rnd(minR,maxR);out.push([Math.cos(a)*r,Math.sin(a)*r*.8+35])}return out}
const treePts=[...ringPoints(18,105,210,.1),...ringPoints(18,215,340,.28)];
const rockPts=[...ringPoints(12,125,220,.45),...ringPoints(12,230,345,.62)];
const berryPts=ringPoints(10,115,310,.22);
const trees=treePts.map((p,i)=>({id:'t'+i,type:'tree',x:p[0],y:p[1],hp:3,max:3,respawn:0,flash:0}));
const rocks=rockPts.map((p,i)=>({id:'r'+i,type:'rock',x:p[0],y:p[1],hp:4,max:4,respawn:0,flash:0}));
const berries=berryPts.map((p,i)=>({id:'b'+i,type:'berry',x:p[0],y:p[1],hp:2,max:2,respawn:0,flash:0}));
const nodes=[...trees,...rocks,...berries];
let zombies=[],waveSpawned=false,barricadeHp=0,barricadeMax=0,fx=[];

const AudioLite=(()=>{
  let ac=null,master=null,started=false,muted=false,step=0;
  const notes=[261.6,329.6,392,523.3,392,329.6,293.7,392];
  function ensure(){if(ac)return;ac=new (window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.12;master.connect(ac.destination)}
  function tone(freq,dur=.08,type='triangle',gain=.04,when=0){if(!ac||muted)return;const o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+when;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(master);o.start(t);o.stop(t+dur+.03)}
  function tick(){if(!ac||muted)return;const f=notes[step%notes.length];tone(f,.12,'triangle',.018);if(step%2===0)tone(f/2,.16,'sine',.013,.02);if(step%4===0)tone(92,.05,'square',.009);step++}
  function start(){ensure();ac.resume?.();if(started)return;started=true;setInterval(tick,230);$('sound').textContent='♪ ON'}
  function toggle(){ensure();start();muted=!muted;$('sound').textContent=muted?'♪ OFF':'♪ ON'}
  return{start,toggle,chop(){tone(145,.055,'square',.025);tone(90,.06,'triangle',.018,.02)},mine(){tone(240,.05,'square',.025);tone(360,.04,'triangle',.018,.035)},pickup(){tone(650,.08,'triangle',.025);tone(820,.10,'triangle',.02,.06)},build(){tone(330,.12,'triangle',.035);tone(440,.14,'triangle',.035,.08);tone(660,.18,'triangle',.03,.16)},hit(){tone(105,.05,'sawtooth',.025)},rare(){tone(660,.1,'triangle',.035);tone(880,.14,'triangle',.03,.09);tone(1100,.18,'triangle',.025,.18)}}
})();
$('sound').onclick=()=>AudioLite.toggle();

function resize(){W=innerWidth;H=innerHeight;c.width=Math.ceil(W*DPR);c.height=Math.ceil(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);ctx.imageSmoothingEnabled=false}
addEventListener('resize',resize);resize();
const sx=x=>W/2+x-camera.x,sy=y=>H/2+y-camera.y;
function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(x,y,w,h)}
function ellipse(x,y,rx,ry,col){ctx.fillStyle=col;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function line(x1,y1,x2,y2,w,col){ctx.strokeStyle=col;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function log(msg){$('ticker').textContent=msg;$('ticker').animate?.([{opacity:.55},{opacity:1}],{duration:140})}
function saveFlash(){const e=$('saveState');e.classList.add('flash');setTimeout(()=>e.classList.remove('flash'),160)}
function costText(cost){return Object.entries(cost).map(([k,v])=>`${{wood:'木',stone:'石',food:'食',gold:'G'}[k]||k} ${v}`).join(' / ')}
function canPay(cost){return Object.entries(cost).every(([k,v])=>(state.res[k]||0)>=v)}
function pay(cost){for(const[k,v]of Object.entries(cost))state.res[k]=Math.max(0,(state.res[k]||0)-v)}
function add(k,v){state.res[k]=clamp((state.res[k]||0)+v,0,CAP)}
function lv(id){return Math.max(1,state.lv[id]||1)}
function cap(){return Math.min(NPC_MAX,state.built.inn?12+lv('inn')*8:state.built.hut?3:0)}
function built(){return BUILDINGS.filter(b=>state.built[b.id])}
function site(id){return BUILDINGS.find(b=>b.id===id)}
function passiveRate(){return{wood:state.built.lumber?.18*lv('lumber'):0,stone:state.built.quarry?.16*lv('quarry'):0,food:state.built.inn?.035*lv('inn'):0}}

function drawTerrain(){rect(0,0,W,H,state.phase==='night'?'#1b2b33':'#30473d');rect(sx(-540),sy(-420),1080,840,state.phase==='night'?'#22383a':'#354e43');for(let yy=-330;yy<=330;yy+=16)for(let xx=-410;xx<=410;xx+=16){const h=Math.abs((xx*17+yy*31)%97);if(h<21){rect(sx(xx),sy(yy),2,6,state.phase==='night'?'#2b4743':'#496352');if(h<7)rect(sx(xx+4),sy(yy+2),2,2,'#8a815c')}}ellipse(sx(0),sy(74),118,73,state.phase==='night'?'#2b3430':'#5d5b45')}
function drawTree(n){if(n.respawn>now())return;const x=sx(n.x),y=sy(n.y),r=n.hp/n.max;ellipse(x,y+13,19,6,'#14252288');rect(x-4,y-11,8,28,n.flash>0?'#b8874d':'#654930');rect(x-2,y-9,3,26,'#96704b');const cc=r>.66?'#46604b':r>.33?'#65704d':'#756747';rect(x-19,y-33,38,14,cc);rect(x-13,y-42,26,12,'#5f7656');rect(x-23,y-27,46,11,'#385442')}
function drawRock(n){if(n.respawn>now())return;const x=sx(n.x),y=sy(n.y);ellipse(x,y+12,18,6,'#14252288');const col=n.flash>0?'#bbc0b4':'#78817d';rect(x-17,y-4,34,16,col);rect(x-12,y-13,24,12,'#929992');rect(x-6,y-19,13,8,'#a8ada3');rect(x+8,y-8,8,5,'#5b6665')}
function drawBerry(n){if(n.respawn>now())return;const x=sx(n.x),y=sy(n.y);ellipse(x,y+7,14,5,'#15241f88');rect(x-14,y-9,28,17,n.flash>0?'#648663':'#426048');rect(x-10,y-15,20,10,'#557a54');for(const [dx,dy]of[[-7,-6],[1,-8],[8,0],[-2,2]])rect(x+dx,y+dy,3,3,'#b95d6f')}
function roof(x,y,w,col){rect(x-w/2+4,y-28,w-8,16,col);rect(x-w/2,y-22,w,12,col);rect(x-w/2+8,y-32,w-16,4,'#9a8056')}
function building(b){const x=sx(b.x),y=sy(b.y),w=b.w,h=b.h,L=lv(b.id);ellipse(x+5,y+h/2-2,w*.52,9,'#14201f88');if(b.type==='wall'){rect(x-w/2,y-8,w,18,'#5d4633');for(let i=-w/2+4;i<w/2;i+=12){rect(x+i,y-16,8,27,'#76573d');rect(x+i,y-18,8,3,'#9c744a')}return}if(b.type==='quarry'){rect(x-w/2,y+2,w,14,'#665d52');for(let i=-35;i<35;i+=18){rect(x+i,y-12,15,15,'#8a8d86');rect(x+i+4,y-18,8,8,'#a5a79e')}return}const wall=b.type==='forge'?'#7c7567':'#b6a77f';rect(x-w/2,y-h/2+22,w,h-22,wall);roof(x,y-h/2+20,w,b.type==='guild'?'#40566a':b.type==='forge'?'#464d50':'#82483f');rect(x-11,y+h/2-35,22,35,'#3c2f2a');rect(x-8,y+h/2-32,16,32,'#251f20');rect(x-7,y-h/2+31,14,12,'#d5a657');rect(x-5,y-h/2+33,10,8,'#f2d188');if(L>1){ctx.fillStyle='#e1bd6a';ctx.font='7px '+getComputedStyle(document.body).fontFamily;ctx.textAlign='center';ctx.fillText('LV '+L,x,y-h/2-7)}}
function ghost(b){if(state.built[b.id])return;const x=sx(b.x),y=sy(b.y);ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle=b.unlock()?'#d9b55e':'#6f786f';ctx.setLineDash([4,4]);ctx.strokeRect(x-b.w/2,y-b.h/2,b.w,b.h);ctx.setLineDash([]);rect(x-17,y-5,34,10,'#0d2122cc');ctx.fillStyle=b.unlock()?'#e2bf69':'#8c958b';ctx.font='7px '+getComputedStyle(document.body).fontFamily;ctx.textAlign='center';ctx.fillText('建設',x,y+2);ctx.restore()}
function actor(wx,wy,dir,color,isPlayer=false,walk=0){let x=sx(wx),y=sy(wy);ellipse(x,y+12,isPlayer?15:12,5,'#14201f88');const bob=Math.floor(walk)%2?1:0;rect(x-7,y-29-bob,14,10,isPlayer?'#c7b98e':color);rect(x-8,y-19-bob,16,17,color);rect(x-6,y-2-bob,5,12,'#343d42');rect(x+2,y-2+(bob?0:1),5,11,'#343d42');if(isPlayer&&toolSwing>0){const a=(1-toolSwing)*2.2-1.1,tx=x+Math.cos(a)*19,ty=y-8+Math.sin(a)*19;line(x+7,y-9,tx,ty,2,'#d2d7ce');rect(tx-2,ty-2,7,3,target?.kind==='rock'?'#a8aca3':'#aa7d48')}}
function zombie(z){actor(z.x,z.y,z.dir,'#657d56',false,z.walk);rect(sx(z.x)-10,sy(z.y)-38,20,3,'#3b2021');rect(sx(z.x)-10,sy(z.y)-38,20*(z.hp/z.max),3,'#c9615e')}
function drawCamp(){const x=sx(0),y=sy(78);ellipse(x,y+14,26,8,'#15201d88');rect(x-23,y+9,46,5,'#5b3c27');const f=Math.sin(time*.006)*2;ctx.fillStyle='#ec6d32';ctx.beginPath();ctx.moveTo(x-12,y+8);ctx.quadraticCurveTo(x-15,y-8,x+f,y-27);ctx.quadraticCurveTo(x+16,y-7,x+10,y+8);ctx.fill();ctx.fillStyle='#ffd06b';ctx.beginPath();ctx.moveTo(x-5,y+8);ctx.quadraticCurveTo(x-5,y-5,x+1,y-17);ctx.quadraticCurveTo(x+8,y-3,x+5,y+8);ctx.fill()}
function drawFx(dt){for(let i=fx.length-1;i>=0;i--){const p=fx[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0){fx.splice(i,1);continue}ctx.globalAlpha=Math.min(1,p.life*2);rect(sx(p.x),sy(p.y),p.s,p.s,p.c);ctx.globalAlpha=1}}
function burst(x,y,c,count=10){for(let i=0;i<count;i++)fx.push({x:x+rnd(-8,8),y:y+rnd(-6,6),vx:rnd(-42,42),vy:rnd(-68,-15),life:rnd(.35,.65),s:rnd(2,4),c})}
function render(dt){drawTerrain();const list=[];for(const n of nodes)if(n.respawn<=now())list.push({y:n.y+14,fn:()=>n.type==='tree'?drawTree(n):n.type==='rock'?drawRock(n):drawBerry(n)});for(const b of BUILDINGS)list.push({y:b.y+b.h/2,fn:()=>state.built[b.id]?building(b):ghost(b)});for(const w of state.crew)list.push({y:w.y+14,fn:()=>actor(w.x,w.y,w.dir,w.color,false,w.walk)});for(const z of zombies)list.push({y:z.y+14,fn:()=>zombie(z)});list.push({y:92,fn:drawCamp});list.push({y:player.y+14,fn:()=>actor(player.x,player.y,player.dir,'#748fa0',true,player.walk)});list.sort((a,b)=>a.y-b.y).forEach(o=>o.fn());drawFx(dt);if(state.phase==='night'){ctx.fillStyle='rgba(8,14,31,.28)';ctx.fillRect(0,0,W,H)}}

function updateCamera(dt){const tx=player.x,ty=player.y-55;camera.x+=(tx-camera.x)*Math.min(1,dt*3.6);camera.y+=(ty-camera.y)*Math.min(1,dt*3.6)}
function blocked(x,y){if(x<-365||x>365||y<-300||y>320)return true;for(const b of built())if(b.id!=='barricade'&&x>b.x-b.w/2-10&&x<b.x+b.w/2+10&&y+12>b.y-b.h/2+25&&y+12<b.y+b.h/2+8)return true;return false}
function move(dx,dy){const nx=player.x+dx,ny=player.y+dy;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny}
function nearest(){let best=null,d0=1e9;for(const n of nodes){if(n.respawn>now())continue;const d=Math.hypot(player.x-n.x,player.y-n.y);if(d<54&&d<d0){best={kind:n.type,node:n,d};d0=d}}for(const z of zombies){const d=Math.hypot(player.x-z.x,player.y-z.y);if(d<61&&d<d0){best={kind:'zombie',z,d};d0=d}}return best}
function context(){target=nearest();const k=$('contextKicker'),t=$('contextTitle'),s=$('contextSub'),a=$('action');a.classList.remove('auto');if(!target){k.textContent='AUTO';t.textContent='探索中';s.textContent='木・石・食料に近づくと自動採取';a.textContent='AUTO';a.classList.add('auto');a.disabled=true;return}if(target.kind==='tree'){k.textContent='AUTO GATHER';t.textContent='木を伐採中';s.textContent=`耐久 ${target.node.hp}/${target.node.max} · 自動`;a.textContent='AUTO';a.classList.add('auto');a.disabled=true}else if(target.kind==='rock'){k.textContent='AUTO GATHER';t.textContent='石を採掘中';s.textContent=`耐久 ${target.node.hp}/${target.node.max} · 自動`;a.textContent='AUTO';a.classList.add('auto');a.disabled=true}else if(target.kind==='berry'){k.textContent='AUTO GATHER';t.textContent='食料を採集中';s.textContent=`残り ${target.node.hp}/${target.node.max} · 自動`;a.textContent='AUTO';a.classList.add('auto');a.disabled=true}else{k.textContent='ENEMY';t.textContent='ゾンビ';s.textContent=`HP ${target.z.hp}/${target.z.max}`;a.textContent='攻撃';a.disabled=false}}
function autoHarvest(dt){if(!target||target.kind==='zombie'||target.node.respawn>now())return;autoTimer-=dt*state.speed;if(autoTimer>0)return;autoTimer=.48;const n=target.node;n.hp--;n.flash=.11;toolSwing=1;state.harvested++;if(n.type==='tree'){add('wood',1);AudioLite.chop();burst(n.x,n.y,'#b9864e',4)}else if(n.type==='rock'){add('stone',1);AudioLite.mine();burst(n.x,n.y,'#9da29b',5)}else{add('food',1);AudioLite.pickup();burst(n.x,n.y,'#b95d6f',3)}if(n.hp<=0){if(n.type==='tree'){add('wood',2);log('木を伐りきった　WOOD +2');n.respawn=now()+8000}else if(n.type==='rock'){add('stone',2);log('岩を採りきった　STONE +2');n.respawn=now()+9500}else{add('food',1);log('食料を回収　FOOD +1');n.respawn=now()+6500}n.hp=n.max;AudioLite.pickup()}save('auto-gather')}
function build(b){if(!b.unlock()){log('もう少し街を広げると解放');return}if(!canPay(b.cost)){log(`素材不足　${costText(b.cost)}`);return}pay(b.cost);state.built[b.id]=true;state.lv[b.id]=1;if(b.id==='barricade'){barricadeMax=90;barricadeHp=90}burst(b.x,b.y,'#efc973',22);AudioLite.build();log(`${b.name} 完成！`);save('build')}
function upgrade(b){const L=lv(b.id),cost={wood:Math.ceil(7*L*1.45),stone:Math.ceil(4*L*1.4)};if(!canPay(cost)){log(`強化素材不足　${costText(cost)}`);return}pay(cost);state.lv[b.id]=L+1;burst(b.x,b.y,'#d7ae59',15);AudioLite.build();log(`${b.name} → Lv.${state.lv[b.id]}`);save('upgrade')}
function attack(z){z.hp--;toolSwing=1;AudioLite.hit();burst(z.x,z.y,'#c9615e',4);if(z.hp<=0){state.kills++;zombies.splice(zombies.indexOf(z),1);add('gold',2);if(Math.random()<.18){add('crystal',1);AudioLite.rare();log('ゾンビ撃破　星晶 +1')}else log('ゾンビ撃破　2G');save('kill')}}
$('action').onpointerdown=e=>{e.preventDefault();if(target?.kind==='zombie')attack(target.z)};

function crewColor(r){return r==='SSR'?'#c69a50':r==='SR'?'#8e6aae':r==='R'?'#5a8798':'#6e7b75'}
function makeCrew(i,rarity='N'){return{id:'c'+Date.now()+'-'+i,x:rnd(-26,26),y:rnd(88,135),dir:'down',walk:0,cool:rnd(0,2),rarity,color:crewColor(rarity)}}
function hire(){if(!state.built.hut){log('まず開拓小屋を建てよう');return}if(state.crew.length>=cap()){log(`人員上限 ${cap()}人`);return}const cost={food:2+Math.floor(state.crew.length/3)};if(!canPay(cost)){log(`FOOD不足　${costText(cost)}`);return}pay(cost);state.crew.push(makeCrew(state.crew.length));AudioLite.build();log('新しい人員が加入した');save('hire')}
function workerTick(dt){if(state.phase!=='day')return;for(const w of state.crew){w.cool-=dt*state.speed;if(w.cool>0)continue;w.cool=rnd(1.3,2.3);const n=nodes.filter(v=>v.respawn<=now()).sort(()=>Math.random()-.5)[0];if(!n)continue;const dx=n.x-w.x,dy=n.y-w.y,l=Math.hypot(dx,dy)||1;w.x+=dx/l*20;w.y+=dy/l*20;w.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');w.walk+=1;if(Math.hypot(w.x-n.x,w.y-n.y)<48){if(n.type==='tree')add('wood',.35);else if(n.type==='rock')add('stone',.32);else add('food',.18)}}}
function spawnWave(){if(waveSpawned)return;waveSpawned=true;const count=Math.min(8,1+Math.floor(state.day*.5));zombies=[];for(let i=0;i<count;i++){const a=i/count*Math.PI*2,r=330+rnd(0,50);zombies.push({x:Math.cos(a)*r,y:45+Math.sin(a)*r*.8,hp:3,max:3,dir:'down',walk:0,atk:0})}log('夜襲　でも今夜は建設の邪魔をする程度だ')}
function phaseChange(){if(state.phase==='day'){state.phase='night';state.phaseElapsed=0;waveSpawned=false;spawnWave()}else{state.phase='day';state.day++;state.phaseElapsed=0;zombies=[];waveSpawned=false;add('gold',4+state.day);log(`DAY ${state.day}　建設ボーナス GOLD +${4+state.day}`);save('dawn')}}
function zombieTick(dt){if(state.phase!=='night')return;for(const z of zombies){const dx=-z.x,dy=80-z.y,l=Math.hypot(dx,dy)||1;z.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');z.walk+=dt*5;if(l>55){z.x+=dx/l*15*dt;z.y+=dy/l*15*dt}else{z.atk-=dt;if(z.atk<=0){z.atk=1.5;if(state.built.barricade&&barricadeHp>0)barricadeHp=Math.max(0,barricadeHp-3);else state.core=Math.max(0,state.core-2)}}}}
function useSpeed(){if(state.res.sand<=0){log('倍速には時砂が必要');return}if(state.speed>=3){log('最大 ×3');return}state.res.sand--;state.speed++;state.speedLeft=30;save('speed')}
$('speed').onpointerdown=e=>{e.preventDefault();useSpeed()};
function summon(){if(state.res.crystal<5){log('星晶5個が必要');return}state.res.crystal-=5;state.pity++;const r=Math.random();let rarity='N';if(state.pity>=20){rarity='SR';state.pity=0}else if(r<.02)rarity='SSR';else if(r<.10)rarity='SR';else if(r<.35)rarity='R';const names=['リオ','ミナ','ガレス','ノア','セラ','ユアン'];const unit={name:names[(Math.random()*names.length)|0],rarity};state.collection.push(unit);AudioLite.rare();log(`${rarity} ${unit.name} が加入候補になった`);save('summon')}

function serialize(){return{v:92,revision:++state.revision,savedAt:Date.now(),state:{day:state.day,phase:state.phase,phaseElapsed:state.phaseElapsed,res:{...state.res},core:state.core,kills:state.kills,harvested:state.harvested,pity:state.pity,built:{...state.built},lv:{...state.lv},collection:state.collection},player:{x:player.x,y:player.y,dir:player.dir},crew:state.crew.slice(0,NPC_MAX),nodes:nodes.map(n=>({id:n.id,hp:n.hp,respawn:n.respawn})),zombies,waveSpawned,barricadeHp,barricadeMax}}
function save(reason='auto'){try{const payload=JSON.stringify(serialize()),old=localStorage.getItem(SAVE);if(old)localStorage.setItem(BACK,old);localStorage.setItem(SAVE,payload);state.savedAt=Date.now();saveFlash();return true}catch(e){console.warn('save failed',reason,e);return false}}
function parse(s){try{return JSON.parse(s)}catch{return null}}
function restore(s){if(!s||s.v!==92||!s.state)return false;const q=s.state;state.day=Math.max(1,+q.day||1);state.phase=q.phase==='night'?'night':'day';state.phaseElapsed=Math.max(0,+q.phaseElapsed||0);for(const k of ['wood','stone','food','gold','crystal','sand'])state.res[k]=clamp(+(q.res?.[k]||0),0,CAP);state.core=clamp(+q.core||100,0,100);state.kills=Math.max(0,+q.kills||0);state.harvested=Math.max(0,+q.harvested||0);state.pity=clamp(+q.pity||0,0,99);state.built=q.built&&typeof q.built==='object'?{...q.built}:{};state.lv=q.lv&&typeof q.lv==='object'?{...q.lv}:{};state.collection=Array.isArray(q.collection)?q.collection.slice(0,500):[];if(s.player){player.x=clamp(+s.player.x||0,-360,360);player.y=clamp(+s.player.y||110,-300,320);player.dir=s.player.dir||'down'}state.crew=Array.isArray(s.crew)?s.crew.slice(0,NPC_MAX).map((w,i)=>({...makeCrew(i,w.rarity||'N'),...w})):[];if(Array.isArray(s.nodes))for(const qn of s.nodes){const n=nodes.find(v=>v.id===qn.id);if(n){n.hp=clamp(+qn.hp||n.max,1,n.max);n.respawn=Math.max(0,+qn.respawn||0)}}zombies=Array.isArray(s.zombies)?s.zombies.slice(0,16):[];waveSpawned=!!s.waveSpawned;barricadeHp=Math.max(0,+s.barricadeHp||0);barricadeMax=Math.max(0,+s.barricadeMax||0);camera.x=player.x;camera.y=player.y-55;return true}
function load(){if(restore(parse(localStorage.getItem(SAVE)))){log('オートセーブから再開');return true}if(restore(parse(localStorage.getItem(BACK)))){log('バックアップから復旧');return true}return false}

function mission(){let m='歩くだけで木と石を集めて、開拓小屋を建てる';if(state.built.hut&&!state.built.lumber)m='木こり小屋を建ててWOODを自動化';else if(state.built.lumber&&!state.built.quarry)m='採石場を建ててSTONEを自動化';else if(state.built.quarry&&state.crew.length===0)m='人員を1人雇って街を動かす';else if(state.crew.length>0&&!state.built.inn)m='宿屋を建てて街を広げる';else if(state.built.inn&&!state.built.forge)m='鍛冶場を建てる';else if(state.built.forge&&!state.built.guild)m='ギルド本部を建てる';else if(state.built.guild)m='好きな建物を強化して街を育てる';$('missionText').textContent=m}
function ui(){for(const k of ['wood','stone','food','gold'])$(k).textContent=fmt(state.res[k]);$('crystal').textContent=fmt(state.res.crystal);$('sand').textContent=fmt(state.res.sand);$('crewCount').textContent=state.crew.length;$('dayLabel').textContent=String(state.day).padStart(2,'0');$('phaseLabel').textContent=state.phase==='day'?'DAY':'NIGHT';const total=state.phase==='day'?state.dayDuration:state.nightDuration,left=Math.max(0,total-state.phaseElapsed);$('clock').textContent=`${state.phase==='day'?'昼':'夜'} ${Math.floor(left/60)}:${Math.floor(left%60).toString().padStart(2,'0')}`;$('speed').textContent=state.speed===1?`×1 砂${state.res.sand}`:`×${state.speed} ${Math.ceil(state.speedLeft)}s`;document.body.classList.toggle('night',state.phase==='night');mission();context()}
function update(dt){time+=dt*1000;toolSwing=Math.max(0,toolSwing-dt*3.2);for(const n of nodes)n.flash=Math.max(0,n.flash-dt);if(state.speedLeft>0){state.speedLeft=Math.max(0,state.speedLeft-dt);if(!state.speedLeft){state.speed=1;log('時砂終了　×1');save('speed-end')}}const sim=dt*state.speed;state.phaseElapsed+=sim;if(state.phaseElapsed>=(state.phase==='day'?state.dayDuration:state.nightDuration))phaseChange();move(player.vx*dt,player.vy*dt);if(Math.abs(player.vx)+Math.abs(player.vy)>2)player.walk+=dt*10;updateCamera(dt);const rate=passiveRate();add('wood',rate.wood*dt*state.speed);add('stone',rate.stone*dt*state.speed);add('food',rate.food*dt*state.speed);workerTick(dt);zombieTick(dt);context();autoHarvest(dt);if(state.core<=0){state.core=70;state.phase='day';state.phaseElapsed=0;zombies=[];log('拠点を修復して朝から再開');save('defeat')}saveTimer+=dt;if(saveTimer>=1.5){saveTimer=0;save('heartbeat')}}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);render(dt);ui();requestAnimationFrame(loop)}
function vector(e){const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,d=Math.hypot(dx,dy),dead=5,max=82,k=d<dead?0:clamp((d-dead)/(max-dead),0,1),nx=d?dx/d:0,ny=d?dy/d:0,base=154;player.vx=nx*base*k;player.vy=ny*base*k;if(Math.abs(player.vx)>Math.abs(player.vy))player.dir=player.vx>0?'right':'left';else if(k>0)player.dir=player.vy>0?'down':'up'}
c.addEventListener('pointerdown',e=>{if(pointer)return;e.preventDefault();AudioLite.start();pointer={id:e.pointerId,x:e.clientX,y:e.clientY};try{c.setPointerCapture(e.pointerId)}catch{}});
c.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;e.preventDefault();vector(e)});
function release(e){if(!pointer||e.pointerId!==pointer.id)return;player.vx=player.vy=0;pointer=null}
c.addEventListener('pointerup',release);c.addEventListener('pointercancel',release);c.addEventListener('lostpointercapture',()=>{player.vx=player.vy=0;pointer=null});

function showSheet(tab){const title=$('sheetTitle'),body=$('sheetBody');$('sheet').hidden=false;let html='';if(tab==='build'){title.textContent='建築';html='<p class="sheetNote">作業台は廃止。素材があればすぐ建てられる。主役は「街が広がる気持ちよさ」</p><div class="sheetGrid">'+BUILDINGS.map(b=>`<div class="sheetRow"><div><b>${b.name} ${state.built[b.id]?`Lv.${lv(b.id)}`:''}</b><small>${b.desc}<br>${state.built[b.id]?'強化可能':costText(b.cost)}</small></div><button data-build="${b.id}" ${!b.unlock()&&!state.built[b.id]?'disabled':''}>${state.built[b.id]?'強化':'建設'}</button></div>`).join('')+'</div>'}else if(tab==='crew'){title.textContent='人員';html=`<p class="sheetNote">開拓小屋を建てたら雇用可能。人員は昼に木・石・食料を自動回収する</p><div class="sheetRow"><div><b>人員 ${state.crew.length} / ${cap()}</b><small>雇用コストはFOOD中心</small></div><button id="hireBtn" ${!state.built.hut?'disabled':''}>雇う</button></div>`}else if(tab==='bag'){title.textContent='バッグ';html=`<p class="sheetNote">レア資源と倍速アイテム</p><div class="sheetGrid"><div class="sheetRow"><div><b>◇ 星晶 ${state.res.crystal}</b><small>5個で召喚</small></div><span></span></div><div class="sheetRow"><div><b>時砂 ${state.res.sand}</b><small>30秒の倍速。最大×3</small></div><span></span></div></div>`}else if(tab==='summon'){title.textContent='召喚';html=`<p class="sheetNote">N 65% / R 25% / SR 8% / SSR 2% · 20回でSR以上保証</p><div class="sheetRow"><div><b>召喚</b><small>星晶5個</small></div><button id="summonBtn">召喚する</button></div><div class="sheetGrid" style="margin-top:7px">${state.collection.slice(-8).reverse().map(u=>`<div class="sheetRow"><div><b class="rarity-${u.rarity}">${u.rarity} ${u.name}</b></div><span></span></div>`).join('')}</div>`}else{title.textContent='目標';html=`<p class="sheetNote">DAY ${state.day} · ${state.phase==='day'?'昼':'夜'} · 採取 ${state.harvested}</p><div class="sheetRow"><div><b>${$('missionText').textContent}</b><small>歩く → 自動採取 → 建設 → 自動化 → さらに建設</small></div><span></span></div>`}body.innerHTML=html;body.querySelectorAll('[data-build]').forEach(btn=>btn.onclick=()=>{const b=site(btn.dataset.build);state.built[b.id]?upgrade(b):build(b);showSheet('build')});const h=$('hireBtn');if(h)h.onclick=()=>{hire();showSheet('crew')};const s=$('summonBtn');if(s)s.onclick=()=>{summon();showSheet('summon')}}
document.querySelectorAll('.dock button').forEach(b=>b.onpointerdown=e=>{e.preventDefault();AudioLite.start();showSheet(b.dataset.tab)});$('sheetClose').onclick=()=>{$('sheet').hidden=true};$('sheet').onpointerdown=e=>{if(e.target===$('sheet'))$('sheet').hidden=true};

setInterval(()=>save('interval'),2000);addEventListener('pagehide',()=>save('pagehide'));addEventListener('beforeunload',()=>save('beforeunload'));document.addEventListener('visibilitychange',()=>{player.vx=player.vy=0;last=performance.now();if(document.hidden)save('hidden')});
const q=new URLSearchParams(location.search);if(q.get('demo')){localStorage.removeItem(SAVE);localStorage.removeItem(BACK);Object.assign(state.res,{wood:22,stone:18,food:10,gold:12,crystal:3,sand:2});if(q.get('demo')==='town'){state.built={hut:true,lumber:true,quarry:true,store:true};state.crew=[makeCrew(0,'R'),makeCrew(1,'N')]}if(q.get('demo')==='night'){state.built={hut:true,lumber:true,quarry:true,barricade:true};state.phase='night';state.day=3;state.phaseElapsed=5;barricadeMax=90;barricadeHp=90;spawnWave()}}else load();
if(!localStorage.getItem(SAVE))save('initial');requestAnimationFrame(loop);log(state.crew.length?'前回の続きから再開':'近づくだけで自動採取。好きに歩いて街を広げよう');
window.GUILD_V092={state:()=>JSON.parse(JSON.stringify({day:state.day,phase:state.phase,res:state.res,crew:state.crew.length,built:state.built})),save:()=>save('api'),load,hire,summon};
})();
