const REPEAT_CAP_MAX={hut:18,lantern:24,watchtower:8};
const RESOURCE_MIN_ACTIVE={tree:18,rock:12,food:8};
const RESOURCE_RESPAWN_MS={tree:12000,rock:14000,food:8000};
function repeatBuildCap(type){if(type==='hut')return Math.min(REPEAT_CAP_MAX.hut,3+settlementLevel()*3);if(type==='lantern')return Math.min(REPEAT_CAP_MAX.lantern,4+settlementLevel()*4);if(type==='watchtower')return Math.min(REPEAT_CAP_MAX.watchtower,2+settlementLevel());return 99}
function nearestNode(o,type,claimed=new Set()){let best=null,bd=1e9;for(const n of state.nodes){if(!n.alive||n.type!==type||claimed.has(n.id))continue;const d=Math.hypot(o.x-n.x,o.y-n.y);if(d<bd){best=n;bd=d}}return best}
function respawnNearFrontier(n){const B=bounds(),side=Math.floor(Math.random()*4),margin=58+rnd(0,72);if(side===0){n.x=B.l-margin;n.y=rnd(B.t-70,B.b+70)}else if(side===1){n.x=B.r+margin;n.y=rnd(B.t-70,B.b+70)}else if(side===2){n.x=rnd(B.l-80,B.r+80);n.y=B.t-margin}else{n.x=rnd(B.l-80,B.r+80);n.y=B.b+margin}n.x=clamp(n.x,WORLD.minX+35,WORLD.maxX-35);n.y=clamp(n.y,WORLD.minY+35,WORLD.maxY-35)}
function reviveNode(n){if(state.palisade.built&&inside(n.x,n.y,bounds()))respawnNearFrontier(n);n.alive=true;n.hp=n.maxHp;n.respawnAt=0;n.starter=false;fxBurst(n.x,n.y,n.type==='tree'?'#5d8352':n.type==='rock'?'#aaa99b':'#9d7157',7,.7)}
function hitNode(n,source='player'){if(!n?.alive)return;const lm=1+(state.buildings.find(b=>b.type==='lumber')?.level||0)*.12,qm=1+(state.buildings.find(b=>b.type==='quarry')?.level||0)*.12,eff=source==='worker'?(.45+.45*state.morale/100):1;let gain=0;if(n.type==='tree'){gain=(source==='worker'?1.05:1.5)*lm*eff;addRes('wood',gain);floatText(n.x,n.y-18,'+'+gain.toFixed(1),'#d59a5d');fxBurst(n.x,n.y,COLORS.wood,6);A.sfx('chop')}else if(n.type==='rock'){gain=(source==='worker'?.88:1.25)*qm*eff;addRes('stone',gain);floatText(n.x,n.y-15,'+'+gain.toFixed(1),'#c0c1b6');fxBurst(n.x,n.y,COLORS.stone,6);A.sfx('mine')}else{gain=source==='worker'?1.05:1.5;addRes('food',gain);floatText(n.x,n.y-13,'+'+gain.toFixed(1),'#d78678');fxBurst(n.x,n.y,COLORS.food,5);A.sfx('pickup')}const nodeDamage=source==='worker'?(n.type==='rock'?1.25:1):(n.type==='rock'?3:2);n.hp-=nodeDamage;if(n.hp<=0){n.alive=false;n.respawnAt=Date.now()+RESOURCE_RESPAWN_MS[n.type];fxBurst(n.x,n.y,n.type==='tree'?'#6f472f':n.type==='rock'?'#696e69':'#507353',13,1.2);floatText(n.x,n.y-8,`${Math.round(RESOURCE_RESPAWN_MS[n.type]/1000)}s RESPAWN`,'#c9b98f');autoTarget=null}updateHud()}
function respawnNodes(){const now=Date.now();for(const n of state.nodes)if(!n.alive&&n.respawnAt&&n.respawnAt<=now)reviveNode(n);const active={tree:0,rock:0,food:0};for(const n of state.nodes)if(n.alive)active[n.type]=(active[n.type]||0)+1;for(const type of Object.keys(RESOURCE_MIN_ACTIVE)){let need=RESOURCE_MIN_ACTIVE[type]-(active[type]||0);if(need<=0)continue;for(const n of state.nodes.filter(n=>!n.alive&&n.type===type).sort((a,b)=>(a.respawnAt||0)-(b.respawnAt||0))){if(need<=0)break;reviveNode(n);need--}}}
function playerGather(dt){respawnNodes();if(input.mag>.2){autoTarget=null;playerWork=0;return}if(!autoTarget||!autoTarget.alive||dist(state.player,autoTarget)>48){let best=null,bd=48;for(const n of state.nodes){if(!n.alive)continue;const d=dist(state.player,n);if(d<bd){best=n;bd=d}}autoTarget=best}if(!autoTarget){playerWork=0;return}playerWork+=dt;if(playerWork>.32){playerWork=0;state.player.swing=1;hitNode(autoTarget,'player')}}
function buildRadius(type){if(type==='lantern')return 22;if(type==='watchtower')return 31;if(type==='hut')return 38;return 40}
function buildCandidates(type){const B=bounds(),pad=32,r=buildRadius(type),step=type==='lantern'?40:56,out=[];for(let y=B.t+pad;y<=B.b-pad;y+=step){for(let x=B.l+pad;x<=B.r-pad;x+=step){if(Math.abs(x)<52&&Math.abs(y-24)<68)continue;if(Math.abs(x)<38&&y>B.b-80)continue;let ok=true;for(const b of state.buildings){if(Math.hypot(x-b.x,y-b.y)<r+buildRadius(b.type)+7){ok=false;break}}if(ok)out.push({p:[x,y],i:`${type}:${Math.round(x)}:${Math.round(y)}`,d:Math.hypot(state.player.x-x,state.player.y-y)})}}return out.sort((a,b)=>a.d-b.d)}
function freeSlot(type){return buildCandidates(type)[0]||null}
function build(type){A.enable();if(type==='palisade'){const next=state.palisade.built?state.palisade.level+1:1;if(next>6){toast('城壁は最大Lv.6');return}if(next>WALL_CAP[rankIndex()]){toast(`RANK ${RANKS[Math.min(5,next-1)]}で城壁Lv.${next}解禁`);return}const c=wallStats(next);if(!hasCost(c)){toast('城壁素材不足 · '+fmtCost(c),true);return}pay(c);state.palisade={built:true,level:next,hp:c.hp,maxHp:c.hp,builtAt:performance.now()};state.stats.bestWall=Math.max(state.stats.bestWall,next);clearInside();fxBurst(0,0,'#d6a45f',30,1.5);toast(next===1?'防壁完成 · 夜が本番になる':`領土拡張 · 城壁Lv.${next}`);A.sfx('build');closeSheet();save();updateHud();return}const d=BUILD[type];if(!d)return;if(rankIndex()<d.unlock){toast(`RANK ${RANKS[d.unlock]}で解禁`);return}const existing=state.buildings.filter(b=>b.type===type);if(!d.repeat&&existing.length){toast(d.name+'は建設済み');return}if(d.repeat&&existing.length>=repeatBuildCap(type)){toast(`${d.name} 建設上限 ${existing.length}/${repeatBuildCap(type)} · 城壁を拡張`);return}const c=costFor(type,1);if(!hasCost(c)){toast(d.name+' 素材不足 · '+fmtCost(c),true);return}const s=freeSlot(type);if(!s){toast('城内に建築スペースがない · 城壁を拡張');return}pay(c);const b={id:'b'+Date.now()+Math.random(),type,level:1,slot:`${s.i}:${Date.now()}`,x:s.p[0],y:s.p[1],builtAt:performance.now()};state.buildings.push(b);fxBurst(b.x,b.y,'#d7b26e',20,1.25);toast(`${d.name} 完成 · ${existing.length+1}棟`);A.sfx('build');closeSheet();save();updateHud()}
function upgrade(type){const b=state.buildings.find(x=>x.type===type&&x.level<(BUILD[type]?.max||1));if(!b)return;const c=costFor(type,b.level+1);if(!hasCost(c)){toast('強化素材不足 · '+fmtCost(c),true);return}pay(c);b.level++;b.builtAt=performance.now();fxBurst(b.x,b.y,'#f0cf84',28,1.4);if(type==='guild')toast(`GUILD RANK UP · ${rank()}`);else toast(`${BUILD[type].name} Lv.${b.level}`);A.sfx('build');save();updateHud()}
function hire(role){if(!maxWorkers()){toast('まずHOUSEを建てる');return}if(state.workers.length>=maxWorkers()){toast('人口上限 · HOUSEかRANKを上げる');return}if(role==='guard'&&!state.buildings.some(b=>b.type==='barracks')){toast('衛兵にはBARRACKSが必要');return}const food=role==='guard'?9:role==='food'?5:6;if(state.food<food){toast(`FOOD ${food} 必要`,true);return}state.food-=food;const h=state.buildings.find(b=>b.type==='hut')||{x:0,y:0},i=state.workers.length;const maxHp=role==='guard'?120:85;state.workers.push({id:'w'+Date.now()+Math.random(),role,x:h.x+rnd(-10,10),y:h.y+22+rnd(-5,7),seed:i%4,targetId:null,work:0,anim:rnd(0,6),cool:0,hp:maxHp,maxHp,dead:false,death:0,hit:0});toast(ROLE_NAMES[role]+' が加入');A.sfx('hire');save();updateHud()}
function route(o,tx,ty){if(!state.palisade.built||state.palisade.hp<=0)return{x:tx,y:ty};const B=bounds(),a=inside(o.x,o.y,B),b=inside(tx,ty,B);if(a===b)return{x:tx,y:ty};const inGate={x:0,y:B.b-18},outGate={x:0,y:B.b+24};if(a){if(dist(o,inGate)>10)return inGate;return outGate}else{if(dist(o,outGate)>10)return outGate;return inGate}}
function move(o,tx,ty,speed,dt){const dx=tx-o.x,dy=ty-o.y,d=Math.hypot(dx,dy)||1;o.x+=dx/d*speed*dt;o.y+=dy/d*speed*dt;o.anim=(o.anim||0)+dt*7;return d<speed*dt+2}
function ensureWorkerVitals(w){if(!Number.isFinite(w.maxHp))w.maxHp=w.role==='guard'?120:85;if(!Number.isFinite(w.hp))w.hp=w.maxHp;if(typeof w.dead!=='boolean')w.dead=false;if(!Number.isFinite(w.death))w.death=0;if(!Number.isFinite(w.hit))w.hit=0;if(!Number.isFinite(w.cool))w.cool=0}
function nearestWorkerEnemy(w,range){let best=null,bd=range;for(const e of state.enemies){if(e.dead)continue;const d=dist(w,e);if(d<bd){best=e;bd=d}}return best}
function workerCombat(w,dt){const guard=w.role==='guard',range=guard?220:54,e=nearestWorkerEnemy(w,range);if(!e)return false;w.targetId=null;w.state='combat';const d=dist(w,e);if(guard&&d>30){const rt=route(w,e.x,e.y);move(w,rt.x,rt.y,52,dt);return true}if(!guard&&d>33)return false;if(w.cool<=0){w.cool=guard?.62:.95;w.swing=1;const dmg=guard?(14+(state.buildings.find(b=>b.type==='barracks')?.level||1)*4):5;damageEnemy(e,dmg,w.x,w.y,true)}return true}
function updateWorkers(dt){const claimed=new Set();for(const w of state.workers)if(w.targetId)claimed.add(w.targetId);for(let i=0;i<state.workers.length;i++){const w=state.workers[i];ensureWorkerVitals(w);if(w.dead)continue;w.cool=Math.max(0,(w.cool||0)-dt);w.hit=Math.max(0,(w.hit||0)-dt);if(workerCombat(w,dt))continue;if(w.role==='guard'){const B=bounds(),tx=clamp(Math.sin(i*2.1+performance.now()/2500)*65,B.l+20,B.r-20),ty=clamp(Math.cos(i*1.4+performance.now()/3000)*45,B.t+20,B.b-20);w.state='patrol';move(w,tx,ty,24,dt);continue}const type=w.role==='wood'?'tree':w.role==='stone'?'rock':'food';let n=state.nodes.find(n=>n.id===w.targetId&&n.alive);if(!n){n=nearestNode(w,type,claimed);w.targetId=n?.id||null;if(n)claimed.add(n.id)}if(!n){w.state='idle';continue}if(dist(w,n)>31){w.state='moving';const rt=route(w,n.x,n.y);move(w,rt.x,rt.y,38,dt)}else{w.state='working';w.work+=dt*(.65+.35*state.morale/100);const cycle=w.role==='stone'?.62:w.role==='wood'?.78:.72;if(w.work>cycle){w.work=0;hitNode(n,'worker');if(!n.alive)w.targetId=null}}}towerCombat(dt)}
function towerCombat(dt){for(const b of state.buildings.filter(b=>b.type==='watchtower')){b.cool=Math.max(0,(b.cool||0)-dt);if(b.cool>0)continue;const range=145+b.level*28,z=state.enemies.filter(e=>!e.dead&&dist(b,e)<range).sort((a,b2)=>dist(b,a)-dist(b,b2))[0];if(!z)continue;b.cool=Math.max(.36,1.05-b.level*.12);state.projectiles.push({kind:'arrow',x:b.x,y:b.y-38,tx:z.x,ty:z.y,target:z,speed:260,damage:10+b.level*6,life:2});A.sfx('hit')}}
function enemySpec(type,wave){const T=threat(),base={walker:{hp:55,spd:25,dmg:10},runner:{hp:42,spd:42,dmg:8},brute:{hp:150,spd:18,dmg:25},spitter:{hp:78,spd:22,dmg:15},warden:{hp:360,spd:16,dmg:34}}[type];return{hp:Math.round(base.hp*(1+T*.09+wave*.08)),spd:base.spd*(1+Math.min(.35,T*.02)),dmg:Math.round(base.dmg*(1+T*.07+wave*.06))}}
function enemyType(i,wave){if(state.day%5===0&&wave===3&&i===0)return'warden';const r=Math.random();if(state.day>=7&&r<.18)return'spitter';if(state.day>=4&&r<.38)return'brute';if(state.day>=2&&r<.62)return'runner';return'walker'}
