(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),last=performance.now(),pointer=null,origin={x:0,y:0},input={x:0,y:0,mag:0},currentPanel=null,autoTarget=null,playerWork=0,lastWorkerHash='',nightWaveMask=0,lastDay=1,lastFullWarn=0;
const SAVE='guild-infinity-frontier-v15',BACKUP=SAVE+'-backup',WORLD={minX:-900,maxX:900,minY:-680,maxY:720};
const RANKS=[{name:'E',pop:40,wall:2},{name:'D',pop:70,wall:3},{name:'C',pop:100,wall:4},{name:'B',pop:150,wall:5},{name:'A',pop:200,wall:6},{name:'S',pop:300,wall:6}];
const BASE_RECIPES={hut:{name:'小屋',wood:22,stone:8,repeat:true,max:5},lumber:{name:'木材所',wood:48,stone:24,repeat:false,max:5},quarry:{name:'採石所',wood:52,stone:34,repeat:false,max:5},lantern:{name:'灯火塔',wood:16,stone:8,repeat:true,max:3},warehouse:{name:'倉庫',wood:38,stone:28,repeat:false,max:5},watchtower:{name:'見張り台',wood:76,stone:48,repeat:false,max:5},barracks:{name:'兵舎',wood:96,stone:68,repeat:false,max:5},guildhall:{name:'ギルド本部',wood:135,stone:92,repeat:false,max:5},palisade:{name:'集落防壁',wood:36,stone:10,repeat:false,max:6}};
const ROLE_NAMES={wood:'木こり',stone:'採石人',food:'採集人',guard:'衛兵'},NAMES=['リナ','ガルド','ミラ','レオン','ノア','セラ','エリナ','ロウ','カイ','フィア','ユノ','バルド','アネラ','ジン','マオ','トト','ルゥ','ベル','ニナ','オルド'];
const PERSONALITIES=[['明るい','手際よし','今日も街を広げよう！','作業速度 +3%'],['慎重','丁寧仕事','急がず、壊れないように','採取ロス -5%'],['無口','集中力','……仕事、行ってくる','採取間隔 -4%'],['熱血','全力作業','任せろ、すぐ終わらせる！','戦闘 +6%'],['のんびり','節約上手','まあ、焦らずいこう','食料消費 -4%']];
const SKINS=['#d7ad83','#c99469','#e1b98f','#b97f5b','#e5c39d'],HAIRS=['#342720','#5b3d27','#20282b','#7a5535','#8d6a46','#3f3030'],CLOTHS=['#617653','#6a6280','#865a4e','#527080','#837149','#675b4d'],ACCENTS=['#d3a25d','#709267','#708cad','#aa6e61'];
const state={version:15,day:1,cycle:.18,phase:'day',wood:0,stone:0,food:0,gold:0,gem:0,hourglass:1,ticket:0,boost:1,boostUntil:0,morale:100,player:{x:0,y:104,vx:0,vy:0,dir:'down',walk:0,swing:0},nodes:[],buildings:[],workers:[],zombies:[],palisade:{built:false,hp:0,maxHp:0,level:0,builtAt:0},lastSaved:0};
const cam={x:0,y:34},worldFx=[],screenFx=[],floats=[],rings=[],slashes=[],projectiles=[];
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rnd=(a,b)=>a+Math.random()*(b-a),sx=x=>W/2+x-cam.x,sy=y=>H/2+y-cam.y;
function toast(text){$('ticker-text').textContent=text;$('ticker').classList.remove('flash');void $('ticker').offsetWidth;$('ticker').classList.add('flash')}
function savePulse(){const d=$('save-dot');if(!d)return;d.classList.add('flash');setTimeout(()=>d.classList.remove('flash'),150)}
function phaseInfo(c=state.cycle){if(c<.06)return['dawn','DAWN'];if(c<.66)return['day','DAY'];if(c<.75)return['dusk','DUSK'];return['night','NIGHT']}
function building(type){return state.buildings.find(b=>b.type===type&&!b.ruined)}function buildings(type){return state.buildings.filter(b=>b.type===type&&!b.ruined)}
function guildLevel(){return building('guildhall')?.level||0}function rankIndex(){return clamp(guildLevel(),0,5)}function rankInfo(){return RANKS[rankIndex()]}
function hutCapacity(b){return 3+(b.level||1)*3}function housingCap(){return state.buildings.filter(b=>b.type==='hut'&&!b.ruined).reduce((s,b)=>s+hutCapacity(b),0)}function maxWorkers(){const allowed=Math.min(rankInfo().pop,housingCap());return Math.max(state.workers.length,allowed)}
function storageCaps(){const L=building('warehouse')?.level||0;return{wood:240+L*520,stone:160+L*360,food:140+L*260}}
function moraleFactor(){return .55+.45*clamp(state.morale,0,100)/100}
function resourceGain(type,amt,wx=null,wy=null){const caps=storageCaps(),cap=caps[type]??999999,before=state[type],next=Math.min(cap,before+amt),got=next-before;state[type]=next;if(got<amt&&Date.now()-lastFullWarn>1500){lastFullWarn=Date.now();toast(`${type.toUpperCase()} FULL · 倉庫を強化しよう`)}if(wx!==null&&got>0){floatWorld(wx,wy,`+${type.toUpperCase()} ${got<1?got.toFixed(1):Math.ceil(got)}`)}return got}
function wallStats(level){const L=clamp(level,1,6);return{maxHp:[0,360,680,1160,1880,2920,4300][L],wood:[0,36,70,125,210,330,500][L],stone:[0,10,28,62,120,210,340][L]}}
function settlementLevel(){return state.palisade.built?state.palisade.level:1}function palisadeBounds(level=settlementLevel()){const l=Math.max(1,level),halfW=160+(l-1)*78,halfH=112+(l-1)*56,gap=42+l*5;return{l:-halfW,r:halfW,t:-halfH,b:halfH,gap}}
function insideRect(x,y,B){return x>B.l&&x<B.r&&y>B.t&&y<B.b}function insideSettlement(x,y){return insideRect(x,y,palisadeBounds())}
function upkeepCost(){return Math.ceil(state.workers.length*.28+state.buildings.filter(b=>!b.ruined).length*.18)}
function updateHud(){const caps=storageCaps();$('wood').textContent=Math.floor(state.wood);$('stone').textContent=Math.floor(state.stone);$('food').textContent=Math.floor(state.food);$('wood-cap').textContent='/'+caps.wood;$('stone-cap').textContent='/'+caps.stone;$('food-cap').textContent='/'+caps.food;[['wood',state.wood,caps.wood],['stone',state.stone,caps.stone],['food',state.food,caps.food]].forEach(([id,v,c])=>$(`${id}`).parentElement.classList.toggle('full',v>=c-.01));$('people').textContent=`${state.workers.length}/${maxWorkers()}`;$('morale').textContent='M'+Math.floor(state.morale);$('rank').textContent='RANK '+rankInfo().name;$('day').textContent='DAY '+state.day;const[ph,label]=phaseInfo();state.phase=ph;$('phase').textContent=label;const mins=Math.floor(state.cycle*1440),hh=String(Math.floor(mins/60)%24).padStart(2,'0'),mm=String(mins%60).padStart(2,'0');$('clock').textContent=hh+':'+mm;$('people-caption').textContent=maxWorkers()>0?`${state.workers.length}/${maxWorkers()}`:'小屋で解禁';$('hourglass').textContent=state.hourglass;$('ticket').textContent=state.ticket;$('gem').textContent=state.gem;$('speed').textContent='×'+state.boost;$('people-lock').hidden=maxWorkers()>0;$('build-rank').textContent=rankInfo().name;$('build-wall').textContent='Lv.'+(state.palisade.level||0);$('build-count').textContent=state.buildings.filter(b=>!b.ruined).length;$('people-morale').textContent=Math.floor(state.morale);$('people-upkeep').textContent=upkeepCost();$('people-guard').textContent='×'+guardMultiplier().toFixed(2);updateNightUi();updateBuildUI();renderWorkers()}
function updateNightUi(){const box=$('night-pressure');if(state.phase!=='night'&&state.phase!=='dusk'){box.hidden=true;return}box.hidden=false;const enemyCount=state.zombies.filter(z=>!z.dead).length;$('wave-label').textContent=state.phase==='dusk'?'NIGHT SOON':`ENEMY ${enemyCount}`;const fill=state.phase==='dusk'?((state.cycle-.66)/.09*20):(20+(state.cycle-.75)/.25*80);$('wave-fill').style.width=clamp(fill,0,100)+'%';$('wall-hp').textContent=state.palisade.built?`WALL ${Math.ceil(state.palisade.hp)}/${state.palisade.maxHp}`:'NO WALL'}
function identity(i){const p=PERSONALITIES[i%PERSONALITIES.length];return{name:NAMES[i%NAMES.length],personality:p[0],trait:p[1],line:p[2],bonus:p[3],visual:{skin:SKINS[i%SKINS.length],hair:HAIRS[(i*3+1)%HAIRS.length],cloth:CLOTHS[(i*5+2)%CLOTHS.length],accent:ACCENTS[i%ACCENTS.length]}}}
function ensureWorker(w,i){const d=identity(i);if(!w.name)Object.assign(w,d);if(!w.visual)w.visual=d.visual;if(!w.state)w.state='idle';if(!Number.isFinite(w.hp))w.hp=100;return w}
function workerStatus(w){if(w.role==='guard')return state.phase==='night'?'防衛中':'巡回中';if(w.state==='working')return w.role==='wood'?'伐採中':w.role==='stone'?'採掘中':'採集中';if(w.state==='moving')return'移動中';return'待機'}
function renderWorkers(){const hash=state.workers.map(w=>`${w.id}:${w.role}:${w.name}:${w.state}:${Math.floor(w.hp||100)}`).join('|');if(hash===lastWorkerHash)return;lastWorkerHash=hash;const el=$('worker-list');if(!el)return;if(!state.workers.length){el.innerHTML='<div class="notice">まだ仲間はいない · 小屋を建てて最初の一人を迎えよう</div>';return}el.innerHTML=state.workers.slice(0,14).map((w,i)=>{ensureWorker(w,i);const v=w.visual;return `<article class="worker-card"><span class="worker-face" style="--skin:${v.skin};--hair:${v.hair};--cloth:${v.cloth};--accent:${v.accent}"><i class="head"></i><i class="hair"></i><i class="eyes"></i><i class="body"></i></span><span class="worker-copy"><b>${w.name} · ${ROLE_NAMES[w.role]}</b><small>${w.personality} / ${w.line}</small><span>${workerStatus(w)} · HP ${Math.ceil(w.hp||100)}</span></span><em class="status">${w.trait}</em></article>`}).join('')+(state.workers.length>14?`<div class="notice">ほか ${state.workers.length-14}人</div>`:'')}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function shadow(x,y,w,h=6,a=.48){ctx.fillStyle=`rgba(3,8,6,${a})`;ctx.fillRect(Math.round(x-w/2),Math.round(y-h/2),Math.round(w),Math.round(h))}function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fill()}function glow(x,y,r,color='255,181,83',a=.18){ctx.save();ctx.globalCompositeOperation='screen';const g=ctx.createRadialGradient(x,y,2,x,y,r);g.addColorStop(0,`rgba(${color},${a})`);g.addColorStop(1,`rgba(${color},0)`);ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore()}
function drawGround(){const ph=state.phase,top=ph==='night'?'#0d1c22':ph==='dusk'?'#354646':ph==='dawn'?'#405b50':'#45654f',bot=ph==='night'?'#16261f':ph==='dusk'?'#504936':ph==='dawn'?'#4c654d':'#506d50';const gr=ctx.createLinearGradient(0,0,0,H);gr.addColorStop(0,top);gr.addColorStop(1,bot);ctx.fillStyle=gr;ctx.fillRect(0,0,W,H);for(let i=0;i<130;i++){const wx=(i*127)%1760-880,wy=(i*83)%1320-650,x=sx(wx),y=sy(wy);if(x<0||x>W||y<0||y>H)continue;rect(x,y,2+(i%2),1,i%3?'#98a16822':'#d1ac641d')}const B=palisadeBounds();if(state.palisade.built){ctx.fillStyle='rgba(133,103,64,.24)';ctx.fillRect(sx(B.l+8),sy(B.t+8),B.r-B.l-16,B.b-B.t-16)}const cx=sx(0),cy=sy(0);rect(cx-8,cy-205,16,295,'rgba(174,142,84,.17)');rect(cx-220,cy+10,440,14,'rgba(174,142,84,.16)');shadow(cx,cy+12,28,5,.35);rect(cx-2,cy-16,4,28,'#6d4b31');poly([[cx-1,cy-16],[cx+18,cy-10],[cx-1,cy-4]],'#b65f47')}
function drawTree(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+22,32,6,.5);rect(x-5,y-5,10,29,'#61412c');rect(x-2,y-4,3,25,'#9c6b40');poly([[x-22,y-22],[x-14,y-37],[x-2,y-44],[x+13,y-37],[x+22,y-21],[x+14,y-10],[x-15,y-11]],'#183b2d');poly([[x-16,y-31],[x-8,y-45],[x+6,y-50],[x+17,y-37],[x+10,y-24],[x-10,y-22]],'#28523b');rect(x-9,y-37,7,7,'#416b49');rect(x+6,y-31,8,6,'#355f43')}
function drawRock(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+12,28,5,.44);poly([[x-14,y+7],[x-11,y-6],[x-5,y-13],[x+8,y-11],[x+14,y+1],[x+9,y+10],[x-8,y+11]],'#59615e');poly([[x-8,y-4],[x-2,y-10],[x+6,y-8],[x+10,y-2],[x+3,y+1]],'#858878');rect(x-7,y+3,6,3,'#aaa792')}
function drawFood(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+10,24,4,.32);poly([[x-12,y+7],[x-9,y-4],[x-2,y-9],[x+7,y-6],[x+12,y+5],[x+8,y+11],[x-8,y+11]],'#2b4933');rect(x-8,y-5,16,7,'#4d714d');for(const d of[-6,0,6])rect(x+d-1,y+1,3,3,'#c66359')}
function drawCharacterBase(x,y,v,dir,walk,tool){const bob=Math.sin(walk)*1.15,step=Math.sin(walk)*2;shadow(x,y+17,20,5,.5);rect(x-6,y+5-bob-step*.15,4,10,'#303638');rect(x+2,y+5+bob+step*.15,4,10,'#303638');rect(x-8,y-12+bob,16,18,v.cloth);rect(x-8,y-4+bob,16,3,v.accent);rect(x-10,y-9+bob,3,8,v.skin);rect(x+7,y-9+bob,3,8,v.skin);rect(x-6,y-22+bob,12,10,v.skin);rect(x-7,y-27+bob,14,7,v.hair);if(dir==='down'){rect(x-3,y-18+bob,2,2,'#241b18');rect(x+2,y-18+bob,2,2,'#241b18')}else if(dir==='left')rect(x-4,y-18+bob,2,2,'#241b18');else if(dir==='right')rect(x+3,y-18+bob,2,2,'#241b18');rect(x-1,y-14+bob,3,1,'#925f49');if(tool==='axe'){ctx.strokeStyle='#795534';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+6,y-7);ctx.lineTo(x+13,y+4);ctx.stroke();rect(x+11,y,6,4,'#aab0ad')}if(tool==='pick'){ctx.strokeStyle='#795534';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+6,y-7);ctx.lineTo(x+13,y+5);ctx.stroke();rect(x+9,y-1,8,2,'#aab0ad')}if(tool==='spear'){ctx.strokeStyle='#9f875f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+8,y-14);ctx.lineTo(x+8,y+10);ctx.stroke();poly([[x+8,y-18],[x+5,y-12],[x+11,y-12]],'#c8c5b8')}}
const PLAYER_VIS={skin:'#d8aa7e',hair:'#483326',cloth:'#b85a40',accent:'#d18a54'};
function drawPlayer(){const p=state.player,x=sx(p.x),y=sy(p.y);drawCharacterBase(x,y,PLAYER_VIS,p.dir,p.walk,'axe');if(p.swing>0){const a=(1-p.swing)*Math.PI*.95-.35,ax=x+Math.cos(a)*21,ay=y-7+Math.sin(a)*19;ctx.strokeStyle='#7b5634';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+7,y-7);ctx.lineTo(ax,ay);ctx.stroke();rect(ax-2,ay-5,9,7,'#afb5b2')}}
function drawWorker(w,i){ensureWorker(w,i);const x=sx(w.x),y=sy(w.y),tool=w.role==='wood'?'axe':w.role==='stone'?'pick':w.role==='guard'?'spear':null;drawCharacterBase(x,y,w.visual,'down',w.anim||0,tool)}
function drawBuilding(b){const x=sx(b.x),y=sy(b.y),age=clamp((performance.now()-b.builtAt)/720,0,1),rise=(1-age)*18,L=b.level||1;ctx.save();ctx.translate(0,rise);ctx.globalAlpha=.28+.72*age;shadow(x,y+18,b.type==='lantern'?22:70+(L-1)*5,7,.5);if(b.type==='hut'){const w=50+L*6,h=26+L*5;rect(x-w/2,y-h+18,w,h,'#7a5a42');poly([[x-w*.62,y-h+18],[x,y-h-9],[x+w*.62,y-h+18]],L>=4?'#73513f':'#9a6542');rect(x-6,y+1,12,20,'#2f251f');for(let i=0;i<Math.min(4,L);i++)rect(x-w/2+9+i*14,y-h+24,7,7,'#e4b96a');if(L>=3)rect(x+w/2-13,y-h-2,6,17,'#60412d')}else if(b.type==='lumber'){rect(x-31,y-6,62,26,'#725039');poly([[x-35,y-6],[x-19,y-25],[x+23,y-25],[x+35,y-6]],'#9b6b43');for(let i=-22;i<=22;i+=14)rect(x+i,y+17,8,14,'#4e3524');if(L>=2)rect(x+20,y-22,8,17,'#765137');if(L>=4)rect(x-24,y-18,9,13,'#a77b47')}else if(b.type==='quarry'){rect(x-31,y+1,62,18,'#505958');poly([[x-29,y+2],[x-19,y-15],[x+19,y-19],[x+31,y+1]],'#6e7770');rect(x-10,y+6,20,5,'#363d3c');for(let i=1;i<L;i++)rect(x-24+i*10,y-18-i*2,7,5,'#939489')}else if(b.type==='lantern'){rect(x-3,y-28,6,42,'#765137');rect(x-13,y-34,26,9,'#272e31');rect(x-8,y-32,16,5,'#f0b85c');glow(x,y-29,72+L*18,'255,178,78',.23)}else if(b.type==='warehouse'){const ww=58+L*5;rect(x-ww/2,y-9,ww,31,'#665044');poly([[x-ww/2-5,y-9],[x,y-31-L*2],[x+ww/2+5,y-9]],'#6f4b39');rect(x-10,y+2,20,20,'#2f2924');for(let i=0;i<Math.min(5,L+1);i++)rect(x-ww/2+7+i*11,y+10-(i%2)*5,9,8,'#9b7144')}else if(b.type==='watchtower'){const hh=48+L*9;rect(x-4,y-hh+18,8,hh,'#6e4b31');rect(x-18,y-hh+8,36,12,'#6a5440');poly([[x-21,y-hh+8],[x,y-hh-6],[x+21,y-hh+8]],'#8d5d3e');rect(x-15,y-hh+12,30,3,'#b48a54');if(L>=3)rect(x-2,y-hh-13,4,12,'#a47849')}else if(b.type==='barracks'){const ww=66+L*5;rect(x-ww/2,y-10,ww,32,'#714d40');poly([[x-ww/2-5,y-10],[x,y-34],[x+ww/2+5,y-10]],'#814838');rect(x-7,y+1,14,21,'#2e2522');rect(x-ww/2+8,y-2,8,9,'#d49b59');rect(x+ww/2-16,y-2,8,9,'#d49b59');rect(x+ww/2-9,y-31,3,26,'#6a4630');poly([[x+ww/2-6,y-30],[x+ww/2+12,y-24],[x+ww/2-6,y-18]],'#b04d3d')}else if(b.type==='guildhall'){const ww=78+L*8,hh=42+L*6;rect(x-ww/2,y-hh+20,ww,hh,'#7b5c43');poly([[x-ww/2-6,y-hh+20],[x,y-hh-12-L*2],[x+ww/2+6,y-hh+20]],'#704538');rect(x-8,y+1,16,22,'#2c2421');for(let i=-1;i<=1;i+=2)rect(x+i*(ww/2-18)-4,y-hh+28,9,10,'#ecc46f');rect(x-3,y-hh-21-L*2,6,20+L*2,'#6c4932');poly([[x,y-hh-22-L*2],[x+18,y-hh-16-L*2],[x,y-hh-10-L*2]],'#c39448');if(L>=3){rect(x-ww/2+8,y-hh+6,10,16,'#6f4f3c');rect(x+ww/2-18,y-hh+6,10,16,'#6f4f3c')}}ctx.restore()}
function drawPalisade(){if(!state.palisade.built)return;const B=palisadeBounds(),L=state.palisade.level,age=clamp((performance.now()-state.palisade.builtAt)/900,0,1),segs=[];for(let x=B.l;x<=B.r;x+=14){if(x>-B.gap/2&&x<B.gap/2)continue;segs.push([x,B.t]);segs.push([x,B.b])}for(let y=B.t+14;y<B.b;y+=14){segs.push([B.l,y]);segs.push([B.r,y])}const visible=Math.floor(segs.length*age);for(let i=0;i<visible;i++){const[wx,wy]=segs[i],x=sx(wx),y=sy(wy);shadow(x,y+8,13,4,.38);if(L>=4)rect(x-6,y-12,12,27,'#74766e');else{rect(x-4,y-11,8,24,'#6d482e');rect(x-1,y-11,2,21,'#a16e42');if(L>=2)rect(x-7,y-2,14,4,'#8d5e39');poly([[x-4,y-11],[x,y-17],[x+4,y-11]],'#8d5e39')}if(L>=6)rect(x-6,y-15,12,5,'#9c9a8e')}const gy=sy(B.b),gx=sx(0);rect(gx-B.gap/2-6,gy-24,10,37,L>=4?'#77796f':'#5f3f29');rect(gx+B.gap/2-4,gy-24,10,37,L>=4?'#77796f':'#5f3f29');if(L>=2)rect(gx-B.gap/2+3,gy-16,B.gap-6,4,L>=4?'#969486':'#8d5e39')}
function enemyVisual(type){return type==='runner'?{body:'#795d64',skin:'#aaa38b',eye:'#ff9b6d',scale:.88}:type==='brute'?{body:'#4e6655',skin:'#8d947a',eye:'#ff654f',scale:1.45}:type==='spitter'?{body:'#506f55',skin:'#93aa79',eye:'#d7ff72',scale:1.05}:{body:'#64795e',skin:'#a6a289',eye:'#d35d4c',scale:1}}
function drawZombie(z){const x=sx(z.x),y=sy(z.y),v=enemyVisual(z.type),s=v.scale||1,bob=Math.sin(z.anim||0)*1.5,step=Math.sin((z.anim||0)*1.25)*4,death=z.dead?clamp(z.death/.7,0,1):1;ctx.save();ctx.globalAlpha=death;if(z.dead){ctx.translate(x,y+14);ctx.rotate((1-death)*.55);ctx.translate(-x,-y-14)}shadow(x,y+15,18*s,5,.48*death);rect(x-7*s,y-13*s+bob,14*s,19*s,z.hit>0?'#d8cba0':v.body);rect(x-5*s,y-22*s+bob,10*s,10*s,v.skin);rect(x-4*s,y-19*s+bob,2*s,2*s,v.eye);rect(x+2*s,y-19*s+bob,2*s,2*s,v.eye);rect(x-7*s,y-7*s+bob+step*.18,3*s,10*s,v.body);rect(x+4*s,y-7*s+bob-step*.18,3*s,10*s,v.body);rect(x-6*s,y+5*s+bob+step*.22,4*s,10*s,'#413534');rect(x+2*s,y+5*s+bob-step*.22,4*s,10*s,'#413534');if(z.type==='brute'){rect(x-11*s,y-10*s,5*s,12*s,'#4a5a4d');rect(x+6*s,y-10*s,5*s,12*s,'#4a5a4d')}if(z.type==='spitter')rect(x-2*s,y-13*s,4*s,3*s,'#b6dc69');if(z.hit>0){ctx.strokeStyle='#f0b89a';ctx.lineWidth=1;ctx.strokeRect(x-8*s,y-24*s,16*s,38*s)}ctx.restore();if(!z.dead&&(z.hit>0||Math.hypot(state.player.x-z.x,state.player.y-z.y)<85)){const ww=22*s,ratio=clamp(z.hp/z.maxHp,0,1);rect(x-ww/2,y-31*s,ww,3,'#231716');rect(x-ww/2,y-31*s,ww*ratio,3,ratio>.5?'#8cb06d':ratio>.25?'#d0a05f':'#c85b4d')}}
function fxWorld(wx,wy,color,count=8,power=1){for(let i=0;i<count;i++)worldFx.push({x:wx,y:wy,vx:rnd(-50,50)*power,vy:rnd(-70,-18)*power,life:rnd(.32,.62),size:rnd(2,4),color})}function floatWorld(wx,wy,text,color='#f0cf87',life=.85){floats.push({x:wx,y:wy,text,color,life})}function ringWorld(wx,wy,color='#f0c878'){rings.push({x:wx,y:wy,r:5,life:.55,color})}function slashWorld(wx,wy,angle,color='#f4d6aa'){slashes.push({x:wx,y:wy,angle,life:.24,color})}
function hudMote(wx,wy,color){const target=$('resources').getBoundingClientRect();screenFx.push({x:sx(wx),y:sy(wy),tx:target.left+target.width*.45,ty:target.top+target.height*.5,life:.55,color})}
function drawFx(dt){for(let i=worldFx.length-1;i>=0;i--){const p=worldFx[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt;p.life-=dt;if(p.life<=0){worldFx.splice(i,1);continue}ctx.globalAlpha=clamp(p.life*2,0,1);rect(sx(p.x),sy(p.y),p.size,p.size,p.color);ctx.globalAlpha=1}for(let i=floats.length-1;i>=0;i--){const f=floats[i];f.y-=21*dt;f.life-=dt;if(f.life<=0){floats.splice(i,1);continue}ctx.globalAlpha=clamp(f.life*1.5,0,1);ctx.font='900 9px ui-monospace,monospace';ctx.textAlign='center';ctx.fillStyle='#000b';ctx.fillText(f.text,sx(f.x)+1,sy(f.y)+1);ctx.fillStyle=f.color;ctx.fillText(f.text,sx(f.x),sy(f.y));ctx.globalAlpha=1}for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.r+=72*dt;r.life-=dt;if(r.life<=0){rings.splice(i,1);continue}ctx.globalAlpha=r.life;ctx.strokeStyle=r.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(sx(r.x),sy(r.y),r.r,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}for(let i=slashes.length-1;i>=0;i--){const s=slashes[i];s.life-=dt;if(s.life<=0){slashes.splice(i,1);continue}ctx.save();ctx.globalAlpha=clamp(s.life*4,0,1);ctx.translate(sx(s.x),sy(s.y));ctx.rotate(s.angle);ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,18,-.65,.65);ctx.stroke();ctx.restore()}for(let i=screenFx.length-1;i>=0;i--){const p=screenFx[i],t=1-p.life/.55;p.x=lerp(p.x,p.tx,.08+.12*t);p.y=lerp(p.y,p.ty,.08+.12*t);p.life-=dt;if(p.life<=0){screenFx.splice(i,1);continue}ctx.globalAlpha=clamp(p.life*2,0,1);rect(p.x,p.y,4,4,p.color);ctx.globalAlpha=1}for(const p of projectiles){ctx.save();ctx.translate(sx(p.x),sy(p.y));ctx.rotate(Math.atan2(p.vy,p.vx));rect(-6,-1,12,2,p.kind==='spit'?'#9ccf63':'#c7b487');ctx.restore()}}
function makeNode(id,x,y,type,starter=false){const hp=type==='food'?2:type==='rock'?6:5;return{id,x,y,type,hp,maxHp:hp,alive:true,respawnAt:0,seed:Math.random(),starter}}
function outsidePosition(pad=80){const B=palisadeBounds(),a=Math.random()*Math.PI*2,rx=Math.max(Math.abs(B.l),Math.abs(B.r))+pad+rnd(30,300),ry=Math.max(Math.abs(B.t),Math.abs(B.b))+pad+rnd(20,230);return{x:clamp(Math.cos(a)*rx,WORLD.minX+35,WORLD.maxX-35),y:clamp(Math.sin(a)*ry,WORLD.minY+35,WORLD.maxY-35)}}
function seedNodes(){if(state.nodes.length)return;let id=0;const starter=[[-46,136,'tree'],[55,140,'tree'],[-108,94,'tree'],[118,96,'tree'],[-126,52,'rock'],[130,56,'rock'],[-22,190,'food'],[75,198,'food']];state.nodes=starter.map(v=>makeNode('n'+id++,...v,true));for(let i=0;i<30;i++){const p=outsidePosition(88);state.nodes.push(makeNode('n'+id++,p.x,p.y,'tree'))}for(let i=0;i<20;i++){const p=outsidePosition(95);state.nodes.push(makeNode('n'+id++,p.x,p.y,'rock'))}for(let i=0;i<12;i++){const p=outsidePosition(80);state.nodes.push(makeNode('n'+id++,p.x,p.y,'food'))}}
function relocateOutside(n){const p=outsidePosition(80);n.x=p.x;n.y=p.y;n.starter=false;n.hp=n.maxHp;n.alive=true;n.respawnAt=0}
function clearInsideResources(){if(!state.palisade.built)return;for(const n of state.nodes)if(n.alive&&insideSettlement(n.x,n.y))relocateOutside(n)}
function respawnNodes(){const now=Date.now();for(const n of state.nodes)if(!n.alive&&n.respawnAt&&now>=n.respawnAt)relocateOutside(n)}
function nearestPlayerNode(){let best=null,d=50;for(const n of state.nodes){if(!n.alive)continue;const q=Math.hypot(state.player.x-n.x,state.player.y-n.y);if(q<d){d=q;best=n}}return best}
function efficiency(type){if(type==='tree')return 1+(building('lumber')?.level||0)*.18;if(type==='rock')return 1+(building('quarry')?.level||0)*.18;return 1}
function hitNode(n,source='player'){if(!n||!n.alive)return;let gain=0,color='#d0af6a',sfx='pickup';if(n.type==='tree'){gain=(source==='worker'?.22:1.35)*efficiency('tree')*moraleFactor();resourceGain('wood',gain,n.x,n.y-18);color='#b77c47';sfx='chop'}else if(n.type==='rock'){gain=(source==='worker'?.16:.85)*efficiency('rock')*moraleFactor();resourceGain('stone',gain,n.x,n.y-15);color='#a7a79b';sfx='mine'}else{gain=(source==='worker'?.28:1.4)*moraleFactor();resourceGain('food',gain,n.x,n.y-12);color='#c46659';sfx='pickup'}fxWorld(n.x,n.y,color,source==='player'?9:4,.9);if(source==='player')hudMote(n.x,n.y,color);FrontierAudio.sfx(sfx);n.hp--;if(n.hp<=0){n.alive=false;n.respawnAt=Date.now()+(n.type==='food'?14000:19000);fxWorld(n.x,n.y,color,14,1.2);ringWorld(n.x,n.y,'#d0af6a');if(Math.random()<.018){state.hourglass++;floatWorld(n.x,n.y-24,'HOURGLASS +1','#d7b5ff');FrontierAudio.sfx('rare')}}updateHud()}
function playerAutoGather(dt){respawnNodes();if(input.mag>.18){autoTarget=null;playerWork=0;return}if(!autoTarget||!autoTarget.alive||Math.hypot(state.player.x-autoTarget.x,state.player.y-autoTarget.y)>52)autoTarget=nearestPlayerNode();if(!autoTarget){playerWork=0;return}const p=state.player;p.dir=Math.abs(autoTarget.x-p.x)>Math.abs(autoTarget.y-p.y)?(autoTarget.x>p.x?'right':'left'):(autoTarget.y>p.y?'down':'up');playerWork+=dt*state.boost;if(playerWork>=.48){playerWork=0;p.swing=1;hitNode(autoTarget,'player');if(!autoTarget.alive)autoTarget=null}}
function recipeCost(type,nextLevel=1){const base=BASE_RECIPES[type];if(!base)return null;if(type==='hut'){const count=buildings('hut').length,f=1+count*.42;return{wood:Math.ceil(base.wood*f),stone:Math.ceil(base.stone*f)}}if(type==='lantern'){const count=buildings('lantern').length,f=1+count*.18;return{wood:Math.ceil(base.wood*f),stone:Math.ceil(base.stone*f)}}const f=1+Math.max(0,nextLevel-1)*.78;return{wood:Math.ceil(base.wood*f),stone:Math.ceil(base.stone*f)}}
function unlockReason(type){const wall=state.palisade.level||0,g=guildLevel(),huts=buildings('hut').length;if(type==='warehouse'||type==='lumber'||type==='quarry'||type==='lantern')return wall>=1?'':'城壁 Lv.1 が必要';if(type==='watchtower')return wall>=2?'':'城壁 Lv.2 が必要';if(type==='guildhall')return wall>=2&&huts>=3?'':`城壁Lv.2 + 小屋3軒 (${huts}/3)`;if(type==='barracks')return g>=1?'':'ギルド本部が必要';return ''}
function buildSlots(){const B=palisadeBounds(),margin=44,pts=[];for(let ring=0;ring<settlementLevel()+2;ring++){const rx=65+ring*62,ry=45+ring*42;for(let k=0;k<8;k++){const a=k/8*Math.PI*2+(ring%2)*.18;pts.push([Math.round(Math.cos(a)*rx),Math.round(Math.sin(a)*ry+10)])}}pts.push([0,-30],[0,62],[-65,18],[65,18]);return pts.filter(p=>p[0]>B.l+margin&&p[0]<B.r-margin&&p[1]>B.t+margin&&p[1]<B.b-margin)}
function availableBuildSlot(){const used=state.buildings.filter(b=>Number.isInteger(b.slot)).map(b=>`${b.slot}`),slots=buildSlots();return slots.map((p,i)=>({p,i,d:Math.hypot(state.player.x-p[0],state.player.y-p[1])})).filter(v=>!used.includes(`${v.i}`)).sort((a,b)=>a.d-b.d)[0]||null}
function wallAllowedMax(){return rankInfo().wall}
function canBuild(type){if(type==='palisade'){const next=state.palisade.built?state.palisade.level+1:1;if(next>6||next>wallAllowedMax())return false;const c=wallStats(next);return state.wood>=c.wood&&state.stone>=c.stone}const reason=unlockReason(type);if(reason)return false;const base=BASE_RECIPES[type];if(!base)return false;const existing=building(type);if(!base.repeat&&existing&&(existing.level||1)>=base.max)return false;const next=existing&&!base.repeat?(existing.level||1)+1:1,c=recipeCost(type,next);if(state.wood<c.wood||state.stone<c.stone)return false;return !!availableBuildSlot()||!!existing&&!base.repeat}
function buildLabel(type){const btn=document.querySelector(`[data-build="${type}"]`);if(!btn)return;const b=btn.querySelector('b'),s=btn.querySelector('small'),base=BASE_RECIPES[type],existing=building(type),reason=unlockReason(type);btn.classList.remove('locked','maxed');if(type==='palisade'){const next=state.palisade.built?state.palisade.level+1:1;if(next>6){b.textContent='城壁 MAX Lv.6';s.innerHTML='最大拡張済み';btn.classList.add('maxed');return}if(next>wallAllowedMax()){b.textContent=`城壁 Lv.${next} LOCK`;s.innerHTML=`GUILD RANK ${RANKS.find(r=>r.wall>=next)?.name||'S'} が必要`;btn.classList.add('locked');return}const c=wallStats(next);b.textContent=state.palisade.built?`城壁拡張 Lv.${state.palisade.level} → ${next}`:'集落防壁';s.innerHTML=`W${c.wood} · S${c.stone}<br>敷地・HP・建築枠UP`;return}if(reason){b.textContent=base.name+' LOCK';s.innerHTML=reason;btn.classList.add('locked');return}if(existing&&!base.repeat){const L=existing.level||1;if(L>=base.max){b.textContent=`${base.name} MAX Lv.${L}`;s.innerHTML='最大強化済み';btn.classList.add('maxed');return}const c=recipeCost(type,L+1);b.textContent=`${base.name} Lv.${L} → ${L+1}`;s.innerHTML=`W${c.wood} · S${c.stone}<br>${type==='guildhall'?'RANK / 上限解放':type==='warehouse'?'資源上限UP':type==='watchtower'?'射程 / 火力UP':type==='barracks'?'衛兵火力UP':'効率UP'}`;return}const c=recipeCost(type,1);b.textContent=base.name;s.innerHTML=`W${c.wood} · S${c.stone}<br>${type==='hut'?'人口枠UP':type==='lantern'?'何本でも建設可':type==='warehouse'?'資源上限UP':type==='watchtower'?'敵を自動射撃':type==='barracks'?'衛兵解禁 / 強化':type==='guildhall'?'RANK / 上限解放':type==='lumber'?'木こり効率UP':'採石効率UP'}`}
function updateBuildUI(){Object.keys(BASE_RECIPES).forEach(buildLabel);const h=buildings('hut').filter(b=>(b.level||1)<5).sort((a,b)=>(a.level||1)-(b.level||1))[0],u=$('upgrade-hut'),d=$('hut-upgrade-desc');if(u&&d){u.disabled=!h;if(!h)d.textContent=buildings('hut').length?'全小屋 MAX Lv.5':'小屋を建てると解禁';else{const next=(h.level||1)+1,c=hutUpgradeCost(next);d.textContent=`Lv.${h.level||1} → ${next} · W${c.wood} / S${c.stone} · 人口枠UP`}}}
function build(type){FrontierAudio.enable();if(type==='palisade'){const next=state.palisade.built?state.palisade.level+1:1;if(next>wallAllowedMax()){toast(`GUILD RANK ${rankInfo().name} では城壁Lv.${next}は未解放`);return}if(next>6){toast('城壁 MAX Lv.6');return}const c=wallStats(next);if(state.wood<c.wood||state.stone<c.stone){toast(`城壁 Lv.${next} · W${c.wood} / S${c.stone} 必要`);return}state.wood-=c.wood;state.stone-=c.stone;state.palisade={built:true,level:next,maxHp:c.maxHp,hp:c.maxHp,builtAt:performance.now()};clearInsideResources();const B=palisadeBounds();for(let i=0;i<28;i++){const side=i%4,wx=side<2?rnd(B.l,B.r):(side===2?B.l:B.r),wy=side<2?(side===0?B.t:B.b):rnd(B.t,B.b);fxWorld(wx,wy,'#c69558',7,1.2)}ringWorld(0,0,'#f2cc82');FrontierAudio.sfx('build');toast(`城壁 Lv.${next} · 領地拡張`);closeSheet();save();return}
const base=BASE_RECIPES[type];if(!base)return;const reason=unlockReason(type);if(reason){toast(reason);return}let existing=building(type);if(existing&&!base.repeat){if((existing.level||1)>=base.max){toast(`${base.name} MAX Lv.${base.max}`);return}const next=(existing.level||1)+1,c=recipeCost(type,next);if(state.wood<c.wood||state.stone<c.stone){toast(`${base.name} Lv.${next} · W${c.wood} / S${c.stone} 必要`);return}state.wood-=c.wood;state.stone-=c.stone;existing.level=next;existing.maxHp=buildingHp(type,next);existing.hp=existing.maxHp;existing.builtAt=performance.now();fxWorld(existing.x,existing.y,'#e2bd79',28,1.4);ringWorld(existing.x,existing.y,'#ffd990');FrontierAudio.sfx('build');toast(`${base.name} LEVEL UP · Lv.${next}${type==='guildhall'?' · RANK '+rankInfo().name:''}`);normalizeResources();save();return}
const c=recipeCost(type,1),slot=availableBuildSlot();if(!slot){toast('建築枠不足 · 城壁を拡張しよう');return}if(state.wood<c.wood||state.stone<c.stone){toast(`${base.name} · W${c.wood} / S${c.stone} 必要`);return}state.wood-=c.wood;state.stone-=c.stone;const b={id:'b'+Date.now()+Math.random(),type,slot:slot.i,x:slot.p[0],y:slot.p[1],level:1,builtAt:performance.now(),maxHp:buildingHp(type,1),hp:buildingHp(type,1),ruined:false,towerCd:0};state.buildings.push(b);fxWorld(b.x,b.y,'#d0aa67',24,1.3);ringWorld(b.x,b.y,'#f0c878');FrontierAudio.sfx('build');toast(`${base.name} 完成`);normalizeResources();closeSheet();save()}
function buildingHp(type,L){const base={hut:150,lumber:210,quarry:240,lantern:90,warehouse:260,watchtower:220,barracks:320,guildhall:420}[type]||180;return Math.round(base*(1+(L-1)*.45))}
function hutUpgradeCost(level){return{wood:Math.ceil(18*Math.pow(1.72,level-1)),stone:Math.ceil(7*Math.pow(1.68,level-1))}}
function upgradeHut(){const h=buildings('hut').filter(b=>(b.level||1)<5).sort((a,b)=>(a.level||1)-(b.level||1))[0];if(!h){toast('強化できる小屋がない');return}const next=(h.level||1)+1,c=hutUpgradeCost(next);if(state.wood<c.wood||state.stone<c.stone){toast(`小屋 Lv.${next} · W${c.wood} / S${c.stone} 必要`);return}state.wood-=c.wood;state.stone-=c.stone;h.level=next;h.maxHp=buildingHp('hut',next);h.hp=h.maxHp;h.builtAt=performance.now();fxWorld(h.x,h.y,'#e2bd79',28,1.4);ringWorld(h.x,h.y,'#ffd990');FrontierAudio.sfx('build');toast(`小屋 Lv.${next} · 人口枠 ${maxWorkers()}`);save()}
function guardMultiplier(){return 1+(building('barracks')?.level||0)*.22}
function hire(role){if(role==='guard'&&!building('barracks')){toast('衛兵は兵舎を建てると解禁');return}const cap=maxWorkers();if(housingCap()<=0){toast('まず小屋を建てよう');return}if(state.workers.length>=cap){toast(cap>=rankInfo().pop?'GUILD RANKを上げて人口上限を解放':'小屋を建設/強化しよう');return}const cost=role==='guard'?12:role==='food'?7:8;if(state.food<cost){toast('FOOD不足 · '+cost);return}state.food-=cost;const hut=buildings('hut')[0]||{x:0,y:0},i=state.workers.length,d=identity(i);state.workers.push({id:'w'+Date.now()+Math.random(),role,x:hut.x+rnd(-12,12),y:hut.y+22+rnd(-5,8),targetId:null,work:0,anim:0,swing:0,state:'idle',hp:100,...d});FrontierAudio.sfx('hire');toast(`${d.name} · ${ROLE_NAMES[role]} が加入`);save()}
function nodeById(id){return state.nodes.find(n=>n.id===id)}function chooseWorkerTarget(w,claimed){const type=w.role==='wood'?'tree':w.role==='stone'?'rock':w.role==='food'?'food':null;if(!type)return null;let best=null,d=99999;for(const n of state.nodes){if(!n.alive||n.type!==type||claimed.has(n.id))continue;const q=Math.hypot(w.x-n.x,w.y-n.y);if(q<d){d=q;best=n}}w.targetId=best?.id||null;if(best)claimed.add(best.id);return best}
function moveStraight(o,tx,ty,speed,dt){const dx=tx-o.x,dy=ty-o.y,d=Math.hypot(dx,dy)||1;if(d<2)return true;o.x+=dx/d*speed*dt;o.y+=dy/d*speed*dt;return d<speed*dt+2}
function gateRouteTarget(o,tx,ty){if(!state.palisade.built||state.palisade.hp<=0)return{x:tx,y:ty};const B=palisadeBounds(),insideA=insideRect(o.x,o.y,B),insideT=insideRect(tx,ty,B);if(insideA===insideT)return{x:tx,y:ty};const outside={x:0,y:B.b+26},inside={x:0,y:B.b-22};if(insideA){if(Math.hypot(o.x-inside.x,o.y-inside.y)>10)return inside;return outside}else{if(Math.hypot(o.x-outside.x,o.y-outside.y)>10)return outside;return inside}}
function updateWorkers(dt){const claimed=new Set();for(const w of state.workers){const n=nodeById(w.targetId);if(n?.alive)claimed.add(n.id)}state.workers.forEach((w,i)=>{ensureWorker(w,i);w.swing=Math.max(0,(w.swing||0)-dt*3.4);w.anim=(w.anim||0)+dt*7;if(w.role==='guard'){const z=nearestLivingEnemy(w.x,w.y,220);if(state.phase==='night'&&z){w.state='moving';const B=palisadeBounds();if(state.palisade.built&&state.palisade.hp>0&&!insideSettlement(z.x,z.y)){const wp={x:clamp(z.x,B.l+18,B.r-18),y:clamp(z.y,B.t+18,B.b-18)};moveStraight(w,wp.x,wp.y,46,dt);if(distanceToWall(z)<48){w.work=(w.work||0)+dt;if(w.work>.72){w.work=0;w.swing=1;slashWorld(z.x,z.y,Math.atan2(z.y-w.y,z.x-w.x));damageZombie(z,11*guardMultiplier(),w.x,w.y)}}}else{const rt=gateRouteTarget(w,z.x,z.y);moveStraight(w,rt.x,rt.y,46,dt);if(Math.hypot(w.x-z.x,w.y-z.y)<30){w.work=(w.work||0)+dt;if(w.work>.72){w.work=0;w.swing=1;damageZombie(z,13*guardMultiplier(),w.x,w.y)}}}}else{w.state='idle';const a=(i*1.9+performance.now()/3600)%6.28,B=palisadeBounds();w.x=lerp(w.x,clamp(Math.cos(a)*60,B.l+22,B.r-22),.01);w.y=lerp(w.y,clamp(Math.sin(a)*40+10,B.t+22,B.b-22),.01)}return}let n=nodeById(w.targetId);if(!n||!n.alive)n=chooseWorkerTarget(w,claimed);if(!n){w.state='idle';return}const d=Math.hypot(w.x-n.x,w.y-n.y);if(d>31){w.state='moving';const rt=gateRouteTarget(w,n.x,n.y);moveStraight(w,rt.x,rt.y,32,dt);return}w.state='working';w.work=(w.work||0)+dt*(w.trait==='集中力'?1.05:1)*moraleFactor();if(w.work>=1.35){w.work=0;w.swing=1;hitNode(n,'worker');if(!n.alive)w.targetId=null}});renderWorkers()}
function wallCollision(x,y,r=9){if(!state.palisade.built||state.palisade.hp<=0)return false;const B=palisadeBounds(),th=9;if(x+r>B.l-th&&x-r<B.r+th){if(y+r>B.t-th&&y-r<B.t+th)return true;if(y+r>B.b-th&&y-r<B.b+th&&!(x>-B.gap/2+r&&x<B.gap/2-r))return true}if(y+r>B.t-th&&y-r<B.b+th){if(x+r>B.l-th&&x-r<B.l+th)return true;if(x+r>B.r-th&&x-r<B.r+th)return true}return false}
function movement(dt){const p=state.player,tx=input.x*140,ty=input.y*140,a=input.mag>.04?1-Math.pow(.00002,dt):1-Math.pow(.00025,dt);p.vx=lerp(p.vx,tx,a);p.vy=lerp(p.vy,ty,a);if(Math.abs(p.vx)<.35)p.vx=0;if(Math.abs(p.vy)<.35)p.vy=0;let nx=clamp(p.x+p.vx*dt*state.boost,WORLD.minX,WORLD.maxX),ny=p.y;if(!wallCollision(nx,ny))p.x=nx;else p.vx=0;nx=p.x;ny=clamp(p.y+p.vy*dt*state.boost,WORLD.minY,WORLD.maxY);if(!wallCollision(nx,ny))p.y=ny;else p.vy=0;if(Math.hypot(p.vx,p.vy)>3){p.walk+=dt*10;const ax=Math.abs(p.vx),ay=Math.abs(p.vy);p.dir=ax>ay?(p.vx>0?'right':'left'):(p.vy>0?'down':'up')}p.swing=Math.max(0,p.swing-dt*3.8);cam.x=lerp(cam.x,p.x,1-Math.pow(.0003,dt));cam.y=lerp(cam.y,p.y-44,1-Math.pow(.0003,dt))}
function enemyType(){const r=Math.random();if(state.day>=7&&r<.14)return'spitter';if(state.day>=5&&r<.32)return'brute';if(state.day>=3&&r<.58)return'runner';return'walker'}
function makeEnemy(type,x,y,wave){const base={walker:{hp:42,speed:22,damage:8},runner:{hp:30,speed:38,damage:7},brute:{hp:125,speed:14,damage:19},spitter:{hp:58,speed:17,damage:10}}[type],scale=1+(state.day-1)*.11+wave*.08;return{id:'z'+Date.now()+Math.random(),type,x,y,hp:Math.round(base.hp*scale),maxHp:Math.round(base.hp*scale),speed:base.speed*(1+Math.min(.25,state.day*.015)),damage:base.damage*(1+state.day*.08),hit:0,dead:false,death:0,cool:rnd(0,.4),anim:rnd(0,6.2),wave,knockX:0,knockY:0}}
function spawnWave(index){const base=Math.min(22,5+Math.floor(state.day*1.7)+index*3),B=palisadeBounds();for(let i=0;i<base;i++){const side=i%4,x=side===0?B.l-150:side===1?B.r+150:rnd(B.l-160,B.r+160),y=side===2?B.t-135:side===3?B.b+145:rnd(B.t-125,B.b+125);state.zombies.push(makeEnemy(enemyType(),x,y,index))}toast(`WAVE ${index+1} · ${base}体`);FrontierAudio.setMood('night');FrontierAudio.sfx('warning')}
function distanceToWall(z){const B=palisadeBounds();return Math.min(Math.abs(z.x-B.l),Math.abs(z.x-B.r),Math.abs(z.y-B.t),Math.abs(z.y-B.b))}
function nearestWallPoint(z){const B=palisadeBounds(),x=clamp(z.x,B.l,B.r),y=clamp(z.y,B.t,B.b),choices=[{x,y:B.t},{x,y:B.b},{x:B.l,y},{x:B.r,y}];return choices.sort((a,b)=>Math.hypot(z.x-a.x,z.y-a.y)-Math.hypot(z.x-b.x,z.y-b.y))[0]}
function nearestLivingEnemy(x,y,range=9999){let best=null,d=range;for(const z of state.zombies){if(z.dead)continue;const q=Math.hypot(z.x-x,z.y-y);if(q<d){best=z;d=q}}return best}
function damageZombie(z,amount,sx0=null,sy0=null){if(!z||z.dead)return;z.hp-=amount;z.hit=.14;floatWorld(z.x,z.y-24,`-${Math.round(amount)}`,'#ffb18f',.62);fxWorld(z.x,z.y,'#d6b09a',7,.8);if(sx0!==null){const dx=z.x-sx0,dy=z.y-sy0,d=Math.hypot(dx,dy)||1;z.x+=dx/d*3;z.y+=dy/d*3}FrontierAudio.sfx('hit');if(z.hp<=0)killZombie(z)}
function killZombie(z){if(z.dead)return;z.dead=true;z.death=.7;z.hp=0;fxWorld(z.x,z.y,z.type==='spitter'?'#96b76f':'#788c6b',20,1.3);ringWorld(z.x,z.y,z.type==='brute'?'#d68a67':'#a7b88a');floatWorld(z.x,z.y-18,'DOWN','#e6d3ae',.75);if(Math.random()<.08)state.gem++;FrontierAudio.sfx('rare')}
function fireProjectile(x,y,target,damage,kind='arrow'){const dx=target.x-x,dy=target.y-y,d=Math.hypot(dx,dy)||1,speed=kind==='spit'?115:210;projectiles.push({x,y,vx:dx/d*speed,vy:dy/d*speed,life:2.4,targetId:target.id||null,targetX:target.x,targetY:target.y,damage,kind})}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;if(p.life<=0){projectiles.splice(i,1);continue}if(p.kind==='arrow'){const z=state.zombies.find(z=>z.id===p.targetId&&!z.dead);if(!z){projectiles.splice(i,1);continue}const dx=z.x-p.x,dy=z.y-p.y,d=Math.hypot(dx,dy)||1;p.vx=dx/d*220;p.vy=dy/d*220;p.x+=p.vx*dt;p.y+=p.vy*dt;if(d<10){damageZombie(z,p.damage,p.x,p.y);projectiles.splice(i,1)}}else{p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.hypot(p.x-p.targetX,p.y-p.targetY)<10){if(state.palisade.hp>0){state.palisade.hp=Math.max(0,state.palisade.hp-p.damage);floatWorld(p.targetX,p.targetY-8,`-${Math.round(p.damage)}`,'#9fe36d');fxWorld(p.targetX,p.targetY,'#91c96c',7,.8)}projectiles.splice(i,1)}}}}
function updateWatchtower(dt){const t=building('watchtower');if(!t)return;t.towerCd=(t.towerCd||0)-dt;if(t.towerCd>0)return;const z=nearestLivingEnemy(t.x,t.y,230+(t.level||1)*35);if(!z)return;t.towerCd=Math.max(.48,1.35-(t.level||1)*.13);fireProjectile(t.x,t.y-45,z,12+(t.level||1)*8,'arrow')}
function updateZombies(dt){for(const z of state.zombies){if(z.dead){z.death-=dt;continue}z.anim=(z.anim||0)+dt*z.speed*.22;if(z.hit>0)z.hit-=dt;if(z.cool>0)z.cool-=dt;let target={x:0,y:0,wall:false};if(state.palisade.built&&state.palisade.hp>0){const p=nearestWallPoint(z);target={...p,wall:true}}const dx=target.x-z.x,dy=target.y-z.y,d=Math.hypot(dx,dy)||1;if(z.type==='spitter'&&target.wall&&d<125&&d>58){if(z.cool<=0){z.cool=1.6;fireProjectile(z.x,z.y,target,z.damage,'spit')}continue}if(d>22){z.x+=dx/d*z.speed*dt*state.boost;z.y+=dy/d*z.speed*dt*state.boost}else if(z.cool<=0){z.cool=z.type==='runner'?.65:z.type==='brute'?1.25:1;FrontierAudio.sfx('hit');if(target.wall){const dmg=z.damage*(z.type==='brute'?1.25:1);state.palisade.hp=Math.max(0,state.palisade.hp-dmg);floatWorld(target.x,target.y-8,`-${Math.round(dmg)}`,'#e59c7b');fxWorld(target.x,target.y,'#8d5d3d',7,1);if(state.palisade.hp<=0)toast('防壁崩壊 · 敵が城内へ侵入！')}else{const lossW=Math.min(state.wood,z.damage*.16),lossS=Math.min(state.stone,z.damage*.08);state.wood-=lossW;state.stone-=lossS;if(Math.random()<.08)state.morale=Math.max(0,state.morale-1)}}}state.zombies=state.zombies.filter(z=>!z.dead||z.death>0)}
function contextTarget(){let best=null,d=68;for(const z of state.zombies){if(z.dead)continue;const q=Math.hypot(state.player.x-z.x,state.player.y-z.y);if(q<d){best={kind:'attack',obj:z};d=q}}if(state.palisade.built&&state.palisade.hp<state.palisade.maxHp&&state.wood>=5){const B=palisadeBounds(),q=Math.min(Math.abs(state.player.x-B.l),Math.abs(state.player.x-B.r),Math.abs(state.player.y-B.t),Math.abs(state.player.y-B.b));if(q<45&&q<d)best={kind:'repair',obj:state.palisade}}return best}
function refreshContext(){const t=contextTarget();$('context').hidden=!t;if(!t)return;if(t.kind==='attack'){$('context-main').textContent='ATTACK';$('context-sub').textContent=`${t.obj.type.toUpperCase()} · HP ${Math.ceil(t.obj.hp)}`}else{$('context-main').textContent='REPAIR';$('context-sub').textContent='WOOD 5'}}
function contextAct(){const t=contextTarget();if(!t)return;FrontierAudio.enable();if(t.kind==='attack'){state.player.swing=1;slashWorld(t.obj.x,t.obj.y,Math.atan2(t.obj.y-state.player.y,t.obj.x-state.player.x));damageZombie(t.obj,24+guildLevel()*2,state.player.x,state.player.y)}else{state.wood-=5;state.palisade.hp=Math.min(state.palisade.maxHp,state.palisade.hp+80+state.palisade.level*20);FrontierAudio.sfx('build');toast('防壁を修理')}save()}
function dawnEconomy(){const cost=upkeepCost();if(state.food>=cost){state.food-=cost;state.morale=Math.min(100,state.morale+4);toast(`DAWN · 維持費 FOOD -${cost} · 士気 ${Math.floor(state.morale)}`)}else{const shortage=cost-state.food;state.food=0;state.morale=Math.max(20,state.morale-12-Math.ceil(shortage*.4));toast(`FOOD不足 · 士気低下 ${Math.floor(state.morale)}`)}const g=guildLevel();if(g>0)state.gold+=Math.ceil(state.workers.length*g*.18)}
function phaseTick(dt){const prev=state.phase;state.cycle+=dt/112*state.boost;if(state.cycle>=1){state.cycle-=1;state.day++;nightWaveMask=0;dawnEconomy();FrontierAudio.setMood('day');FrontierAudio.sfx('dawn');save()}const[ph]=phaseInfo();state.phase=ph;if(ph==='night'){const thresholds=[.755,.815,.88,.945];thresholds.forEach((t,i)=>{if(state.cycle>=t&&!(nightWaveMask&(1<<i))){nightWaveMask|=1<<i;spawnWave(i)}})}if(prev!==ph&&ph==='dusk'){toast(`DUSK · DAY ${state.day} / 4 WAVES`);FrontierAudio.sfx('warning')}if(state.boostUntil&&Date.now()>=state.boostUntil){state.boost=1;state.boostUntil=0;toast('砂時計の効果終了 · ×1');save()}}
function draw(){drawGround();const items=[];for(const n of state.nodes)if(n.alive)items.push({y:n.y,draw:()=>n.type==='tree'?drawTree(n):n.type==='rock'?drawRock(n):drawFood(n)});for(const b of state.buildings.filter(b=>!b.ruined))items.push({y:b.y+20,draw:()=>drawBuilding(b)});state.workers.slice(0,30).forEach((w,i)=>items.push({y:w.y+16,draw:()=>drawWorker(w,i)}));state.zombies.forEach(z=>{if(!z.dead||z.death>0)items.push({y:z.y+15,draw:()=>drawZombie(z)})});items.push({y:state.player.y+17,draw:drawPlayer});items.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());drawPalisade();if(state.phase==='night'){ctx.fillStyle='rgba(4,9,15,.27)';ctx.fillRect(0,0,W,H);for(const b of buildings('lantern'))glow(sx(b.x),sy(b.y)-24,90+(b.level||1)*12,'255,173,76',.2)}}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;movement(dt);playerAutoGather(dt);updateWorkers(dt);phaseTick(dt);updateWatchtower(dt);updateZombies(dt);updateProjectiles(dt);refreshContext();updateHud();draw();drawFx(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function vec(e){let dx=e.clientX-origin.x,dy=e.clientY-origin.y,mag=Math.hypot(dx,dy),max=62;if(mag<7){input={x:0,y:0,mag:0};return}if(mag>max){dx=dx/mag*max;dy=dy/mag*max;mag=max}input={x:dx/max,y:dy/max,mag:mag/max}}
canvas.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();FrontierAudio.enable();pointer=e.pointerId;origin={x:e.clientX,y:e.clientY};input={x:0,y:0,mag:0};try{canvas.setPointerCapture(pointer)}catch(_){}});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();vec(e)});function end(e){if(pointer===null||e.pointerId!==pointer)return;pointer=null;input={x:0,y:0,mag:0};save()}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
function openPanel(name){currentPanel=name;$('sheet').hidden=false;$('sheet-title').textContent=name==='build'?'BUILD':name==='people'?'PEOPLE':'BAG';['build','people','bag'].forEach(p=>{$('panel-'+p).hidden=p!==name});document.querySelectorAll('#dock button').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));updateHud();FrontierAudio.sfx('confirm')}
function closeSheet(){$('sheet').hidden=true;currentPanel=null;document.querySelectorAll('#dock button').forEach(b=>b.classList.remove('active'))}document.querySelectorAll('#dock [data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));$('sheet-close').onclick=()=>{closeSheet();FrontierAudio.sfx('cancel')};document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));document.querySelectorAll('[data-hire]').forEach(b=>b.onclick=()=>hire(b.dataset.hire));$('upgrade-hut')?.addEventListener('click',upgradeHut);$('context').onclick=contextAct;
$('sound').onclick=async()=>{$('sound').textContent=(await FrontierAudio.toggle())?'♪':'♪ ON'};$('speed').onclick=()=>{FrontierAudio.enable();if(state.hourglass<=0){toast('砂時計が必要');return}if(state.boost>=3){toast('最大×3');return}state.hourglass--;state.boost++;state.boostUntil=Date.now()+30000;toast(`砂時計 · ×${state.boost} / 30秒`);FrontierAudio.sfx('rare');save();updateHud()};
function normalizeResources(){const c=storageCaps();state.wood=Math.min(state.wood,c.wood);state.stone=Math.min(state.stone,c.stone);state.food=Math.min(state.food,c.food)}
function normalizeBuildings(){state.buildings.forEach((b,i)=>{b.level=clamp(Number(b.level)||1,1,BASE_RECIPES[b.type]?.max||5);b.maxHp=buildingHp(b.type,b.level);b.hp=Number.isFinite(b.hp)?Math.min(b.maxHp,b.hp):b.maxHp;b.ruined=!!b.ruined;b.builtAt=Number.isFinite(b.builtAt)?b.builtAt:performance.now()-1000;b.towerCd=0;if(!Number.isInteger(b.slot))b.slot=i})}
function serial(){return JSON.stringify(state)}function apply(o){if(!o||o.version!==15)return false;Object.assign(state,o);state.player={...state.player,...o.player};state.palisade={...state.palisade,...o.palisade};state.nodes=Array.isArray(o.nodes)?o.nodes:[];state.buildings=Array.isArray(o.buildings)?o.buildings:[];state.workers=Array.isArray(o.workers)?o.workers:[];state.zombies=Array.isArray(o.zombies)?o.zombies:[];return true}
function migrateOld(){for(const key of['guild-infinity-frontier-v14','guild-infinity-frontier-v13','guild-infinity-buildjoy-v12']){try{const raw=localStorage.getItem(key);if(!raw)continue;const o=JSON.parse(raw);if(!o?.player)continue;state.day=Number(o.day)||1;state.cycle=Number(o.cycle)||.18;state.wood=Number(o.wood)||0;state.stone=Number(o.stone)||0;state.food=Number(o.food)||0;state.gem=Number(o.gem)||0;state.hourglass=Number(o.hourglass)||1;state.ticket=Number(o.ticket)||0;state.player={...state.player,...o.player};state.buildings=Array.isArray(o.buildings)?o.buildings.filter(b=>BASE_RECIPES[b.type]).map((b,i)=>({...b,level:Number(b.level)||1,slot:Number.isInteger(b.slot)?b.slot:i,builtAt:performance.now()-1000})):[];state.workers=Array.isArray(o.workers)?o.workers.map((w,i)=>({...w,...identity(i),targetId:null,work:0,state:'idle',hp:100})):[];if(o.palisade?.built)state.palisade={built:true,hp:Number(o.palisade.hp)||360,maxHp:Number(o.palisade.maxHp)||360,level:clamp(Number(o.palisade.level)||1,1,6),builtAt:performance.now()-1000};state.morale=90;return true}catch(_){}}return false}
function save(){try{const prev=localStorage.getItem(SAVE);if(prev)localStorage.setItem(BACKUP,prev);state.lastSaved=Date.now();localStorage.setItem(SAVE,serial());savePulse();return true}catch(_){return false}}
function load(){for(const key of[SAVE,BACKUP]){try{const raw=localStorage.getItem(key);if(raw&&apply(JSON.parse(raw)))return true}catch(_){}}return migrateOld()}
setInterval(()=>save(),1000);addEventListener('pagehide',save);addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});
const loaded=load();if(!state.nodes.length)seedNodes();normalizeBuildings();if(state.palisade.built)clearInsideResources();if(state.boostUntil<=Date.now()){state.boost=1;state.boostUntil=0}normalizeResources();updateHud();toast(loaded?'v1.5 · ECONOMY REBALANCED / MIDGAME ONLINE':'v1.5 · BUILD / DEFEND / RANK UP');FrontierAudio.setMood(state.phase==='night'?'night':'day');window.GUILD_V15=Object.freeze({getState:()=>JSON.parse(serial()),save,build,hire,upgradeHut});
})();