(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),last=performance.now(),pointer=null,origin={x:0,y:0},input={x:0,y:0,mag:0},autoTarget=null,workClock=0,passiveClock=0,nightSpawned=false,lastWorkerHash='';
const SAVE='guild-infinity-buildjoy-v11',BACKUP=SAVE+'-backup',LEGACY='guild-infinity-buildjoy-v10',DB='guild-infinity-buildjoy-db-v11',STORE='save',WORLD={minX:-690,maxX:690,minY:-470,maxY:510};
const BUILD_SLOTS=[[-72,44],[72,44],[-150,-45],[150,-45],[-220,82],[220,82],[-72,-145],[72,-145],[-292,-78],[292,-78],[0,178],[-184,198],[184,198],[0,-242]];
const RECIPES={hut:{name:'小屋',wood:10,stone:3},lumber:{name:'木材所',wood:16,stone:5},quarry:{name:'採石所',wood:12,stone:9},barricade:{name:'集落防壁',wood:24,stone:4},lantern:{name:'灯火塔',wood:6,stone:2}};
const ROLE_NAMES={wood:'木こり',stone:'採石人',food:'採集人',guard:'衛兵'};
const NAMES=['リナ','ガルド','ミラ','レオン','ノア','セラ','エリナ','ロウ','カイ','フィア','トト','ユノ','バルド','アネラ','ジン','マオ'];
const PERSONALITIES=[
 {id:'cheerful',name:'明るい',trait:'手際よし',line:'今日も街を広げよう！',bonus:'作業速度 +3%'},
 {id:'careful',name:'慎重',trait:'丁寧仕事',line:'急がず、壊れないように',bonus:'防衛/修理 +6%'},
 {id:'quiet',name:'無口',trait:'集中力',line:'……仕事、行ってくる',bonus:'採取安定 +5%'},
 {id:'hot',name:'熱血',trait:'全力作業',line:'任せろ、すぐ終わらせる！',bonus:'木材/戦闘 +5%'},
 {id:'easy',name:'のんびり',trait:'節約上手',line:'まあ、焦らずいこうよ',bonus:'食料消費 -4%'}
];
const SKINS=['#d7ad83','#c99469','#e0b890','#b97f5b','#e5c39d'],HAIRS=['#342720','#5b3d27','#1f2528','#7b5533','#8e6b46','#3f302f'],CLOTHS=['#6c7f58','#6e6687','#8c5e50','#557383','#8b7549','#6c5f50'];
const state={version:11,day:1,cycle:.12,phase:'day',wood:0,stone:0,food:0,gold:0,gem:0,hourglass:1,ticket:0,boost:1,boostUntil:0,player:{x:0,y:115,vx:0,vy:0,dir:'down',walk:0,swing:0},nodes:[],buildings:[],workers:[],zombies:[],lastSaved:0};
const cam={x:0,y:42};const particles=[],floats=[];
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rnd=(a,b)=>a+Math.random()*(b-a),sx=x=>W/2+x-cam.x,sy=y=>H/2+y-cam.y;
function toast(t){$('ticker-text').textContent=t;$('ticker').classList.remove('flash');void $('ticker').offsetWidth;$('ticker').classList.add('flash')}
function phaseInfo(c=state.cycle){if(c<.06)return['dawn','DAWN'];if(c<.70)return['day','DAY'];if(c<.78)return['dusk','DUSK'];return['night','NIGHT']}
function objective(){if(!state.buildings.some(b=>b.type==='hut'))return'小屋を建てて最初の住人を迎えよう';if(state.workers.length===0)return'小屋完成 · 最初の仲間を雇おう';if(!state.buildings.some(b=>b.type==='lumber'))return'木材所を建てて自動化を加速';if(!state.buildings.some(b=>b.type==='barricade'))return'夜に備えて集落防壁を一気に建てよう';return`開拓を広げる · BUILDINGS ${state.buildings.length}`}
function updateHud(){
 $('wood').textContent=Math.floor(state.wood);$('stone').textContent=Math.floor(state.stone);$('food').textContent=Math.floor(state.food);$('people').textContent=state.workers.length+'/200';$('rank').textContent=1+Math.floor((state.buildings.length+state.workers.length)/4);$('day').textContent='DAY '+state.day;const [ph,label]=phaseInfo();state.phase=ph;$('phase').textContent=label;const mins=Math.floor(state.cycle*24*60),hh=String(Math.floor(mins/60)%24).padStart(2,'0'),mm=String(mins%60).padStart(2,'0');$('clock').textContent=hh+':'+mm;$('objective-text').textContent=objective();$('worker-caption').textContent=state.buildings.some(b=>b.type==='hut')?state.workers.length+'/200':'小屋で解禁';$('hourglass').textContent=state.hourglass;$('ticket').textContent=state.ticket;$('gem').textContent=state.gem;$('last-save').textContent=state.lastSaved?new Date(state.lastSaved).toLocaleTimeString('ja-JP'):'--:--:--';$('save-status').textContent=state.lastSaved?'SAVED':'AUTO';$('speed').textContent='×'+state.boost;renderWorkerList();
}
function identityFor(i){const p=PERSONALITIES[i%PERSONALITIES.length];return{name:NAMES[i%NAMES.length],personality:p.id,personalityName:p.name,trait:p.trait,line:p.line,bonus:p.bonus,visual:{skin:SKINS[i%SKINS.length],hair:HAIRS[(i*3+1)%HAIRS.length],cloth:CLOTHS[(i*5+2)%CLOTHS.length],accent:['#d7ad62','#73996a','#7690af','#b27265'][i%4]}}}
function ensureWorkerIdentity(w,i){const d=identityFor(i);if(!w.name)Object.assign(w,d);if(!w.visual)w.visual=d.visual;return w}
function renderWorkerList(){const hash=state.workers.map(w=>w.id+':'+w.role+':'+w.name).join('|');if(hash===lastWorkerHash)return;lastWorkerHash=hash;const el=$('worker-list');if(!el)return;if(!state.workers.length){el.innerHTML='<div class="panel-note">まだ仲間はいない · 小屋を建てて最初の一人を迎えよう</div>';return}el.innerHTML=state.workers.slice(0,8).map((w,i)=>{ensureWorkerIdentity(w,i);const v=w.visual||identityFor(i).visual;return `<article class="worker-card"><span class="worker-face" style="--skin:${v.skin};--hair:${v.hair};--cloth:${v.cloth};--accent:${v.accent}"><i class="skin"></i><i class="hair"></i><i class="eyes"></i><i class="body"></i></span><span class="worker-copy"><b>${w.name} · ${ROLE_NAMES[w.role]||w.role}</b><small>${w.personalityName} / ${w.line}</small><span>${w.bonus}</span></span><em class="trait-badge">${w.trait}</em></article>`}).join('')+(state.workers.length>8?`<div class="panel-note">ほか ${state.workers.length-8}人 · 人口 ${state.workers.length}/200</div>`:'')}
function makeNode(id,x,y,type){return{id,x,y,type,hp:type==='food'?1:3,maxHp:type==='food'?1:3,alive:true,respawnAt:0}}
function seedNodes(){if(state.nodes.length)return;let id=0;const near=[[-44,148,'tree'],[50,160,'tree'],[-94,104,'tree'],[106,92,'tree'],[-150,140,'tree'],[155,145,'tree'],[-115,62,'rock'],[128,63,'rock'],[-176,188,'rock'],[176,198,'rock'],[-26,218,'food'],[78,225,'food']];state.nodes=near.map(v=>makeNode('n'+id++,...v));for(let i=0;i<40;i++){const a=i/40*Math.PI*2,r=180+(i%6)*60;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-32,32),Math.sin(a)*r*.72+rnd(-26,26),'tree'))}for(let i=0;i<26;i++){const a=(i+.35)/26*Math.PI*2,r=145+(i%5)*86;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-28,28),Math.sin(a)*r*.70+rnd(-24,24),'rock'))}for(let i=0;i<15;i++){const a=(i+.7)/15*Math.PI*2,r=125+(i%4)*95;state.nodes.push(makeNode('n'+id++,Math.cos(a)*r+rnd(-22,22),Math.sin(a)*r*.68+rnd(-20,20),'food'))}}
seedNodes();
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function shadow(x,y,w,h=6){ctx.fillStyle='#08110f8c';ctx.fillRect(Math.round(x-w/2),Math.round(y-h/2),Math.round(w),Math.round(h))}
function drawGround(){const ph=state.phase,top=ph==='night'?'#0d1d25':ph==='dusk'?'#303e47':ph==='dawn'?'#365553':'#36594c',bot=ph==='night'?'#17261f':ph==='dusk'?'#4b4a34':ph==='dawn'?'#465c49':'#435f4e';const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,top);g.addColorStop(1,bot);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const ox=((-cam.x)%32+32)%32,oy=((-cam.y)%32+32)%32;ctx.strokeStyle='rgba(181,168,123,.035)';for(let x=ox;x<W;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=oy;y<H;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(let i=0;i<48;i++){const x=sx((i*137)%1050-520),y=sy((i*89)%760-350);if(x<0||x>W||y<0||y>H)continue;rect(x,y,2+(i%3),2,'#71805b38')}const cx=sx(0),cy=sy(0);rect(cx-25,cy+10,50,6,'#51493a');rect(cx-16,cy+4,10,6,'#81755a');rect(cx+6,cy+4,10,6,'#81755a')}
function drawTree(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+20,30,6);rect(x-5,y-3,10,26,'#5f422e');rect(x-2,y-3,3,22,'#9c6c40');rect(x-19,y-26,38,18,'#19392e');rect(x-16,y-37,32,19,'#244c3a');rect(x-9,y-44,20,13,'#355e44');rect(x-12,y-31,7,7,'#4d724f');rect(x+5,y-27,8,6,'#40694a')}
function drawRock(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+13,28,5);ctx.fillStyle='#59615f';ctx.beginPath();ctx.moveTo(x-14,y+8);ctx.lineTo(x-11,y-5);ctx.lineTo(x-4,y-13);ctx.lineTo(x+9,y-10);ctx.lineTo(x+14,y+3);ctx.lineTo(x+8,y+10);ctx.closePath();ctx.fill();ctx.fillStyle='#858777';ctx.beginPath();ctx.moveTo(x-8,y-4);ctx.lineTo(x-3,y-9);ctx.lineTo(x+5,y-7);ctx.lineTo(x+8,y-1);ctx.closePath();ctx.fill();rect(x-7,y+3,6,3,'#a09f8b')}
function drawFood(n){const x=sx(n.x),y=sy(n.y);shadow(x,y+12,26,4);rect(x-13,y+2,26,11,'#27422f');rect(x-10,y-5,20,10,'#476948');rect(x-4,y-9,9,7,'#5f7b50');for(const d of[-7,-1,6])rect(x+d,y+1,3,3,'#c06058')}
function drawFace(x,y,skin,hair,dir){rect(x-6,y-22,12,10,skin);rect(x-7,y-27,14,7,hair);if(dir==='down'||dir==='left'||dir==='right'){if(dir==='down'){rect(x-3,y-18,2,2,'#2b211e');rect(x+2,y-18,2,2,'#2b211e')}else if(dir==='left')rect(x-4,y-18,2,2,'#2b211e');else rect(x+3,y-18,2,2,'#2b211e')}rect(x-1,y-14,3,1,'#9b654d')}
function drawPlayer(){const p=state.player,x=sx(p.x),y=sy(p.y),bob=Math.sin(p.walk)*1.15;shadow(x,y+17,22,6);rect(x-8,y-13+bob,16,19,'#b9563f');rect(x-7,y-9+bob,14,4,'#d08b55');rect(x-8,y-3+bob,16,3,'#47342c');drawFace(x,y+bob,'#d8aa7e','#483326',p.dir);rect(x-6,y+6-bob,4,10,'#30363a');rect(x+2,y+6+bob,4,10,'#30363a');rect(x-10,y-9+bob,3,8,'#d8aa7e');rect(x+7,y-9+bob,3,8,'#d8aa7e');if(p.swing>0){const a=(1-p.swing)*Math.PI*.95-.35,ax=x+Math.cos(a)*21,ay=y-7+Math.sin(a)*20;ctx.strokeStyle='#7f5b36';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+7,y-7);ctx.lineTo(ax,ay);ctx.stroke();rect(ax-2,ay-5,9,7,'#aab0ae');rect(ax+3,ay-5,4,2,'#d2d1c4')}}
function drawWorker(w,i){ensureWorkerIdentity(w,i);const v=w.visual,x=sx(w.x),y=sy(w.y),bob=Math.sin(performance.now()*.006+i)*1;shadow(x,y+14,18,4);rect(x-7,y-12+bob,14,17,v.cloth);rect(x-7,y-4+bob,14,3,v.accent);drawFace(x,y+bob,v.skin,v.hair,'down');rect(x-5,y+5-bob,3,9,'#31363a');rect(x+2,y+5+bob,3,9,'#31363a');if(w.role==='wood'){ctx.strokeStyle='#795535';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+6,y-7);ctx.lineTo(x+13,y+3);ctx.stroke();rect(x+11,y-1,6,4,'#aab0ae')}else if(w.role==='stone'){ctx.strokeStyle='#795535';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+6,y-8);ctx.lineTo(x+13,y+3);ctx.stroke();rect(x+9,y-4,8,3,'#aab0ae')}else if(w.role==='food'){rect(x+7,y-4,9,8,'#8f6c43');rect(x+9,y-6,5,2,'#ba9561')}else if(w.role==='guard'){rect(x+8,y-15,2,22,'#b7b2a5');rect(x+5,y-14,8,3,'#91704a')}}
function buildingAge(b){const elapsed=Date.now()-(b.builtEpoch||Date.now());return clamp(elapsed/700,0,1)}
function drawHut(b){const x=sx(b.x),y=sy(b.y),p=buildingAge(b),rise=(1-p)*18;ctx.save();ctx.globalAlpha=.3+.7*p;ctx.translate(0,rise);shadow(x,y+20,58,7);rect(x-27,y-9,54,32,'#7b5a40');for(let s=-21;s<23;s+=10)rect(x+s,y-5,2,24,'#9a7150');ctx.fillStyle='#b98750';ctx.beginPath();ctx.moveTo(x-33,y-9);ctx.lineTo(x,y-35);ctx.lineTo(x+33,y-9);ctx.closePath();ctx.fill();for(let i=-21;i<=14;i+=9)rect(x+i,y-12-Math.abs(i)*.15,8,3,'#8c5f3c');rect(x-7,y+4,14,19,'#2c241e');rect(x+11,y,8,8,'#e5b85d');glow(x+15,y+4,38);ctx.restore()}
function drawLumber(b){const x=sx(b.x),y=sy(b.y),p=buildingAge(b),rise=(1-p)*18;ctx.save();ctx.globalAlpha=.3+.7*p;ctx.translate(0,rise);shadow(x,y+20,64,7);rect(x-29,y-7,58,28,'#6e4b32');rect(x-25,y-13,50,7,'#a57748');for(let i=-22;i<=22;i+=11){rect(x+i-3,y+12,7,13,'#4e3524');rect(x+i-3,y+8,7,4,'#aa7948')}for(let i=0;i<3;i++){rect(x+14+i*5,y-20-i*2,18,4,'#98683d');rect(x+28+i*5,y-20-i*2,4,4,'#4b321f')}ctx.restore()}
function drawQuarry(b){const x=sx(b.x),y=sy(b.y),p=buildingAge(b),rise=(1-p)*18;ctx.save();ctx.globalAlpha=.3+.7*p;ctx.translate(0,rise);shadow(x,y+17,62,7);rect(x-30,y+1,60,18,'#505958');ctx.fillStyle='#737a71';ctx.beginPath();ctx.moveTo(x-28,y);ctx.lineTo(x-17,y-14);ctx.lineTo(x-3,y-8);ctx.lineTo(x+9,y-19);ctx.lineTo(x+29,y-5);ctx.lineTo(x+27,y+4);ctx.closePath();ctx.fill();rect(x+20,y-27,4,27,'#806043');rect(x+4,y-25,22,3,'#8e6c47');ctx.strokeStyle='#b7a67f';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+7,y-23);ctx.lineTo(x+7,y-7);ctx.stroke();ctx.restore()}
function drawLantern(b){const x=sx(b.x),y=sy(b.y),p=buildingAge(b),rise=(1-p)*18;ctx.save();ctx.globalAlpha=.3+.7*p;ctx.translate(0,rise);shadow(x,y+13,22,4);rect(x-3,y-29,6,43,'#745039');rect(x-16,y-37,32,9,'#283039');rect(x-10,y-34,20,5,'#f0bd62');rect(x-8,y-31,16,7,'#d98948');glow(x,y-30,105);ctx.restore()}
function wallSegments(b){const rx=b.rx||260,ry=b.ry||175,cx=b.x||0,cy=b.y||45,segs=[];for(let x=-rx;x<=rx;x+=18){segs.push({x:cx+x,y:cy-ry,side:'back',o:'h'});if(Math.abs(x)>46)segs.push({x:cx+x,y:cy+ry,side:'front',o:'h'})}for(let y=-ry+18;y<ry;y+=18){segs.push({x:cx-rx,y:cy+y,side:'back',o:'v'});segs.push({x:cx+rx,y:cy+y,side:'back',o:'v'})}return segs}
function drawWallSegment(s,progress){const x=sx(s.x),y=sy(s.y),rise=(1-progress)*20;ctx.save();ctx.globalAlpha=.25+.75*progress;ctx.translate(0,rise);if(s.o==='h'){shadow(x,y+12,17,4);rect(x-6,y-19,12,33,'#6b472e');rect(x-3,y-19,3,29,'#a16d42');ctx.fillStyle='#6b472e';ctx.beginPath();ctx.moveTo(x-6,y-19);ctx.lineTo(x,y-26);ctx.lineTo(x+6,y-19);ctx.fill()}else{shadow(x,y+9,13,4);rect(x-5,y-15,10,27,'#62402a');rect(x-2,y-15,3,24,'#9a673e')}ctx.restore()}
function drawWall(b,part){const p=buildingAge(b),all=wallSegments(b),visible=Math.ceil(all.length*p);let count=0;for(const s of all){if((part==='back'&&s.side==='front')||(part==='front'&&s.side!=='front'))continue;if(count++>visible)break;drawWallSegment(s,p)}if(part==='front'){const x=sx(b.x||0),y=sy((b.y||45)+(b.ry||175));rect(x-44,y-25,6,39,'#765039');rect(x+38,y-25,6,39,'#765039');rect(x-44,y-25,88,5,'#9c7048');ctx.fillStyle='#d5aa5b';ctx.beginPath();ctx.moveTo(x-6,y-25);ctx.lineTo(x,y-34);ctx.lineTo(x+6,y-25);ctx.fill();const r=clamp(b.hp/b.maxHp,0,1);rect(x-34,y+19,68,4,'#171413');rect(x-34,y+19,68*r,4,r>.5?'#6d9765':r>.25?'#c5964e':'#b75b4c')}}
function drawBuilding(b){if(b.type==='hut')drawHut(b);else if(b.type==='lumber')drawLumber(b);else if(b.type==='quarry')drawQuarry(b);else if(b.type==='lantern')drawLantern(b)}
function glow(x,y,r){ctx.save();ctx.globalCompositeOperation='screen';const g=ctx.createRadialGradient(x,y,4,x,y,r);g.addColorStop(0,'rgba(255,191,87,.27)');g.addColorStop(1,'rgba(255,135,50,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore()}
function drawZombie(z){const x=sx(z.x),y=sy(z.y);shadow(x,y+14,19,5);rect(x-8,y-14,16,20,z.hit>0?'#ddd3aa':'#637b5d');rect(x-6,y-23,12,10,'#9da287');rect(x-5,y-20,2,2,'#31201e');rect(x+3,y-20,2,2,'#31201e');rect(x-7,y+5,4,11,'#453735');rect(x+3,y+5,4,11,'#453735');rect(x-11,y-30,22,3,'#160f0f');rect(x-11,y-30,22*clamp(z.hp/z.maxHp,0,1),3,'#a45045')}
function particlesAt(wx,wy,color,count=7){for(let i=0;i<count;i++)particles.push({x:wx,y:wy,vx:rnd(-44,44),vy:rnd(-64,-18),life:rnd(.35,.65),color,size:rnd(2,4)})}function floatText(wx,wy,text,color='#f0d187'){floats.push({x:wx,y:wy,text,color,life:1})}
function rareDrop(wx,wy){const r=Math.random();if(r<.025){state.hourglass++;toast('RARE DROP · 砂時計 +1');floatText(wx,wy,'HOURGLASS!','#c6a6ff');BuildjoyAudio.sfx('rare');return}if(r<.04){state.ticket++;toast('RARE DROP · 召喚券 +1');floatText(wx,wy,'TICKET!','#8dd8ff');BuildjoyAudio.sfx('rare');return}if(r<.055){state.gem++;toast('RARE DROP · GEM +1');floatText(wx,wy,'GEM!','#9ac5ff');BuildjoyAudio.sfx('rare')}}
function nearestNode(){let best=null,d=999;for(const n of state.nodes){if(!n.alive)continue;const q=Math.hypot(state.player.x-n.x,state.player.y-n.y);if(q<52&&q<d){best=n;d=q}}return best}
function workNode(n){if(!n||!n.alive)return;state.player.dir=Math.abs(n.x-state.player.x)>Math.abs(n.y-state.player.y)?(n.x>state.player.x?'right':'left'):(n.y>state.player.y?'down':'up');state.player.swing=1;const mul=n.type==='tree'?(state.buildings.some(b=>b.type==='lumber')?1.3:1):n.type==='rock'?(state.buildings.some(b=>b.type==='quarry')?1.3:1):1;if(n.type==='tree'){const gain=3*mul;state.wood+=gain;floatText(n.x,n.y-20,'+WOOD '+Math.ceil(gain));particlesAt(n.x,n.y,'#c18b50',9);BuildjoyAudio.sfx('chop')}else if(n.type==='rock'){const gain=2*mul;state.stone+=gain;floatText(n.x,n.y-16,'+STONE '+Math.ceil(gain));particlesAt(n.x,n.y,'#a6a79c',8);BuildjoyAudio.sfx('mine')}else{state.food+=3;floatText(n.x,n.y-14,'+FOOD 3');particlesAt(n.x,n.y,'#c36a5d',8);BuildjoyAudio.sfx('pickup')}n.hp--;if(n.hp<=0){n.alive=false;n.respawnAt=Date.now()+(n.type==='food'?5500:8000);rareDrop(n.x,n.y)}save('mutation');updateHud()}
function respawnNodes(){const now=Date.now();for(const n of state.nodes)if(!n.alive&&n.respawnAt&&now>=n.respawnAt){n.alive=true;n.hp=n.maxHp;n.respawnAt=0}}
function build(type){const r=RECIPES[type];if(!r)return;if(state.wood<r.wood||state.stone<r.stone){toast(`${r.name} · 素材不足 W${r.wood} / S${r.stone}`);BuildjoyAudio.sfx('cancel');return}if(state.buildings.some(b=>b.type===type)&&type!=='hut'){toast(r.name+' は建設済み');BuildjoyAudio.sfx('cancel');return}state.wood-=r.wood;state.stone-=r.stone;if(type==='barricade'){const b={id:'wall'+Date.now(),type:'barricade',x:0,y:45,rx:260,ry:178,hp:520,maxHp:520,builtEpoch:Date.now(),level:1};state.buildings.push(b);for(const s of wallSegments(b).filter((_,i)=>i%4===0))particlesAt(s.x,s.y,'#d0a065',3);floatText(0,45,'PALISADE COMPLETE','#ffd48a');BuildjoyAudio.sfx('build');toast('集落防壁 COMPLETE · 外周を一気に囲った');closeSheet();save('mutation');updateHud();return}const used=new Set(state.buildings.filter(b=>Number.isInteger(b.slot)).map(b=>b.slot)),candidates=BUILD_SLOTS.map((p,i)=>({p,i,d:Math.hypot(state.player.x-p[0],state.player.y-p[1])})).filter(v=>!used.has(v.i)).sort((a,b)=>a.d-b.d);if(!candidates.length){toast('建築スロットがいっぱい');return}const s=candidates[0];state.buildings.push({id:'b'+Date.now()+Math.random(),type,slot:s.i,x:s.p[0],y:s.p[1],hp:220,maxHp:220,builtEpoch:Date.now(),level:1});particlesAt(s.p[0],s.p[1],'#e1b769',20);floatText(s.p[0],s.p[1]-30,'BUILD!','#ffd785');BuildjoyAudio.sfx('build');toast(r.name+' 完成 · 街が広がった');closeSheet();save('mutation');updateHud()}
function hire(role){if(!state.buildings.some(b=>b.type==='hut')){toast('小屋を建てると雇用できる');return}const cost=role==='guard'?7:role==='food'?4:5;if(state.food<cost){toast('FOOD不足 · '+cost);BuildjoyAudio.sfx('cancel');return}if(state.workers.length>=200){toast('人口上限 200');return}state.food-=cost;const i=state.workers.length,d=identityFor(i),b=state.buildings.find(b=>b.type==='hut')||{x:0,y:0};state.workers.push({id:'w'+Date.now()+Math.random(),role,x:b.x+rnd(-22,22),y:b.y+rnd(10,34),...d});BuildjoyAudio.sfx('hire');toast(`${d.name} が加入 · ${d.personalityName} / ${d.trait}`);lastWorkerHash='';save('mutation');updateHud()}
function passiveWorkers(dt){passiveClock+=dt;if(passiveClock<.75)return;passiveClock=0;for(const w of state.workers){const p=PERSONALITIES.find(p=>p.id===w.personality);const bonus=p?.id==='cheerful'?1.03:p?.id==='quiet'?1.05:1;if(w.role==='wood')state.wood+=(state.buildings.some(b=>b.type==='lumber')?1.5:.95)*bonus;else if(w.role==='stone')state.stone+=(state.buildings.some(b=>b.type==='quarry')?1.2:.78)*bonus;else if(w.role==='food')state.food+=.9*(p?.id==='easy'?1.04:1)}updateHud()}
function spawnNight(){if(nightSpawned||state.phase!=='night')return;nightSpawned=true;const count=Math.min(4,2+Math.floor(state.day/3));for(let i=0;i<count;i++){const side=i%4,x=side===0?-630:side===1?630:rnd(-340,340),y=side===2?-430:side===3?480:rnd(-250,310);state.zombies.push({id:'z'+Date.now()+i,x,y,hp:48,maxHp:48,hit:0,dead:false,cool:0})}toast('NIGHT · 少数のゾンビが接近');BuildjoyAudio.sfx('warning');BuildjoyAudio.setMood('night')}
function nearestWallPoint(z,b){const cx=b.x||0,cy=b.y||45,rx=b.rx||260,ry=b.ry||178,dx=z.x-cx,dy=z.y-cy;const nx=Math.abs(dx/rx),ny=Math.abs(dy/ry);if(nx>ny)return{x:cx+(dx<0?-rx:rx),y:clamp(z.y,cy-ry+15,cy+ry-15)};let tx=clamp(z.x,cx-rx+15,cx+rx-15);if(dy>0&&Math.abs(tx-cx)<52)tx=cx+(tx<cx?-58:58);return{x:tx,y:cy+(dy<0?-ry:ry)}}
function updateZombies(dt){const wall=state.buildings.find(b=>b.type==='barricade'&&b.hp>0);for(const z of state.zombies){if(z.dead)continue;if(z.hit>0)z.hit-=dt;if(z.cool>0)z.cool-=dt;let target=wall?nearestWallPoint(z,wall):{x:0,y:20},kind=wall?'wall':'camp';const dx=target.x-z.x,dy=target.y-z.y,d=Math.hypot(dx,dy)||1;if(d>24){z.x+=dx/d*20*dt*state.boost;z.y+=dy/d*20*dt*state.boost}else if(z.cool<=0){z.cool=1.05;if(kind==='wall'){wall.hp=Math.max(0,wall.hp-6);particlesAt(target.x,target.y,'#9a6b47',4);if(wall.hp===0)toast('防壁が破られた · 修理が必要')}else{state.wood=Math.max(0,state.wood-1);state.stone=Math.max(0,state.stone-.5)}BuildjoyAudio.sfx('hit')}}const guards=state.workers.filter(w=>w.role==='guard').length;if(guards){for(const z of state.zombies){if(z.dead)continue;const care=state.workers.filter(w=>w.role==='guard'&&w.personality==='careful').length;z.hp-=(guards*3+care*.35)*dt;if(z.hp<=0)killZombie(z)}}}
function killZombie(z){z.dead=true;particlesAt(z.x,z.y,'#7e936c',9);floatText(z.x,z.y-18,'DOWN','#d9d1aa');if(Math.random()<.12){state.gem++;toast('DROP · GEM +1');BuildjoyAudio.sfx('rare')}else BuildjoyAudio.sfx('pickup');save('mutation')}
function contextTarget(){let best=null,d=999;for(const z of state.zombies){if(z.dead)continue;const q=Math.hypot(state.player.x-z.x,state.player.y-z.y);if(q<58&&q<d){best={kind:'attack',obj:z};d=q}}const wall=state.buildings.find(b=>b.type==='barricade'&&b.hp<b.maxHp);if(wall){const q=Math.hypot(state.player.x-(wall.x||0),state.player.y-((wall.y||45)+(wall.ry||178)));if(q<90&&q<d)best={kind:'repair',obj:wall}}return best}
function refreshContext(){const t=contextTarget();$('context').hidden=!t;if(!t)return;if(t.kind==='attack'){$('context-main').textContent='ATTACK';$('context-sub').textContent='斧で敵を攻撃'}else{$('context-main').textContent='REPAIR';$('context-sub').textContent='WOOD 4 で防壁修理'}}
function contextAct(){const t=contextTarget();if(!t)return;BuildjoyAudio.enable();if(t.kind==='attack'){t.obj.hp-=32;t.obj.hit=.12;particlesAt(t.obj.x,t.obj.y,'#c7b4a2',7);BuildjoyAudio.sfx('hit');if(t.obj.hp<=0)killZombie(t.obj)}else{if(state.wood<4){toast('WOOD不足 · 4');return}state.wood-=4;t.obj.hp=Math.min(t.obj.maxHp,t.obj.hp+70);BuildjoyAudio.sfx('build');toast('集落防壁 REPAIR +70')}save('mutation');updateHud()}
function phaseTick(dt){state.cycle+=dt/210*state.boost;if(state.cycle>=1){state.cycle-=1;state.day++;nightSpawned=false;state.zombies=state.zombies.filter(z=>!z.dead);BuildjoyAudio.setMood('day');toast('DAWN · DAY '+state.day+' · FOOD +2');state.food+=2;BuildjoyAudio.sfx('hire');save('mutation')}const prev=state.phase,[ph]=phaseInfo();state.phase=ph;if(prev!==ph){if(ph==='dusk'){toast('DUSK · そろそろ夜');BuildjoyAudio.sfx('warning')}if(ph==='night')spawnNight();if(ph==='day')BuildjoyAudio.setMood('day')}if(state.boostUntil&&Date.now()>=state.boostUntil){state.boost=1;state.boostUntil=0;toast('砂時計終了 · ×1');save('mutation')}}
function movement(dt){const p=state.player,m=input.mag,tx=input.x*140,ty=input.y*140,acc=m>.04?1-Math.pow(.000002,dt):1-Math.pow(.00015,dt);p.vx=lerp(p.vx,tx,acc);p.vy=lerp(p.vy,ty,acc);if(Math.abs(p.vx)<.3)p.vx=0;if(Math.abs(p.vy)<.3)p.vy=0;if(autoTarget&&m<.55){p.vx*=.35;p.vy*=.35}else{p.x=clamp(p.x+p.vx*dt*state.boost,WORLD.minX,WORLD.maxX);p.y=clamp(p.y+p.vy*dt*state.boost,WORLD.minY,WORLD.maxY)}if(Math.hypot(p.vx,p.vy)>3){p.walk+=dt*12;const ax=Math.abs(p.vx),ay=Math.abs(p.vy);p.dir=ax>ay?(p.vx>0?'right':'left'):(p.vy>0?'down':'up')}p.swing=Math.max(0,p.swing-dt*4.8);cam.x=lerp(cam.x,p.x,1-Math.pow(.00003,dt));cam.y=lerp(cam.y,p.y-48,1-Math.pow(.00003,dt))}
function autoGather(dt){respawnNodes();const p=state.player;if(input.mag>.62){autoTarget=null;workClock=0;return}if(!autoTarget||!autoTarget.alive||Math.hypot(p.x-autoTarget.x,p.y-autoTarget.y)>54)autoTarget=nearestNode();if(!autoTarget){workClock=0;return}const d=Math.hypot(p.x-autoTarget.x,p.y-autoTarget.y);if(d>45)return;workClock+=dt*state.boost;if(workClock>=.34){workClock=0;workNode(autoTarget);if(!autoTarget.alive)autoTarget=null}}
function respawnNodes(){const now=Date.now();for(const n of state.nodes)if(!n.alive&&n.respawnAt&&now>=n.respawnAt){n.alive=true;n.hp=n.maxHp;n.respawnAt=0}}
function drawEffects(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=65*dt;p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}ctx.globalAlpha=clamp(p.life*2,0,1);rect(sx(p.x),sy(p.y),p.size,p.size,p.color);ctx.globalAlpha=1}for(let i=floats.length-1;i>=0;i--){const f=floats[i];f.y-=23*dt;f.life-=dt;if(f.life<=0){floats.splice(i,1);continue}ctx.globalAlpha=clamp(f.life,0,1);ctx.font='900 9px ui-monospace,monospace';ctx.textAlign='center';ctx.fillStyle='#000c';ctx.fillText(f.text,sx(f.x)+1,sy(f.y)+1);ctx.fillStyle=f.color;ctx.fillText(f.text,sx(f.x),sy(f.y));ctx.globalAlpha=1}}
function draw(){drawGround();const wall=state.buildings.find(b=>b.type==='barricade');if(wall)drawWall(wall,'back');const list=[];for(const n of state.nodes)if(n.alive)list.push({y:n.y,draw:()=>n.type==='tree'?drawTree(n):n.type==='rock'?drawRock(n):drawFood(n)});for(const b of state.buildings)if(b.type!=='barricade')list.push({y:b.y+20,draw:()=>drawBuilding(b)});state.workers.slice(0,16).forEach((w,i)=>list.push({y:w.y+16,draw:()=>drawWorker(w,i)}));for(const z of state.zombies)if(!z.dead)list.push({y:z.y+15,draw:()=>drawZombie(z)});list.push({y:state.player.y+17,draw:drawPlayer});list.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());if(wall)drawWall(wall,'front');if(state.phase==='night'){ctx.fillStyle='rgba(4,8,16,.23)';ctx.fillRect(0,0,W,H)}for(const b of state.buildings)if(b.type==='lantern')glow(sx(b.x),sy(b.y)-30,110)}
function tick(dt){movement(dt);autoGather(dt);passiveWorkers(dt);phaseTick(dt);updateZombies(dt);refreshContext();updateHud()}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;tick(dt);draw();drawEffects(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function vec(e){let dx=e.clientX-origin.x,dy=e.clientY-origin.y,mag=Math.hypot(dx,dy),max=62;if(mag<6){input={x:0,y:0,mag:0};return}if(mag>max){dx=dx/mag*max;dy=dy/mag*max;mag=max}input={x:dx/max,y:dy/max,mag:mag/max}}
canvas.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();BuildjoyAudio.enable();pointer=e.pointerId;origin={x:e.clientX,y:e.clientY};input={x:0,y:0,mag:0};try{canvas.setPointerCapture(pointer)}catch(_){}});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();vec(e)});function end(e){if(pointer===null||e.pointerId!==pointer)return;pointer=null;input={x:0,y:0,mag:0};save('mutation')}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
function openSheet(name){$('sheet').hidden=false;$('sheet-title').textContent=name.toUpperCase();$('build-panel').hidden=name!=='build';$('workers-panel').hidden=name!=='workers';$('bag-panel').hidden=name!=='bag';$('save-panel').hidden=name!=='save';if(name==='workers'){$('workers-lock').hidden=state.buildings.some(b=>b.type==='hut');lastWorkerHash='';renderWorkerList()}}function closeSheet(){$('sheet').hidden=true}
$('build-open').onclick=()=>openSheet('build');$('workers-open').onclick=()=>openSheet('workers');$('bag-open').onclick=()=>openSheet('bag');$('save-open').onclick=()=>openSheet('save');$('sheet-close').onclick=closeSheet;document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));document.querySelectorAll('[data-hire]').forEach(b=>b.onclick=()=>hire(b.dataset.hire));$('context').onclick=contextAct;$('manual-save').onclick=()=>{save('manual');toast('保存した')};$('sound').onclick=async()=>{$('sound').textContent=(await BuildjoyAudio.toggle())?'♪ OFF':'♪ ON'};$('speed').onclick=()=>{BuildjoyAudio.enable();if(state.hourglass<=0){toast('砂時計が必要');BuildjoyAudio.sfx('cancel');return}if(state.boost>=3){toast('最大×3');return}state.hourglass--;state.boost++;state.boostUntil=Date.now()+30000;toast(`砂時計 · ×${state.boost} / 30秒`);BuildjoyAudio.sfx('rare');save('mutation');updateHud()};
function serial(){return JSON.stringify(state)}function migrateWorker(w,i){ensureWorkerIdentity(w,i);return w}function apply(o){if(!o||![10,11].includes(o.version))return false;Object.assign(state,o);state.version=11;state.player={...state.player,...o.player};state.nodes=Array.isArray(o.nodes)?o.nodes:[];state.buildings=Array.isArray(o.buildings)?o.buildings:[];state.workers=Array.isArray(o.workers)?o.workers.map(migrateWorker):[];state.zombies=Array.isArray(o.zombies)?o.zombies:[];for(const b of state.buildings){if(b.builtAt&&!b.builtEpoch)b.builtEpoch=Date.now()-650;if(b.type==='barricade'&&!b.rx){b.x=0;b.y=45;b.rx=260;b.ry=178;b.hp=Math.max(300,b.hp||520);b.maxHp=Math.max(520,b.maxHp||520)}}return true}
function idbOpen(){return new Promise((res,rej)=>{if(!('indexedDB'in window))return rej();const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function mirror(){try{const db=await idbOpen(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(serial(),'current');tx.oncomplete=()=>db.close()}catch(_){}}
function save(reason='auto'){try{const prev=localStorage.getItem(SAVE);if(prev)localStorage.setItem(BACKUP,prev);state.lastSaved=Date.now();localStorage.setItem(SAVE,serial());if(reason!=='auto')mirror();updateHud();return true}catch(_){return false}}
async function load(){let ok=false;for(const key of[SAVE,BACKUP,LEGACY]){try{const raw=localStorage.getItem(key);if(raw&&apply(JSON.parse(raw))){ok=true;break}}catch(_){}}if(!ok){try{const db=await idbOpen(),raw=await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get('current');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();if(raw)ok=apply(JSON.parse(raw))}catch(_){}}if(!state.nodes.length)seedNodes();state.boost=state.boostUntil>Date.now()?clamp(state.boost,1,3):1;if(state.boost===1)state.boostUntil=0;lastWorkerHash='';updateHud();return ok}
setInterval(()=>save('auto'),1000);setInterval(mirror,5000);addEventListener('pagehide',()=>save('lifecycle'));addEventListener('beforeunload',()=>save('lifecycle'));document.addEventListener('visibilitychange',()=>{if(document.hidden)save('lifecycle')});
load().then(ok=>{updateHud();toast(ok?'AUTO SAVE · 続きから再開':'BUILDJOY v1.1 · 自動採取から街を広げよう');BuildjoyAudio.setMood(state.phase==='night'?'night':'day')});
window.BUILDJOY=Object.freeze({version:'1.1-reference-polish',getState:()=>JSON.parse(serial()),save,build,hire});
})();