'use strict';
/* Regional state is separate from the village: no node/enemy array swapping. */
const WorldGame=(()=>{
 const regions=[
  {id:'forest',name:'へそ曲がりの森',resource:'crooked_wood',resourceName:'曲がった木',color:'#719c67',ground:'#344e3b',path:'#697755',blurb:'木まで反抗期。奥では切り株係長が待つ。',basic:'wood',enemy:'runner',boss:'切り株係長'},
  {id:'canyon',name:'石頭の峡谷',resource:'iron_ore',resourceName:'鉄鉱石',color:'#cf9d6f',ground:'#795943',path:'#a28059',blurb:'石橋を叩きすぎた村の、石だらけの出張先。',basic:'stone',enemy:'brute',boss:'岩盤課長'},
  {id:'marsh',name:'会議の長い沼',resource:'glowcap',resourceName:'夜光キノコ',color:'#96b3ac',ground:'#324d55',path:'#557267',blurb:'光るキノコと、結論の出ない沼の主。',basic:'food',enemy:'spitter',boss:'議長マッシュ'},
  {id:'volcano',name:'噴火待ち火山',resource:'obsidian',resourceName:'火山ガラス',color:'#df8874',ground:'#513d40',path:'#7b5950',blurb:'いつ噴くかは調整中。現場責任者は怒っている。',basic:'stone',enemy:'brute',boss:'火口監督'},
  {id:'port',name:'船出だけは一人前',resource:'sea_glass',resourceName:'海のガラス',color:'#82bdc3',ground:'#416776',path:'#aa9a73',blurb:'波に磨かれたお宝と、出航しない船長。',basic:'wood',enemy:'runner',boss:'停泊船長'}
 ];
 const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{},arr=v=>Array.isArray(v)?v:[];
 const num=(v,d=0,max=1e9)=>Number.isFinite(v)?clamp(v,0,max):d;
 const ids=new Set(regions.map(r=>r.id)),definition=id=>regions.find(r=>r.id===id);
 const raw=obj(state.world),w=state.world={region:ids.has(raw.region)?raw.region:'home',time:num(raw.time),resources:{},collected:{},scenes:{},outposts:{},shipments:{},tradeCooldown:num(raw.tradeCooldown,0,30),bosses:[...new Set(arr(raw.bosses).filter(id=>ids.has(id)))],visited:[...new Set(arr(raw.visited).filter(id=>ids.has(id)))],expeditions:[],log:arr(raw.log).filter(n=>n&&typeof n.text==='string').slice(-40).map(n=>({text:n.text.slice(0,160),time:num(n.time)})),serial:Math.floor(num(raw.serial)),home:{x:0,y:120,camX:0,camY:80},whistleRemaining:num(raw.whistleRemaining,0,22),rallyRemaining:num(raw.rallyRemaining,0,5)};
 const savedHome=obj(raw.home);for(const k of Object.keys(w.home))if(Number.isFinite(savedHome[k]))w.home[k]=clamp(savedHome[k],-900,900);
 for(const r of regions){w.resources[r.resource]=Math.floor(num(obj(raw.resources)[r.resource],0,999));w.collected[r.resource]=Math.floor(Math.max(w.resources[r.resource],num(obj(raw.collected)[r.resource],0,999999)));w.outposts[r.id]=Math.floor(num(obj(raw.outposts)[r.id],0,5));w.shipments[r.id]=Math.floor(num(obj(raw.shipments)[r.id],0,999999));}
 function available(id){const i=regions.findIndex(r=>r.id===id);return i>=0&&(i===0||w.collected[regions[i-1].resource]>=5)}
 if(w.region!=='home'&&!available(w.region))w.region='home';
 function log(text){w.log.push({text,time:w.time});if(w.log.length>40)w.log.shift()}
 function reward(r,q){q=Math.floor(num(q,0,100));w.resources[r.resource]=Math.min(999,w.resources[r.resource]+q);w.collected[r.resource]=Math.min(999999,w.collected[r.resource]+q)}
 function seedScene(r){const index=regions.indexOf(r),nodes=[];
  for(let i=0;i<18;i++){let x,y;if(i<4){x=[-42,44,-92,99][i];y=[126,145,199,224][i]}else{const a=i*2.39996+index*.3,d=240+(i%5)*65;x=Math.round(Math.cos(a)*d);y=Math.round(Math.sin(a)*d)}nodes.push({id:r.id+'-n'+i,x,y,hp:8,maxHp:8,alive:true,remaining:0})}
  const enemies=[];for(let i=0;i<6;i++){const a=i*1.06,d=355+(i%2)*125;enemies.push(makeEnemy(r,i,Math.cos(a)*d,Math.sin(a)*d))}enemies.push(makeEnemy(r,6,0,-530,true));return{nodes,enemies};
 }
 function makeEnemy(r,i,x,y,boss=false){const index=regions.indexOf(r),hp=boss?180+index*35:40+index*8;return{id:r.id+'-e'+i,type:boss?'warden':r.enemy,x,y,homeX:x,homeY:y,hp,maxHp:hp,spd:boss?20:index===0?25:22,dmg:boss?10+index:5+index,anim:0,cool:1,hit:0,dead:false,remaining:0,boss,warning:0}}
 function normalizeScene(r){const fresh=seedScene(r),old=obj(obj(raw.scenes)[r.id]);
  for(const key of ['nodes','enemies']){const source=arr(old[key]);fresh[key]=fresh[key].map(base=>{const s=source.find(n=>n&&n.id===base.id);if(!s)return base;const n={...base};for(const k of ['x','y'])if(Number.isFinite(s[k]))n[k]=clamp(s[k],-630,630);n.hp=num(s.hp,base.hp,base.maxHp);if(key==='nodes'){n.alive=s.alive!==false;n.remaining=num(s.remaining,0,30);if(!n.alive)n.hp=0}else{n.dead=!!s.dead;n.remaining=num(s.remaining,0,75);n.cool=num(s.cool,1,3);n.warning=num(s.warning,0,1);if(n.dead)n.hp=0}return n})}return fresh;
 }
 for(const r of regions)w.scenes[r.id]=normalizeScene(r);
 const workerIds=new Set();state.workers=state.workers.filter(worker=>{if(!worker||workerIds.has(worker.id))return false;workerIds.add(worker.id);delete worker.expeditionId;return true});
 function expeditionCost(id,party){return{food:8+arr(party).length*7+Math.max(0,regions.findIndex(r=>r.id===id))*3}}
 function expeditionDuration(id,party){return Math.max(30,65+Math.max(0,regions.findIndex(r=>r.id===id))*12-arr(party).length*7-w.outposts[id]*3||65)}
 function jobReward(r,party){const L=w.outposts[r.id];return{special:r.resource,quantity:4+party.length*2+L*2,wood:12+L*3,stone:8+L*2,food:5,iron:1,xp:14+L*3}}
 // Rebuild one valid job and its reservations; malformed/orphan flags never strand residents.
 for(const j of arr(raw.expeditions).slice(0,10)){const r=definition(j?.region),party=arr(j?.workers);if(!r||!available(r.id)||typeof j.id!=='string'||!j.id||party.length<1||party.length>3||new Set(party).size!==party.length||!party.every(id=>state.workers.some(worker=>worker.id===id&&!worker.dead)))continue;const duration=num(j.duration,expeditionDuration(r.id,party),240)||60;const remaining=num(j.remaining,duration,duration);const originalReward=jobReward(r,party),savedReward=obj(j.reward);for(const [key,cap] of Object.entries({quantity:20,wood:30,stone:18,food:5,iron:1,xp:29}))originalReward[key]=Math.floor(num(savedReward[key],originalReward[key],cap));const job={id:j.id.slice(0,80),region:r.id,workers:party.slice(),duration,remaining,status:remaining<=0?'ready':'travel',reward:originalReward};w.expeditions.push(job);for(const id of party)state.workers.find(worker=>worker.id===id).expeditionId=job.id;break}
 function dispatch(id,party){const r=definition(id);if(!r||!available(id)||w.expeditions.length||!Array.isArray(party)||party.length<1||party.length>3||new Set(party).size!==party.length)return false;const workers=party.map(id=>state.workers.find(worker=>worker.id===id&&!worker.dead&&!worker.expeditionId));if(workers.some(worker=>!worker))return false;const cost=expeditionCost(id,party);if(!hasCost(cost))return false;const duration=expeditionDuration(id,party),job={id:'trip-'+(++w.serial)+'-'+Math.floor(w.time),region:id,workers:party.slice(),remaining:duration,duration,status:'travel',reward:jobReward(r,party)};pay(cost);w.expeditions.push(job);for(const worker of workers){worker.expeditionId=job.id;worker.targetId=null;worker.state='expedition'}log(r.name+'へ '+workers.length+'人を派遣');save();return true}
 function finishJob(id,claim){const j=w.expeditions.find(j=>j.id===id);if(!j||(claim&&j.status!=='ready'))return false;w.expeditions=w.expeditions.filter(job=>job.id!==id);for(const worker of state.workers)if(worker.expeditionId===id){delete worker.expeditionId;worker.state='idle';if(claim)Citizens.gain(worker,j.reward.xp)}if(claim){reward(definition(j.region),j.reward.quantity);for(const key of ['wood','stone','food'])addRes(key,j.reward[key]);state.iron=Math.min(99999,state.iron+j.reward.iron)}log(definition(j.region).name+(claim?'の遠征報告を受理':'から全員を呼び戻した'));save();return true}
 function outpostCost(id){const r=definition(id);if(!r)return{};const L=w.outposts[id];return{[r.resource]:6+L*6,wood:20+L*22,stone:12+L*18}}
 function upgradeOutpost(id){const r=definition(id);if(!r||!available(id)||w.outposts[id]>=5)return false;const cost=outpostCost(id);if(w.resources[r.resource]<cost[r.resource]||!hasCost(cost))return false;w.resources[r.resource]-=cost[r.resource];pay(cost);w.outposts[id]++;log(r.name+'の前哨地 Lv.'+w.outposts[id]);save();return true}
 function tradeCost(id){const r=definition(id);return r?{[r.resource]:25}:{}}
 function trade(id){const r=definition(id);if(!r||!available(id)||w.tradeCooldown>0||w.resources[r.resource]<25||(state.iron>=99999&&state.renown>=999999))return false;w.resources[r.resource]-=25;state.iron=Math.min(99999,state.iron+1);state.renown=Math.min(999999,state.renown+2);w.shipments[id]=Math.min(999999,w.shipments[id]+1);w.tradeCooldown=30;log(r.resourceName+'25個を出荷 · 鉄1・名声2');toast('出荷完了！ 鉄 +1 / 名声 +2');save();return true}
 function clear(){Pocket.clearInput();autoTarget=null;playerWork=0;fx.length=floats.length=slashes.length=0}
 function visit(id){if(!available(id)||w.region===id||state.player.down>0)return false;if(w.region==='home')w.home={x:state.player.x,y:state.player.y,camX:cam.x,camY:cam.y};w.whistleRemaining=Math.max(w.whistleRemaining,clamp((state.pocket.whistleUntil-Date.now())/1000,0,22));w.region=id;state.player.x=0;state.player.y=140;cam.x=0;cam.y=100;clear();if(!w.visited.includes(id)){w.visited.push(id);log(definition(id).name+'を発見')}save();toast(definition(id).name+' · 奥ほど危険、帰村はいつでも無料');return true}
 function home(){if(w.region==='home')return false;w.region='home';Object.assign(state.player,{x:w.home.x,y:w.home.y,vx:0,vy:0});cam.x=w.home.camX;cam.y=w.home.camY;clear();save();return true}
 function current(){return definition(w.region)||null}
 function scene(){return w.scenes[w.region]}
 function hit(e,amount){if(!e||e.dead)return;e.hp=Math.max(0,e.hp-amount);e.hit=.2;floatText(e.x,e.y-27,'-'+Math.round(amount),'#ffe2a1');fxBurst(e.x,e.y,current().color,5,.8);if(e.hp<=0){e.dead=true;e.remaining=e.boss?75:35;state.stats.kills++;if(e.boss&&!w.bosses.includes(w.region)){w.bosses.push(w.region);reward(current(),12);state.iron=Math.min(99999,state.iron+3);state.renown+=3;log(current().boss+'を撃破！ 特産12・鉄3');toast(current().boss+'、決裁完了！');save()}}}
 function gather(dt){if(input.mag>.2||state.player.down>0){playerWork=0;return}const n=scene().nodes.find(n=>n.alive&&dist(n,state.player)<48);if(!n){playerWork=0;return}playerWork+=dt;if(playerWork>=.52){playerWork=0;state.player.swing=1;const q=1+Math.floor(w.outposts[w.region]/2)+(w.rallyRemaining>0?1:0);reward(current(),q);addRes(current().basic,1+w.outposts[w.region]*.2);n.hp--;if(n.hp<=0){n.alive=false;n.remaining=20}floatText(n.x,n.y-30,'+'+q+' '+current().resourceName,current().color);fxBurst(n.x,n.y,current().color,5,.7);A.sfx(current().basic==='stone'?'mine':'chop')}}
 function combat(){const p=state.player;if(p.down>0||p.attackCd>0)return;const near=scene().enemies.filter(e=>!e.dead&&dist(e,p)<64).sort((a,b)=>dist(a,p)-dist(b,p));if(!near.length)return;p.attackCd=.46;p.swing=1;const mult=window.ChiefShop?.damageMultiplier()||1;hit(near[0],28*mult);if(mult>1)for(const e of near.slice(1,5))hit(e,14*mult);A.sfx('hit')}
 function enemies(dt){const p=state.player;for(const e of scene().enemies){if(e.dead){e.remaining=Math.max(0,e.remaining-dt);if(e.remaining<=0){e.dead=false;e.hp=e.maxHp;e.x=e.homeX;e.y=e.homeY}continue}e.hit=Math.max(0,e.hit-dt);e.cool=Math.max(0,e.cool-dt);e.anim+=dt*3;const d=dist(e,p);if(d>230||Math.hypot(p.x,p.y-140)<125)continue;const range=e.type==='spitter'?98:28;if(d>range){e.x+=(p.x-e.x)/d*e.spd*dt;e.y+=(p.y-e.y)/d*e.spd*dt}else if(e.cool<=0){if(e.boss&&e.warning<=0){e.warning=.65;e.cool=.65;floatText(e.x,e.y-44,'大きな決裁！','#f7b886');continue}e.warning=0;e.cool=e.boss?1.8:1.1;damagePlayer(e.dmg,e)}}}
 function tick(dt){if(Pocket.paused()||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,300);w.time+=dt;w.tradeCooldown=Math.max(0,w.tradeCooldown-dt);w.whistleRemaining=Math.max(0,w.whistleRemaining-dt);if(w.whistleRemaining>0)state.pocket.whistleUntil=Date.now()+w.whistleRemaining*1000;w.rallyRemaining=Math.max(0,w.rallyRemaining-dt);for(const j of w.expeditions)if(j.status==='travel'){j.remaining=Math.max(0,j.remaining-dt);if(j.remaining===0){j.status='ready';log(definition(j.region).name+'の遠征隊が帰還');toast('遠征隊が帰還！ 世界 → 遠征で報告を受け取る');save()}}if(w.region!=='home'){for(const n of scene().nodes)if(!n.alive){n.remaining=Math.max(0,n.remaining-dt);if(n.remaining<=0){n.alive=true;n.hp=n.maxHp}}state.player.x=clamp(state.player.x,-650,650);state.player.y=clamp(state.player.y,-650,650);if(state.player.down>0){state.player.down=0;state.player.hp=Math.ceil(state.player.maxHp*.7);state.player.invuln=2;home();toast('出張先から無事に退避 · HP 70%')}}}
 function whistle(){if(w.region==='home'||Pocket.paused()||state.player.down>0||w.whistleRemaining>0||Date.now()<state.pocket.whistleUntil)return false;w.whistleRemaining=22;w.rallyRemaining=5;state.pocket.whistleUntil=Date.now()+22000;for(const e of scene().enemies)if(!e.dead&&dist(e,state.player)<115){hit(e,12*(window.ChiefShop?.damageMultiplier()||1));const d=Math.max(1,dist(e,state.player));e.x+=(e.x-state.player.x)/d*30;e.y+=(e.y-state.player.y)/d*30}fxBurst(state.player.x,state.player.y,'#ffe7a4',20,1.5);A.sfx('hire');save();return true}
 const visible=(x,y,pad=100)=>sx(x)>-pad&&sx(x)<W+pad&&sy(y)>-pad&&sy(y)<H+pad;
 function drawNodeRegional(n,r){const x=sx(n.x),y=sy(n.y);shadow(x,y,26);if(!n.alive){rect(x-7,y-2,14,3,r.path);return}if(r.id==='forest'){rect(x-4,y-31,8,31,'#715139');rect(x+2,y-42,7,21,'#715139');rect(x-19,y-45,39,17,'#526c47');rect(x-13,y-57,30,16,r.color);rect(x+13,y-31,14,10,'#6d8854');rect(x-2,y-27,2,13,'#a78253');rect(x+4,y-41,2,9,'#aa8658');rect(x-9,y-53,10,3,'#92ae70');rect(x+5,y-46,8,3,'#85a36a');rect(x-16,y-36,7,3,'#688c57');rect(x+17,y-29,5,2,'#9aae72')}else if(r.id==='marsh'){rect(x-3,y-21,6,21,'#b7bba3');rect(x-16,y-26,32,9,'#698f8c');rect(x-10,y-32,21,7,r.color);rect(x-9,y-25,4,3,'#d9ead0');rect(x+7,y-25,3,3,'#d9ead0')}else{poly([[x-18,y-3],[x-13,y-22],[x+4,y-33],[x+18,y-17],[x+14,y]],r.color);poly([[x+4,y-33],[x+18,y-17],[x+14,y],[x+2,y-9]],r.id==='volcano'?'#342b48':'#66838c');rect(x-7,y-19,4,11,'#e9d4a4')}if(w.outposts[r.id]){rect(x+18,y-13,2,13,'#dec89a');rect(x+20,y-13,8,5,r.color)}}
 function drawRegion(){const r=current();ctx.fillStyle=r.ground;ctx.fillRect(0,0,W,H);rect(sx(-30),sy(-620),60,1260,r.path);for(let i=0;i<130;i++){const x=(i*179)%1300-650,y=(i*103)%1300-650;if(!visible(x,y,20))continue;rect(sx(x),sy(y),i%3?3:12,2,i%3?r.color:r.path);if(i%5===0){rect(sx(x)+5,sy(y)-4,2,5,r.color);rect(sx(x)+8,sy(y)-2,2,3,r.color)}}
  // Per-region static terrain landmarks: grove, strata, pools, lava, and docks.
  for(let i=0;i<12;i++){const x=(i%2?1:-1)*(145+(i%3)*130),y=-500+i*95;if(!visible(x,y,130))continue;const px=sx(x),py=sy(y);if(r.id==='forest'){rect(px-5,py-50,10,50,'#594732');poly([[px-33,py-20],[px,py-92],[px+30,py-20]],'#233e32');poly([[px-26,py-42],[px+2,py-108],[px+28,py-42]],'#456246')}else if(r.id==='canyon'){for(let j=0;j<4;j++)rect(px-j*4,py-j*8,73+j*5,8,j%2?'#9e7353':'#bd9368')}else if(r.id==='marsh'){rect(px-42,py-14,86,28,'#263b49');rect(px-31,py-18,63,5,'#6b8c83');rect(px-22,py-3,12,3,r.color)}else if(r.id==='volcano'){poly([[px-65,py-10],[px+20,py-15],[px+60,py+8],[px-35,py+14]],'#b25b47');rect(px-23,py-5,42,3,'#e1aa65')}else{rect(px-50,py-20,100,35,'#346074');for(let j=0;j<5;j++)rect(px-36+j*15,py-15,12,38,'#977b57');rect(px-39,py-14,82,3,'#c0a579')}}
  const items=scene().nodes.filter(n=>visible(n.x,n.y)).map(n=>({y:n.y,paint:()=>drawNodeRegional(n,r)}));for(const e of scene().enemies)if(!e.dead&&visible(e.x,e.y))items.push({y:e.y,paint:()=>{drawEnemy(e);if(e.boss){const x=sx(e.x),y=sy(e.y);rect(x-13,y-48,26,5,'#ebc878');rect(x-13,y-55,4,10,'#ebc878');rect(x-2,y-59,4,12,'#ebc878');rect(x+9,y-55,4,10,'#ebc878');if(e.warning>0){ctx.strokeStyle='#e6b06e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,36,0,Math.PI*2);ctx.stroke()}}}});items.push({y:state.player.y,paint:()=>drawPlayerEntity()});items.sort((a,b)=>a.y-b.y).forEach(item=>item.paint());rect(sx(-37),sy(177),74,4,'#dfd0a0');rect(sx(-2),sy(171),4,24,'#dfd0a0');ctx.fillStyle='#f3e5bb';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText('安全な入口',sx(0),sy(215));ctx.textAlign='start';
 }
 function drawMap(){if(!current())return false;const c=$('pocket-map').getContext('2d'),mx=x=>(x+650)/1300*152,my=y=>(y+650)/1300*134;c.fillStyle=current().ground;c.fillRect(0,0,152,134);c.fillStyle=current().color;for(const n of scene().nodes)if(n.alive)c.fillRect(mx(n.x),my(n.y),3,3);for(const e of scene().enemies)if(!e.dead){c.fillStyle=e.boss?'#ffe294':'#db8271';c.fillRect(mx(e.x),my(e.y),e.boss?5:3,e.boss?5:3)}c.fillStyle='#fff';c.fillRect(mx(state.player.x)-2,my(state.player.y)-2,4,4);return true}
 // Scope legacy worker iteration to present residents. Serial always sees the full roster,
 // including if a legacy combat callback saves during the scoped update.
 let roster=null;const oldSerial=serial;serial=function(){if(!roster)return oldSerial();const present=state.workers;state.workers=roster;try{return oldSerial()}finally{state.workers=present}};
 function residents(fn,args){if(!state.workers.some(worker=>worker.expeditionId))return fn(...args);const all=state.workers;roster=all;state.workers=all.filter(worker=>!worker.expeditionId);try{return fn(...args)}finally{const remaining=new Set(state.workers);state.workers=all.filter(worker=>worker.expeditionId||remaining.has(worker));roster=null}}
 const workers0=updateWorkers;updateWorkers=function(dt){if(w.region==='home')return residents(workers0,[dt])};
 const enemies0=updateEnemies;updateEnemies=function(dt){return w.region==='home'?residents(enemies0,[dt]):enemies(dt)};
 const human0=updateHumanLife;updateHumanLife=function(dt){if(w.region==='home')residents(human0,[dt]);else{state.player.attackCd=Math.max(0,(state.player.attackCd||0)-dt);state.player.invuln=Math.max(0,(state.player.invuln||0)-dt);Chief.tick(dt)}tick(dt)};
 const gather0=playerGather;playerGather=function(dt){return w.region==='home'?gather0(dt):gather(dt)};
 const combat0=playerAutoCombat;playerAutoCombat=function(){return w.region==='home'?combat0():combat()};
 const phase0=phaseTick;phaseTick=function(dt){if(w.region==='home')phase0(dt)};
 const collision0=wallCollision;wallCollision=function(...args){return w.region==='home'?collision0(...args):false};
 const draw0=draw;draw=function(){return w.region==='home'?draw0():drawRegion()};
 const workerDraw0=drawWorkerEntity;drawWorkerEntity=function(worker){if(!worker.expeditionId)return workerDraw0(worker)};
 const damageWorker0=damageWorker;damageWorker=function(worker,...args){if(!worker.expeditionId)return damageWorker0(worker,...args)};
 for(const action of ['train','reassign']){const old=Citizens[action];Citizens[action]=function(id,...args){if(state.workers.some(worker=>worker.id===id&&worker.expeditionId))return false;return old(id,...args)}}
 if(w.region!=='home'){cam.x=state.player.x;cam.y=state.player.y-40;clear()}
 return{get state(){return w},get away(){return w.region!=='home'},regions,current,available,visit,home,tick,drawMap,whistle,dispatch,claimExpedition:id=>finishJob(id,true),cancelExpedition:id=>finishJob(id,false),upgradeOutpost,outpostCost,trade,tradeCost,expeditionCost,expeditionDuration,hasResident:id=>(roster||state.workers).some(worker=>worker.id===id&&!worker.dead)||(state.chief?.crew?.retired||[]).some(worker=>worker.id===id)};
})();window.WorldGame=WorldGame;
