'use strict';
/* Small, observed encounters; no random offscreen friendships. */
const VillageSocial=(()=>{
 const pools={
 work:[['{b}、この石に名前をつけた。','{a}、ペットは倉庫に納品できないよ。'],['木目を読んだら「休め」って。','{a}、それ昨日も言われてた木だね。'],['同じ持ち場だと道具の音が揃うね。','{a}、休む間も揃えよう。'],['採った木、村長像になるのかな。','{a}、本人以外は注文してないはず。']],
 cargo:[['{b}、肩が残業代を請求してる。','{a}、右肩と左肩、別会計なの？'],['背負い籠が私より出世しそう。','{a}、荷物部長って呼んでおこう。'],['これを届けたらもう一往復だ。','{a}、帰り道の石に気をつけて。'],['{b}、荷紐が今日の命綱だよ。','{a}、結び目にもお礼を言おう。']],
 full:[['倉庫がいっぱい。肩が仮設倉庫だ。','{a}、屋根まで載せられる前に休もう。'],['{b}、この荷物の席、空いてる？','{a}、立ち見まで満員みたい。'],['棚が空くまでここで待とう。','{a}、採った分はなくさず持っておこう。'],['荷物が「まだですか」って顔してる。','{a}、石の顔はいつもそうだよ。']],
 delivery:[['{b}、薪の領収書は木に書く？','{a}、その領収書も薪になるよ。'],['空の籠、重さゼロで満点だ。','{a}、中身ゼロの報告書とは違うね。'],['採った分、ぜんぶ数えて渡した。','{a}、帳簿にも君の仕事が残るね。'],['石を納品した。拍手がほしい。','{a}、石の方に？ 君の方に？']],
 morning:[['{b}、朝礼を夢の中で済ませた。','{a}、出席簿が枕だったんだね。'],['道具も目を覚ましたみたい。','{a}、まずは軽い仕事から。'],['朝ごはんの湯気がまだ見える。','{a}、そのうち薪を足しておこう。'],['{b}、太陽って毎日出勤するね。','{a}、昼寝派から苦情が来そう。']],
 night:[['{b}、門の灯りが見えてきた。','{a}、今日の荷は明日でも届けられる。'],['夜勤を星空鑑賞って呼んでみた。','{a}、斧を持つ観客は珍しいね。'],['枕が私の帰宅を待っている。','{a}、村でいちばん熱心な上司だね。'],['仕事の音が、もう虫の声だ。','{a}、道具も一晩眠らせよう。']],
 danger:[['門の外が少し騒がしかったね。','{a}、灯りのある道を使おう。'],['{b}、敵にも入村申請が要るよね。','{a}、受付をする前に門を閉めよう。'],['今日は遠い木を残しておこう。','{a}、帰れることがいちばんだ。'],['{b}、逃げ足だけ査定してほしい。','{a}、全員で帰れたら満点だよ。']],
 friendship:[['{b}と組むと、道が短く感じる。','{a}、話す分だけ足も進むからかな。'],['君の足音、もう覚えたよ。','{a}、お腹の音は秘密にしてね。'],['次の休憩、一緒にお茶にしよう。','{a}、荷を下ろす楽しみが増えたね。'],['{b}、親友の任命書を作った。','{a}、ごはん粒の印鑑でいい？']],
 rivalry:[['{b}、今日は私の束の方が大きい。','{a}、大きさより運び方で勝負ね。'],['{b}、私の石は角まで真面目だ。','{a}、性格の採点は石に聞いてよ。'],['先に倉庫へ着くのはどっちかな。','{a}、走って落としたら負けだよ。'],['今日の働き者、私に一票。','{a}、その投票箱も私が運んだよ。']],
 return:[['{b}、村の道、久しぶりだね。','{a}、留守の間もここを守ったよ。'],['遠くでもこの門を思い出した。','{a}、帰った荷は急がず下ろしてね。'],['{b}、旅先にも会議があった。','{a}、世界って意外と狭いんだね。'],['旅の話は荷物よりたくさんある。','{a}、話の方は倉庫に入れないでね。']]
 };
 const num=(v,max=1e9)=>Number.isFinite(v)?clamp(v,0,max):0,raw=Chief.state.social||{};
 const s=Chief.state.social={time:num(raw.time),nextAt:num(raw.nextAt),serial:Math.floor(num(raw.serial)),cooldowns:{},relations:{},journal:[],used:{},active:null};
 const valid=id=>typeof id==='string'&&WorldGame.hasResident(id);
 for(const [id,t] of Object.entries(raw.cooldowns||{}).slice(0,200))if(valid(id))s.cooldowns[id]=Math.min(s.time+28,num(t));
 for(const [id,rels] of Object.entries(raw.relations||{}).slice(0,200))if(valid(id))s.relations[id]=(Array.isArray(rels)?rels:[]).filter(r=>r&&r.id!==id&&valid(r.id)).slice(0,3).map(r=>({id:r.id,score:Number.isFinite(r.score)?clamp(r.score,-10,10):0,at:num(r.at)}));
 s.journal=(Array.isArray(raw.journal)?raw.journal:[]).filter(e=>e&&typeof e.text==='string').slice(-30).map(e=>({id:String(e.id||'entry').slice(0,80),time:num(e.time),workerIds:(Array.isArray(e.workerIds)?e.workerIds:[]).filter(id=>typeof id==='string').slice(0,2),type:String(e.type||'conversation').slice(0,24),text:e.text.slice(0,160)}));
 for(const context of Object.keys(pools))s.used[context]=(Array.isArray(raw.used?.[context])?raw.used[context]:[]).filter(i=>Number.isInteger(i)&&i>=0&&i<pools[context].length).slice(0,pools[context].length);
 let previousAway=new Set(state.workers.filter(w=>w.expeditionId).map(w=>w.id)),phase=state.phase,lastEncounter=new Map(),pending=[];
 const relationFor=id=>(s.relations[id]||[]).map(r=>({...r}));
 const journalFor=id=>s.journal.filter(e=>e.workerIds.includes(id));
 function journal(type,a,b,text){s.journal.push({id:'social-'+(++s.serial),time:s.time,workerIds:[a.id,...(b?[b.id]:[])],type,text});if(s.journal.length>30)s.journal.shift()}
 function eligible(w){return w&&!w.dead&&!w.hiddenAtHome&&!w.expeditionId&&!['fighting','combat'].includes(w.state)&&!state.enemies.some(e=>!e.dead&&dist(w,e)<95)}
 function available(a,b){return !WorldGame.away&&!Pocket.paused()&&!s.active&&s.time>=s.nextAt&&a!==b&&eligible(a)&&eligible(b)&&dist(a,b)<65&&s.time>=(s.cooldowns[a.id]||0)&&s.time>=(s.cooldowns[b.id]||0)}
 function line(w,text){w.say=text;w.sayUntil=Pocket.clock+3;if(dist(w,state.player)<170)A.voice(Citizens.ensure(w).trait,false)}
 function startConversation(a,b,context='work'){if(!available(a,b))return false;if(!pools[context])context='work';let used=s.used[context];if(used.length>=pools[context].length)used=s.used[context]=[];const index=pools[context].findIndex((_,i)=>!used.includes(i));used.push(index);const names={a:Citizens.ensure(a).name,b:Citizens.ensure(b).name},lines=pools[context][index].map(t=>t.replace(/\{([ab])\}/g,(_,k)=>names[k]));s.nextAt=s.time+12;s.cooldowns[a.id]=s.cooldowns[b.id]=s.time+28;s.active={a:a.id,b:b.id,context,reply:lines[1],at:s.time+3,end:s.time+6,replied:false};line(a,lines[0]);journal('conversation',a,b,names.a+'「'+lines[0]+'」 '+names.b+'「'+lines[1]+'」');Logistics.emit('conversation',a,{otherId:b.id,context,text:lines[0],reply:lines[1]});return true}
 function relate(a,b,context){if(!eligible(a)||!eligible(b)||dist(a,b)>65)return;const key=[a.id,b.id].sort().join('|');if(s.time-(lastEncounter.get(key)??-100)<24)return;lastEncounter.set(key,s.time);if(lastEncounter.size>600)lastEncounter.delete(lastEncounter.keys().next().value);const rivalry=context==='work'&&Citizens.ensure(a).trait===0&&Citizens.ensure(b).trait===3||context==='work'&&Citizens.ensure(b).trait===0&&Citizens.ensure(a).trait===3,delta=rivalry?-1:1;
  for(const [w,other] of [[a,b],[b,a]]){const list=s.relations[w.id]||(s.relations[w.id]=[]);let rel=list.find(r=>r.id===other.id);if(!rel){if(list.length>=3)list.splice(list.reduce((best,r,i)=>list[best].at>r.at?i:best,0),1);list.push(rel={id:other.id,score:0,at:s.time})}rel.score=clamp(rel.score+delta,-10,10);rel.at=s.time;const life=Council.ensure(w);life.friendId=other.id;life.relation=rel.score;life.mood=clamp(life.mood+(rel.score>=3?.5:rel.score<=-3?-.3:0),0,100)}journal('relationship',a,b,Citizens.ensure(a).name+'と'+Citizens.ensure(b).name+(rivalry?'、仕事の腕を競った。':'、仕事の息が合った。'));Logistics.emit('relationship',a,{otherId:b.id,context,amount:delta,total:s.relations[a.id].find(r=>r.id===b.id).score})}
 window.addEventListener('village-event',e=>{if(WorldGame.away||!['delivery','harvest'].includes(e.detail?.type))return;const a=state.workers.find(w=>w.id===e.detail.workerId);if(!eligible(a))return;const b=state.workers.find(w=>w!==a&&eligible(w)&&dist(a,w)<60&&(e.detail.type==='delivery'||w.targetId===a.targetId&&w.state==='working'));if(b){relate(a,b,e.detail.type==='delivery'?'delivery':'work');pending.push({a:a.id,b:b.id,context:e.detail.type==='delivery'?'delivery':'work'});pending=pending.slice(-12)}});
 function tick(dt){if(WorldGame.away||Pocket.paused()||!Number.isFinite(dt)||dt<=0)return;s.time+=Math.min(dt,300);if(s.active){const a=state.workers.find(w=>w.id===s.active.a),b=state.workers.find(w=>w.id===s.active.b);if(!eligible(a)||!eligible(b)||dist(a,b)>85||s.time>=s.active.end)s.active=null;else if(!s.active.replied&&s.time>=s.active.at){a.sayUntil=0;line(b,s.active.reply);s.active.replied=true}}
  const nowAway=new Set(state.workers.filter(w=>w.expeditionId).map(w=>w.id)),residents=state.workers.filter(eligible);for(const id of previousAway)if(!nowAway.has(id)){const a=residents.find(w=>w.id===id),b=residents.find(w=>w.id!==id&&a&&dist(a,w)<65);if(a&&b)pending.push({a:id,b:b.id,context:'return'})}previousAway=nowAway;
  if(!s.active){const queued=pending.shift();if(queued){const a=residents.find(w=>w.id===queued.a),b=residents.find(w=>w.id===queued.b);if(a&&b)startConversation(a,b,queued.context)}if(!s.active)for(let i=0;i<residents.length;i++){const a=residents[i],b=residents.find((w,j)=>j>i&&dist(a,w)<60);if(!b)continue;const rel=(s.relations[a.id]||[]).find(r=>r.id===b.id)?.score||0;const context=a.state==='storage-full'?'full':a.cargoMode==='returning'?'cargo':phase!==state.phase&&['dawn','day'].includes(state.phase)?'morning':['night','dusk'].includes(state.phase)?'night':state.enemies.some(e=>!e.dead)?'danger':rel>=3?'friendship':rel<=-3?'rivalry':'work';if(startConversation(a,b,context))break}}phase=state.phase;
  // Keep expedition relationships: hasResident consults World's complete roster.
  for(const id of Object.keys(s.relations))if(!valid(id))delete s.relations[id];else s.relations[id]=s.relations[id].filter(r=>valid(r.id));for(const id of Object.keys(s.cooldowns))if(!valid(id))delete s.cooldowns[id];
 }
 const human=updateHumanLife;updateHumanLife=function(dt){human(dt);tick(dt)};
 return{state:s,tick,relationFor,journalFor,startConversation,report:()=>({relations:s.relations,journal:s.journal,active:s.active,lineCount:Object.values(pools).reduce((n,p)=>n+p.length*2,0),exchangeCount:Object.values(pools).reduce((n,p)=>n+p.length,0)})};
})();window.VillageSocial=VillageSocial;
