
(()=>{"use strict";const c=document.getElementById("c"),x=c.getContext("2d",{alpha:false}),$=i=>document.getElementById(i);let W=innerWidth,H=innerHeight,D=1,last=performance.now(),cam={x:0,y:0},spd=1,fever=0,shake=0,T=0;const S={gold:100,wood:30,food:18,lv:1},P={x:0,y:120,dir:1,walk:0},parts=[],floats=[],npcs=[];const B=[{id:"guild",x:0,y:0,w:154,h:104,n:"GUILD HALL"},{id:"inn",x:-230,y:110,w:106,h:78,n:"INN"},{id:"quest",x:232,y:92,w:88,h:66,n:"QUEST"},{id:"forge",x:205,y:-135,w:102,h:74,n:"FORGE"},{id:"store",x:-210,y:-140,w:96,h:70,n:"MARKET"},{id:"tower",x:0,y:-205,w:76,h:102,n:"WATCH"}];
function resize(){D=.5;W=innerWidth;H=innerHeight;c.width=Math.ceil(W*D);c.height=Math.ceil(H*D);x.setTransform(D,0,0,D,0,0);x.imageSmoothingEnabled=false}addEventListener("resize",resize);resize();const rnd=(a,b)=>a+Math.random()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),sx=v=>W/2+v-cam.x,sy=v=>H/2+v-cam.y;function fmt(n){if(n>=1e9)return(n/1e9).toFixed(2)+"B";if(n>=1e6)return(n/1e6).toFixed(2)+"M";if(n>=1e3)return(n/1e3).toFixed(1)+"K";return Math.floor(n)}function msg(s){const d=document.createElement("div");d.className="msg";d.textContent=s;$("log").appendChild(d);setTimeout(()=>d.remove(),3050)}function r(a,b,w,h,col){x.fillStyle=col;x.fillRect(Math.round(a),Math.round(b),Math.round(w),Math.round(h))}function ln(a,b,c1,d,col,w=1){x.strokeStyle=col;x.lineWidth=w;x.beginPath();x.moveTo(a,b);x.lineTo(c1,d);x.stroke()}function tx(s,a,b,z=10,col="#fff"){x.font=`800 ${z}px ui-monospace,monospace`;x.textAlign="center";x.fillStyle="#000b";x.fillText(s,a+1,b+1);x.fillStyle=col;x.fillText(s,a,b)}function poly(p,col){x.fillStyle=col;x.beginPath();x.moveTo(...p[0]);for(let i=1;i<p.length;i++)x.lineTo(...p[i]);x.closePath();x.fill()}function sh(a,b,rx,ry,o=.3){x.fillStyle=`rgba(0,0,0,${o})`;x.beginPath();x.ellipse(a,b,rx,ry,0,0,Math.PI*2);x.fill()}
function choose(n){const b=B[1+((Math.random()*(B.length-1))|0)];n.tx=Math.round(b.x/24)*24;n.ty=Math.round((b.y+b.h/2+26)/24)*24;n.route=null;n.phase=0;n.carry=false}
function add(){const pal=["#b64f43","#4e76a4","#71834f","#8e5b9e","#bd9240","#9d6752","#4b8b87"];let n={x:0,y:96,tx:0,ty:0,phase:0,v:rnd(20,31),c:pal[(Math.random()*pal.length)|0],bob:rnd(0,6.28),carry:false};choose(n);npcs.push(n)}for(let i=0;i<10;i++){add();const n=npcs[i],b=B[1+i%5];n.x=Math.round((b.x+(i>=5?24:-24))/24)*24;n.y=Math.round((b.y+b.h/2+26)/24)*24;}
function fire(){let a=sx(0),b=sy(82);sh(a,b+11,22,7,.48);r(a-18,b+8,36,5,"#5a3920");let q=T*.012;x.fillStyle="#ff7432";x.beginPath();x.moveTo(a-12,b+7);x.quadraticCurveTo(a-17,b-11,a+Math.sin(q)*4,b-27);x.quadraticCurveTo(a+19,b-8,a+10,b+8);x.fill();x.fillStyle="#ffd368";x.beginPath();x.moveTo(a-6,b+7);x.quadraticCurveTo(a-5,b-6,a+1,b-16);x.quadraticCurveTo(a+9,b-3,a+5,b+7);x.fill();if(Math.random()<.28)parts.push({x:rnd(-6,6),y:70,vx:rnd(-4,4),vy:rnd(-25,-12),life:rnd(.5,1),c:"#ffbf61",s:rnd(1,3)})}
function atmosphere(){x.globalAlpha=.09;for(let i=0;i<4;i++){let y=H*.25+i*100+Math.sin(T*.00035+i)*22,g=x.createLinearGradient(0,y-35,0,y+35);g.addColorStop(0,"transparent");g.addColorStop(.5,"#c8d3ce");g.addColorStop(1,"transparent");x.fillStyle=g;x.fillRect(0,y-38,W,76)}x.globalAlpha=1;let a=sx(0),b=sy(80),g=x.createRadialGradient(a,b,10,a,b,170);g.addColorStop(0,"rgba(255,185,87,.26)");g.addColorStop(.5,"rgba(255,109,39,.07)");g.addColorStop(1,"rgba(0,0,0,0)");x.fillStyle=g;x.fillRect(a-180,b-180,360,360);let v=x.createRadialGradient(W/2,H/2,Math.min(W,H)*.2,W/2,H/2,Math.max(W,H)*.72);v.addColorStop(0,"transparent");v.addColorStop(1,"rgba(0,0,0,.55)");x.fillStyle=v;x.fillRect(0,0,W,H)}
function update(dt){T+=dt*1000;let m=spd*(fever>0?2.6:1),d=dt*m;if(fever>0){fever=Math.max(0,fever-dt);if(fever===0)GuildAudio.setMood("day")}updateInput(dt);cam.x+=(P.x-cam.x)*Math.min(1,dt*3.2);cam.y+=(P.y-55-cam.y)*Math.min(1,dt*3.2);S.gold+=d*(.42+S.lv*.17+npcs.length*.035);S.wood+=d*(.024+S.lv*.004);S.food+=d*(.032+S.lv*.005);npcs.forEach(n=>{n.bob+=dt*7*spd;if(!n.route)n.route=findRoute(n.x,n.y,n.tx,n.ty);const target=n.route.length?n.route[0]:{x:n.tx,y:n.ty};let dx=target.x-n.x,dy=target.y-n.y,l=Math.hypot(dx,dy)||1,v=Math.min(l,n.v*d);n.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"down":"up");n.x+=dx/l*v;n.y+=dy/l*v;if(l<2){n.x=target.x;n.y=target.y;if(n.route.length>1){n.route.shift();return}n.route=null;if(n.phase===0){n.phase=1;n.carry=true;n.tx=[-48,-24,0,24,48][(Math.random()*5)|0];n.ty=96}else{n.phase=0;n.carry=false;let q=(9+S.lv*3)*(fever>0?2:1);S.gold+=q;S.wood+=rnd(.2,.8);S.food+=rnd(.1,.5);floats.push({x:n.x,y:n.y,s:"+"+Math.floor(q)+"G",life:1.2});if(Math.random()<.12)msg("Quest complete  •  +"+Math.floor(q)+" Gold");coin();choose(n)}}})}
function render(dt){x.save();if(shake>0){x.translate(rnd(-shake,shake),rnd(-shake,shake));shake*=.9}ground();drawDestination();const drawables=[...GuildGraphics.getPropDrawables({width:W,height:H,cam,time:T,ctx:x}),...B.map(b=>({y:b.y+b.h/2,draw:()=>building(b)})),...npcs.map(n=>({y:n.y+14,draw:()=>npc(n)})),{y:P.y+14,draw:player},{y:94,draw:fire}];drawables.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());for(let i=parts.length-1;i>=0;i--){let p=parts[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0){parts.splice(i,1);continue}x.globalAlpha=cl(p.life,0,1);r(sx(p.x),sy(p.y),p.s,p.s,p.c);x.globalAlpha=1}for(let i=floats.length-1;i>=0;i--){let f=floats[i];f.y-=18*dt;f.life-=dt;if(f.life<=0){floats.splice(i,1);continue}x.globalAlpha=cl(f.life,0,1);tx(f.s,sx(f.x),sy(f.y),10,"#ffe08e");x.globalAlpha=1}atmosphere();x.restore();$("gold").textContent=fmt(S.gold);$("wood").textContent=fmt(S.wood);$("food").textContent=fmt(S.food);$("level").textContent="Lv."+S.lv;$("cost").textContent=fmt(upgradeCost())+"G";$("roster").textContent=npcs.length+" / 10";$("fever-time").textContent=fever>0?Math.ceil(fever)+"秒":"20 sec"}
function loop(now){let dt=Math.min(.034,(now-last)/1000);last=now;update(dt);render(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function tone(){GuildAudio.sfx("confirm")}function coin(){GuildAudio.sfx("coin")}function ups(){GuildAudio.sfx("upgrade")}
$("sound").onclick=async()=>{try{await GuildAudio.toggle();$("sound").textContent=GuildAudio.isMuted?"♪ OFF":"♪ ON";$("sound").setAttribute("aria-pressed",String(!GuildAudio.isMuted));}catch(e){msg("音声を開始できませんでした｜もう一度 ♪ を押してください")}};
$("speed").onclick=()=>{let a=[1,2,5,10],i=a.indexOf(spd);spd=a[(i+1)%a.length];$("speed").textContent="×"+spd;msg("World speed ×"+spd)};$("hire").onclick=()=>{if(S.gold<60){msg("Gold不足  •  60G 必要");return}if(npcs.length>=10){msg("冒険者は10人まで｜ギルド強化で街を育てよう");return}S.gold-=60;add();tone(330,.08,"square",.04);tone(494,.13,"triangle",.05,.08);msg("New adventurer joined  •  "+npcs.length+" total")};$("upgrade").onclick=()=>{let cost=upgradeCost();if(S.gold<cost){msg("Gold不足  •  "+fmt(cost)+"G 必要");return}S.gold-=cost;S.lv++;shake=7;let q=0;for(let i=0;i<35;i++)parts.push({x:rnd(-70,70),y:rnd(-50,50),vx:rnd(-65,65),vy:rnd(-85,-20),life:rnd(.5,1.2),c:Math.random()<.5?"#ffd36d":"#ff884d",s:rnd(2,5)});ups();msg("GUILD LEVEL "+S.lv+"  •  街の設備が成長した")};$("fever").onclick=()=>{if(fever>0){msg("FEVERは発動中です");return}fever=20;GuildAudio.setMood("fever");shake=3;for(let i=0;i<45;i++)parts.push({x:rnd(-300,300),y:rnd(-220,260),vx:rnd(-15,15),vy:rnd(-40,-8),life:rnd(.8,1.8),c:"#ffd56d",s:rnd(1,4)});tone(220,.16,"sawtooth",.035);tone(440,.2,"triangle",.05,.12);tone(880,.32,"triangle",.045,.25);msg("FEVER  •  Production ×2.6  •  20 sec")};
// Coordinator lane: discrete input, validated persistence, collision, menu hooks.
function upgradeCost(){return Math.min(1e12,Math.floor(120*Math.pow(1.72,Math.min(48,S.lv-1))))}
const GRID=24, LIMIT=10, SAVE_KEY="guild-infinity-save-v1", STEP_TIME=.14;
const held=new Map(), keyDirs={ArrowUp:"up",ArrowDown:"down",ArrowLeft:"left",ArrowRight:"right",w:"up",s:"down",a:"left",d:"right"};
let pendingDir=null,menuOpen=false,activeStep=null,saveElapsed=0,lastSaved=0,autoRoute=[],destination=null,arrivalAction=false,fieldPointer=null,lastDrag=0;
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};P.dir="down";
function canWalk(wx,wy){if(!Number.isFinite(wx)||!Number.isFinite(wy))return false;if(wx< -408||wx>408||wy< -288||wy>336)return false;if(GuildGraphics.isTerrainBlocked(wx,wy))return false;return !B.some(b=>wx>b.x-b.w/2-8&&wx<b.x+b.w/2+14&&wy+14>b.y-b.h/2+28&&wy+14<b.y+b.h/2+10)}
function move(dir){if(menuOpen||!dirs[dir])return false;autoRoute=[];destination=null;pendingDir=dir;return true}
function clearInput(){held.clear();pendingDir=null;autoRoute=[];destination=null;arrivalAction=false;fieldPointer=null;document.querySelectorAll(".pressed").forEach(e=>e.classList.remove("pressed"))}
function updateInput(dt){
  saveElapsed+=dt;if(saveElapsed>=15){saveElapsed=0;save()}
  if(activeStep){activeStep.t=Math.min(STEP_TIME,activeStep.t+dt);const f=activeStep.t/STEP_TIME;P.x=activeStep.x+activeStep.dx*f;P.y=activeStep.y+activeStep.dy*f;P.walk+=dt*19;if(f>=1){P.x=activeStep.x+activeStep.dx;P.y=activeStep.y+activeStep.dy;activeStep=null}}
  if(menuOpen)return;
  if(!activeStep){let dir=pendingDir||Array.from(held.values()).at(-1);pendingDir=null;if(dir){autoRoute=[];destination=null}else{while(autoRoute.length&&autoRoute[0].x===P.x&&autoRoute[0].y===P.y)autoRoute.shift();if(autoRoute.length){const target=autoRoute[0];dir=target.x>P.x?"right":target.x<P.x?"left":target.y>P.y?"down":"up"}else if(destination){destination=null;if(arrivalAction){arrivalAction=false;action("A")}}}if(dir){P.dir=dir;const [dx,dy]=dirs[dir],nx=Math.round(P.x/GRID)*GRID+dx*GRID,ny=Math.round(P.y/GRID)*GRID+dy*GRID;if(canWalk(nx,ny)){activeStep={x:P.x,y:P.y,dx:nx-P.x,dy:ny-P.y,t:0};GuildAudio.sfx("step")}else if(!held.size)GuildAudio.sfx("cancel")}}
}
function findRoute(px,py,tx,ty){
 const snap=v=>Math.round(v/GRID)*GRID;let start={x:snap(px),y:snap(py)};const goal={x:snap(tx),y:snap(ty)};
 if(!canWalk(start.x,start.y)){for(let rad=1;rad<5;rad++){let found=false;for(let dx=-rad;dx<=rad&&!found;dx++)for(let dy=-rad;dy<=rad&&!found;dy++){const nx=start.x+dx*GRID,ny=start.y+dy*GRID;if(canWalk(nx,ny)){start={x:nx,y:ny};found=true}}if(found)break}}
 const key=n=>n.x+","+n.y,queue=[{...start,g:0,path:[start]}],best=new Map([[key(start),0]]);
 for(let iter=0;queue.length&&iter<1200;iter++){queue.sort((a,b)=>(a.g+Math.abs(a.x-goal.x)+Math.abs(a.y-goal.y))-(b.g+Math.abs(b.x-goal.x)+Math.abs(b.y-goal.y)));const n=queue.shift();if(n.x===goal.x&&n.y===goal.y)return n.path;for(const [dx,dy]of Object.values(dirs)){const next={x:n.x+dx*GRID,y:n.y+dy*GRID},k=key(next),g=n.g+GRID;if(!canWalk(next.x,next.y)||g>=(best.get(k)??Infinity))continue;best.set(k,g);queue.push({...next,g,path:[...n.path,next]})}}
 return [start];
}
function ground(){GuildGraphics.drawTerrain(x,{width:W,height:H,cam,time:T})}
function building(b){GuildGraphics.drawBuilding(x,{...b,x:sx(b.x),y:sy(b.y)},S.lv,T)}
function npc(n){GuildGraphics.drawActor(x,{x:sx(n.x),y:sy(n.y),dir:n.dir||"down",frame:Math.floor(n.bob*1.1)%4,color:n.c,isPlayer:false,carry:n.carry})}
function player(){GuildGraphics.drawActor(x,{x:sx(P.x),y:sy(P.y),dir:P.dir,frame:activeStep?Math.floor(P.walk)%4:0,color:"#7595a6",isPlayer:true,carry:false})}
function setMenu(open){menuOpen=open;clearInput();$("menu").hidden=!open;if(open){$("menu-status").textContent="ギルド Lv."+S.lv+"　冒険者 "+npcs.length+" / 10";$("menu-close").focus()}else $("action-X").focus();GuildAudio.sfx(open?"confirm":"cancel")}
function action(button){if(window.GUILD_INPUT&&typeof window.GUILD_INPUT["on"+button]==="function"&&window.GUILD_INPUT["on"+button]({x:P.x,y:P.y,face:P.dir})===true)return true;window.dispatchEvent(new CustomEvent("guild:button",{detail:{button,player:{x:P.x,y:P.y,face:P.dir}}}));document.dispatchEvent(new CustomEvent("guild:action",{detail:{button,player:{x:P.x,y:P.y,dir:P.dir},menuOpen}}));
  if(button==="X"){setMenu(!menuOpen);return true}if(button==="B"){if(menuOpen)setMenu(false);else{clearInput();msg("行きたい場所をタップ｜建物をタップして調べる");GuildAudio.sfx("cancel")}return true}
  if(menuOpen)return false;
  if(button==="Y"){msg("GUILD Lv."+S.lv+"｜冒険者 "+npcs.length+"人｜自動クエスト稼働中");GuildAudio.sfx("confirm");return true}
  if(button==="A"){const b=B.map(b=>({b,d:Math.hypot(P.x-b.x,P.y-(b.y+b.h/2+24))})).sort((a,b)=>a.d-b.d)[0];GuildAudio.sfx("confirm");if(b.d<120){const text={guild:"ギルドホール｜設備を強化すると生産力と建築が育つ",inn:"宿屋｜旅を終えた冒険者の帰る場所",quest:"依頼所｜冒険者は仕事を受け、資源を持ち帰る",forge:"鍛冶場｜ギルドの成長に合わせて設備が充実",store:"市場｜街の暮らしを支える交易の拠点",tower:"見張り塔｜この街と遠くの旅路を見守る"};msg(text[b.b.id])}else msg("建物をタップして調べる｜X でギルド台帳");return true}return false}
function touchMove(wx,wy){if(menuOpen||!Number.isFinite(wx)||!Number.isFinite(wy))return false;let gx=Math.round(wx/GRID)*GRID,gy=Math.round(wy/GRID)*GRID;arrivalAction=false;
 const hit=B.find(b=>wx>b.x-b.w/2-12&&wx<b.x+b.w/2+20&&wy>b.y-b.h/2-20&&wy<b.y+b.h/2+16);
 if(hit){gx=Math.round(hit.x/GRID)*GRID;gy=Math.round((hit.y+hit.h/2+26)/GRID)*GRID;arrivalAction=true}
 if(!canWalk(gx,gy)){GuildAudio.sfx("cancel");return false}
 const start=activeStep?{x:activeStep.x+activeStep.dx,y:activeStep.y+activeStep.dy}:P,path=findRoute(start.x,start.y,gx,gy),last=path.at(-1);
 if(!last||last.x!==gx||last.y!==gy){GuildAudio.sfx("cancel");return false}held.clear();pendingDir=null;autoRoute=path;destination={x:gx,y:gy};return true}
 function drawDestination(){if(!destination)return;const a=Math.round(sx(destination.x)),b=Math.round(sy(destination.y))+12;x.strokeStyle="#f1ce83";x.lineWidth=2;x.strokeRect(a-8,b-5,16,10);r(a-2,b-1,4,2,"#f7d497")}
 function setTouchTarget(e){touchMove(e.clientX-W/2+cam.x,e.clientY-H/2+cam.y)}
 c.addEventListener("pointerdown",e=>{if(menuOpen||fieldPointer!==null)return;e.preventDefault();fieldPointer=e.pointerId;lastDrag=performance.now();try{c.setPointerCapture(e.pointerId)}catch(_){}setTouchTarget(e)});
 c.addEventListener("pointermove",e=>{if(e.pointerId!==fieldPointer||performance.now()-lastDrag<85)return;lastDrag=performance.now();setTouchTarget(e)});
 c.addEventListener("pointerup",e=>{if(e.pointerId===fieldPointer)fieldPointer=null});
 c.addEventListener("pointercancel",e=>{if(e.pointerId===fieldPointer){fieldPointer=null;clearInput()}});
 c.addEventListener("lostpointercapture",e=>{if(e.pointerId===fieldPointer)fieldPointer=null});
 document.querySelectorAll("[data-dir]").forEach(el=>{el.addEventListener("pointerdown",e=>{e.preventDefault();if(menuOpen)return;try{el.setPointerCapture(e.pointerId)}catch(_){};held.set("pointer"+e.pointerId,el.dataset.dir);pendingDir=el.dataset.dir;el.classList.add("pressed")});const release=e=>{held.delete("pointer"+e.pointerId);el.classList.remove("pressed")};el.addEventListener("pointerup",release);el.addEventListener("pointercancel",release);el.addEventListener("lostpointercapture",release)});
document.querySelectorAll("[data-action]").forEach(el=>{el.addEventListener("pointerdown",e=>{e.preventDefault();try{el.setPointerCapture(e.pointerId)}catch(_){};el.classList.add("pressed");action(el.dataset.action)});const release=()=>el.classList.remove("pressed");el.addEventListener("pointerup",release);el.addEventListener("pointercancel",release);el.addEventListener("lostpointercapture",release)});
addEventListener("keydown",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key,dir=keyDirs[k];if(dir){e.preventDefault();if(!e.repeat&&!menuOpen){held.set("key"+k,dir);pendingDir=dir}return}const a={" ":"A",Enter:"A",Escape:"B",Backspace:"B",x:"X",y:"Y"}[k];if(a){e.preventDefault();if(!e.repeat)action(a)}});
addEventListener("keyup",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(keyDirs[k]){e.preventDefault();held.delete("key"+k)}});
addEventListener("blur",clearInput);document.addEventListener("visibilitychange",()=>{clearInput();last=performance.now();if(document.hidden){save();GuildAudio.pause()}else GuildAudio.resume()});addEventListener("pagehide",()=>{clearInput();save()});
function stateSnapshot(){return {resources:{...S},player:{x:P.x,y:P.y,dir:P.dir},npcs:npcs.length,speed:spd,menuOpen,fever,worldGridSize:GRID,lastSaved,destination:destination?{...destination}:null}}
function save(){try{const player=activeStep?{x:activeStep.x+activeStep.dx,y:activeStep.y+activeStep.dy,dir:P.dir}:{x:P.x,y:P.y,dir:P.dir};localStorage.setItem(SAVE_KEY,JSON.stringify({version:1,resources:S,player,npcs:npcs.map(n=>({...n})),speed:spd,fever}));lastSaved=Date.now();return true}catch(_){return false}}
const finite=(v,min,max)=>typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max;
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;const s=JSON.parse(raw),r=s.resources;if(s.version!==1||!r||!['gold','wood','food'].every(k=>finite(r[k],0,1e15))||!finite(r.lv,1,1e6)||!Number.isInteger(r.lv))return false;S.gold=r.gold;S.wood=r.wood;S.food=r.food;S.lv=r.lv;
  activeStep=null;clearInput();const p=s.player;if(p&&finite(p.x,-408,408)&&finite(p.y,-288,336)){const px=Math.round(p.x/GRID)*GRID,py=Math.round(p.y/GRID)*GRID;if(canWalk(px,py)){P.x=px;P.y=py}}P.dir=p&&dirs[p.dir]?p.dir:"down";
  spd=[1,2,5,10].includes(s.speed)?s.speed:1;fever=finite(s.fever,0,20)?s.fever:0;$("speed").textContent="×"+spd;
  if(Array.isArray(s.npcs)&&s.npcs.length>0){const valid=s.npcs.slice(0,LIMIT).filter(n=>['x','y','tx','ty'].every(k=>finite(n[k],-1000,1000))&&finite(n.v,10,50));if(valid.length){npcs.length=0;valid.forEach(n=>npcs.push({x:n.x,y:n.y,tx:n.tx,ty:n.ty,v:n.v,phase:n.phase===1?1:0,carry:!!n.carry,bob:finite(n.bob,0,1e9)?n.bob:0,c:/^#[0-9a-f]{6}$/i.test(n.c)?n.c:"#71834f"}))}}
  cam.x=P.x;cam.y=P.y-55;return true}catch(_){return false}}
$("menu-close").onclick=()=>setMenu(false);$("menu-save").onclick=()=>{msg(save()?"ギルドの記録を保存した":"このブラウザでは保存できません");GuildAudio.sfx("confirm")};
window.GUILD_INPUT={GRID,step(dx,dy){if(activeStep)return false;const dir=dx===1&&dy===0?"right":dx===-1&&dy===0?"left":dx===0&&dy===1?"down":dx===0&&dy===-1?"up":null;return dir?move(dir):false},button:action,getPlayer:()=>({x:P.x,y:P.y,face:P.dir,moving:!!activeStep}),onA:null,onB:null,onX:null,onY:null};
window.GUILD_API=Object.freeze({getState:stateSnapshot,move,action,save,load,canWalk,touchMove,worldToScreen:(wx,wy)=>({x:sx(wx),y:sy(wy)}),worldGridSize:GRID,setSpeed(v){if(![1,2,5,10].includes(v))return false;spd=v;$("speed").textContent="×"+spd;return true},spawnAdventurer(){if(npcs.length>=LIMIT)return false;add();return true}});
load();
// Upgrade costs are bounded to keep the persistent economy finite.
const originalUpgrade=$("upgrade").onclick;$("upgrade").onclick=()=>{originalUpgrade();save()};
document.querySelectorAll("button").forEach(el=>el.addEventListener("click",()=>{if(!el.dataset.action&&!el.dataset.dir)save()}));

})();
