(()=>{'use strict';
const c=document.getElementById('c'),x=c.getContext('2d',{alpha:false}),$=id=>document.getElementById(id),G=window.GuildGraphics,A=window.GuildAudio;
let W=innerWidth,H=innerHeight,D=.5,last=performance.now(),T=0,fever=0,shake=0,sheetOpen=false,saveClock=0,selectedBuilding=null,boostSpeed=1,boostTime=0;
const ROSTER_CAP=200,VISIBLE_CAP=24;
const S={gold:100,wood:30,food:18,lv:1,roster:6,boostItems:2};
const P={x:0,y:120,vx:0,vy:0,dir:'down',walk:0},cam={x:0,y:65},parts=[],logs=[];
const B=[
{id:'guild',x:0,y:0,w:154,h:104,n:'GUILD HALL',jp:'ギルドホール',effect:'街全体の生産効率'},
{id:'inn',x:-230,y:110,w:106,h:78,n:'INN',jp:'宿屋',effect:'FOOD効率と帰還速度'},
{id:'quest',x:232,y:92,w:88,h:66,n:'QUEST',jp:'依頼所',effect:'GOLD獲得効率'},
{id:'forge',x:205,y:-135,w:102,h:74,n:'FORGE',jp:'鍛冶場',effect:'WOOD獲得効率'},
{id:'store',x:-210,y:-140,w:96,h:70,n:'MARKET',jp:'市場',effect:'GOLDと売却効率'},
{id:'tower',x:0,y:-205,w:76,h:102,n:'WATCH',jp:'見張り塔',effect:'放置収益の上限時間'}
];
const buildingLv=Object.fromEntries(B.map(b=>[b.id,1]));
const pal=['#b64f43','#4e76a4','#71834f','#8e5b9e','#bd9240','#4b8b87','#9d6752','#678f76'];
const npcs=[];let pointer=null,firstMove=false;
const rnd=(a,b)=>a+Math.random()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),sx=v=>W/2+v-cam.x,sy=v=>H/2+v-cam.y,fmt=n=>n>=1e9?(n/1e9).toFixed(2)+'B':n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':Math.floor(n);
function resize(){W=innerWidth;H=innerHeight;D=.5;c.width=Math.ceil(W*D);c.height=Math.ceil(H*D);x.setTransform(D,0,0,D,0,0);x.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
function r(a,b,w,h,col){x.fillStyle=col;x.fillRect(Math.round(a),Math.round(b),Math.round(w),Math.round(h))}
function sh(a,b,rx,ry,o=.35){x.fillStyle=`rgba(0,0,0,${o})`;x.beginPath();x.ellipse(a,b,rx,ry,0,0,Math.PI*2);x.fill()}
function nowLabel(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function pushLog(text,{quiet=false}={}){logs.unshift({time:nowLabel(),text});if(logs.length>60)logs.length=60;const ticker=$('ticker-text');if(ticker)ticker.textContent=text;if(!quiet&&navigator.vibrate)try{navigator.vibrate(4)}catch(_){};if(currentPanel==='logs'&&!$('dock-sheet').hidden)renderSheet('logs')}
function msg(text){pushLog(text)}
function guildCost(){return Math.floor(120*Math.pow(1.55,S.lv-1))}
function hireCost(){return Math.floor(45+Math.pow(S.roster+1,1.13)*3.2)}
function facilityCost(id){const base={guild:[85,8],inn:[65,5],quest:[80,6],forge:[78,7],store:[72,5],tower:[90,8]}[id],lv=buildingLv[id];return{gold:Math.floor(base[0]*Math.pow(1.58,lv-1)),wood:Math.floor(base[1]*Math.pow(1.4,lv-1))}}
function productivity(){return 1+(buildingLv.guild-1)*.07}
function blocked(wx,wy){if(wx<-408||wx>408||wy<-288||wy>336)return true;if(G.isTerrainBlocked(wx,wy))return true;return B.some(b=>wx>b.x-b.w/2-9&&wx<b.x+b.w/2+13&&wy+13>b.y-b.h/2+27&&wy+13<b.y+b.h/2+9)}
function moveContinuous(dx,dy){const nx=P.x+dx,ny=P.y+dy;if(!blocked(nx,P.y))P.x=nx;else P.vx=0;if(!blocked(P.x,ny))P.y=ny;else P.vy=0}
function pickJob(n){const b=B[1+((Math.random()*(B.length-1))|0)];n.tx=b.x+rnd(-30,30);n.ty=b.y+b.h/2+30+rnd(-10,10);n.wait=rnd(.2,.8)}
function makeNpc(i=npcs.length){const n={x:rnd(-25,25),y:rnd(86,130),tx:0,ty:0,dir:'down',v:rnd(23,31),c:pal[i%pal.length],bob:0,carry:false,wait:.2};pickJob(n);return n}
function syncVisible(){const want=Math.min(S.roster,VISIBLE_CAP);while(npcs.length<want)npcs.push(makeNpc(npcs.length));if(npcs.length>want)npcs.length=want}
syncVisible();
function fire(){const a=sx(0),b=sy(82);sh(a,b+11,22,7,.45);r(a-18,b+8,36,5,'#5a3920');const q=T*.012;x.fillStyle='#ff7432';x.beginPath();x.moveTo(a-12,b+7);x.quadraticCurveTo(a-17,b-11,a+Math.sin(q)*4,b-27);x.quadraticCurveTo(a+19,b-8,a+10,b+8);x.fill();x.fillStyle='#ffd368';x.beginPath();x.moveTo(a-6,b+7);x.quadraticCurveTo(a-5,b-6,a+1,b-16);x.quadraticCurveTo(a+9,b-3,a+5,b+7);x.fill();if(Math.random()<.16)parts.push({x:rnd(-6,6),y:70,vx:rnd(-4,4),vy:rnd(-25,-12),life:rnd(.5,1),c:'#ffbf61',s:rnd(1,3)})}
function productionRates(){const labor=Math.pow(Math.max(1,S.roster),.78),g=productivity(),q=1+(buildingLv.quest-1)*.055,s=1+(buildingLv.store-1)*.035,f=1+(buildingLv.forge-1)*.065,i=1+(buildingLv.inn-1)*.065;return{gold:(.1+labor*.072)*g*q*s,wood:(.009+labor*.004)*g*f,food:(.012+labor*.0042)*g*i}}
function update(dt){T+=dt*1000;if(boostTime>0){boostTime=Math.max(0,boostTime-dt);if(boostTime===0){boostSpeed=1;pushLog('砂時計の効果が切れた｜世界速度 ×1',{quiet:true})}}if(fever>0){fever=Math.max(0,fever-dt);if(fever===0){A.setMood('day');pushLog('FEVER終了｜街は通常運転へ',{quiet:true})}}
 const sim=dt*boostSpeed,prod=fever>0?1.35:1,rates=productionRates();if(!sheetOpen){moveContinuous(P.vx*dt,P.vy*dt);if(Math.abs(P.vx)+Math.abs(P.vy)>2)P.walk+=dt*11}
 cam.x+=(P.x-cam.x)*Math.min(1,dt*4.8);cam.y+=(P.y-55-cam.y)*Math.min(1,dt*4.8);
 S.gold+=sim*rates.gold*prod;S.wood+=sim*rates.wood*prod;S.food+=sim*rates.food*prod;
 npcs.forEach(n=>{n.bob+=dt*6*boostSpeed;if(n.wait>0){n.wait-=sim;return}const dx=n.tx-n.x,dy=n.ty-n.y,l=Math.hypot(dx,dy)||1;if(l<4){if(n.carry){const q=2+buildingLv.quest*.35;S.gold+=q;n.carry=false}pickJob(n);n.wait=rnd(.35,1.1);return}n.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');const v=Math.min(l,n.v*sim),mx=dx/l*v,my=dy/l*v;if(!blocked(n.x+mx,n.y))n.x+=mx;if(!blocked(n.x,n.y+my))n.y+=my;if(Math.random()<.0015*boostSpeed)n.carry=true});
 saveClock+=dt;if(saveClock>=15){saveClock=0;save()}updateHUD()}
function updateHUD(){const cost=guildCost();$('gold').textContent=fmt(S.gold);$('wood').textContent=fmt(S.wood);$('food').textContent=fmt(S.food);$('level').textContent='Lv.'+S.lv;$('cost').textContent=fmt(cost)+'G';$('roster').textContent=`${S.roster} / ${ROSTER_CAP}`;$('fever-time').textContent=fever>0?Math.ceil(fever)+' sec':'20 sec';$('boost-items').textContent=S.boostItems;$('boost-speed').textContent='×'+boostSpeed;$('boost-label').textContent=boostTime>0?`${Math.ceil(boostTime)}s`:`砂時計 ${S.boostItems}`;if(selectedBuilding)updateBuildingContext()}
function render(dt){x.save();if(shake>0){x.translate(rnd(-shake,shake),rnd(-shake,shake));shake*=.88}G.drawTerrain(x,{width:W,height:H,cam,time:T});const drawables=[...G.getPropDrawables({width:W,height:H,cam,time:T,ctx:x}),...B.map(b=>({y:b.y+b.h/2,draw:()=>G.drawBuilding(x,{...b,x:sx(b.x),y:sy(b.y)},buildingLv[b.id],T)})),...npcs.map(n=>({y:n.y+14,draw:()=>G.drawActor(x,{x:sx(n.x),y:sy(n.y),dir:n.dir,frame:Math.floor(n.bob)%2,color:n.c,isPlayer:false,carry:n.carry})})),{y:P.y+14,draw:()=>G.drawActor(x,{x:sx(P.x),y:sy(P.y),dir:P.dir,frame:Math.floor(P.walk)%2,color:'#7595a6',isPlayer:true,carry:false})},{y:94,draw:fire}];drawables.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());for(let i=parts.length-1;i>=0;i--){const p=parts[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0){parts.splice(i,1);continue}x.globalAlpha=cl(p.life,0,1);r(sx(p.x),sy(p.y),p.s,p.s,p.c);x.globalAlpha=1}G.drawAtmosphere(x,{width:W,height:H,cam,time:T});x.restore()}
function loop(now){const dt=Math.min(.034,(now-last)/1000);last=now;update(dt);render(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function selectBuilding(b){selectedBuilding=b;$('building-context').hidden=false;updateBuildingContext();pushLog(`${b.jp}を選択｜Lv.${buildingLv[b.id]} · ${b.effect}`,{quiet:true});A.sfx('confirm')}
function updateBuildingContext(){if(!selectedBuilding)return;const b=selectedBuilding,c=facilityCost(b.id);$('building-name').textContent=b.jp;$('building-kicker').textContent=b.n;$('building-effect').textContent=`Lv.${buildingLv[b.id]} · ${b.effect}`;$('building-cost').textContent=`${fmt(c.gold)}G / ${fmt(c.wood)}W`}
function inspect(clientX,clientY){const wx=clientX-W/2+cam.x,wy=clientY-H/2+cam.y,hit=B.find(b=>wx>b.x-b.w/2-18&&wx<b.x+b.w/2+20&&wy>b.y-b.h/2-24&&wy<b.y+b.h/2+24);if(!hit)return false;selectBuilding(hit);return true}
function upgradeBuilding(id){const b=B.find(v=>v.id===id);if(!b)return;const cst=facilityCost(id);if(S.gold<cst.gold||S.wood<cst.wood){pushLog(`${b.jp}｜資源不足 ${fmt(cst.gold)}G / ${fmt(cst.wood)}W`);A.sfx('cancel');return}S.gold-=cst.gold;S.wood-=cst.wood;buildingLv[id]++;shake=3;A.sfx('upgrade');if(buildingLv[id]%5===0){S.boostItems++;pushLog(`${b.jp} Lv.${buildingLv[id]}｜砂時計を1個獲得`)}else pushLog(`${b.jp} Lv.${buildingLv[id]}｜${b.effect}が上昇`);updateBuildingContext();if(currentPanel==='facilities')renderSheet('facilities');save()}
function vector(e){const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,dist=Math.hypot(dx,dy),dead=6,max=58,k=dist<dead?0:cl((dist-dead)/(max-dead),0,1),nx=dist?dx/dist:0,ny=dist?dy/dist:0,base=138;P.vx=nx*base*k;P.vy=ny*base*k;if(Math.abs(P.vx)>Math.abs(P.vy))P.dir=P.vx>0?'right':'left';else if(k>0)P.dir=P.vy>0?'down':'up'}
c.addEventListener('pointerdown',e=>{if(sheetOpen||pointer)return;e.preventDefault();pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,drag:false};try{c.setPointerCapture(e.pointerId)}catch(_){};A.enable()});
c.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;e.preventDefault();pointer.lastX=e.clientX;pointer.lastY=e.clientY;if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>8)pointer.drag=true;vector(e);if(!firstMove){firstMove=true;$('hint').style.opacity='.35'}});
function release(e){if(!pointer||e.pointerId!==pointer.id)return;const tap=!pointer.drag,px=pointer.lastX,py=pointer.lastY;P.vx=P.vy=0;pointer=null;if(tap)inspect(px,py)}c.addEventListener('pointerup',release);c.addEventListener('pointercancel',release);c.addEventListener('lostpointercapture',e=>{if(pointer&&e.pointerId===pointer.id){P.vx=P.vy=0;pointer=null}});
const held=new Set();addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){held.add(k);e.preventDefault()}if(k==='escape')closeSheet()});addEventListener('keyup',e=>held.delete(e.key.toLowerCase()));setInterval(()=>{if(sheetOpen||pointer)return;let dx=0,dy=0;if(held.has('a')||held.has('arrowleft'))dx--;if(held.has('d')||held.has('arrowright'))dx++;if(held.has('w')||held.has('arrowup'))dy--;if(held.has('s')||held.has('arrowdown'))dy++;const l=Math.hypot(dx,dy)||1;P.vx=dx/l*138;P.vy=dy/l*138;if(dx||dy)P.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');else P.vx=P.vy=0},16);
$('sound').onclick=async()=>{await A.toggle();$('sound').textContent=A.isMuted?'♪ OFF':'♪ ON'};
function guildUp(){const q=guildCost();if(S.gold<q){pushLog(`GUILD UP｜GOLD不足 あと${fmt(q-S.gold)}G`);A.sfx('cancel');return}S.gold-=q;S.lv++;shake=5;A.sfx('upgrade');for(let i=0;i<22;i++)parts.push({x:rnd(-65,65),y:rnd(-35,45),vx:rnd(-40,40),vy:rnd(-55,-15),life:rnd(.5,1.1),c:'#ffd36d',s:rnd(1,4)});if(S.lv%3===0){S.boostItems++;pushLog(`GUILD Lv.${S.lv}｜砂時計を1個獲得`)}else pushLog(`GUILD Lv.${S.lv}｜街の生産効率が上昇`);if(currentPanel==='growth')renderSheet('growth');save()}
function hire(){if(S.roster>=ROSTER_CAP){pushLog('冒険者名簿は200人で満員');A.sfx('cancel');return}const q=hireCost();if(S.gold<q){pushLog(`HIRE｜GOLD不足 ${fmt(q)}G必要`);A.sfx('cancel');return}S.gold-=q;S.roster++;syncVisible();A.sfx('confirm');if(S.roster%25===0){S.boostItems++;pushLog(`冒険者 ${S.roster}人｜節目報酬 砂時計+1`)}else pushLog(`新しい冒険者が加入｜${S.roster} / ${ROSTER_CAP}`);if(currentPanel==='roster')renderSheet('roster');save()}
function triggerFever(){if(fever>0){pushLog('FEVER発動中');return}fever=20;shake=2;A.setMood('fever');A.sfx('fever');pushLog('FEVER｜20秒間、獲得量 +35%')}
function useBoost(){if(boostSpeed>=3){pushLog('世界速度は×3が最大');return}if(S.boostItems<=0){pushLog('砂時計がない｜ギルドや施設の節目で獲得できる');A.sfx('cancel');return}S.boostItems--;boostSpeed++;boostTime=Math.max(boostTime,30);A.sfx('confirm');pushLog(`砂時計を使用｜世界速度 ×${boostSpeed} · 30秒`);updateHUD();save()}
$('upgrade').onclick=guildUp;$('hire').onclick=hire;$('fever').onclick=triggerFever;$('boost').onclick=useBoost;$('building-upgrade').onclick=()=>selectedBuilding&&upgradeBuilding(selectedBuilding.id);$('building-dismiss').onclick=()=>{selectedBuilding=null;$('building-context').hidden=true};
let currentPanel='growth';const sheet=$('dock-sheet'),sheetBody=$('sheet-body');
function setTab(panel){document.querySelectorAll('.dock-tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel))}
function openSheet(panel){currentPanel=panel;sheetOpen=true;P.vx=P.vy=0;setTab(panel);renderSheet(panel);sheet.hidden=false;A.sfx('confirm')}
function closeSheet(){if(sheet.hidden)return;sheet.hidden=true;sheetOpen=false;P.vx=P.vy=0;A.sfx('cancel')}
function facilityCards(){return B.map(b=>{const lv=buildingLv[b.id],c=facilityCost(b.id);return `<article class="sheet-card"><small>${b.n}</small><strong>${b.jp} Lv.${lv}</strong><p>${b.effect}</p><button class="sheet-action" data-building="${b.id}">強化 ${fmt(c.gold)}G / ${fmt(c.wood)}W</button></article>`}).join('')}
function renderSheet(panel){const titles={growth:['GUILD GROWTH','育成'],roster:['ADVENTURER ROSTER','冒険者'],facilities:['FACILITIES','施設'],logs:['GUILD LOG','ログ']};$('sheet-kicker').textContent=titles[panel][0];$('sheet-title').textContent=titles[panel][1];if(panel==='growth'){const q=guildCost();sheetBody.innerHTML=`<div class="sheet-grid"><article class="sheet-card"><small>GUILD LEVEL</small><strong>Lv.${S.lv}</strong><p>街全体の基礎効率を育てる</p><button class="sheet-action" data-act="guild">GUILD UP ${fmt(q)}G</button></article><article class="sheet-card"><small>TIME ITEM</small><strong>砂時計 ${S.boostItems}</strong><p>中央ボタンで×2→×3。30秒で×1に戻る</p></article><article class="sheet-card"><small>FEVER</small><strong>${fever>0?Math.ceil(fever)+'秒':'READY'}</strong><p>時間速度とは別に獲得量を35%上げる</p><button class="sheet-action" data-act="fever">FEVER</button></article><article class="sheet-card"><small>NEXT REWARD</small><strong>Lv.${Math.ceil((S.lv+1)/3)*3}</strong><p>3レベルごとに砂時計+1</p></article></div>`}
 else if(panel==='roster'){const pct=S.roster/ROSTER_CAP*100,q=hireCost();sheetBody.innerHTML=`<div class="sheet-grid"><article class="sheet-card"><small>ROSTER</small><strong>${S.roster} / ${ROSTER_CAP}</strong><div class="roster-meter"><i style="width:${pct}%"></i></div><p>画面に出す人数は最大${VISIBLE_CAP}人。残りは遠征・裏方として生産に参加</p><button class="sheet-action" data-act="hire">HIRE ${fmt(q)}G</button></article><article class="sheet-card"><small>ON DUTY</small><strong>${npcs.length}人</strong><p>街で実際に見える冒険者。画面密度を守る</p></article><article class="sheet-card"><small>MILESTONE</small><strong>${Math.min(ROSTER_CAP,Math.ceil((S.roster+1)/25)*25)}人</strong><p>25人ごとの到達で砂時計+1</p></article></div>`}
 else if(panel==='facilities')sheetBody.innerHTML=`<div class="sheet-grid">${facilityCards()}</div>`;
 else if(panel==='logs')sheetBody.innerHTML=(logs.length?logs:[{time:'--:--',text:'まだログはありません'}]).map(v=>`<div class="sheet-log"><time>${v.time}</time>${v.text}</div>`).join('')}
document.querySelectorAll('.dock-tab').forEach(b=>b.onclick=()=>openSheet(b.dataset.panel));$('ticker-open').onclick=()=>openSheet('logs');$('sheet-close').onclick=closeSheet;sheetBody.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.building)upgradeBuilding(btn.dataset.building);if(btn.dataset.act==='guild')guildUp();if(btn.dataset.act==='hire')hire();if(btn.dataset.act==='fever')triggerFever()});
const SAVE='guild-v08-bottom-first',CAP=1e15;const finite=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b;
function save(){try{localStorage.setItem(SAVE,JSON.stringify({v:8,savedAt:Date.now(),S:{gold:cl(S.gold,0,CAP),wood:cl(S.wood,0,CAP),food:cl(S.food,0,CAP),lv:S.lv,roster:S.roster,boostItems:S.boostItems},p:{x:P.x,y:P.y,dir:P.dir},buildingLv,npcs:npcs.map(n=>({x:n.x,y:n.y,c:n.c}))}))}catch(_){}}
function applyOffline(savedAt){if(!finite(savedAt,1,Date.now()+60000))return;const maxHours=4+(buildingLv.tower-1)*.5,seconds=cl((Date.now()-savedAt)/1000,0,maxHours*3600);if(seconds<30)return;const rates=productionRates(),eff=.28;S.gold=cl(S.gold+seconds*rates.gold*eff,0,CAP);S.wood=cl(S.wood+seconds*rates.wood*eff,0,CAP);S.food=cl(S.food+seconds*rates.food*eff,0,CAP);setTimeout(()=>pushLog(`帰還報酬｜留守中 ${Math.floor(seconds/60)}分ぶんを受取`),200)}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE)||'null');if(!s||s.v!==8)return;const q=s.S;if(q&&finite(+q.gold,0,CAP)&&finite(+q.wood,0,CAP)&&finite(+q.food,0,CAP)){S.gold=+q.gold;S.wood=+q.wood;S.food=+q.food;S.lv=cl(Math.floor(+q.lv||1),1,999);S.roster=cl(Math.floor(+q.roster||6),1,ROSTER_CAP);S.boostItems=cl(Math.floor(+q.boostItems||0),0,999)}if(s.p&&finite(+s.p.x,-408,408)&&finite(+s.p.y,-288,336)&&!blocked(+s.p.x,+s.p.y)){P.x=+s.p.x;P.y=+s.p.y;P.dir=['up','down','left','right'].includes(s.p.dir)?s.p.dir:'down'}if(s.buildingLv)for(const b of B)buildingLv[b.id]=cl(Math.floor(+s.buildingLv[b.id]||1),1,99);syncVisible();if(Array.isArray(s.npcs)){s.npcs.slice(0,Math.min(VISIBLE_CAP,npcs.length)).forEach((v,i)=>{if(finite(+v.x,-1000,1000)&&finite(+v.y,-1000,1000)){npcs[i].x=+v.x;npcs[i].y=+v.y;if(/^#[0-9a-f]{6}$/i.test(v.c))npcs[i].c=v.c}})}cam.x=P.x;cam.y=P.y-55;applyOffline(+s.savedAt)}catch(_){}}
load();updateHUD();pushLog('街は静かに動き始めている',{quiet:true});addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{P.vx=P.vy=0;last=performance.now();if(document.hidden){save();A.pause()}else A.resume()});
window.GUILD_API=Object.freeze({getState:()=>({resources:{...S},player:{x:P.x,y:P.y,dir:P.dir},visibleNpcs:npcs.length,roster:S.roster,buildings:{...buildingLv},boostSpeed,boostTime,fever,control:'smooth-drag-v08'}),save,load,openSheet,closeSheet,selectBuilding:(id)=>{const b=B.find(v=>v.id===id);if(b)selectBuilding(b)},canWalk:(x,y)=>!blocked(x,y)});
})();
