(()=>{'use strict';
const $=id=>document.getElementById(id),c=$('game'),g=c.getContext('2d',{alpha:false});
let W=0,H=0,D=1,last=performance.now(),spd=1,fever=0,night=0,shake=0,near=null,muted=false,AC=null,music=null,mstep=0;
const rnd=(a,b)=>a+Math.random()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const state={gold:100,wood:30,food:18,lv:1,quests:0},p={x:0,y:145,vx:0,vy:0,a:-1.57,ta:-1.57,walk:0},cam={x:0,y:50};
const input={x:0,y:0,id:null,cx:0,cy:0},keys=new Set(),parts=[],floaters=[];
const buildings=[
 {id:'guild',x:0,y:0,w:168,h:126,n:'GUILD HALL',a:'#c99455'},
 {id:'inn',x:-290,y:125,w:122,h:92,n:'MOON INN',a:'#8299b9'},
 {id:'quest',x:305,y:110,w:108,h:82,n:'QUEST BOARD',a:'#d3aa61'},
 {id:'forge',x:255,y:-180,w:126,h:94,n:'EMBER FORGE',a:'#c06a50'},
 {id:'market',x:-260,y:-185,w:120,h:88,n:'MARKET',a:'#91a861'},
 {id:'tower',x:40,y:-310,w:104,h:118,n:'WATCH TOWER',a:'#9280b7'}];
const npcs=Array.from({length:8},(_,i)=>({x:rnd(-50,50),y:rnd(30,100),tx:0,ty:0,sp:rnd(24,38),c:['#b85a4e','#587aa1','#71884f','#8b619c','#bd9348','#a46d58'][i%6],phase:0,b:rnd(0,6.2)}));
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;g.setTransform(D,0,0,D,0,0);g.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const sx=x=>W/2+x-cam.x,sy=y=>H/2+y-cam.y;
function fmt(n){return n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':Math.floor(n)}
function rect(x,y,w,h,col){g.fillStyle=col;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function poly(a,col){g.fillStyle=col;g.beginPath();g.moveTo(...a[0]);for(let i=1;i<a.length;i++)g.lineTo(...a[i]);g.closePath();g.fill()}
function txt(t,x,y,z=9,col='#eee'){g.font=`800 ${z}px ui-monospace,monospace`;g.textAlign='center';g.fillStyle='#000b';g.fillText(t,x+1,y+1);g.fillStyle=col;g.fillText(t,x,y)}
function sh(x,y,rx,ry,a=.3){g.fillStyle=`rgba(0,0,0,${a})`;g.beginPath();g.ellipse(x,y,rx,ry,0,0,6.29);g.fill()}
function log(t){const d=document.createElement('div');d.className='log';d.textContent=t;$('questlog').append(d);setTimeout(()=>d.remove(),3500)}
function target(n){const b=buildings[1+(Math.random()*(buildings.length-1)|0)];n.tx=b.x+rnd(-38,38);n.ty=b.y+rnd(20,52);n.phase=0}npcs.forEach(target);
function ground(){let q=g.createLinearGradient(0,0,0,H);q.addColorStop(0,'#111827');q.addColorStop(.34,'#202a29');q.addColorStop(1,'#352a20');g.fillStyle=q;g.fillRect(0,0,W,H);
 const off=(cam.x*.05)%160;for(let l=0;l<3;l++){g.fillStyle=['#0c121a','#131b20','#192324'][l];g.beginPath();g.moveTo(-180,H*.18);for(let x=-180-off;x<W+220;x+=120){let y=H*(.15+l*.04);g.lineTo(x,y-rnd(20,55));g.lineTo(x+60,y+10)}g.lineTo(W+220,H*.3);g.closePath();g.fill()}
 const roads=[[0,24,-290,125],[0,24,305,110],[0,18,255,-180],[0,18,-260,-185],[0,-10,40,-310]];g.lineCap='round';for(const r of roads){g.strokeStyle='#554536';g.lineWidth=54;g.beginPath();g.moveTo(sx(r[0]),sy(r[1]));g.lineTo(sx(r[2]),sy(r[3]));g.stroke();g.strokeStyle='#8f754f';g.lineWidth=42;g.stroke()}
 for(let i=0;i<80;i++){let x=sx((i*139)%1000-500),y=sy((i*83)%760-380);if(x<0||x>W||y<50||y>H)continue;rect(x,y,2+i%3,2,'#a58b5a44')}
}
function building(b){const x=sx(b.x),y=sy(b.y),w=b.w,h=b.h;sh(x,y+42,w*.48,16,.42);poly([[x-w/2,y-h/2+32],[x+w/2,y-h/2+32],[x+w/2,y+h/2+18],[x-w/2,y+h/2+18]],b.id==='guild'?'#4c3526':'#49382b');poly([[x+w/2,y-h/2+32],[x+w/2+12,y-h/2+22],[x+w/2+12,y+h/2+8],[x+w/2,y+h/2+18]],'#281f1a');rect(x-w/2+8,y-h/2+40,w-16,h-46,b.id==='guild'?'#6d4a30':'#5d4431');
 const roof=b.id==='guild'?'#6d3c36':b.id==='forge'?'#6c3a31':'#67493b';poly([[x-w/2-14,y-h/2+34],[x,y-h/2-24],[x+w/2+16,y-h/2+34],[x+w/2-5,y-h/2+43],[x,y-h/2-10],[x-w/2+5,y-h/2+43]],roof);rect(x-13,y+18,26,31,'#1d1713');
 for(const k of [-.24,.17]){g.save();g.shadowColor=b.a;g.shadowBlur=12;rect(x+w*k,y+3,18,17,b.a);g.restore();rect(x+w*k+3,y+6,12,11,'#f7d58b')}rect(x-20,y-h/2+44,40,17,'#171216');txt(b.id==='guild'?'∞':b.id==='inn'?'Z':b.id==='quest'?'!':b.id==='forge'?'⚒':b.id==='tower'?'▲':'$',x,y-h/2+57,12,'#f0ca7b');txt(b.n,x,y+h/2+34,9,'#ddc9a7')}
function actor(a,isPlayer=false){const x=sx(a.x),y=sy(a.y),bob=Math.sin(a.b||a.walk)*1.4,ang=isPlayer?p.a:Math.atan2(a.ty-a.y,a.tx-a.x),dx=Math.cos(ang),dy=Math.sin(ang);sh(x,y+14,10,5,.36);rect(x-6,y+4+bob,4,8,'#27221f');rect(x+2,y+4-bob,4,8,'#27221f');rect(x-8,y-13+bob,16,18,isPlayer?'#d2cec4':a.c);rect(x-6,y-21+bob,12,9,'#d6ad82');rect(x-7,y-24+bob,14,5,isPlayer?'#292326':'#382923');if(isPlayer){g.strokeStyle='#e6d5b5';g.lineWidth=3;g.beginPath();g.moveTo(x+dx*5,y-5+dy*3);g.lineTo(x+dx*15,y-7+dy*8);g.stroke();txt('YOU',x,y-31,8,'#f2d294')}}
function fire(){const x=sx(0),y=sy(72);sh(x,y+10,25,8,.52);rect(x-19,y+7,38,5,'#4b3121');let t=performance.now()*.012;g.save();g.shadowColor='#ff8d38';g.shadowBlur=18;g.fillStyle='#ff7931';g.beginPath();g.moveTo(x-10,y+7);g.quadraticCurveTo(x-15,y-10,x+Math.sin(t)*4,y-27);g.quadraticCurveTo(x+17,y-7,x+8,y+7);g.fill();g.fillStyle='#ffd26c';g.beginPath();g.moveTo(x-4,y+6);g.quadraticCurveTo(x-6,y-7,x,y-15);g.quadraticCurveTo(x+7,y-3,x+4,y+6);g.fill();g.restore();if(Math.random()<.2)parts.push({x:0+rnd(-6,6),y:60,vx:rnd(-7,7),vy:rnd(-28,-12),life:rnd(.5,1),c:'#ffc266'})}
function effects(dt){for(let i=parts.length-1;i>=0;i--){let a=parts[i];a.x+=a.vx*dt;a.y+=a.vy*dt;a.life-=dt;if(a.life<=0){parts.splice(i,1);continue}g.globalAlpha=a.life;rect(sx(a.x),sy(a.y),2,2,a.c);g.globalAlpha=1}for(let i=floaters.length-1;i>=0;i--){let a=floaters[i];a.y-=16*dt;a.life-=dt;if(a.life<=0){floaters.splice(i,1);continue}g.globalAlpha=a.life;txt(a.t,sx(a.x),sy(a.y),9,'#f3d78e');g.globalAlpha=1}}
function light(){const d=.1+night*.2;g.fillStyle=`rgba(6,9,18,${d})`;g.fillRect(0,0,W,H);g.save();g.globalCompositeOperation='screen';const x=sx(0),y=sy(72),q=g.createRadialGradient(x,y,4,x,y,190);q.addColorStop(0,'rgba(255,175,75,.35)');q.addColorStop(1,'rgba(255,120,40,0)');g.fillStyle=q;g.fillRect(x-190,y-190,380,380);g.restore();const v=g.createRadialGradient(W/2,H/2,Math.min(W,H)*.25,W/2,H/2,Math.max(W,H)*.75);v.addColorStop(0,'#0000');v.addColorStop(1,'#0008');g.fillStyle=v;g.fillRect(0,0,W,H)}
function update(dt){const kx=(keys.has('ArrowRight')||keys.has('KeyD'))-(keys.has('ArrowLeft')||keys.has('KeyA')),ky=(keys.has('ArrowDown')||keys.has('KeyS'))-(keys.has('ArrowUp')||keys.has('KeyW'));let ix=cl(input.x+kx,-1,1),iy=cl(input.y+ky,-1,1),m=Math.hypot(ix,iy);if(m>1){ix/=m;iy/=m;m=1}const base=138,targetX=ix*base,targetY=iy*base,a=1-Math.pow(.00003,dt);p.vx=lerp(p.vx,targetX,a);p.vy=lerp(p.vy,targetY,a);p.x=cl(p.x+p.vx*dt*spd,-740,740);p.y=cl(p.y+p.vy*dt*spd,-500,500);if(m>.08){p.ta=Math.atan2(iy,ix);p.walk+=dt*13}let da=((p.ta-p.a+Math.PI*3)%(Math.PI*2))-Math.PI;p.a+=da*Math.min(1,dt*15);cam.x=lerp(cam.x,p.x,1-Math.pow(.002,dt));cam.y=lerp(cam.y,p.y-55,1-Math.pow(.002,dt));
 const mul=fever>0?2.5:1;state.gold+=dt*spd*(.5+state.lv*.2+npcs.length*.025)*mul;state.wood+=dt*spd*.025;state.food+=dt*spd*.03;if(fever>0)fever-=dt;
 npcs.forEach(n=>{n.b+=dt*7;let dx=n.tx-n.x,dy=n.ty-n.y,d=Math.hypot(dx,dy)||1;n.x+=dx/d*n.sp*dt*spd;n.y+=dy/d*n.sp*dt*spd;if(d<7){if(n.phase===0){n.phase=1;n.tx=rnd(-50,50);n.ty=rnd(20,70)}else{let r=8+state.lv*3;state.gold+=r;state.quests++;floaters.push({x:n.x,y:n.y-8,t:'+'+r+'G',life:1.1});sfx('coin');target(n)}}});near=null;let nd=1e9;for(const b of buildings){let d=Math.hypot(p.x-b.x,p.y-b.y);if(d<115&&d<nd){near=b;nd=d}}$('action').textContent=near?(near.id==='quest'?'QUEST':'ENTER'):'ACTION';$('action').classList.toggle('actionHot',!!near);night=(Math.sin(performance.now()/23000)+1)/2}
function render(dt){g.save();if(shake>0){g.translate(rnd(-shake,shake),rnd(-shake,shake));shake*=.86}ground();let draw=[...buildings.map(b=>({y:b.y+35,f:()=>building(b)})),...npcs.map(n=>({y:n.y,f:()=>actor(n)})),{y:p.y,f:()=>actor(p,true)}].sort((a,b)=>a.y-b.y);draw.forEach(o=>o.f());fire();effects(dt);light();g.restore();$('gold').textContent=fmt(state.gold);$('wood').textContent=fmt(state.wood);$('food').textContent=fmt(state.food);$('lv').textContent='Lv.'+state.lv;$('cost').textContent=fmt(Math.floor(120*Math.pow(1.72,state.lv-1)))+'G';let d=Math.hypot(p.x,p.y);$('zone').textContent=d<250?'EMBER CAMP':d<520?'WILDLANDS':'OUTER RING'}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);setTimeout(()=>log('Drag the world to move'),450);
const guide=$('dragGuide');function drag(e){const max=42;let dx=e.clientX-input.cx,dy=e.clientY-input.cy,d=Math.hypot(dx,dy)||1;if(d>max){dx=dx/d*max;dy=dy/d*max}if(Math.hypot(dx,dy)<5)dx=dy=0;input.x=dx/max;input.y=dy/max;guide.style.setProperty('--dx',Math.round(dx*.42)+'px');guide.style.setProperty('--dy',Math.round(dy*.42)+'px')}
c.addEventListener('pointerdown',e=>{e.preventDefault();audio();input.id=e.pointerId;input.cx=e.clientX;input.cy=e.clientY;guide.style.left=e.clientX+'px';guide.style.top=e.clientY+'px';guide.style.display='block';c.setPointerCapture?.(e.pointerId);drag(e)});c.addEventListener('pointermove',e=>{if(e.pointerId===input.id){e.preventDefault();drag(e)}});function end(e={}){if(input.id!==null&&e.pointerId!==undefined&&e.pointerId!==input.id)return;input.id=null;input.x=input.y=0;guide.style.display='none'}c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);addEventListener('pointerup',end);addEventListener('keydown',e=>{audio();keys.add(e.code);if(e.code.startsWith('Arrow'))e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();end({})});
function audio(){if(!AC){AC=new(window.AudioContext||window.webkitAudioContext)();let master=AC.createGain();master.gain.value=.28;master.connect(AC.destination);music=master;setInterval(()=>{if(muted||!AC)return;let notes=[220,247,294,330,392,330,294,247],i=mstep++%8;tone(notes[i],.3,'triangle',.025);if(i%2===0)tone(notes[i]/2,.6,'sine',.03)},440)}if(AC.state==='suspended')AC.resume().catch(()=>{})}function tone(f,d,type='sine',v=.04,delay=0){if(!AC||muted)return;let o=AC.createOscillator(),a=AC.createGain(),t=AC.currentTime+delay;o.type=type;o.frequency.value=f;a.gain.setValueAtTime(.001,t);a.gain.linearRampToValueAtTime(v,t+.01);a.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(a);a.connect(music);o.start(t);o.stop(t+d+.03)}function sfx(k){if(k==='coin'){tone(880,.06,'square',.018);tone(1320,.08,'square',.014,.05)}if(k==='up'){tone(392,.1,'triangle',.04);tone(523,.12,'triangle',.04,.09);tone(659,.18,'triangle',.04,.18)}}
$('sound').onclick=()=>{audio();muted=!muted;$('sound').textContent=muted?'×':'♪'};$('speed').onclick=()=>{spd=spd===1?2:spd===2?4:1;$('speed').textContent='×'+spd;log('World speed ×'+spd)};$('action').onclick=()=>{audio();if(!near){log('Nothing nearby');return}if(near.id==='quest'){let r=24+state.lv*8;state.gold+=r;log('Quest complete · +'+r+'G')}else log(near.n+' · interaction online')};$('upgrade').onclick=()=>{audio();let cost=Math.floor(120*Math.pow(1.72,state.lv-1));if(state.gold<cost){log('Gold不足 · '+cost+'G');return}state.gold-=cost;state.lv++;shake=7;sfx('up');log('GUILD LEVEL '+state.lv)};$('hire').onclick=()=>{audio();if(state.gold<60){log('Gold不足 · 60G');return}state.gold-=60;log('Recruitment reserved · population stays capped in this polish pass')};$('burst').onclick=()=>{audio();fever=20;log('FEVER · production ×2.5 · 20s')};
window.GUILD_API={version:'0.5-legacy-ui-drag',getState:()=>({...state,player:{x:p.x,y:p.y}}),message:log,grantGold:n=>state.gold+=Number(n)||0};
})();