(()=>{'use strict';
const c=document.getElementById('c'),ctx=c.getContext('2d',{alpha:false}),$=id=>document.getElementById(id),G=window.GuildGraphics||null,A=window.GuildAudio||{enable(){},toggle(){},sfx(){},setMood(){}};
let W=innerWidth,H=innerHeight,D=.5,last=performance.now(),time=0,pointer=null,sheetOpen=false,saveFlash=0,toastClock=0,currentTarget=null;
const KEY='guild-survival-v09-primary',BACK='guild-survival-v09-backup',SCHEMA=9;
const PHASES=[['day',150],['dusk',20],['night',70],['dawn',10]],RARITIES=[['COMMON',55],['UNCOMMON',25],['RARE',13],['EPIC',6],['LEGENDARY',1]];
const RECIPES={workbench:{name:'作業台',wood:12,food:0,desc:'クラフトと防衛設備を解放'},barricade:{name:'バリケード',wood:10,food:0,desc:'夜襲の最初の盾',requires:'workbench'},bed:{name:'簡易寝床',wood:16,food:4,desc:'募集所の前提',requires:'workbench'},recruit:{name:'募集所',wood:24,food:8,desc:'初めて人を雇える',requires:'bed'},crate:{name:'木箱',wood:8,food:0,desc:'資源保存の象徴',requires:'workbench'}};
const BUILD_SLOTS={workbench:[-70,78],barricade:[0,154],bed:[70,82],recruit:[-128,28],crate:[128,36]};
const trees=[[-220,-140],[-120,-185],[20,-180],[155,-155],[245,-70],[-250,45],[250,80],[-185,180],[180,190]].map((p,i)=>({id:'tree'+i,x:p[0],y:p[1],hp:3,max:3,respawn:0}));
const bushes=[[-170,-40],[110,-80],[205,20],[-80,195]].map((p,i)=>({id:'bush'+i,x:p[0],y:p[1],ready:true,respawn:0}));
function fresh(){return{schema:SCHEMA,savedAt:Date.now(),day:1,phase:0,phaseTime:PHASES[0][1],resources:{wood:0,food:0,scrap:0,crystal:0,hourglass:0},player:{x:0,y:120,hp:100,maxHp:100,dir:'up',walk:0},buildings:{},villagers:[],relics:[],pity:0,boost:{speed:1,time:0},barricadeHp:{},zombies:[],logs:[{t:Date.now(),text:'斧一本。まず木を集めろ'}]}}
let S=fresh();
function safeParse(v){try{return JSON.parse(v)}catch(_){return null}}
function valid(s){return s&&s.schema===SCHEMA&&s.resources&&s.player&&Array.isArray(s.villagers)&&s.buildings}
function load(){const p=safeParse(localStorage.getItem(KEY));if(valid(p)){S=p;log('オートセーブから復元',{quiet:true});return}const b=safeParse(localStorage.getItem(BACK));if(valid(b)){S=b;localStorage.setItem(KEY,JSON.stringify(S));log('バックアップから復元',{quiet:true})}}
function save(reason='auto'){S.savedAt=Date.now();const out=JSON.stringify(S);try{const prev=localStorage.getItem(KEY);if(prev)localStorage.setItem(BACK,prev);localStorage.setItem(KEY,out)}catch(_){}saveFlash=.65;updateHud();if(reason!=='auto'){} }
function mutate(fn,msg){fn();if(msg)log(msg);save('mutation')}
function log(text,{quiet=false}={}){S.logs.unshift({t:Date.now(),text});S.logs=S.logs.slice(0,80);$('ticker').textContent=text;if(!quiet&&navigator.vibrate)try{navigator.vibrate(5)}catch(_){}if(sheetOpen&&$('sheet-title').textContent==='記録')renderSheet('log')}
function toast(text,cls=''){const e=$('toast');e.textContent=text;e.className=cls;e.hidden=false;toastClock=2.1}
load();
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,1);c.width=Math.ceil(W*D);c.height=Math.ceil(H*D);ctx.setTransform(D,0,0,D,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const cl=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),phaseName=()=>PHASES[S.phase][0],sx=x=>W/2+(x-S.player.x*.35),sy=y=>H*.49+(y-S.player.y*.35);
function phaseLabel(){return phaseName().toUpperCase()}
function fmtTime(sec){sec=Math.max(0,Math.ceil(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function updateHud(){const r=S.resources;$('day').textContent=S.day;$('phase').textContent=phaseLabel();$('clock').textContent=fmtTime(S.phaseTime);$('phase-note').textContent=phaseName()==='day'?'夜まで':phaseName()==='dusk'?'襲撃まで':phaseName()==='night'?'朝まで':'夜明け';$('wood').textContent=r.wood;$('food').textContent=r.food;$('scrap').textContent=r.scrap;$('crystal').textContent=r.crystal;$('hp').textContent=Math.max(0,Math.ceil(S.player.hp));$('villagers').textContent=S.villagers.length;$('hourglass').textContent=`砂時計 ${r.hourglass}`;$('boost-speed').textContent='×'+S.boost.speed;$('save-indicator').style.opacity=saveFlash>0?'1':'.35';document.body.classList.toggle('night',phaseName()==='night')}
function phaseAdvance(){S.phase=(S.phase+1)%PHASES.length;if(S.phase===0)S.day++;S.phaseTime=PHASES[S.phase][1];const p=phaseName();if(p==='dusk'){log('日が沈み始めた｜拠点へ戻れ');try{A.setMood('night')}catch(_){}}if(p==='night'){spawnRaid();log(`夜襲開始｜ゾンビ ${S.zombies.length}体`)}if(p==='dawn'){S.zombies=[];survivalReward();log('夜明け｜生存した');try{A.setMood('day')}catch(_){}}if(p==='day')log(`DAY ${S.day}｜新しい朝`);save('phase')}
function survivalReward(){S.resources.food+=2+Math.min(6,S.day);if(Math.random()<.35){S.resources.hourglass++;toast('DROP｜砂時計 +1','rarity-rare')}}
function spawnRaid(){const n=Math.min(3+Math.floor(S.day/2),10);S.zombies=[];for(let i=0;i<n;i++){const a=(Math.PI*2*i/n)+Math.random()*.5,rr=330+Math.random()*80;S.zombies.push({id:'z'+Date.now()+i,x:Math.cos(a)*rr,y:Math.sin(a)*rr,hp:24+S.day*3,max:24+S.day*3,atk:.8+S.day*.06,hit:0})}}
function treeNearest(){let best=null,bd=55;for(const t of trees){if(t.respawn>0)continue;const d=Math.hypot(S.player.x-t.x,S.player.y-t.y);if(d<bd){bd=d;best=t}}return best}
function bushNearest(){let best=null,bd=48;for(const b of bushes){if(!b.ready)continue;const d=Math.hypot(S.player.x-b.x,S.player.y-b.y);if(d<bd){bd=d;best=b}}return best}
function zombieNearest(){let best=null,bd=66;for(const z of S.zombies){const d=Math.hypot(S.player.x-z.x,S.player.y-z.y);if(d<bd){bd=d;best=z}}return best}
function buildingNear(){let best=null,bd=52;for(const [id,b] of Object.entries(S.buildings)){const p={x:b.x,y:b.y},d=Math.hypot(S.player.x-p.x,S.player.y-p.y);if(d<bd){bd=d;best={id,...b}}}return best}
function updateTarget(){const z=zombieNearest();if(z){currentTarget={type:'zombie',obj:z};$('context-kicker').textContent='HOSTILE';$('context-name').textContent='ゾンビ';$('context-detail').textContent=`HP ${Math.ceil(z.hp)} / ${z.max}`;$('context-action').textContent='斧 / 攻撃';$('context-action').disabled=false;return}const t=treeNearest();if(t){currentTarget={type:'tree',obj:t};$('context-kicker').textContent='RESOURCE';$('context-name').textContent='木';$('context-detail').textContent=`耐久 ${t.hp} / ${t.max}`;$('context-action').textContent='斧 / 伐採';$('context-action').disabled=false;return}const b=bushNearest();if(b){currentTarget={type:'bush',obj:b};$('context-kicker').textContent='RESOURCE';$('context-name').textContent='野生の実';$('context-detail').textContent='FOODを採集できる';$('context-action').textContent='採集';$('context-action').disabled=false;return}const bn=buildingNear();if(bn){currentTarget={type:'building',obj:bn};$('context-kicker').textContent='FACILITY';$('context-name').textContent=RECIPES[bn.id]?.name||bn.id;$('context-detail').textContent=bn.id==='barricade'?`HP ${S.barricadeHp[bn.id]||100} / 100`:'稼働中';$('context-action').textContent='確認';$('context-action').disabled=false;return}currentTarget=null;$('context-kicker').textContent='TARGET';$('context-name').textContent='探索中';$('context-detail').textContent='木や資源へ近づく';$('context-action').textContent='斧 / 伐採';$('context-action').disabled=true}
function rollDrop(source){const q=Math.random();if(source==='tree'&&q<.04){S.resources.hourglass++;toast('RARE DROP｜砂時計 +1','rarity-rare');log('木材の中から砂時計を発見')}else if(source==='zombie'){S.resources.scrap+=1+Math.floor(Math.random()*2);if(q<.12){S.resources.crystal++;toast('RARE DROP｜CRYSTAL +1','rarity-rare');log('ゾンビがCRYSTALを落とした')}else if(q<.25){S.resources.hourglass++;toast('DROP｜砂時計 +1','rarity-uncommon')}}}
function action(){if(!currentTarget)return;try{A.enable()}catch(_){};const {type,obj}=currentTarget;if(type==='tree'){obj.hp--;try{A.sfx('confirm')}catch(_){};if(obj.hp<=0){mutate(()=>{S.resources.wood+=4;obj.respawn=35;obj.hp=obj.max;rollDrop('tree')},'木を伐採｜WOOD +4')}else log(`斧を振った｜木の耐久 ${obj.hp}/${obj.max}`,{quiet:true})}else if(type==='bush'){mutate(()=>{S.resources.food+=3;obj.ready=false;obj.respawn=28},'採集｜FOOD +3')}else if(type==='zombie'){obj.hp-=12;obj.hit=.18;try{A.sfx('confirm')}catch(_){};if(obj.hp<=0){mutate(()=>{S.zombies=S.zombies.filter(z=>z!==obj);rollDrop('zombie')},'ゾンビ撃破')}else log(`斧で攻撃｜ゾンビ HP ${Math.ceil(obj.hp)}`,{quiet:true})}else if(type==='building'){openSheet('build')}}
$('context-action').onclick=action;
function canBuild(id){const q=RECIPES[id];if(S.buildings[id])return false;if(q.requires&&!S.buildings[q.requires])return false;return S.resources.wood>=q.wood&&S.resources.food>=q.food}
function build(id){const q=RECIPES[id];if(!q||S.buildings[id]||!canBuild(id))return;const [x,y]=BUILD_SLOTS[id];mutate(()=>{S.resources.wood-=q.wood;S.resources.food-=q.food;S.buildings[id]={x,y,builtAt:Date.now()};if(id==='barricade')S.barricadeHp[id]=100},`${q.name}を建設`);toast(`BUILD COMPLETE｜${q.name}`);renderSheet('build')}
function hire(){if(!S.buildings.recruit){toast('募集所が必要');return}if(S.resources.food<6){toast('FOOD 6 が必要');return}if(S.villagers.length>=200)return;const id=Date.now();mutate(()=>{S.resources.food-=6;S.villagers.push({id,name:`SURVIVOR ${S.villagers.length+1}`,role:'木こり'})},'新しい生存者を雇った');toast('SURVIVOR JOINED');renderSheet('people')}
const roles=['木こり','採集','建築','守備'];function cycleRole(v){const i=roles.indexOf(v.role);mutate(()=>v.role=roles[(i+1)%roles.length],`${v.name} → ${v.role}`);renderSheet('people')}
function drawRelic(){if(S.resources.crystal<5){toast('CRYSTAL 5 が必要');return}let r=Math.random()*100,acc=0,rar='COMMON';for(const [n,p] of RARITIES){acc+=p;if(r<acc){rar=n;break}}S.pity++;if(S.pity>=25&&['COMMON','UNCOMMON'].includes(rar))rar='RARE';if(rar==='LEGENDARY')S.pity=0;const names={COMMON:['古びた紐','旅人の札'],UNCOMMON:['青銅のお守り','森番の印'],RARE:['夜守りの徽章','迅速の設計図'],EPIC:['月蝕の図面','不滅の炉心'],LEGENDARY:['黎明の王冠','無限灯の核']};const pool=names[rar],item=pool[Math.floor(Math.random()*pool.length)];mutate(()=>{S.resources.crystal-=5;S.relics.push({rarity:rar,name:item,t:Date.now()})},`RELIC DRAW｜${rar} ${item}`);toast(`${rar}｜${item}`,`rarity-${rar.toLowerCase()}`);renderSheet('relic')}
function useBoost(){if(S.resources.hourglass<=0){toast('砂時計がない');return}mutate(()=>{S.resources.hourglass--;S.boost.speed=S.boost.speed===1?2:3;S.boost.time=30},`砂時計使用｜世界速度 ×${S.boost.speed}`)}$('boost').onclick=useBoost;
function openSheet(name){sheetOpen=true;$('sheet').hidden=false;renderSheet(name)}function closeSheet(){sheetOpen=false;$('sheet').hidden=true} $('sheet-close').onclick=closeSheet;document.querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>openSheet(b.dataset.sheet));
function renderSheet(name){const titles={build:'建築',people:'人',relic:'RELIC',log:'記録'};$('sheet-title').textContent=titles[name]||name;const body=$('sheet-body');if(name==='build'){body.innerHTML=`<div class="card-grid">${Object.entries(RECIPES).map(([id,q])=>{const built=!!S.buildings[id],locked=q.requires&&!S.buildings[q.requires];return `<div class="card"><small>${built?'BUILT':locked?'LOCKED':'RECIPE'}</small><strong>${q.name}</strong><p>${q.desc}<br>${q.wood}W${q.food?` + ${q.food}F`:''}</p><button data-build="${id}" ${built||locked||!canBuild(id)?'disabled':''}>${built?'建設済み':locked?'前提施設が必要':'建てる'}</button></div>`}).join('')}</div>`;body.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build))}else if(name==='people'){body.innerHTML=`<div class="card"><small>RECRUIT</small><strong>生存者を雇う</strong><p>募集所 + FOOD 6｜現在 ${S.villagers.length}/200</p><button id="hire-now" ${!S.buildings.recruit||S.resources.food<6?'disabled':''}>雇用する</button></div>${S.villagers.map((v,i)=>`<div class="role-row">${i+1}. ${v.name} <b>${v.role}</b><button data-role="${v.id}">役割変更</button></div>`).join('')}`;const h=$('hire-now');if(h)h.onclick=hire;body.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>cycleRole(S.villagers.find(v=>String(v.id)===b.dataset.role)))}else if(name==='relic'){body.innerHTML=`<div class="card"><small>RELIC DRAW</small><strong>CRYSTAL 5</strong><p>COMMON 55 / UNCOMMON 25 / RARE 13 / EPIC 6 / LEGENDARY 1</p><button id="draw-now" ${S.resources.crystal<5?'disabled':''}>DRAW</button></div>${S.relics.slice().reverse().map(r=>`<div class="relic-row rarity-${r.rarity.toLowerCase()}">${r.rarity}｜${r.name}</div>`).join('')||'<div class="log-row">まだRELICはない</div>'}`;$('draw-now').onclick=drawRelic}else{body.innerHTML=S.logs.map(l=>`<div class="log-row"><time>${new Date(l.t).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</time>${l.text}</div>`).join('')}}
function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function ellipse(x,y,rx,ry,col){ctx.fillStyle=col;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function drawGround(){const p=phaseName(),night=p==='night',dusk=p==='dusk',dawn=p==='dawn';const base=night?'#0c181b':dusk?'#23302a':dawn?'#263d35':'#27483c';rect(0,0,W,H,base);for(let y=0;y<H;y+=12)for(let x=0;x<W;x+=12){const n=(x*13+y*7)%37;if(n<5)rect(x,y,2,2,night?'#19302c':'#355b49');if(n===11)rect(x+5,y+4,1,4,'#6d7555')}ellipse(W/2,H*.54,170,88,night?'#1d2824':'#3a513d');ellipse(W/2,H*.54+2,140,70,night?'#202b25':'#465b42')}
function drawTree(t){if(t.respawn>0)return;const x=sx(t.x),y=sy(t.y);ellipse(x,y+14,18,7,'#0007');rect(x-4,y-10,8,28,'#4b3426');rect(x-24,y-34,48,28,phaseName()==='night'?'#16352f':'#235c43');rect(x-18,y-44,36,18,phaseName()==='night'?'#1a4038':'#2c6c4b');rect(x-10,y-50,20,12,phaseName()==='night'?'#1d493d':'#397853');if(currentTarget?.obj===t)ctx.strokeStyle='#e5bd67',ctx.strokeRect(Math.round(x-26)+.5,Math.round(y-53)+.5,52,73)}
function drawBush(b){if(!b.ready)return;const x=sx(b.x),y=sy(b.y);ellipse(x,y+8,12,4,'#0006');rect(x-14,y-9,28,16,phaseName()==='night'?'#21402f':'#3f7047');rect(x-9,y-13,18,11,'#567b4f');rect(x+3,y-8,3,3,'#c55b52');rect(x-7,y-5,3,3,'#d27662')}
function drawCampfire(){const x=sx(0),y=sy(96);ellipse(x,y+10,20,6,'#0008');rect(x-18,y+7,36,5,'#563a25');const f=4+Math.sin(time*.01)*3;ctx.fillStyle='#ff8a3d';ctx.beginPath();ctx.moveTo(x-9,y+8);ctx.quadraticCurveTo(x-12,y-8,x,y-22-f);ctx.quadraticCurveTo(x+13,y-5,x+8,y+8);ctx.fill();ctx.fillStyle='#ffd067';ctx.beginPath();ctx.moveTo(x-4,y+8);ctx.quadraticCurveTo(x-5,y-3,x+1,y-12-f*.4);ctx.quadraticCurveTo(x+6,y,x+4,y+8);ctx.fill()}
function drawBuilding(id,b){const x=sx(b.x),y=sy(b.y),night=phaseName()==='night';ellipse(x,y+13,26,7,'#0008');if(id==='barricade'){const hp=S.barricadeHp[id]||100;for(let i=-2;i<=2;i++){rect(x+i*10-3,y-18+(Math.abs(i)%2)*4,6,34,hp<40?'#5d4032':'#765039');rect(x+i*10-5,y-9,10,3,'#3e2c23')}return}if(id==='workbench'){rect(x-25,y-5,50,14,'#60422f');rect(x-21,y+8,6,19,'#3f2c24');rect(x+15,y+8,6,19,'#3f2c24');rect(x-14,y-19,7,14,'#9a7044');rect(x+5,y-15,14,5,'#a47a4c');return}const w=id==='recruit'?66:48,h=id==='recruit'?38:30;rect(x-w/2,y-h/2,w,h,night?'#26352f':'#594d3a');ctx.fillStyle=night?'#273f38':'#6d6046';ctx.beginPath();ctx.moveTo(x-w/2-5,y-h/2);ctx.lineTo(x,y-h/2-22);ctx.lineTo(x+w/2+5,y-h/2);ctx.fill();rect(x-6,y+2,12,h/2-2,'#2a211d');if(id==='recruit')rect(x-14,y-h/2+8,28,8,'#d0a45a')}
function drawPlayer(){const p=S.player,x=sx(p.x),y=sy(p.y),f=Math.floor(p.walk)%2;ellipse(x,y+15,10,4,'#0008');if(G?.drawActor){G.drawActor(ctx,{x,y,dir:p.dir,frame:f,color:'#7595a6',isPlayer:true,carry:false})}else{rect(x-6,y-12,12,19,'#7595a6');rect(x-7,y-20,14,10,'#e2c69d');rect(x+7,y-8,3,15,'#93633d');rect(x+9,y-12,8,3,'#b9b7aa')}rect(x+8,y-12,2,17,'#a67a46');rect(x+9,y-13,7,3,'#d2c3a2')}
function drawZombie(z){const x=sx(z.x),y=sy(z.y);ellipse(x,y+14,10,4,'#0008');rect(x-6,y-12,12,20,z.hit>0?'#b77267':'#546f5b');rect(x-6,y-20,12,9,'#779077');rect(x-4,y-18,2,2,'#d46e62');rect(x+2,y-18,2,2,'#d46e62');const hp=cl(z.hp/z.max,0,1);rect(x-12,y-28,24,3,'#211a1a');rect(x-12,y-28,24*hp,3,'#b65b50')}
function drawVillagers(){S.villagers.slice(0,8).forEach((v,i)=>{const a=time*.00025+i*1.7,rr=55+i*4,x=sx(Math.cos(a)*rr),y=sy(78+Math.sin(a)*24);ellipse(x,y+12,7,3,'#0006');rect(x-4,y-10,8,18,['#8a6d50','#6c856a','#7b698f','#8a7b54'][i%4]);rect(x-4,y-16,8,7,'#d8bb96')})}
function drawWorld(){drawGround();trees.slice().sort((a,b)=>a.y-b.y).forEach(drawTree);bushes.forEach(drawBush);drawCampfire();Object.entries(S.buildings).sort((a,b)=>a[1].y-b[1].y).forEach(([id,b])=>drawBuilding(id,b));drawVillagers();S.zombies.forEach(drawZombie);drawPlayer();if(phaseName()==='night'){ctx.fillStyle='rgba(5,10,18,.38)';ctx.fillRect(0,0,W,H);ctx.globalCompositeOperation='destination-out';const x=sx(S.player.x),y=sy(S.player.y);const g=ctx.createRadialGradient(x,y,40,x,y,150);g.addColorStop(0,'rgba(0,0,0,.78)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,150,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over'}}
function updateNodes(dt){for(const t of trees)if(t.respawn>0){t.respawn-=dt*S.boost.speed;if(t.respawn<=0)t.respawn=0}for(const b of bushes)if(!b.ready){b.respawn-=dt*S.boost.speed;if(b.respawn<=0){b.ready=true;b.respawn=0}}}
function updateVillagerProduction(dt){if(!S.villagers.length)return;const m=dt*S.boost.speed;for(const v of S.villagers){if(v.role==='木こり')S.resources.wood+=.018*m;else if(v.role==='採集')S.resources.food+=.012*m;else if(v.role==='建築'&&S.buildings.barricade){S.barricadeHp.barricade=Math.min(100,(S.barricadeHp.barricade||100)+.025*m)}}}
function updateZombies(dt){if(phaseName()!=='night')return;for(const z of S.zombies){z.hit=Math.max(0,z.hit-dt);let tx=S.player.x,ty=S.player.y,target='player';if(S.buildings.barricade&&(S.barricadeHp.barricade||0)>0){tx=S.buildings.barricade.x;ty=S.buildings.barricade.y;target='barricade'}const dx=tx-z.x,dy=ty-z.y,l=Math.hypot(dx,dy)||1;if(l>18){const sp=(16+S.day*.5)*dt;z.x+=dx/l*sp;z.y+=dy/l*sp}else{z.hit=Math.max(z.hit,.1);if(target==='barricade'){S.barricadeHp.barricade=Math.max(0,(S.barricadeHp.barricade||100)-z.atk*dt*2.3);if(S.barricadeHp.barricade<=0&&Math.random()<.01)log('バリケードが破壊された')}else{S.player.hp=Math.max(0,S.player.hp-z.atk*dt*2.1);if(S.player.hp<=0){S.player.hp=S.player.maxHp;S.player.x=0;S.player.y=110;log('倒れた｜焚き火で復帰');save('death')}}}}}
function update(dt){time+=dt*1000;if(!sheetOpen&&pointer){const dx=pointer.lastX-pointer.startX,dy=pointer.lastY-pointer.startY,d=Math.hypot(dx,dy);if(d>6){const speed=115,k=Math.min(1,(d-6)/44),nx=dx/d,ny=dy/d;S.player.x=cl(S.player.x+nx*speed*k*dt,-300,300);S.player.y=cl(S.player.y+ny*speed*k*dt,-220,230);S.player.walk+=dt*10;if(Math.abs(dx)>Math.abs(dy))S.player.dir=dx>0?'right':'left';else S.player.dir=dy>0?'down':'up'}}const sim=dt*S.boost.speed;S.phaseTime-=sim;if(S.phaseTime<=0)phaseAdvance();if(S.boost.time>0){S.boost.time-=dt;if(S.boost.time<=0){S.boost.time=0;S.boost.speed=1;log('砂時計終了｜×1') }}updateNodes(dt);updateVillagerProduction(dt);updateZombies(dt);saveFlash=Math.max(0,saveFlash-dt);toastClock=Math.max(0,toastClock-dt);if(toastClock===0)$('toast').hidden=true;updateTarget();updateHud()}
function frame(now){const dt=Math.min(.034,(now-last)/1000);last=now;update(dt);drawWorld();requestAnimationFrame(frame)}requestAnimationFrame(frame);
c.addEventListener('pointerdown',e=>{if(sheetOpen||pointer)return;e.preventDefault();pointer={id:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY};try{c.setPointerCapture(e.pointerId)}catch(_){};try{A.enable()}catch(_){}});c.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;e.preventDefault();pointer.lastX=e.clientX;pointer.lastY=e.clientY;$('hint').style.opacity='.3'});function release(e){if(!pointer||e.pointerId!==pointer.id)return;pointer=null}c.addEventListener('pointerup',release);c.addEventListener('pointercancel',release);c.addEventListener('lostpointercapture',()=>pointer=null);
setInterval(()=>save('auto'),2000);addEventListener('pagehide',()=>save('pagehide'));addEventListener('beforeunload',()=>save('beforeunload'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save('hidden')});
updateHud();log(`DAY ${S.day}｜主人公1人・住民0人から開始`,{quiet:true});
window.GUILD_SURVIVAL={getState:()=>structuredClone(S),save:()=>save('manual'),reset:()=>{localStorage.removeItem(KEY);localStorage.removeItem(BACK);location.reload()},build,hire,drawRelic};
})();
