const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});let checks=0;const check=(v,m)=>{assert(v,m);checks++;console.log('PASS',m)};const errors=[];try{const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173/prototype-chief.html');await p.waitForTimeout(300);
check(await p.evaluate(()=>!!window.Chief&&!!window.Citizens),'Chief and citizen engines boot');check(await p.locator('#speed,#sound,#utility').count()===0,'speed and audio-toggle controls removed');check(await p.evaluate(()=>state.boost===1&&state.hourglass===0),'speed inventory converted and simulation is normal speed');check(await p.title()==='村長、正気ですか？ | CHIEF, REALLY?','renamed Japanese title');
const x=await p.evaluate(()=>state.player.x);await p.mouse.move(150,480);await p.mouse.down();await p.mouse.move(215,480);await p.waitForTimeout(500);await p.mouse.up();check(await p.evaluate(x=>state.player.x>x+25,x),'actual pointer drag moves village chief');check(await p.evaluate(()=>A.report().enabled&&A.report().tracks===6&&A.report().context==='running'),'first gesture unlocks six-score audio engine');
await p.click('[data-panel="build"]');const t=await p.evaluate(()=>state.cycle);await p.waitForTimeout(150);check(await p.evaluate(t=>state.cycle===t&&input.mag===0,t),'menus pause and clear movement');await p.evaluate(()=>{state.wood=300;state.stone=240;state.food=200;forceUiRefresh()});await p.click('[data-build="forge"]');check(await p.evaluate(()=>state.buildings.some(b=>b.type==='forge')),'forge built with real UI');await p.click('[data-panel="record"]');await p.click('[data-chief="forge"]');check(await p.evaluate(()=>!!Chief.state.forge&&!Chief.startForge()),'forge charges once and rejects concurrent job');const snapshot=await p.evaluate(()=>({wood:state.wood,stone:state.stone,iron:state.iron,remaining:Chief.state.forge.remaining}));await p.waitForTimeout(150);check(await p.evaluate(r=>Chief.state.forge.remaining===r,snapshot.remaining),'forge respects menu pause');await p.reload();await p.click('[data-panel="record"]');check(await p.evaluate(s=>state.wood===s.wood&&state.stone===s.stone&&Chief.state.forge.remaining>0&&Chief.state.forge.remaining<=s.remaining,snapshot),'unfinished forge job survives reload without paying again');check(await p.evaluate(n=>{Chief.tick(13);Chief.tick(0);return state.iron===n+1&&Chief.state.earnedIron===1&&!Chief.state.forge},snapshot.iron),'forge produces exactly one guaranteed iron');check(await p.evaluate(()=>{Chief.state.autoForge=true;state.wood=59;state.stone=59;Chief.tick(1);const low=!Chief.state.forge;state.wood=60;state.stone=60;Chief.tick(1);Chief.state.autoForge=false;return low&&state.wood===48&&state.stone===42&&!!Chief.state.forge}),'automatic forge preserves reserve threshold');
check(await p.evaluate(()=>{Chief.state.forge=null;state.wood=0;state.stone=0;return !Chief.startForge()&&!Chief.state.forge&&state.wood===0}),'unaffordable forge is atomic');
await p.evaluate(()=>{state.wood=300;state.stone=240;state.food=200;forceUiRefresh()});await p.click('#sheet-close');await p.click('[data-panel="build"]');await p.click('[data-build="hut"]');await p.click('[data-panel="people"]');await p.click('[data-hire="stone"]');await p.click('[data-hire="wood"]');check(await p.evaluate(()=>state.workers.length===2&&state.workers[0].citizen.name==='ポン'&&state.workers[1].citizen.trait===1),'named distinct personalities assigned on actual hire');check(await p.evaluate(()=>{const w=state.workers[0],base=node('test',500,500,'rock');state.stone=0;Chief.setActor(w);hitNode(base,'worker');Chief.setActor(null);return Math.abs(state.stone-.72*1.22)<.0001}),'meticulous trait really increases stone yield');check(await p.evaluate(()=>{const w=state.workers[1];w.citizen.trait=3;return Citizens.speed(w)===1.22&&Citizens.yieldBonus(w,'wood')===-.08}),'impatient trait has speed benefit and yield tradeoff');
check(await p.evaluate(()=>{const w=state.workers[0];state.wood=200;state.food=200;const c=Citizens.trainCost(w),wood=state.wood,food=state.food;const ok=Citizens.train(w.id);return ok&&w.citizen.level===2&&!Citizens.train(w.id)&&state.wood===wood-c.wood&&state.food===food-c.food}),'training gains XP, pays once, and enforces cooldown');check(await p.evaluate(()=>{const w=state.workers[0];return Citizens.reassign(w.id,'food')&&w.role==='food'&&!Citizens.reassign(w.id,'guard')}),'job reassignment works and guard requires barracks');
const citizen=await p.evaluate(()=>{save();return JSON.stringify(state.workers[0].citizen)});await p.reload();check(await p.evaluate(c=>{const w=state.workers[0];return w.citizen.name===c.name&&w.citizen.level===c.level&&w.citizen.trait===c.trait&&w.citizen.xp===c.xp},JSON.parse(citizen)),'personality name level and XP persist');
await p.click('[data-panel="record"]');check(await p.evaluate(()=>{state.wood=300;state.stone=240;state.food=220;const j=Chief.contract(),r=state.renown,ok=Chief.fulfill(j.id);return ok&&!Chief.fulfill(j.id)&&state.renown===r+j.renown&&Chief.state.contracts===1}),'delivery reward cannot be claimed twice');check(await p.evaluate(()=>{Chief.state.contracts=999;const c=Chief.contract().cost,cap=capacity();Chief.state.contracts=1;return Object.entries(c).every(([k,v])=>v<=cap[k]*.72)}),'late delivery cost remains within storage capacity');check(await p.evaluate(()=>{state.wood=300;state.stone=240;state.iron=40;state.renown=50;const cap=capacity().wood;return Chief.charter()&&Chief.state.charter===1&&capacity().wood===cap+45&&state.player.maxHp===124}),'development chapter increases storage and chief health');
check(await p.evaluate(()=>{const w=state.workers[0];w.citizen.level=20;w.citizen.trait=0;state.progression.tech.masonry=25;state.buildings.push({id:'qt',type:'quarry',x:0,y:0,level:12});Chief.setActor(w);const m=Chief.gatherMultiplier('worker','rock');Chief.setActor(null);return m<=2.2&&m>1}),'stacked production bonuses bounded');check(await p.evaluate(()=>{state.progression.tech.masonry=25;state.buildings.push({id:'wt',type:'warehouse',x:50,y:40,level:20});state.wood=4200;state.stone=3200;state.food=2500;state.progression.groups.housing=12;syncGroup('hut');save();return true}),'prepare high-level save');await p.reload();check(await p.evaluate(()=>state.buildings.find(b=>b.type==='warehouse').level===20&&state.wood>4000&&techLevel('masonry')===25&&groupLevel('hut')===12),'expanded warehouse resources housing and research survive load');
await p.click('[data-panel="record"]');check(await p.evaluate(()=>{const cap=capacity();return Object.keys(WORK_TECH).every(k=>Object.entries(techCost(k,25)).every(([r,v])=>!(r in cap)||v<=cap[r]))}),'all final research resource costs are reachable');
check(await p.evaluate(()=>{const w=state.workers[0];w.role='wood';w.maxHp=85;w.hp=42.5;state.buildings.push({id:'reassign-barr',type:'barracks',level:1,x:0,y:0});Citizens.reassign(w.id,'guard');const guard=w.maxHp===120&&w.hp===60;Citizens.reassign(w.id,'wood');return guard&&w.maxHp===85&&w.hp===42.5}),'role transition normalizes health and preserves damage ratio');
await p.evaluate(()=>{openPanel('record');$('sheet').scrollTop=$('sheet').scrollHeight;openPanel('people')});check(await p.evaluate(()=>$('sheet').scrollTop===0),'switching panels returns to the top');
check(await p.evaluate(()=>{const w=state.workers[1];w.role='guard';w.citizen.trait=1;w.citizen.level=1;w.cool=0;w.x=0;w.y=0;state.enemies=[{id:'enemy',x:190,y:0,hp:1000,maxHp:1000,dead:false}];state.projectiles=[];state.palisade={built:true,level:1,hp:360,maxHp:360};state.workers=[w];state.buildings.push({id:'barr',type:'barracks',level:1,x:-80,y:0});updateWorkers(.01);const a=state.projectiles.find(p=>p.kind==='arrow');state.enemies=[];state.projectiles=[];return !!a&&Math.abs(a.damage-23*1.18)<.001}),'guard personality applies to launched arrow damage');
const gates=await p.evaluate(()=>{state.palisade={built:true,level:3,hp:980,maxHp:980};const B=bounds(),targets=[{x:0,y:B.t-140},{x:B.r+140,y:0},{x:0,y:B.b+140},{x:B.l-140,y:0}];return ['wood','stone','food'].flatMap(role=>targets.map(target=>{const w={x:0,y:0,role,anim:0};let valid=true,prior=true,out=false,back=false;for(const dest of [target,{x:0,y:0}])for(let i=0;i<1200;i++){gfMove(w,dest.x,dest.y,60,1/60);const now=inside(w.x,w.y,B);if(now!==prior){valid=valid&&pointInGateOpening(w.x,w.y,B,0);if(now)back=true;else out=true}prior=now}return valid&&out&&back}))});check(gates.every(Boolean)&&gates.length===12,'all 12 role/gate outward and home routes preserved');check(await p.evaluate(()=>{state.buildings=[];state.projectiles=[];state.enemies=[{x:bounds().r+40,y:0,hp:100,dead:false}];towerCombat(.1);state.enemies=[];return state.projectiles.length===0&&REPEAT_LIMITS.watchtower.max===16}),'walls have no archers and tower cap remains 16');
// Deterministic staged town for visual inspection, not a claim about natural progression.
await p.evaluate(()=>{state.enemies=[];state.workers=[];state.buildings=[];state.wood=6000;state.stone=5000;state.food=4000;state.iron=200;state.renown=200;state.palisade={built:true,level:3,hp:980,maxHp:980};for(const type of ['guild','hut','hut','forge','warehouse','lumber','quarry','watchtower','lantern'])build(type);for(const role of ['stone','wood','food','wood','food','stone'])hire(role);Chief.state.monument=5;state.player.x=0;state.player.y=60;state.cycle=.35;state.phase='day';clearInside();closeSheet();forceUiRefresh()});await p.waitForTimeout(1200);await p.screenshot({path:'qa/chief/village.png'});
await p.click('[data-panel="people"]');await p.locator('#chief-roster').scrollIntoViewIfNeeded();await p.screenshot({path:'qa/chief/citizens.png'});check(await p.locator('.citizen').count()===6,'six individual citizen cards render');await p.click('#sheet-close');await p.click('[data-panel="record"]');await p.screenshot({path:'qa/chief/office.png'});
for(const size of [{width:360,height:640},{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(size);for(const panel of ['build','people','record']){await p.evaluate(n=>openPanel(n),panel);check(await p.evaluate(()=>{const r=$('sheet').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}),`viewport ${size.width} / ${panel} fits`)}await p.screenshot({path:`qa/chief/layout-${size.width}.png`})}
check(await p.evaluate(()=>{for(const scene of ['morning','work','ramble','night','siege','parade']){A.setScene(scene);A.voice(3);A.sfx('chop');if(A.report().scene!==scene)return false}return A.report().active<=36}),'all six music scenes select and voices stay bounded');
check(await p.evaluate(()=>{openPanel('record');state.pocket.tokens=2;Pocket.choosePolicy('harvest');Pocket.claim('first');updateHud(true);return !$('pocket-help').textContent.includes('v2.0')&&$('pocket-progress').textContent.includes(state.pocket.claimed.length+'/9')}),'paused policy UI keeps new branding and live progress');
// Copy-import test in isolated storage; source remains untouched and reset does not re-import.
const legacy=await p.evaluate(()=>{state.chief=undefined;state.day=9;return serial()});const q=await browser.newPage({viewport:{width:390,height:844}});q.on('pageerror',e=>errors.push(e.message));await q.goto('http://127.0.0.1:4173/prototype-chief.html');await q.evaluate(s=>{document.body.dataset.resetting='true';localStorage.clear();localStorage.setItem('guild-pocket-v2',s)},legacy);await q.goto('http://127.0.0.1:4173/prototype-chief.html');check(await q.evaluate(s=>state.day===9&&localStorage.getItem('guild-pocket-v2')===s,legacy),'Pocket save copied once without overwriting source');await q.click('[data-panel="record"]');await q.click('#reset-game');check((await q.locator('#reset-game').textContent()).includes('もう一度'),'reset requires second click');await q.click('#reset-game');await q.waitForTimeout(400);check(await q.evaluate(()=>state.day===1&&state.buildings.length===0&&state.workers.length===0),'reset starts fresh and does not re-import Pocket');check(await q.evaluate(s=>localStorage.getItem('guild-pocket-v2')===s,legacy),'reset preserves original Pocket save');await q.screenshot({path:'qa/chief/first.png'});
check(errors.length===0,'no uncaught browser errors: '+JSON.stringify(errors));fs.writeFileSync('qa/chief/results.json',JSON.stringify({checks,errors,viewports:['360x640','390x844','844x390'],notes:'Chromium emulation; no physical iOS test. Town screenshots use seeded state.'},null,2));console.log('TOTAL',checks)}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
