const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),http=require('http'),path=require('path');
const root=path.resolve(__dirname,'..'),output=process.env.LIVING_UI_OUTPUT||path.join(root,'qa/living');
(async()=>{const server=http.createServer((q,r)=>{try{const p=path.join(root,q.url.split('?')[0]);r.setHeader('Content-Type',p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':p.endsWith('.js')?'application/javascript':p.endsWith('.mp3')?'audio/mpeg':'application/octet-stream');r.end(fs.readFileSync(p))}catch{r.statusCode=404;r.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/tmp/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[],checks=[];const check=(v,m)=>{assert(v,m);checks.push(m);console.log('PASS',m)};fs.mkdirSync(output,{recursive:true});try{
 const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&m.text().includes('v1.6'))errors.push(m.text())});await p.goto('http://127.0.0.1:'+server.address().port+'/prototype-chief-world-standalone.html');await p.waitForFunction(()=>window.LivingUI&&window.VillageTransfer);await p.click('#game',{position:{x:190,y:410}});await p.waitForFunction(()=>VillageAudio.report().decoded===3);check(await p.evaluate(()=>A.report().enabled&&VillageAudio.report().ambience===3),'gesture unlocks music and three environment layers');check(await p.evaluate(()=>VillageAudio.speak('good')&&VillageAudio.report().voicesPlayed===1),'embedded Japanese voice decodes and plays');check(await p.evaluate(()=>!VillageAudio.speak('delivery')),'voice cooldown prevents overlapping chatter');check(await p.locator('#sound,#speed').count()===0,'no removed toggles return');
 // Seeded visual fixture, driven by actual production simulation. Real RAF is paused in a menu.
 await p.evaluate(()=>openPanel('people'));
 await p.evaluate(()=>{state.buildings=[{id:'home',type:'hut',x:-70,y:-5,level:2},{id:'store',type:'warehouse',x:70,y:-10,level:2},{id:'home2',type:'hut',x:-65,y:-95,level:2}];state.wood=60;state.stone=30;state.food=80;state.phase='day';state.cycle=.25;state.workers=[];state.nodes=[];state.enemies=[];state.projectiles=[];state.palisade.built=true;state.palisade.level=1;state.palisade.hp=state.palisade.maxHp=600;state.player.x=0;state.player.y=120;cam.x=0;cam.y=65;for(let i=0;i<6;i++){const w={id:'visual-'+i,role:i%2?'stone':'wood',x:-112+i*43,y:145+(i%2)*20,seed:i,anim:0,work:0,hp:85,maxHp:85,cool:0};Citizens.ensure(w);Logistics.ensure(w);Council.ensure(w);w.citizen.trait=i;state.workers.push(w);state.nodes.push({id:'visual-node-'+i,type:i%2?'rock':'tree',x:w.x,y:w.y+22,hp:1000,maxHp:1000,alive:true})}closeSheet();for(let i=0;i<690;i++){Chief.state.time+=1/60;updateWorkers(1/60);VillageSocial.tick(1/60);drawEffects(1/60)}state.player.x=0;state.player.y=100;input.mag=1;updateHud(true);draw();drawEffects(.016)});
 await p.waitForTimeout(450);await p.screenshot({path:path.join(output,'cargo-mobile.png')});check(await p.evaluate(()=>Logistics.report().carriedTotal>0),'actual workers have visible carried resources');
 await p.evaluate(()=>LivingUI.setTab('production'));await p.screenshot({path:path.join(output,'production-mobile.png')});check(await p.locator('.living-receipt').count()===1,'production shows actual receipt and transit totals');check(await p.locator('.living-ledger strong').first().textContent()===await p.evaluate(()=>Logistics.report().carriedTotal.toFixed(1)),'UI carried total matches engine');
 // Persist the real fixture, then reload without RAF to isolate dialogue from pending
 // 4.2-second trophy notices. Overlay precedence is tested in living-fixes.cjs.
 await p.addInitScript(()=>{requestAnimationFrame=()=>0});await p.evaluate(()=>save());await p.reload();await p.waitForFunction(()=>window.LivingUI&&window.LivingFX);
 await p.evaluate(()=>{closeSheet();const a=state.workers[0],b=state.workers[1];a.x=-30;a.y=90;b.x=12;b.y=95;a.cargo={wood:10.2,stone:0,food:0};b.cargo={wood:0,stone:8.6,food:0};VillageSocial.state.active=null;VillageSocial.state.nextAt=0;VillageSocial.state.cooldowns={};VillageSocial.startConversation(a,b,'cargo');VillageSocial.state.relations[a.id]=[{id:b.id,score:3,at:0}];VillageSocial.state.relations[b.id]=[{id:a.id,score:3,at:0}];draw();drawEffects(.016)});await p.screenshot({path:path.join(output,'conversation-mobile.png')});check(await p.locator('#living-dialogue').isVisible(),'one contextual speech bubble visible');
 await p.evaluate(()=>{LivingUI.setTab('handbook')});await p.click('[data-living-person="visual-0"]');await p.screenshot({path:path.join(output,'handbook-mobile.png')});check((await p.locator('.living-person').first().textContent()).includes('仲良し'),'resident handbook shows real relationship');check(await p.locator('.living-person-detail').count()===1,'individual conversation history can open');
 await p.evaluate(()=>{closeSheet();const w=state.workers[0];state.wood=100;for(let i=0;i<8;i++){w.cargo={wood:12,stone:0,food:0};Logistics.deposit(w)}LivingUI.scan();openPanel('record')});await p.click('[data-living-view="trophies"]');await p.screenshot({path:path.join(output,'trophies-mobile.png')});check(await p.locator('.living-trophy-grid article').count()===15,'fifteen trophy goals');check(await p.locator('.living-trophy-grid .earned').count()>=3,'real achievements unlock once');const trophies=await p.evaluate(()=>Object.keys(LivingUI.state.awards).length);await p.evaluate(()=>{LivingUI.scan();LivingUI.scan()});check(await p.evaluate(()=>Object.keys(LivingUI.state.awards).length)===trophies,'repeat scan does not duplicate awards');await p.locator('[data-living-title="first"]').click();check((await p.locator('.living-title').textContent()).includes('納品見届け人'),'earned title selectable');
 await p.click('[data-living-view="transfer"]');check(await p.locator('[data-transfer="export"]').isVisible(),'save transfer reachable');const packed=await p.evaluate(()=>{state.world.entitlements=['golden_seal'];localStorage.setItem('chief-world-purchase-identity-v1','fixture-identity-not-exported');return VillageTransfer.pack()});check(!packed.includes('fixture-identity-not-exported')&&!packed.includes('entitlements'),'save export excludes purchase authority');check(await p.evaluate(x=>VillageTransfer.parse(x).workers.length===6,packed),'export round trip preserves workers');check(await p.evaluate(()=>{for(const bad of ['{}','{"format":"mayor-world-save","version":1,"save":{"version":16}}','x'.repeat(2100000)]){try{VillageTransfer.parse(bad);return false}catch{}}return true}),'invalid and oversized saves rejected');
 for(const size of [{width:360,height:640},{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(size);for(const tab of ['production','handbook','hire']){await p.evaluate(t=>LivingUI.setTab(t),tab);check(await p.evaluate(()=>{const b=$('sheet').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&b.top>=0&&b.bottom<=innerHeight}),size.width+'px '+tab+' sheet fits')}
 await p.evaluate(()=>{openPanel('record');$('living-record-tools').querySelector('[data-living-view="trophies"]').click()});check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),size.width+'px trophy grid fits')}
 // Clear earlier trophy/festival presentation lifetimes while retaining earned state;
 // the following25 real harvests exclusively exercise the combo presentation.
 await p.evaluate(()=>save());await p.reload();await p.waitForFunction(()=>window.LivingUI&&window.LivingFX);
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{closeSheet();state.player.x=-112;state.player.y=140;cam.x=-20;cam.y=65;state.wood=0;const n=state.nodes[0];n.hp=10000;n.alive=true;for(let i=0;i<25;i++){Chief.state.time+=.3;hitNode(n,'player');drawEffects(.3)}draw();drawEffects(.016)});await p.screenshot({path:path.join(output,'combo-mobile.png')});check(await p.locator('#living-combo').isVisible(),'large combo feedback visible');check(await p.evaluate(()=>LivingFX.report().texts<=24&&LivingFX.report().rings<=16),'effect queues remain bounded');
 await p.evaluate(()=>openPanel('people'));const before=await p.evaluate(()=>({cargo:Logistics.report().carriedTotal,friend:VillageSocial.relationFor('visual-0'),award:Object.keys(LivingUI.state.awards).length}));await p.evaluate(()=>save());await p.addInitScript(()=>{requestAnimationFrame=()=>0});await p.reload();await p.waitForFunction(()=>window.LivingUI);check(await p.evaluate(x=>Math.abs(Logistics.report().carriedTotal-x.cargo)<.01&&JSON.stringify(VillageSocial.relationFor('visual-0'))===JSON.stringify(x.friend)&&Object.keys(LivingUI.state.awards).length===x.award,before),'cargo friendship trophy persist on reload');
 const q=await browser.newPage({viewport:{width:390,height:844}});await q.addInitScript(()=>{requestAnimationFrame=()=>0});await q.goto('http://127.0.0.1:'+server.address().port+'/prototype-chief-world-standalone.html');await q.evaluate(x=>{state.wood=7;save();localStorage.setItem('chief-world-purchase-identity-v1','keep-on-import');VillageTransfer.install(VillageTransfer.parse(x),false)},packed);await q.reload();check(await q.evaluate(()=>state.workers.length===6&&localStorage.getItem('chief-world-purchase-identity-v1')==='keep-on-import'&&JSON.parse(localStorage.getItem('guild-chief-world-v3-before-import')).wood===7),'actual import restores village, backs up prior save, preserves purchase identity');await q.close();
 check(errors.length===0,'no uncaught browser or game-loop errors '+JSON.stringify(errors));fs.writeFileSync(path.join(output,'ui-results.json'),JSON.stringify({checks,errors,notes:'Playwright Chromium mobile emulation; screenshots are explicitly seeded visual fixtures driven by production code, not natural progression. No physical iOS/audio perception testing or real purchase.'},null,2));
 }finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
