const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});let checks=0;const check=(v,msg)=>{assert(v,msg);checks++;console.log('PASS',msg)};try{const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:4173/prototype-buildjoy-pocket.html');check(await p.evaluate(()=>!!window.Pocket),'Pocket entry boots');await p.waitForTimeout(300);
// Actual pointer drag, release, and menu clicks.
const x=await p.evaluate(()=>state.player.x);await p.mouse.move(190,560);await p.mouse.down();await p.mouse.move(255,560);await p.waitForTimeout(600);await p.mouse.up();check(await p.evaluate(x=>state.player.x>x+35,x),'analog drag moves player');
await p.click('[data-panel="build"]');const cycle=await p.evaluate(()=>state.cycle);await p.waitForTimeout(350);check(await p.evaluate(c=>state.cycle===c&&input.mag===0,cycle),'menus pause time and cancel input');
await p.evaluate(()=>{state.wood=150;state.stone=90;state.food=50;forceUiRefresh()});await p.click('[data-build="hut"]');check(await p.evaluate(()=>state.buildings.some(b=>b.type==='hut')&&currentPanel===null),'build creates house and returns to world');
await p.click('[data-panel="people"]');await p.click('[data-hire="wood"]');check(await p.evaluate(()=>state.workers.length===1),'hire via actual UI');await p.click('#sheet-close');await p.click('[data-panel="record"]');await p.click('[data-claim="crew"]');await p.click('[data-policy="harvest"]');check(await p.evaluate(()=>state.pocket.policies.harvest===1&&state.pocket.tokens===0),'earned point purchases policy');check(await p.evaluate(()=>!Pocket.claim('crew')&&!Pocket.choosePolicy('guard')),'duplicate claim and unaffordable choice rejected');await p.screenshot({path:'qa/pocket/policies.png'});
await p.click('#sheet-close');check(await p.evaluate(()=>Pocket.whistle()&&!Pocket.whistle()),'whistle cooldown prevents repeat use');await p.evaluate(()=>{state.nodes[0].pocketHit=9999;state.workers[0].sayUntil=9999;save()});await p.reload();await p.waitForTimeout(100);check(await p.evaluate(()=>state.pocket.claimed.includes('crew')&&state.pocket.policies.harvest===1),'reload preserves choices and claims');check(await p.evaluate(()=>!state.nodes.some(n=>n.pocketHit===9999)&&!state.workers.some(w=>w.sayUntil===9999)),'reload clears transient animation clocks');check(await p.evaluate(()=>Pocket.rally>0),'reload preserves remaining rally benefit');
check(await p.evaluate(()=>{const c=Pocket.caches[0];state.player.x=c.x;state.player.y=c.y;Pocket.tick(.3);const iron=state.iron;Pocket.tick(.3);return state.pocket.caches.filter(x=>x===c.id).length===1&&state.iron===iron}),'exploration reward exactly once');
check(await p.evaluate(()=>{const before=state.pocket.tokens;state.stats.nights=3;state.pocket.nightPaid=0;state.cycle=.4;phaseTick(0);phaseTick(0);return state.pocket.tokens===before+3}),'night reward catch-up exactly once');
check(await p.evaluate(()=>{const real=Date.now,now=real();state.boost=2;state.boostUntil=now+30000;openPanel('record');Date.now=()=>now+31000;closeSheet();phaseTick(0);const ok=state.boost===2&&state.boostUntil-Date.now()>=29000;Date.now=real;state.boost=1;state.boostUntil=0;return ok}),'hourglass remaining duration survives menu pause');
await p.click('[data-panel="record"]');await p.locator('#sheet-close').focus();await p.keyboard.press('Space');check(await p.evaluate(()=>currentPanel===null),'Space activates focused menu button');
check(await p.evaluate(()=>{const real=Date.now,now=real();state.boost=2;state.boostUntil=now+30000;Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));Date.now=()=>now+31000;Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));phaseTick(0);const ok=state.boost===2&&state.boostUntil-Date.now()>=29000&&input.mag===0;Date.now=real;delete document.hidden;state.boost=1;state.boostUntil=0;return ok}),'background pause preserves boost and clears input');
// Isolation from legacy saves.
check(await p.evaluate(()=>{localStorage.setItem('guild-infinity-v16-clean','legacy-sentinel');save();return SAVE==='guild-pocket-v2'&&localStorage.getItem('guild-infinity-v16-clean')==='legacy-sentinel'}),'legacy save isolated');
// Same four-gate simulation as baseline, all roles and outward/return journeys.
const traffic=await p.evaluate(()=>{state.enemies=[];state.palisade={built:true,level:3,hp:980,maxHp:980};const B=bounds(),targets=[{x:0,y:B.t-140},{x:B.r+140,y:0},{x:0,y:B.b+140},{x:B.l-140,y:0}],result=[];for(const role of ['wood','stone','food'])for(const target of targets){const w={x:0,y:0,role,anim:0};let crossed=false,valid=true,prior=true;for(let i=0;i<1200;i++){gfMove(w,target.x,target.y,60,1/60);const now=inside(w.x,w.y,B);if(prior&&!now){crossed=true;valid=valid&&pointInGateOpening(w.x,w.y,B,0)}prior=now}let returned=false;for(let i=0;i<1200;i++){gfMove(w,0,0,60,1/60);const now=inside(w.x,w.y,B);if(!prior&&now){returned=true;valid=valid&&pointInGateOpening(w.x,w.y,B,0)}prior=now}result.push(crossed&&returned&&valid)}return result});check(traffic.every(Boolean)&&traffic.length===12,'12 role/gate combinations outward and return');
check(await p.evaluate(()=>{state.buildings=[];state.projectiles=[];const B=bounds();state.enemies=[{id:'e',x:B.r+40,y:0,hp:100,maxHp:100,dead:false}];towerCombat(1/60);return state.projectiles.length===0&&REPEAT_LIMITS.watchtower.max===16}),'wall archers absent; tower cap 16');
await p.evaluate(()=>{state.pocket.whistleUntil=0;state.enemies=[];state.workers=[];state.player.x=0;state.player.y=100;state.cycle=.4;state.wood=999;state.stone=999;state.food=80;state.iron=30;state.renown=30;for(const t of ['guild','hut','hut','lumber','quarry','watchtower','lantern','lantern'])build(t);state.palisade.hp=state.palisade.maxHp;for(const k of ['wood','stone','food'])capResource(k);for(const r of ['wood','stone','food','wood','food'])hire(r);closeSheet();save()});await p.waitForTimeout(3500);await p.screenshot({path:'qa/pocket/village-day.png'});
await p.evaluate(()=>{state.cycle=.84;state.phase='night';spawnWave(0)});await p.waitForTimeout(300);await p.screenshot({path:'qa/pocket/village-night.png'});
for(const size of [{width:360,height:640},{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(size);await p.click('[data-panel="build"]');check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no page overflow '+size.width);check(await p.evaluate(()=>{const r=document.getElementById('sheet').getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}),'sheet fits '+size.width);await p.screenshot({path:`qa/pocket/layout-${size.width}.png`});await p.click('#sheet-close')}
await p.setViewportSize({width:390,height:844});await p.click('[data-panel="record"]');await p.click('#reset-game');check(await p.locator('#reset-game').textContent().then(t=>t.includes('もう一度')),'reset first click arms');await p.click('#reset-game');await p.waitForTimeout(600);check(await p.evaluate(()=>state.day===1&&state.buildings.length===0&&state.pocket.claimed.length===0),'reset survives lifecycle save and reload');check(await p.evaluate(()=>localStorage.getItem('guild-infinity-v16-clean')==='legacy-sentinel'),'reset leaves legacy save intact');
await p.screenshot({path:'qa/pocket/first-launch.png'});check(errors.length===0,'zero browser runtime errors: '+JSON.stringify(errors));fs.writeFileSync('qa/pocket/results.json',JSON.stringify({checks,errors},null,2));console.log('TOTAL',checks)}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
