/* Focused acceptance: transitions, twelve-member migration, careers, defeat and phone UI. */
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');const root=path.resolve(__dirname,'..'),out=root+'/qa/twelve-v6';fs.mkdirSync(out,{recursive:true});
(async()=>{const server=http.createServer((q,r)=>{try{r.end(fs.readFileSync(path.join(root,q.url.split('?')[0])))}catch{r.statusCode=404;r.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const errors=[],checks=[];const ok=(v,s)=>{assert(v,s);checks.push(s);console.log('PASS',s)};p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='error')errors.push(e.text())});try{await p.goto('http://127.0.0.1:'+server.address().port+'/prototype-chief-world-standalone.html');await p.waitForFunction(()=>window.Twelve);await p.locator('#caravan-start').tap();await p.waitForTimeout(200);ok(await p.evaluate(()=>!!window.Twelve&&!Pocket.paused()),'start and game loop');await p.screenshot({path:out+'/01-field.png'});
 const economy=await p.evaluate(()=>{state.wood=300;state.stone=220;state.food=200;state.iron=20;build('hut');build('barracks');for(let i=0;i<4;i++)hire(['wood','stone','food','guard'][i]);const w=state.workers[0];const before=w.citizen.xp;Twelve.train(w.id);const trained=w.citizen.xp>before;w.citizen.level=4;const job=Twelve.changeJob(w.id,'forester');const b=state.workers[1];Citizens.reassign(b.id,'wood');b.x=w.x+5;b.y=w.y;Twelve.buddy(w.id,b.id);Twelve.gear(w.id);const gain=Twelve.strength(w);return{trained,job,gain,id:w.id,other:b.id,gear:Twelve.ensure(w).gear}});ok(economy.trained&&economy.job&&economy.gear===1&&economy.gain>1.6,'training, specialist, gear and buddy affect real yield');
 await p.evaluate(()=>LivingUI.setTab('handbook'));await p.waitForTimeout(100);await p.screenshot({path:out+'/02-handbook.png'});const sticky=await p.evaluate(()=>{const panel=$('panel-people'),tabs=document.querySelector('.living-tabs'),intro=panel.querySelector('.living-intro'),head=document.querySelector('.sheet-head');const before=[head.getBoundingClientRect().top,tabs.getBoundingClientRect().top,intro.getBoundingClientRect().top];panel.scrollTop=400;return{before,after:[head.getBoundingClientRect().top,tabs.getBoundingClientRect().top,intro.getBoundingClientRect().top],scroll:panel.scrollTop}});ok(sticky.scroll>0&&sticky.before.every((v,i)=>Math.abs(v-sticky.after[i])<2),'sheet header, resident tabs and intro remain fixed while cards scroll');
 await p.evaluate(()=>openPanel('build'));await p.locator('[data-crew-build=research]').tap();ok(await p.locator('[data-tech-upgrade]:visible').count()>0&&await p.locator('[data-build]:visible').count()===0,'research tab isolated from construction');await p.screenshot({path:out+'/03-research.png'});
 await p.evaluate(()=>{closeSheet();state.wood=300;state.stone=220;state.food=200;for(let i=0;i<4;i++)build('hut');for(let i=0;i<20;i++)hire('wood')});ok(await p.evaluate(()=>state.workers.length===12&&maxWorkers()===12),'hiring hard capped at twelve');
 const migration=await p.evaluate(()=>{closeSheet();const w=state.workers[0];for(let i=12;i<300;i++){const a=JSON.parse(JSON.stringify(w));a.id='old-'+i;a.citizen.name='OB'+i;a.citizen.number=i;a.citizen.level=2;a.cargo={wood:2,stone:1,food:0};a.citizen.career.buddy=null;state.workers.push(a)}VillageSocial.state.relations[w.id]=[{id:'old-299',score:6,at:0}];save();const all=state.workers.map(w=>({id:w.id,xp:w.citizen.xp,cargo:{...w.cargo}}));Twelve.archiveOverflow();save();return{all,active:state.workers.length,retired:Twelve.crew.retired.length,tickets:Twelve.crew.mentoring}});ok(migration.active===12&&migration.retired===288&&migration.tickets===288,'300-resident save archives 288 without discarding people');await p.reload();await p.waitForFunction(()=>window.Twelve);ok(await p.evaluate(all=>{const actual=[...state.workers,...Twelve.crew.retired];return all.every(w=>{const a=actual.find(x=>x.id===w.id);return a&&a.citizen.xp===w.xp&&JSON.stringify(a.cargo)===JSON.stringify(w.cargo)})&&VillageSocial.relationFor(state.workers[0].id).some(r=>r.id==='old-299')},migration.all),'all IDs, XP, cargo and archived relationships survive reload');await p.locator('#caravan-start').tap();
 ok(await p.evaluate(()=>Twelve.swap(state.workers[0].id,'old-299')&&state.workers.some(w=>w.id==='old-299')&&state.workers.length===12),'OB can rejoin through one-for-one exchange');
 await p.evaluate(()=>{closeSheet();state.food=100;state.player.hp=10;state.player.invuln=0;damagePlayer(100,{x:state.player.x-20,y:state.player.y});Twelve.update()});ok(await p.evaluate(()=>state.player.down>3&&state.player.hp===0&&Twelve.crew.rescues===1&&state.food<100),'lethal damage causes visible defeat and rescue cost');await p.screenshot({path:out+'/04-rescue.png'});await p.waitForFunction(()=>state.player.down<=0);ok(await p.evaluate(()=>state.player.hp>0&&state.player.invuln>0),'rescue restores play with protection');
 await p.evaluate(()=>{state.player.x=0;state.player.y=120;state.enemies=[];state.projectiles=[];Campaign.state.completed=true;WorldUI.setTab('campaign')});await p.locator('.caravan-depart-card [data-caravan-move=rain]').tap();ok(await p.locator('#caravan-confirm').isVisible(),'departure confirmation opens with touch');await Promise.all([p.waitForEvent('load'),p.locator('#caravan-go').tap()]);await p.waitForFunction(()=>window.Twelve);ok(await p.evaluate(()=>Campaign.current().id==='rain'&&state.workers.length===12&&Twelve.crew.retired.length===288&&state.buildings.length===0),'real tap departure loads next village with roster and archive');await p.locator('#caravan-start').tap();
 await p.evaluate(()=>{LivingUI.celebrate('受賞テスト','小さな通知の位置確認');});ok(await p.evaluate(()=>{const a=$('living-celebration').getBoundingClientRect();return a.width<200&&a.right<=innerWidth&&a.left>innerWidth/3&&a.top<260}),'trophy is a compact top-right notification');
 for(const size of [{width:360,height:640},{width:390,height:844},{width:430,height:932}]){await p.setViewportSize(size);await p.evaluate(()=>LivingUI.setTab('handbook'));await p.waitForTimeout(80);ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&$('sheet').getBoundingClientRect().bottom<innerHeight),'phone layout fits '+size.width);await p.screenshot({path:out+'/handbook-'+size.width+'.png'})}
 ok(errors.length===0,'no runtime errors in scoped checks '+JSON.stringify(errors));fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors,notes:'Chromium phone emulation. Advanced state and migration are explicit test fixtures. Not a physical iPhone or full campaign playthrough.'},null,2));}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
