const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/tmp/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});let checks=0;const errors=[];const check=(v,m)=>{assert(v,m);checks++;console.log('PASS',m)};fs.mkdirSync('qa/world',{recursive:true});try{
 const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&m.text().includes('v1.6'))errors.push(m.text())});await p.goto('http://127.0.0.1:4173/prototype-chief-world.html');await p.waitForFunction(()=>window.WorldUI&&window.WorldGame&&window.Council);
 check((await p.title())==='村長、世界まで行くんですか？','new formal title');check(await p.locator('#dock button').count()===4,'four main mobile actions');check(await p.locator('#speed,#sound').count()===0,'removed speed/audio toggles stay absent');
 const x=await p.evaluate(()=>state.player.x);await p.mouse.move(145,480);await p.mouse.down();await p.mouse.move(215,480);await p.waitForTimeout(400);await p.mouse.up();check(await p.evaluate(x=>state.player.x>x+20,x),'real pointer drag moves the mayor');check(await p.evaluate(()=>A.report().enabled&&A.report().tracks===11),'gesture unlocks eleven score scenes');
 await p.click('[data-panel="world"]');check(await p.locator('.world-region').count()===5,'five destination cards');await p.click('[data-world="visit"][data-region="forest"]');check(await p.evaluate(()=>WorldGame.away&&currentPanel===null),'map button enters playable forest');const time=await p.evaluate(()=>state.cycle);await p.waitForTimeout(350);check(await p.evaluate(t=>state.cycle===t,time),'home clock freezes during exploration');await p.waitForFunction(()=>WorldGame.state.collected.crooked_wood>=5,{},{timeout:7000});check(await p.evaluate(()=>WorldGame.available('canyon')),'actual stopped gathering unlocks canyon without seeded resources');await p.screenshot({path:'qa/world/forest.png'});await p.click('[data-panel="world"]');await p.click('[data-world="visit"][data-region="canyon"]');await p.waitForFunction(()=>WorldGame.state.collected.iron_ore>=5,{},{timeout:7000});await p.screenshot({path:'qa/world/canyon.png'});await p.click('[data-panel="world"]');await p.click('[data-world="visit"][data-region="marsh"]');await p.waitForFunction(()=>WorldGame.state.collected.glowcap>=2,{},{timeout:5000});check(await p.evaluate(()=>WorldGame.state.region==='marsh'&&WorldGame.state.collected.glowcap>=2),'fresh player reaches and gathers in three regions through actual UI');await p.screenshot({path:'qa/world/marsh.png'});await p.click('#world-home');check(await p.evaluate(()=>!WorldGame.away),'visible return-home control works');
 await p.click('[data-panel="world"]');await p.click('[data-tab="shop"]');check(await p.locator('[data-world="buy"]:disabled').count()===3,'unconfigured shop shows three disabled purchases');check((await p.locator('#panel-world').textContent()).includes('販売準備中'),'preview status is explicit');await p.screenshot({path:'qa/world/shop-preview.png'});
 await p.evaluate(()=>{localStorage.setItem('chief-world-forged-purchases',JSON.stringify(['golden_seal','mayor_mech']));state.world.entitlements=['golden_seal'];save()});await p.reload();check(await p.evaluate(()=>ChiefShop.damageMultiplier()===1&&!ChiefShop.owned('golden_seal')),'local save cannot assert a purchase');
 for(const size of [{width:360,height:640},{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(size);for(const name of ['build','people','world','record']){await p.evaluate(n=>openPanel(n),name);check(await p.evaluate(()=>{const r=$('sheet').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}),`viewport ${size.width}: ${name} stays on screen`)}await p.screenshot({path:`qa/world/layout-${size.width}.png`})}
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{Council.tick(24);openPanel('record')});await p.screenshot({path:'qa/world/office.png'});await p.evaluate(()=>WorldUI.setTab('atlas'));await p.screenshot({path:'qa/world/atlas.png'});
 // Test-only network fixture: actual production frontend validates the service response.
 const ctx=await browser.newContext({viewport:{width:390,height:844}});let serverOwned=['golden_seal','mayor_mech'],fail=false;await ctx.route('**/prototype-chief-world.html',async route=>{const r=await route.fetch();let html=await r.text();html=html.replace('</head>','<meta name="chief-payment-api" content="https://payments.example.test"></head>');await route.fulfill({response:r,body:html})});await ctx.route('https://payments.example.test/**',async route=>{if(fail)return route.fulfill({status:503,json:{error:'unavailable'}});const path=new URL(route.request().url()).pathname;const token='test_identity_secret_32_bytes_not_a_real_key';if(path==='/api/catalog')return route.fulfill({json:{mode:'test',products:[]}});if(path==='/api/restore')return route.fulfill({json:{token,playerId:'fixture',entitlements:serverOwned,mode:'test'}});if(path==='/api/entitlements')return route.fulfill({json:{entitlements:serverOwned,mode:'test'}});return route.fulfill({status:404,json:{error:'not_found'}})});
 const q=await ctx.newPage();q.on('pageerror',e=>errors.push(e.message));q.on('console',m=>{if(m.type()==='error'&&m.text().includes('v1.6'))errors.push(m.text())});await q.goto('http://127.0.0.1:4173/prototype-chief-world.html');await q.waitForFunction(()=>window.ChiefShop&&!ChiefShop.busy&&ChiefShop.mode==='test');await q.evaluate(()=>WorldUI.setTab('shop'));await q.fill('#world-recovery','test-recovery');await q.click('[data-world="restore"]');await q.waitForFunction(()=>ChiefShop.owned('golden_seal'));check(await q.evaluate(()=>ChiefShop.damageMultiplier()===4),'verified service entitlement enables fourfold seal');check(await q.locator('[data-world="buy"][data-sku="golden_seal"]:disabled').count()===1,'owned item prevents duplicate checkout in UI');check(await q.evaluate(()=>{state.player.x=0;state.player.y=0;state.player.attackCd=0;state.enemies=[{id:'paid-damage-fixture',x:35,y:0,hp:1000,maxHp:1000,dead:false,hit:0}];playerAutoCombat();const dealt=1000-state.enemies[0].hp;state.enemies=[];return dealt===144}),'golden seal applies real fourfold strike plus32 pulse');await q.click('#sheet-close');await q.click('#world-mech');check(await q.evaluate(()=>ChiefShop.damageMultiplier()===6&&ChiefShop.shieldActive()),'owned mech starts temporary sixfold combat');check(await q.evaluate(()=>{state.player.invuln=0;const hp=state.player.hp;damagePlayer(20,{x:100,y:100});return hp-state.player.hp===4}),'mech actually reduces incoming damage by80percent');await q.screenshot({path:'qa/world/mech-test-fixture.png'});check(await q.evaluate(()=>{ChiefShop.tick(16);return ChiefShop.damageMultiplier()===4&&!ChiefShop.shieldActive()}),'mech expires to permanent seal strength');await q.evaluate(()=>{const token=localStorage.getItem('chief-world-purchase-identity-v1');hardResetGame(false);window.testPurchaseIdentity=token});check(await q.evaluate(()=>localStorage.getItem('chief-world-purchase-identity-v1')===window.testPurchaseIdentity),'village reset preserves purchase identity');
 serverOwned=[];await q.reload();await q.waitForFunction(()=>window.ChiefShop&&!ChiefShop.busy);check(await q.evaluate(()=>!ChiefShop.owned('golden_seal')&&ChiefShop.damageMultiplier()===1),'revoked server entitlement removes effect after revalidation');fail=true;await q.evaluate(()=>ChiefShop.refresh());check(await q.evaluate(()=>ChiefShop.mode==='preview'&&ChiefShop.damageMultiplier()===1),'network failure never grants or retains unverifiable purchase');await ctx.close();
 check(errors.length===0,'no uncaught browser errors: '+JSON.stringify(errors));fs.writeFileSync('qa/world/ui-results.json',JSON.stringify({checks,errors,notes:'Chromium mobile emulation, no physical iOS test. Mech screenshot uses explicitly mocked test service; no real Stripe payment performed.'},null,2));console.log('TOTAL',checks);
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
