(()=>{'use strict';
const atlas=new Image();atlas.src='https://raw.githubusercontent.com/Two-Weeks-Team/openClawWorld/main/packages/client/public/assets/kenney/tiles/tinytown_tilemap.png';const chars=new Image();chars.crossOrigin='anonymous';chars.src='https://raw.githubusercontent.com/Two-Weeks-Team/openClawWorld/main/packages/client/public/assets/kenney/characters/characters_spritesheet.png';
const clickAudio=new Audio('https://raw.githubusercontent.com/Calinou/kenney-ui-audio/master/addons/kenney_ui_audio/click3.wav');clickAudio.volume=.16;const bgm=new Audio('https://raw.githubusercontent.com/ishaanrajiv/snake-rs/main/assets/audio/bgm.ogg');bgm.loop=true;bgm.volume=.10;
const c=document.getElementById('world'),ctx=c.getContext('2d'),pc=document.getElementById('portrait'),pctx=pc.getContext('2d'),$=s=>document.querySelector(s);let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),last=performance.now(),sim=0,prod=0,saveClock=0;function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const KEY='guild-v092-builder-deluxe',rnd=(a,b)=>a+Math.random()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v));const P={x:0,y:60,vx:0,vy:0,swing:0,target:null,dir:'down'},cam={x:0,y:20},parts=[],pops=[];
const residents=[
{name:'TOM',role:'LEADER',trait:'好奇心旺盛 · せっかち',quote:'「次、何建てる？」',bonus:'建設速度 +12% · 自動採取 +5%',col:0,hair:'#3a2b22',skin:'#d6a879',cloth:'#557b78'},
{name:'MIRA',role:'BUILDER',trait:'職人気質 · 無口',quote:'「壁は、一気に囲う」',bonus:'建設速度 +18% · 防壁HP +8%',col:4,hair:'#51372c',skin:'#e2b88d',cloth:'#8b6b42'},
{name:'NOA',role:'LUMBER',trait:'陽気 · おしゃべり',quote:'「森なら任せて！」',bonus:'木材生産 +16% · 士気 +4%',col:7,hair:'#b77b38',skin:'#e1b27f',cloth:'#527347'},
{name:'RITA',role:'MINER',trait:'慎重 · 観察好き',quote:'「この岩、質がいい」',bonus:'石材生産 +20% · レア率 +2%',col:10,hair:'#6b3941',skin:'#d49f78',cloth:'#676b86'}];let selectedResident=0;
const S={day:1,phase:'day',phaseT:0,wood:0,stone:0,food:0,builds:[],wall:null,residentCount:1};const phases=[['day',120],['dusk',12],['night',28],['dawn',8]];
const specs={hut:{name:'住居',sub:'住民が増える · 街の密度UP',cost:{wood:8,stone:3},icon:[63,74,85]},lumber:{name:'木材所',sub:'毎秒 WOOD を自動生産',cost:{wood:10,stone:2},icon:[72,73,115]},quarry:{name:'採石所',sub:'毎秒 STONE を自動生産',cost:{wood:7,stone:7},icon:[48,49,119]},garden:{name:'畑',sub:'毎秒 FOOD を自動生産',cost:{wood:6,stone:2},icon:[36,37,17]},workshop:{name:'工房',sub:'建設演出と生産を強化',cost:{wood:12,stone:8},icon:[52,53,128]},wall:{name:'外周防壁',sub:'1回で拠点を丸ごと囲う',cost:{wood:14,stone:9},icon:[44,45,46]}};
const trees=[],rocks=[],bushes=[];function scatter(arr,count,kind,min=38,max=390){for(let i=0;i<count;i++){const a=i/count*Math.PI*2+rnd(-.16,.16),r=rnd(min,max),x=Math.cos(a)*r+rnd(-28,28),y=Math.sin(a)*r*.70+rnd(-24,24)+30;arr.push({id:kind+i,kind,x,y,hp:kind==='tree'?2:kind==='rock'?3:1,max:kind==='tree'?2:kind==='rock'?3:1,resp:0,hit:0,var:i%4})}}scatter(trees,62,'tree');scatter(rocks,38,'rock',45,370);scatter(bushes,18,'bush',50,330);trees[0].x=40;trees[0].y=64;rocks[0].x=-44;rocks[0].y=66;
const spots=[[-68,6],[70,5],[-126,68],[126,70],[-6,-68],[147,-38],[-150,-38],[20,122],[166,117],[-174,121],[0,-145],[205,20],[-210,22],[90,-132],[-94,-132]];
const sx=x=>W/2+x-cam.x,sy=y=>H/2+y-cam.y-42;function tile(id,x,y,scale=3,alpha=1){if(!atlas.complete)return;ctx.globalAlpha=alpha;ctx.drawImage(atlas,(id%12)*16,Math.floor(id/12)*16,16,16,Math.round(x),Math.round(y),16*scale,16*scale);ctx.globalAlpha=1}
function phaseInfo(){return phases.find(x=>x[0]===S.phase)}function nextPhase(){let i=phases.findIndex(x=>x[0]===S.phase);i=(i+1)%phases.length;S.phase=phases[i][0];S.phaseT=0;if(S.phase==='day')S.day++;save('phase')}
function pop(x,y,text,col='#f6d283'){pops.push({x,y,text,col,life:.8})}function burst(x,y,col,n=10){for(let i=0;i<n;i++)parts.push({x,y,vx:rnd(-55,55),vy:rnd(-70,-8),life:rnd(.28,.6),col,s:rnd(2,5)})}
function save(reason='auto'){S.savedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify({S,P:{x:P.x,y:P.y,dir:P.dir},trees:trees.map(n=>[n.hp,n.resp]),rocks:rocks.map(n=>[n.hp,n.resp]),bushes:bushes.map(n=>[n.hp,n.resp])}))}catch(_){}const el=$('#save');el.classList.add('on');clearTimeout(save.t);save.t=setTimeout(()=>el.classList.remove('on'),330)}function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d)return;Object.assign(S,d.S||{});if(d.P)Object.assign(P,d.P);[trees,rocks,bushes].forEach((a,ai)=>{const q=[d.trees,d.rocks,d.bushes][ai]||[];q.forEach((v,i)=>{if(a[i]){a[i].hp=v[0];a[i].resp=v[1]}})})}catch(_){}}
function sfx(kind){try{if(kind==='ui'){clickAudio.currentTime=0;clickAudio.play().catch(()=>{})}}catch(_){}if(!window.AudioContext&&!window.webkitAudioContext)return;audioStart();const t=AC.currentTime;function tone(f,d,g=.025,delay=0,type='triangle'){const o=AC.createOscillator(),a=AC.createGain();o.type=type;o.frequency.value=f;a.gain.setValueAtTime(g,t+delay);a.gain.exponentialRampToValueAtTime(.001,t+delay+d);o.connect(a);a.connect(M);o.start(t+delay);o.stop(t+delay+d+.02)}if(kind==='wood'){tone(160,.045,.03,0,'square');tone(105,.07,.02,.03)}if(kind==='stone'){tone(530,.035,.025,0,'square');tone(310,.06,.022,.025)}if(kind==='build'){tone(392,.09,.028);tone(523,.1,.03,.055);tone(659,.13,.026,.11)}if(kind==='wall'){[330,392,494,587].forEach((f,i)=>tone(f,.08,.026,i*.045,'square'))}}
let AC=null,M=null,music=true,beat=0,nextBeat=0;function audioStart(){if(!AC){AC=new(window.AudioContext||window.webkitAudioContext)();M=AC.createGain();M.gain.value=.35;M.connect(AC.destination);nextBeat=AC.currentTime+.05}if(music&&bgm.paused)bgm.play().catch(()=>{})}function musicTick(){if(!AC||!music)return;while(nextBeat<AC.currentTime+.08){const seq=S.phase==='night'?[110,123,147,165]:[147,196,220,247,196,165],f=seq[beat%seq.length],o=AC.createOscillator(),g=AC.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.008,nextBeat);g.gain.exponentialRampToValueAtTime(.001,nextBeat+.23);o.connect(g);g.connect(M);o.start(nextBeat);o.stop(nextBeat+.24);if(beat%4===0){const o2=AC.createOscillator(),g2=AC.createGain();o2.type='sine';o2.frequency.value=f/2;g2.gain.setValueAtTime(.006,nextBeat);g2.gain.exponentialRampToValueAtTime(.001,nextBeat+.32);o2.connect(g2);g2.connect(M);o2.start(nextBeat);o2.stop(nextBeat+.33)}nextBeat+=.30;beat++}}
function drawGround(){ctx.fillStyle=S.phase==='night'?'#172629':'#31584a';ctx.fillRect(0,0,W,H);for(let x=-520;x<520;x+=48)for(let y=-410;y<450;y+=48){const id=((x+y)/48)%5===0?1:0;tile(id,sx(x),sy(y),3)}}
function clearRadius(){return S.builds.length?65+Math.min(105,S.builds.length*22):0}function hiddenByTown(n){const r=clearRadius();return r>0&&Math.hypot(n.x,n.y)<r}function drawNode(n){if(n.hp<=0||hiddenByTown(n))return;const X=sx(n.x),Y=sy(n.y);if(n.kind==='tree')tile([5,6,7,8][n.var],X-24,Y-42,3,n.hit>0?.7:1);else if(n.kind==='rock')tile(43,X-20,Y-18,2.5,n.hit>0?.55:1);else tile([17,18,29][n.var%3],X-24,Y-20,3)}
function drawHouse(b){const X=sx(b.x),Y=sy(b.y);if(b.type==='hut'){tile(63,X-24,Y-48,3);tile(74,X-24,Y,3);tile(85,X,Y,3)}else if(b.type==='lumber'){tile(72,X-48,Y-12,3);tile(73,X,Y-12,3);tile(115,X+8,Y-34,2)}else if(b.type==='quarry'){tile(48,X-48,Y-12,3);tile(49,X,Y-12,3);tile(119,X+8,Y-38,2)}else if(b.type==='garden'){tile(36,X-48,Y-10,3);tile(37,X,Y-10,3);tile(17,X-18,Y-24,2)}else{tile(52,X-48,Y-42,3);tile(53,X,Y-42,3);tile(76,X-48,Y+4,3);tile(77,X,Y+4,3);tile(128,X+10,Y-22,2)}}
function wallSegments(){if(!S.wall)return[];const built=S.builds.length,rx=170+Math.min(72,built*5),ry=120+Math.min(50,built*4),seg=[];for(let x=-rx;x<=rx;x+=32){if(Math.abs(x)>=34)seg.push({x,y:ry,edge:'h'});seg.push({x,y:-ry,edge:'h'})}for(let y=-ry+32;y<=ry-32;y+=32){seg.push({x:-rx,y,edge:'v'});seg.push({x:rx,y,edge:'v'})}return seg}
function drawWall(){if(!S.wall)return;const seg=wallSegments(),age=(performance.now()-(S.wall.builtAt||0))/1000;seg.forEach((q,i)=>{const local=cl((age-i*.018)/.18,0,1);if(local<=0)return;const X=sx(q.x),Y=sy(q.y)+(1-local)*15,stone=S.wall.tier>1;let id;if(stone)id=q.edge==='h'?96:123;else id=q.edge==='h'?45:47;tile(id,X-24,Y-24,3,local)});const ry=120+Math.min(50,S.builds.length*4);tile(S.wall.tier>1?112:69,sx(-32),sy(ry)-36,3);tile(S.wall.tier>1?114:70,sx(16),sy(ry)-36,3)}
function drawWorker(b,i){if(S.residentCount<=1)return;const X=sx(b.x),Y=sy(b.y),a=sim*2+i,dx=Math.cos(a)*22,dy=Math.sin(a*.8)*9;drawPerson(X+dx,Y+dy+5,(i+1)%4,.8)}
function drawPerson(X,Y,idx=0,scale=1){if(chars.complete&&chars.naturalWidth){ctx.drawImage(chars,residents[idx].col*17,0,16,16,X-12*scale,Y-25*scale,24*scale,24*scale);return}const r=residents[idx];ctx.save();ctx.translate(Math.round(X),Math.round(Y));ctx.scale(scale,scale);ctx.fillStyle='rgba(0,0,0,.25)';ctx.fillRect(-9,7,18,4);ctx.fillStyle=r.cloth;ctx.fillRect(-7,-7,14,15);ctx.fillStyle=r.skin;ctx.fillRect(-6,-17,12,11);ctx.fillStyle=r.hair;ctx.fillRect(-7,-20,14,6);ctx.fillRect(-7,-16,3,6);ctx.fillStyle='#201d1b';ctx.fillRect(-4,-13,2,2);ctx.fillRect(3,-13,2,2);ctx.fillStyle='#2d4545';ctx.fillRect(-6,7,5,8);ctx.fillRect(2,7,5,8);ctx.restore()}
function drawPlayer(){drawPerson(sx(P.x),sy(P.y),0,1.15);if(P.swing>0&&P.target){const a=(1-P.swing/.26)*1.6-.7,X=sx(P.x),Y=sy(P.y),tx=X+Math.cos(a)*23,ty=Y-9+Math.sin(a)*22;ctx.strokeStyle=P.target.kind==='rock'?'#c9d2ce':'#e5b86f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(X+5,Y-8);ctx.lineTo(tx,ty);ctx.stroke();tile(P.target.kind==='rock'?119:115,tx-8,ty-8,1)}}
function draw(){drawGround();[...trees,...rocks,...bushes].sort((a,b)=>a.y-b.y).forEach(drawNode);S.builds.forEach((b,i)=>{drawHouse(b);drawWorker(b,i)});drawWall();drawPlayer();for(const p of parts){ctx.globalAlpha=cl(p.life*3,0,1);ctx.fillStyle=p.col;ctx.fillRect(sx(p.x),sy(p.y),p.s,p.s)}ctx.globalAlpha=1;ctx.textAlign='center';ctx.font='bold 10px ui-monospace';for(const p of pops){ctx.globalAlpha=cl(p.life*2,0,1);ctx.fillStyle=p.col;ctx.fillText(p.text,sx(p.x),sy(p.y)-18)}ctx.globalAlpha=1;ctx.textAlign='start';if(S.phase==='dusk'){ctx.fillStyle='rgba(211,119,62,.13)';ctx.fillRect(0,0,W,H)}if(S.phase==='night'){ctx.fillStyle='rgba(5,12,31,.42)';ctx.fillRect(0,0,W,H)}}
function nearest(){let best=null,d=80;for(const n of [...trees,...rocks,...bushes]){if(n.hp<=0||hiddenByTown(n))continue;const q=Math.hypot(P.x-n.x,P.y-n.y);if(q<d){d=q;best=n}}return best}let inputting=false,pointer=null,autoCd=0;function hit(n){P.target=n;P.swing=.26;n.hit=.09;n.hp--;if(n.kind==='tree'){S.wood+=2;pop(n.x,n.y,'+2 WOOD');burst(n.x,n.y,'#d5a25c',7);sfx('wood');if(n.hp<=0){S.wood+=3;pop(n.x,n.y-10,'+3 BONUS','#ffe29a');n.resp=4.5}}else if(n.kind==='rock'){S.stone+=2;pop(n.x,n.y,'+2 STONE','#dce7e0');burst(n.x,n.y,'#9aa8a2',8);sfx('stone');if(n.hp<=0){S.stone+=3;pop(n.x,n.y-10,'+3 BONUS','#eef6f0');n.resp=5.5}}else{S.food+=3;pop(n.x,n.y,'+3 FOOD','#f09aa2');burst(n.x,n.y,'#bf6770',6);n.resp=7}save('gather')}
function scaledCost(type){const s=specs[type];if(type==='wall'){if(!S.wall)return s.cost;return S.wall.tier===1?{wood:16,stone:18}:{wood:24,stone:30}}const count=S.builds.filter(b=>b.type===type).length,m=1+count*.14;return{wood:Math.ceil(s.cost.wood*m),stone:Math.ceil(s.cost.stone*m)}}function can(cost){return S.wood>=cost.wood&&S.stone>=cost.stone}
function toast(t,s){$('#toastT').textContent=t;$('#toastS').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),850)}function build(type){const cost=scaledCost(type);if(!can(cost))return false;S.wood-=cost.wood;S.stone-=cost.stone;if(type==='wall'){if(!S.wall){S.wall={tier:1,builtAt:performance.now(),hp:S.residentCount>=2?108:100};toast('PERIMETER COMPLETE','外周が一気につながった');sfx('wall')}else{S.wall.tier=Math.min(3,S.wall.tier+1);S.wall.builtAt=performance.now();toast('WALL UPGRADED',S.wall.tier===2?'木柵 → 石壁':'防壁をさらに強化');sfx('wall')}wallSegments().forEach((q,i)=>setTimeout(()=>burst(q.x,q.y,S.wall.tier>1?'#cfd9d5':'#c99a5b',3),i*18))}else{const i=S.builds.length,sp=spots[i%spots.length],ring=Math.floor(i/spots.length),b={type,x:sp[0]+ring*20,y:sp[1]+ring*15};S.builds.push(b);if(type==='hut')S.residentCount=Math.min(residents.length,S.residentCount+1);burst(b.x,b.y,'#f2c66d',26);pop(b.x,b.y-25,'BUILD! '+specs[type].name,'#ffdb86');sfx('build');toast('BUILD COMPLETE',specs[type].name+' · 生産圏が広がった')}save('build');renderDock();updateHUD();return true}
function update(dt){sim+=dt;prod+=dt;saveClock+=dt;S.phaseT+=dt;if(S.phaseT>=phaseInfo()[1])nextPhase();P.swing=Math.max(0,P.swing-dt);autoCd-=dt;P.x=cl(P.x+P.vx*dt,-440,440);P.y=cl(P.y+P.vy*dt,-330,360);cam.x+=(P.x-cam.x)*Math.min(1,dt*8);cam.y+=(P.y-20-cam.y)*Math.min(1,dt*8);for(const n of [...trees,...rocks,...bushes]){n.hit=Math.max(0,n.hit-dt);if(n.hp<=0&&(n.resp-=dt)<=0){n.hp=n.max;n.resp=0}}if(!inputting&&Math.hypot(P.vx,P.vy)<1&&autoCd<=0){const n=nearest();if(n){hit(n);autoCd=(n.kind==='rock'?.31:.27)*.95}else P.target=null}for(const p of parts){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=75*dt;p.life-=dt}for(let i=parts.length-1;i>=0;i--)if(parts[i].life<=0)parts.splice(i,1);for(const p of pops){p.y-=24*dt;p.life-=dt}for(let i=pops.length-1;i>=0;i--)if(pops[i].life<=0)pops.splice(i,1);if(prod>=1){prod=0;const l=S.builds.filter(b=>b.type==='lumber').length,q=S.builds.filter(b=>b.type==='quarry').length,g=S.builds.filter(b=>b.type==='garden').length,w=S.builds.filter(b=>b.type==='workshop').length,woodTrait=S.residentCount>=3?1.16:1,stoneTrait=S.residentCount>=4?1.20:1,woodGain=Math.max(0,Math.round(l*(2+w)*woodTrait)),stoneGain=Math.max(0,Math.round(q*(2+w)*stoneTrait));if(l)S.wood+=woodGain;if(q)S.stone+=stoneGain;if(g)S.food+=g*2;if(l||q||g){const b=S.builds[S.builds.length-1];if(b)pop(b.x,b.y,`AUTO +${l?woodGain+'W ':''}${q?stoneGain+'S ':''}${g?g*2+'F':''}`,'#bfe8c0')}}if(saveClock>=2){saveClock=0;save('auto')}musicTick();updateHUD()}
function renderIcon(cv,type){const g=cv.getContext('2d');g.imageSmoothingEnabled=false;g.clearRect(0,0,64,52);specs[type].icon.forEach((id,i)=>{if(!atlas.complete)return;g.drawImage(atlas,(id%12)*16,Math.floor(id/12)*16,16,16,5+i*14,8+(i%2)*8,32,32)})}
function renderDock(){const d=$('#buildDock');d.innerHTML='';Object.keys(specs).forEach(type=>{const s=specs[type],cost=scaledCost(type),ready=can(cost),wall=type==='wall',card=document.createElement('div');card.className='build '+(ready?'ready ':'')+(wall?'wall':'');let title=s.name;if(wall&&S.wall)title=S.wall.tier===1?'石壁へ一括強化':'防壁強化 Lv.'+(S.wall.tier+1);card.innerHTML=`<div class="ico"><canvas width="64" height="52"></canvas></div><strong>${title}</strong><div class="sub">${s.sub}</div><div class="cost">W ${cost.wood} · S ${cost.stone}</div><button ${ready?'':'disabled'}>${wall?(S.wall?'一括強化':'一気に囲う'):'建設'}</button>`;card.querySelector('button').onclick=()=>{audioStart();sfx('ui');build(type)};d.appendChild(card);renderIcon(card.querySelector('canvas'),type)})}
function updateHUD(){$('#wood').textContent=Math.floor(S.wood);$('#stone').textContent=Math.floor(S.stone);$('#food').textContent=Math.floor(S.food);$('#phase').textContent=S.phase.toUpperCase()+' '+S.day;const rem=Math.max(0,phaseInfo()[1]-S.phaseT);$('#clock').textContent=String(Math.floor(rem/60)).padStart(2,'0')+':'+String(Math.floor(rem%60)).padStart(2,'0');const n=nearest();$('#target').textContent=inputting?'FREE MOVE':n?`AUTO ${n.kind==='tree'?'CHOP':n.kind==='rock'?'MINE':'GATHER'} · FAST`:'AUTO GATHER · 近くへ移動';if(Math.random()<.12)renderDock()}
function drawPortrait(){const r=residents[selectedResident];pctx.clearRect(0,0,64,72);pctx.imageSmoothingEnabled=false;const grad=pctx.createLinearGradient(0,0,0,72);grad.addColorStop(0,'#435c50');grad.addColorStop(1,'#172725');pctx.fillStyle=grad;pctx.fillRect(0,0,64,72);pctx.fillStyle=r.cloth;pctx.fillRect(10,45,44,27);pctx.fillStyle=r.skin;pctx.fillRect(17,19,30,31);pctx.fillStyle=r.hair;pctx.fillRect(12,11,40,13);pctx.fillRect(12,18,8,21);pctx.fillRect(45,18,6,13);pctx.fillStyle='#201d1b';pctx.fillRect(23,31,4,4);pctx.fillRect(39,31,4,4);pctx.fillStyle='#f4ddbf';pctx.fillRect(24,30,2,1);pctx.fillRect(40,30,2,1);pctx.fillStyle='#8b5144';pctx.fillRect(29,41,9,3);pctx.fillStyle='rgba(255,255,255,.25)';pctx.fillRect(18,20,5,3);$('#rname').textContent=r.name;$('#rrole').textContent=r.role;$('#rtrait').textContent=r.trait;$('#rquote').textContent=r.quote;$('#rbonus').textContent=r.bonus}
$('#cycle').onclick=()=>{selectedResident=(selectedResident+1)%Math.max(1,S.residentCount);drawPortrait();sfx('ui')};$('#music').onclick=()=>{audioStart();music=!music;if(music)bgm.play().catch(()=>{});else bgm.pause();$('#music').textContent=music?'♪':'×';sfx('ui')};chars.onload=()=>drawPortrait();atlas.onload=()=>{renderDock();drawPortrait()};
c.addEventListener('pointerdown',e=>{e.preventDefault();audioStart();if(AC?.state==='suspended')AC.resume();inputting=true;pointer={id:e.pointerId,x:e.clientX,y:e.clientY};c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,d=Math.hypot(dx,dy),k=d<3?0:cl((d-3)/50,0,1),speed=185;P.vx=(d?dx/d:0)*speed*k;P.vy=(d?dy/d:0)*speed*k});function release(e){if(!pointer||e.pointerId!==pointer.id)return;P.vx=P.vy=0;pointer=null;inputting=false}c.addEventListener('pointerup',release);c.addEventListener('pointercancel',release);c.addEventListener('lostpointercapture',()=>{P.vx=P.vy=0;pointer=null;inputting=false});
window.GUILD_V092_API=Object.freeze({grant:(w=0,s=0,f=0)=>{S.wood+=w;S.stone+=s;S.food+=f;renderDock();updateHUD()},build,getState:()=>JSON.parse(JSON.stringify(S)),getPlayer:()=>({...P}),reset:()=>{localStorage.removeItem(KEY);location.reload()}});load();drawPortrait();renderDock();updateHUD();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();